input-output-hk/cardano-sl

.travis.yml

Question: do we really need to build haddock on CI?

travis-ci: speedup by caching and parallelization

---

.travis.yml
shell.nix

Reverts input-output-hk/pos-haskell-prototype#5

Revert "travis-ci: OSX and rocksdb"

---

src/Pos/Util/UserSecret.hs

System.FileLock doesn't support a process writing to a file it previously
locked. Instead the file passed to `withFileLock`/`lockFile` is meant to be an
inter-process mutex (see
https://github.com/takano-akio/filelock/issues/2#issuecomment-275041129).
This change protects multiple writers from concurrently modifying the secret key
file (`secret.key` by default). It does so by using System.FileLock's
inter-process mutexes as intended.

CSLA-25: Fix UserSecret file locking in Windows.

---

cardano-sl.cabal
src/Pos/Crypto/Random.hs
stack.yaml

* remove HsOpenSSL from dependency (easier build on osx)
* move to cryptonite-openssl 0.5
* fix issue with openssl configured without GF2m curves in cryptonite-openssl 0.3

Update random generation from HsOpenSSL to cryptonite-openssl

---

scripts/common.sh
scripts/updateScenario.sh

They were running wrong/old binaries when `stack` was used with `nix` (and other use cases)

Fix scripts

---

daedalus/src/Daedalus/BackendApi.purs
daedalus/src/Daedalus/ClientApi.purs
src/Pos/Aeson/ClientTypes.hs
src/Pos/Wallet/Web/Api.hs
src/Pos/Wallet/Web/ClientTypes.hs
src/Pos/Wallet/Web/Doc.hs
src/Pos/Wallet/Web/Server/Methods.hs
src/wallet-purescript/Main.hs

See details and how to use it here https://issues.serokell.io/issue/DAE-103#comment=96-2206

[DAE-103] Add on demand sync progress endpoint

---

cardano-sl.cabal

Explorer needs `getHeadersFromToIncl` function.

[CSE-20] Expose module Pos.Block.Logic

---

.gitignore

[DAE-107] ignore generated kademlia db files in git repo

---

update_haddock.sh

Now Haddock documentation has all external links.

Rebuilding of Haddock, without no-deps.

---

README.md
daedalus/src/Daedalus/BackendApi.purs
src/Pos/Wallet/Web/Api.hs
src/Pos/Wallet/Web/Doc.hs
src/Pos/Wallet/Web/Server/Methods.hs

Added default 'skip' and 'limit' options, added a small section on README for running the wallet, updated the daedalus-bridge REST api.

[CSM-113] refactored REST api

---

src/Pos/Wallet/Web/Server/Methods.hs

[CSM-113] fixed tabs to spaces.

---

src/Pos/Binary/Communication.hs

optimise small integer message name serialization by adding a special
tag, otherwise leave things as is

CSL-718 - Optimise peerdata serialization

---

.travis.yml
README.md
docs/wallet-web-api.md
src/Pos/Wallet/Web/ClientTypes.hs
src/Pos/Wallet/Web/Doc.hs
src/wallet-web-docs/Main.hs

Working docs generation, added `docs` folder for the destination.

[CSM-146] Fix api docs.

---

src/Pos/Txp/Logic/Local.hs
src/Pos/Txp/Toil/Class.hs
src/Pos/Txp/Toil/DBTxp.hs
src/Pos/Txp/Toil/Failure.hs
src/Pos/Txp/Toil/Logic.hs
src/Pos/Txp/Toil/Trans.hs
src/Pos/Txp/Toil/Types.hs
src/Pos/Txp/Toil/Utxo/Pure.hs

Transaction size check has been added to Toil by introducing `MonadToilEnv` class.

[CSL-862] Add transaction size check to Txp

---

.travis.yml
README.md
appveyor.yml
daedalus/default.nix
daedalus/package.json
shell.nix

Superseeds https://github.com/input-output-hk/cardano-sl/pull/107

[WIP] Improve build (fix appveyor)

---

daedalus/src/Daedalus/BackendApi.purs
daedalus/src/Daedalus/ClientApi.purs
daedalus/src/Daedalus/Types.purs
src/Pos/Wallet/Web/ClientTypes.hs
src/Pos/Wallet/Web/Doc.hs
src/Pos/Wallet/Web/Server/Methods.hs

Tested with:
```
GET localhost:8090/api/profile
{
"Right": {
"cpLocale": ""
}
}
POST localhost:8090/api/profile
{
"cpLocale": "en-US"
}
GET localhost:8090/api/profile
{
"Right": {
"cpLocale": "en-US"
}
}
POST localhost:8090/api/profile
{
"cpLocale": "hr-HR"
}
GET localhost:8090/api/profile
{
"Right": {
"cpLocale": "hr-HR"
}
}
```

[CSM-156] Endpoints for getting and updating users language/locale

---

src/Pos/Ssc/GodTossing/Core/Core.hs
src/Pos/Types/Block/Instances.hs
src/keygen/Testnet.hs

Here I fixed a bug in `genesis.bin` generator and slightly improved logging which was useful for debugging.

[CSL-933] Fix genesis vss certs

---

.travis.yml
daedalus/src/Daedalus/ClientApi.purs

Temp change needed for release until UI implements the change.

[CSM-189] Disable spending password feature

---

.travis.yml
daedalus/default.nix
update_wallet_web_api_docs.sh

Fixes https://travis-ci.org/input-output-hk/cardano-sl/jobs/218426297#L4111

daedalus bridge: use nodejs 7.X

---

src/Pos/Binary/Genesis.hs
src/Pos/CLI.hs
src/Pos/Genesis.hs
src/Pos/Genesis/Arbitrary.hs
src/Pos/Genesis/Types.hs
src/Pos/Launcher/Options.hs
src/keygen/Testnet.hs
src/node/Main.hs
src/smart-generator/Main.hs
src/wallet/Main.hs

Add the opportunity to make two-level (rich and poor) distributions like in testnet, but in development mode.

Feature/csl978:  Rich'n'Poor distribution for development mode 

---

cardano-sl.cabal
daedalus/yarn.lock
src/Pos/Explorer.hs
src/Pos/Update.hs

- `Pos.Explorer.Core.Types`
- `Pos.Explorer.Txp.Toil.Types`
- `Pos.Explorer.DB`
All these modules are needed by `cardano-sl-explorer`

[CSE-67] Expose modules

---

src/Pos/Txp/DB/Utxo.hs

[CSL-810] Don't store genesis utxo in DB

---

daedalus/src/Daedalus/ClientApi.purs

https://input-output-rnd.slack.com/archives/G2FTCSW69/p1492100587626361
`isValidRedemtionKey` -> `isValidRedemptionKey`
`isValidPaperVendRedemtionKey` -> `isValidPaperVendRedemptionKey`

[CSM-204] Fix typo

---

core/Pos/Core/Timestamp.hs

Greek letter mu breaks things.

[CSM-208] Don't print Greek letter mu to the console

---

src/Pos/Client/Txp/Balances.hs
src/Pos/Wallet/WalletMode.hs

It's left to consider mempool transactions while counting balances. CPU usage is gone completely though.

[CSL-211] Use balances DB when counting balances for wallets WIP

---

stack.yaml

Fix time-warp-np/NTP.Client. Bump up kademlia and time-warp-nt

[CSL-1015] Fix bad address (Win)

---

src/Pos/Block/Network/Logic.hs

[CSE-72] Add some logging

---

cardano-sl.cabal
src/Pos/Ssc/Type.hs
src/Pos/Wallet/SscType.hs
src/Pos/Wallet/Web/Server/Full.hs
src/Pos/Wallet/Web/Server/Lite.hs
src/Pos/Wallet/Web/Server/Methods.hs
src/Pos/Wallet/Web/State/Storage.hs
stack.yaml

Removed `ssc` type param, just for _wallet web_.

[CSM-216] Remove ssc type param

---

core/cardano-sl-core.cabal
db/cardano-sl-db.cabal
infra/cardano-sl-infra.cabal
lrc/cardano-sl-lrc.cabal
util-scripts/update-cabal-versions.sh

I also bumped some 0.3.0.0 -> 0.3.0 so they all look the same.
cc @gromakovsky

[CSL-1059] Add update version script

---

scripts/analyze/blocks.sh
src/Pos/Block/Logic.hs
src/Pos/Block/Network/Announce.hs
src/Pos/Block/Network/Logic.hs

See commit descriptions. This should stop node from infinitely asking something when receiving unexpected message (`Nothing` in `requestHeaders` in our case).

CSL-1043 Unexpected block/net logic responses handling

---

db/Pos/DB/Holder.hs
db/cardano-sl-db.cabal
infra/Pos/Slotting/Ntp.hs
src/Pos/Context/Holder.hs
stack.yaml

...with added `withSocketsDo` in NTP

[CSL-959] Bump time-warp-nt

---

stack.yaml

It allowed to do some clean-up in stack.yaml.
@domenkozar allowed me to do it as long as CI passes. This PR will show it :)

[CSL-1079] Switch to LTS-8.12

---

cardano-sl.cabal

Needed for https://github.com/input-output-hk/iohk-nixops/pull/33

[DEVOPS-82] Using gold linker like that breaks Nix

---

src/Pos/Txp/Core/Types.hs

Should be merged before https://github.com/input-output-hk/cardano-sl/pull/304.

[CSM-224] Export TxOut Prism

---

daedalus/src/Daedalus/BackendApi.purs
daedalus/src/Daedalus/ClientApi.purs

Documentation reflecting changes on https://github.com/input-output-hk/cardanodocs.com/blob/task/csld19-hd-wallets/_docs/technical/2017-01-08-wallet-frontend.md

CSM-255 Invalid isValidAddress, added missing documentation

---

DeployCluster.hs

This is a Haskell-based script for deploying a new Cardano SL cluster on `cardano-deployer` server.

Script to deploy a new cluster from scratch.

---

daedalus/src/Daedalus/Types.purs

See https://issues.serokell.io/issue/CSM-257#comment=96-3661

[CSM-257] Fix error message

---

daedalus/src/Daedalus/BackendApi.purs
daedalus/src/Daedalus/ClientApi.purs

https://issues.serokell.io/issue/CSE-143
Also added `deleteWalletSet` endpoint from https://github.com/input-output-hk/cardano-sl/pull/365.

CSE-143 Update comments in ClientApi.purs, added delete walletset.

---

daedalus/src/Daedalus/BackendApi.purs
daedalus/src/Daedalus/ClientApi.purs
daedalus/src/Daedalus/Types.purs
src/Pos/Aeson/ClientTypes.hs
src/Pos/Wallet/Web/Account.hs
src/Pos/Wallet/Web/Api.hs
src/Pos/Wallet/Web/BListener.hs
src/Pos/Wallet/Web/ClientTypes.hs
src/Pos/Wallet/Web/Server/Methods.hs
src/Pos/Wallet/Web/State/State.hs
src/Pos/Wallet/Web/State/Storage.hs
src/Pos/Wallet/Web/Tracking.hs
src/wallet-purescript/Main.hs
src/wallet-web-api-swagger/Main.hs

Some stuff remained untouched or was renamed incorrectly.
It was already fixed in cardano docs, now fixing it here.

[CSM-249] More wallet renamings

---

src/Pos/Wallet/Web/Account.hs
src/Pos/Wallet/Web/ClientTypes.hs
src/Pos/Wallet/Web/Server/Methods.hs
src/Pos/Wallet/Web/State/Storage.hs

_Hardcore only_
This task actually contains three lines of CSM-265 and remaining is the fourth iteration of CSM-249

[CSM-265] Add `isUsed` field to `CAddress`

---

util-scripts/build-client-api.sh
util-scripts/build-daedalus-bridge.sh

Issue: https://issues.serokell.io/issue/CSM-269
This fixes problems with documentation building https://github.com/input-output-hk/cardanodocs.com/pull/15

[CSM-269] Fix client api build script

---

.travis.yml
util-scripts/travis.sh

Superseeds https://github.com/input-output-hk/cardano-sl/pull/346

[DEVOPS-107] Fix CI

---

src/Pos/Genesis.hs
src/Pos/Wallet/Web/ClientTypes.hs
src/Pos/Wallet/Web/Server/Methods.hs

This also fixes smth in genesis HD addresses

[CSM-273] Add isOutgoing flag to returned transaction info

---

util-scripts/recover-from-stack-clean.sh

Please see the comment in the script.

Add `stack clean` recovery script

---

daedalus/src/Daedalus/BackendApi.purs
daedalus/src/Daedalus/ClientApi.purs

Update to https://github.com/input-output-hk/cardano-sl/pull/927 (changes in daedalus bridge weren't added to this PR)

[CSM-278] Update purescript-bridge to comply with changed API

---

src/Pos/Wallet/Web/Api.hs
src/Pos/Wallet/Web/ClientTypes.hs
src/Pos/Wallet/Web/Server/Methods.hs
src/Pos/Wallet/Web/Tracking.hs

This also implements `isUsed` wallet address field properly

[CSM-279] Don't remove spent wallet addresses

---

scripts/launch.sh
src/Pos/Wallet/Web/Server/Full/R.hs
src/Pos/Wallet/Web/Server/Methods.hs

Looks like I lost it in `master`, cherry-picking to `0.5`

[CSM-282] Don't add default wallet in non- wallet-debug mode

---

src/Pos/Block/Logic/Internal.hs
src/Pos/Client/Txp/History.hs
src/Pos/Explorer/Txp/Local.hs
src/Pos/WorkMode.hs
src/Pos/WorkMode/Class.hs
txp/Pos/Txp/Logic/Local.hs
txp/Pos/Txp/MemState/Class.hs
txp/cardano-sl-txp.cabal

Version of #953 for cardano-sl-0.5-rc.

[CSL-1201] Guard the state modifying STM action with a mutex

---

src/Pos/Wallet/Web/Server/Methods.hs
src/Pos/Wallet/Web/State/Acidic.hs
src/Pos/Wallet/Web/State/State.hs
src/Pos/Wallet/Web/State/Storage.hs

[CSM-301] Rename params for new hierarchy - 0.5-rc

---

src/launcher/Main.hs

by creating an external bat script and terminating cardano-launcher
before running updater

Fix csl-1129

---

src/Pos/Wallet/Web/Server/Methods.hs
src/Pos/Wallet/Web/State/Acidic.hs
src/Pos/Wallet/Web/State/State.hs
src/Pos/Wallet/Web/State/Storage.hs

Similar PR based on `cardano-sl-0.5-rc` is already accepted, revert this one to avoid conflicts

Revert "[CSM-301] Rename params for new hierarchy"

---

src/Pos/Util/UserSecret.hs
src/Pos/Wallet/Web/Error/Util.hs
src/Pos/Wallet/Web/Server/Methods.hs
src/keygen/Avvm.hs
src/keygen/Main.hs

Only `File does not exist` now is reported as `RequestError`, all other exceptions are `InternalError`s

[CSM-297] Catch from importWallet nicely

---

infra/Pos/Slotting/Types.hs
update/Pos/Binary/Update.hs
update/Pos/Update/Poll/RollTrans.hs
update/Pos/Update/Poll/Types.hs

I forgot to add this logic to 'RollT' when I added 'SlottingData' to Poll.

[CSL-1222] Fix slotting data processing in 'RollT'

---

src/Pos/Wallet/Web/Server/Methods.hs

This makes two things:
1. `changeWalletPass` endpoint does nothing if pass doesn't change.
It's important, since it creates accounts which correspond to new pass,
then sends money to them and removes new accounts. In case when new pass is same
as old pass, new accounts are also the same and everything goes bad.
2. Now, on pass change, old accounts are not totally removed from db,
but just marked as _removed_ - that's needed for correct transaction history
fetching.
(Note: technique to not actually remove addresses is exploited for a long time, I just now use it in relevant place of pass changing logic as well)

[CSM-307] Fix `importWallet`

---

src/Pos/Wallet/Web/ClientTypes.hs

Previously this case wan't considered, and error was thrown

[CSM-307] Take txs from other wallet into account for tx amount evaluation

---

db/Pos/DB/Redirect.hs
lrc/Pos/Lrc/Core.hs
src/Pos/Block/Logic/Creation.hs
src/Pos/DB/GState/GState.hs
src/Pos/Lrc/Worker.hs

I've merged https://github.com/input-output-hk/cardano-sl/pull/982 too early, so here comes some cosmetic changeset.

[CSL-1209] Cosmetics

---

core/Pos/Crypto/SafeSigning.hs
src/Pos/Util/Servant.hs
src/Pos/Wallet/Web/Api.hs
src/Pos/Wallet/Web/ClientTypes.hs
src/wallet-web-api-swagger/Main.hs

This allows to nicely support optional parameters of requests by means of servant-api

[CSM-291] Add `DefaultApiArg`

---

src/Pos/Wallet/Web/ClientTypes.hs

Now, when tx history of source wallet of such transaction is requested,
we don't show incoming part of transaction (one if `isOutgoing` flag set to true).
It worked incorrect because presence of change address made that transaction
displayed.
Tested with
1. Sending money between wallets
2. Sending money within same account

[CSM-310] Fix history derivation for inter-wallet txs

---

stack.yaml

Switch to time-warp-nt/master

---

scripts/ci/travis.sh

Disable Haddock, again :(

---

daedalus/bower.json
daedalus/src/Daedalus/BackendApi.purs
src/Pos/Block/Worker.hs
src/Pos/Launcher/Scenario.hs

Merge/cardano sl 0.5 rc

---

stack.yaml

I took the commit which was used before (a85eee0610) and
cherry-picked Misha's fix there. My commit is some arbitary commit,
but it's not worse than it was before.

[CSL-1286] Fix Production in node-sketch

---

txp/Pos/Txp/Core/Core.hs
txp/Pos/Txp/Core/Types.hs
txp/Pos/Txp/Toil/Utxo/Functions.hs

I'm not sure whether anything else needs to be done regarding this task, but I grepped for `PubKeyAddress` and these were the only places that looked like they needed to be changed.

[CSL-1202] Allow non-empty distribution for PubKeyAddress

---

cardano-sl.cabal
scripts/common-functions.sh
src/Pos/Launcher/Param.hs
src/Pos/Launcher/Runner.hs
src/Pos/Statistics.hs
src/Pos/Statistics/Ekg.hs
src/Pos/Statistics/Statsd.hs
src/Pos/Util/JsonLog.hs
src/node/NodeOptions.hs
src/node/Params.hs
src/smart-generator/Main.hs
src/wallet/Main.hs

Port of #368.
Where do you want the `--with-rtsopts=-T`? For all the executables in cardano-sl.cabal?

Port ekg statsd to cardano-sl-0.5-rc

---

src/Pos/Wallet/Web/Account.hs
src/Pos/Wallet/Web/Server/Methods.hs
src/Pos/Wallet/Web/State/Storage.hs
src/Pos/Wallet/Web/Tracking.hs
update/Pos/Update/Poll/Logic/Rollback.hs

Merged PRs are: #1031 and #1034. After this PR is merged we should merge #1013 also.

Merge 0.5-rc

---

src/Pos/Wallet/Web/Server/Methods.hs

When fetching addresses of account, all addresses related to txs in mempool,
even ones from other accounts, were taken. Thus, money sending destination
address temporally appeared in all accounts.

[CSM-326] Fix money sent amount being temporaly doubled

---

src/Pos/Wallet/Web/Server/Methods.hs

Do it only on wallet restore.
Tested with daedalus and postman. 
Wallet restoration still takes 20-60 sec

[CSM-336] Do not traverse blockchain on `newWallet`

---

src/Pos/Wallet/Web/Api.hs
src/Pos/Wallet/Web/Server/Methods.hs

* Introduce endpoint for getting fee for transaction (with according to current fee policy)

[CSM-275] Add tx fee endpoint

---

cardano-sl.cabal
src/Pos/Block/BListener.hs
src/Pos/Block/Logic/Slog.hs
src/Pos/Explorer/BListener.hs
src/Pos/Explorer/DB.hs
src/Pos/Wallet/Web/BListener.hs

https://issues.serokell.io/issue/CSE-162
The backend work for CSE-162. The code could be better, I need to check `onApplyPageBlocksExplorer`, but I presume this is a general idea?

CSE-162 explorer slow blocks

---

infra/Pos/Communication/Relay/Logic.hs

[CSL-1312] Fix tx mempool listener

---

cardano-sl.cabal
scripts/generate/certificates.sh
src/Pos/Block/BListener.hs
src/Pos/Block/Logic/Slog.hs
src/Pos/Explorer/BListener.hs
src/Pos/Explorer/DB.hs
src/Pos/Wallet/Web/BListener.hs
src/Pos/Wallet/Web/Server/Methods.hs

Merge to `master`. I hope this is what you were asking for:
```
git checkout master
git pull --ff-only
git checkout -b ksaric/merge-CSE-162-Explorer-slow-blocks-to-master
git merge 75f7c7f8a549af1e37acdbd6d3d66b68bb0e6643
-- fixed conflicts
git add --all
git commit
git push --set-upstream origin ksaric/merge-CSE-162-Explorer-slow-blocks-to-master
```
Some other commits are on this merge since I pulled them from `master` when working on the branch.

CSE-162 explorer slow blocks to master

---

src/Pos/Wallet/Web/Api.hs
src/Pos/Wallet/Web/Server/Methods.hs

Issue: https://issues.serokell.io/issue/CSM-333

[CSM-333] Enable testReset endpoint in production

---

core/Pos/Binary/Crypto.hs
core/Pos/Core/Genesis.hs
core/Pos/Crypto/HD.hs
core/Pos/Crypto/SafeSigning.hs
core/Pos/Crypto/Signing.hs
src/Pos/Util/BackupPhrase.hs
src/Pos/Wallet/Web/Account.hs
stack.yaml
txp/Pos/Script/Examples.hs

Reverts input-output-hk/cardano-sl#1035

Revert "[CSL-1080] Use BIP32 cardano-crypto"

---

src/Pos/Client/Txp/History.hs
src/Pos/Explorer/Txp/Local.hs
src/Pos/Wallet/Light/Redirect.hs
src/Pos/Wallet/Web/BListener.hs
src/Pos/Wallet/Web/Server/Methods.hs
src/Pos/Wallet/Web/State/State.hs
src/Pos/Wallet/Web/State/Storage.hs
src/Pos/Wallet/Web/Tracking.hs
txp/Pos/Txp/Toil/Utxo.hs

See https://github.com/input-output-hk/cardano-sl/pull/1083

[CSM-332] Rewrite tx history - version for 0.5 release

---

daedalus/src/Daedalus/BackendApi.purs
daedalus/src/Daedalus/ClientApi.purs
src/Pos/Client/Txp/Util.hs
src/Pos/Wallet/Web/Api.hs
src/Pos/Wallet/Web/Server/Methods.hs

* Fix fee api: passphrase isn't required anymore

[CSM-275] Dummy endpoint for transaction fees

---

src/Pos/Block/Network/Logic.hs
src/Pos/Block/Network/Retrieval.hs
src/Pos/Block/RetrievalQueue.hs

[CSL-1327] Fix block retrieval and recovery mode

---

src/Pos/Client/Txp/Balances.hs

Cached filtered utxo doesn't contain outputs for redeem addresses, thus redeeming doesn't work.

[CSM-351] Use DB utxo for redeem addresses 

---

scripts/launch/staging.sh

Update start time in staging script

---

src/Pos/Explorer/BListener.hs

Merge to `master` from `cardano-sl-0.5` - https://github.com/input-output-hk/cardano-sl/pull/1131

CSE-178 reverse db block order to master

---

core/Pos/Binary/Core/Types.hs
core/Pos/Core/Arbitrary.hs
core/Pos/Core/BlockVersionData.hs
core/Pos/Core/Constants/Raw.hs
core/Pos/Core/Constants/Typed.hs
core/Pos/Core/Types.hs
core/constants.yaml
lwallet/Main.hs
src/Pos/SafeCopy.hs
test/Test/Pos/Types/Identity/BinarySpec.hs
update/Pos/Binary/Update.hs
update/Pos/Update/Arbitrary/Core.hs
update/Pos/Update/Core/BlockVersion.hs
update/Pos/Update/Core/Types.hs
update/Pos/Update/DB.hs
update/Pos/Update/Poll/Logic/Apply.hs
update/Pos/Update/Poll/Logic/Base.hs
update/Pos/Update/Poll/Logic/Softfork.hs
update/Pos/Update/Poll/Logic/Version.hs
update/Pos/Update/Poll/Trans.hs
update/Pos/Update/Poll/Types.hs

See the issue's [description](https://issues.serokell.io/issue/CSL-1335). It's fully specified there, I just implemented it.

[CSL-1335] Decrease threshold in softfork resolution rule over time 

---

.travis.yml
core/Pos/Util/Config/Contents.hs
core/Pos/Util/Config/Get.hs
core/cardano-sl-core.cabal
daedalus/default.nix
default.nix
lib.nix
nixpkgs-src.json
pkgs/default.nix
pkgs/generate.sh
release.nix
scripts/check-stack2nix.sh
scripts/set_nixpath.sh
shell.nix
stack2nix-src.json

this PR allows hydra to build every PR for cadrano-sl, and report test pass/failure back to github

[DEVOPS-32] initial hydra jobset

---

core/constants.yaml
infra/Pos/Communication/Constants.hs
infra/Pos/Communication/Util.hs
infra/Pos/Infra/Constants.hs

+ remove `networkReceiveTimeout`
+ make `networkWaitLogInterval` configurable (not hardcoded 4s)

[CSL-1318] Remove networkReceiveTimeout

---

src/Pos/Explorer/BListener.hs
src/Pos/Explorer/DB.hs

https://issues.serokell.io/issue/CSE-158
Seems to work.

CSE-158 tx feed delay

---

src/Pos/Wallet/Web/Server/Methods.hs
src/Pos/Wallet/Web/Tracking.hs

Copy of https://github.com/input-output-hk/cardano-sl/pull/1152 for to provide fix for 0.5 release

[CSM-363, CSM-364] Fix bugs in JSON import/export (version for 0.5 branch)

---

src/Pos/Block/Logic/Internal.hs
src/Pos/Delegation/Logic/VAR.hs

[CSL-1354] Introduce dlgNormalize

---

src/Pos/Explorer/BListener.hs
src/Pos/Explorer/DB.hs

https://issues.serokell.io/issue/CSE-158
PR to `master` from https://github.com/input-output-hk/cardano-sl/pull/1140

CS-158 tx feed delay to master

---

lwallet/WalletOptions.hs

Fixes https://github.com/input-output-hk/cardano-sl/pull/1172#pullrequestreview-50289746

[CSM-233] Fix TLS CA options name

---

CODEOWNERS

I added `CODEOWNERS` file and put some stuff which came into my mind there 🤷‍♂️ 
See https://github.com/blog/2392-introducing-code-owners for more info.

[CSL-1392] Add CODEOWNERS

---

src/Pos/Explorer/DB.hs
txp/Pos/Txp/Toil/Utxo/Util.hs

This function is needed in Explorer.

[CSE-182] Extract utxoToAddressCoinPairs to a separate function

---

infra/Pos/Communication/Protocol.hs
infra/Pos/Communication/Relay/Logic.hs
infra/cardano-sl-infra.cabal
lwallet/Pos/Wallet/Light/Launcher/Runner.hs
lwallet/Pos/Wallet/Light/Mode.hs
src/Pos/Communication.hs
src/Pos/Communication/Types.hs
src/Pos/Launcher/Resource.hs
src/Pos/Launcher/Runner.hs
src/Pos/Wallet/WalletMode.hs
src/Pos/Wallet/Web/Mode.hs
src/Pos/WorkMode.hs
src/Pos/WorkMode/Class.hs
ssc/Pos/Ssc/Mode.hs
update/Pos/Update/Mode.hs

stylish-haskell changed imports indentation. I can revert it if needed.

[CSL-1369] Remove Pos.Communication.PeerState

---

src/Pos/GState/BlockExtra.hs

Fixed some inefficiency in the `foldlUpWhileM`, further investigation after switching to `cbore`

[CSM-361] Profile and optimize wallet sync

---

.travis.yml
appveyor.yml
scripts/launch/staging.sh
src/Pos/Wallet/Redirect.hs
src/Pos/Wallet/Web/BListener.hs

This fixes the bug by:
1) Fixing `localChainDifficulty`, which stopped representing actual blockchain syncing progress after last changes in blockchain recovery
2) Making sure that `BListener`s are not applied to wallets when it's inappropriate to do so.

[CSM-377] Fix "Not enough money" bug

---

core/Pos/Core/Genesis/Types.hs
db/Pos/DB/Class.hs
lwallet/Main.hs
lwallet/Pos/Wallet/Light/Launcher/Param.hs
lwallet/Pos/Wallet/Light/Launcher/Runner.hs
lwallet/Pos/Wallet/Light/Mode.hs
lwallet/Pos/Wallet/Light/State/Acidic.hs
lwallet/Pos/Wallet/Light/State/Storage.hs
src/Pos/Client/Txp/History.hs
src/Pos/Client/Txp/Util.hs
src/Pos/Communication/Tx.hs
src/Pos/Context/Functions.hs
src/Pos/Explorer/DB.hs
src/Pos/Genesis.hs
src/Pos/Launcher/Scenario.hs
src/Pos/Wallet/WalletMode.hs
src/Pos/Wallet/Web/Tracking.hs
src/node/Params.hs
test/Test/Pos/Block/Logic/Mode.hs
tools/src/block-gen/Main.hs
txp/Pos/Txp/DB/Balances.hs
txp/Pos/Txp/DB/Utxo.hs
txp/Pos/Txp/Toil/Types.hs

I checked that payments API works in postman (transaction is added to blocks) and that tests pass (CI checks it too).
Need to check lwallet (first need to figure out how to do it). I don't see a way I could break it, but I will check.
Also I had to comment out some code after I realized that CSL-1351 wasn't implemented yet.

CSL-1292 Enable bootstrap era in development mode 

---

src/Pos/Communication/Tx.hs

This adds conditional `txDistr` in boot epoch for redeeming trasactions.

[CSL-1409] Override txdistr (boot era) in redeemtx creation

---

scripts/generate/genesis.sh

Print commit when creating genesis

---

scripts/launch/demo.sh

Adds relative paths in demo , fixes launching from different path then cardano-sl repo

Fix launching demo for explorer. Add relative paths

---

src/Pos/Wallet/Web/BListener.hs
src/Pos/Wallet/Web/Tracking.hs

[CSM-393] Fix txs timestamps set in BListener

---

src/Pos/Wallet/Web/Server/Methods.hs

[CSM-389] Modify syncTip under blkSemaphore

---

src/Pos/Wallet/Web/BListener.hs
src/Pos/Wallet/Web/ClientTypes.hs
src/Pos/Wallet/Web/Server/Methods.hs
src/Pos/Wallet/Web/Tracking.hs

This includes changes made in CSM-352 (+ CSM-392), CSM-393, CSM-389

Merge cardano-sl-0.5 to master

---

CHANGELOG.md

Added information to CHANGELOG.md

---

db/Pos/DB/Functions.hs
lrc/Pos/Lrc/DB/Issuers.hs

Apart from this fix I also performed a small refactoring during initial investigation.

[CSL-1444] Fix 'isInitialized' check in Issuers part of LRC DB

---

core/Pos/Binary/Class/TH.hs

See https://issues.serokell.io/issue/CSL-1448 for context.
After consulting with @neongreen , we opted for removing `Unused` and its logic from the `Binary.Class.TH` module, as it's incomplete and we can always retrieve it back from `git` history when and if we decide to resume working on it.

[CSL-1448] Remove `Unused` constructor from deriveSimpleBi

---

scripts/bench/runbench.sh
scripts/launch/demo.sh

use "flat" to get the flat distribution, anything else to get a
rich-poor distribution.

demo script distribution parameter

---

core/Pos/Core/Constants/Raw.hs
core/constants.yaml
lwallet/WalletOptions.hs
src/Pos/CLI.hs
src/Pos/Wallet/Web/Server/Full.hs
src/Pos/Wallet/Web/Server/Methods.hs
src/Pos/Web.hs
src/Pos/Web/Server.hs
src/Pos/Web/Types.hs
src/node/Main.hs
src/node/NodeOptions.hs

CSL-217: added a flag into constants, which enables/disables requests logging. Tested w and w/o this flag set.
Currently flag is always on, because we have no mainnet mode.
CSM-374: Added type with TLS parameters

[CSL-217 (CSM-397)] [CSM-374] Web stuff

---

bench/Bench/Pos/Criterion/TxSigningBench.hs
core/Pos/Binary/Core/Script.hs
core/Pos/Core/Script.hs
core/Pos/Crypto/SignTag.hs
src/Pos/Client/Txp/Util.hs
src/Pos/Generator/Block/Payload.hs
stack.yaml
test/Test/Pos/Txp/Toil/UtxoSpec.hs
txp/Pos/Arbitrary/Txp.hs
txp/Pos/Binary/Txp/Core.hs
txp/Pos/Script.hs
txp/Pos/Script/Examples.hs
txp/Pos/Txp/Core/Types.hs
txp/Pos/Txp/Toil/Utxo/Functions.hs
txp/cardano-sl-txp.cabal

This one should actually work probably.

[CSL-1068] Use new Plutus

---

src/Pos/Client/Txp/History.hs
src/Pos/Wallet/Web/BListener.hs
src/Pos/Wallet/Web/Tracking.hs

Contains changes which modify logging in wallet

Merge cardano-0.5

---

default.nix
pkgs/generate.sh

Always generate packages for linux, we handle macos as a special case.

[DEVOPS-249] cabal2nix macos improvements

---

infra/Pos/Network/Types.hs
pkgs/default.nix
stack.yaml

Needs https://github.com/serokell/time-warp-nt/pull/88 .

Clear reset failures on SIGHUP

---

scripts/launch/wallet.sh

You can use wallet.sh and it will generate a proper command now.
However, I don't know how to properly execute it from bash.
So current approach is to copy it and execute manually.

CSL-1277 Make wallet.sh almost usable

---

scripts/ci/travis.sh

We have no macOS developers in explorer team (at the moment).
cc @ksaric @akegalj @sectore please confirm if so :)

[DEVOPS-265] Don't build explorer on macOS

---

explorer/frontend/scripts/build-explorer-frontend.sh

https://issues.serokell.io/issue/CSE-202
Fixing building the frontend.

CSE-202 Fix compile scripts

---

scripts/launch/demo.sh

This prevents nodes from trying to communicate with each other before
all the nodes have started up.

demo.sh: start system 30 seconds in the future

---

infra/Pos/Network/CLI.hs
infra/Pos/Network/Types.hs
infra/Pos/Network/Yaml.hs
infra/Pos/Subscription/Common.hs
infra/Pos/Subscription/Dht.hs
src/Pos/Communication/Server.hs

This PR looks bigger than it is because it depends on the not-yet-merged https://github.com/input-output-hk/cardano-sl/pull/1286 .

Limit subscribers

---

daedalus/bower.json
daedalus/yarn.lock

Fix CI issue to fix `bower` dependency

---

infra/Pos/Slotting/Impl/Simple.hs
update/Pos/Update/Poll/Logic/Base.hs

https://issues.serokell.io/issue/CSL-1537
@pva701 Already warned me about this in the review, but I decided to obey the tests - https://github.com/input-output-hk/cardano-sl/pull/1217#discussion_r131148737
I can't find any mention of the error in issue - `grep -r --exclude-dir={.stack-work,.git} "epoch is surprisingly unknown" /home/ksaric/projects/curry/cardano-sl/logs/2017-08-23_001513`
And using `./scripts/launch/demo-with-wallet-api.sh` I can reach `11th slot of 8th epoch`. I'll leave it until morning, but I think this is good.

CSL-1537 Protocol stops after epoch #1.

---

node/src/Pos/Generator/Block/Logic.hs
node/src/Pos/Generator/Block/Param.hs
node/src/Pos/Generator/Block/Payload.hs
node/src/Pos/Generator/BlockEvent.hs
node/test/Test/Pos/Block/Logic/Util.hs
tools/src/block-gen/Main.hs

This fixes bugs and bad design decisions that led to unusable block-gen.

[CSL-1530] Repair blockgen

---

node/src/Pos/Client/CLI/NodeOptions.hs

It's inferred from the topology file.

Removed deprected node-type argument

---

infra/Pos/Communication/Listener.hs
infra/Pos/Communication/Relay/Logic.hs
infra/Pos/Subscription/Common.hs
node/src/Pos/Block/Network/Listeners.hs
node/src/Pos/Communication/Server.hs
node/src/Pos/Launcher/Runner.hs

@dcoutts @avieth We should be on the right track now! 🙏 
Full context: https://issues.serokell.io/issue/TW-160

[TW-160] Reset failure state from listeners eagerly

---

core/Pos/Core/Types.hs
node/src/Pos/Client/Txp/Util.hs
txp/Pos/Txp/Core/Types.hs

Factoring out some cosmetic changes from my PR for CSM-399.

Cosmetic changes

---

node/test/Test/Pos/Block/Logic/Mode.hs

DIscussed with @pva701 in https://serokell.slack.com/archives/G3B0JT7AL/p1503408142000651, he said it was okay to get rid of it.

[CSL-1564] Remove ssc from Test.Pos.Block.Logic.Mode

---

lwallet/Main.hs
node/src/Pos/Client/Txp/Util.hs
node/src/Pos/Communication/Tx.hs
node/src/Pos/Generator/Block/Payload.hs
wallet/src/Pos/Wallet/Web/Methods/Txp.hs

[CSL-1565] Refactor TxError

---

node/src/Pos/Delegation/Listeners.hs

[CSL-1545] Disable light delegation endpoints

---

infra/cardano-sl-infra.cabal
node/cardano-sl.cabal
node/test/Test/Pos/Network/Windows/DnsDomainsSpec.hs
pkgs/default.nix
stack.yaml

@rockbmb Let's start from here in debugging what's going on 😉 
Hopefully the CI will give us some insight!

[CSL-1542] Fix DNS lookups on Windows

---

core/Pos/Core/Constants/Raw.hs
core/constants.yaml
infra/Pos/Reporting/Methods.hs
infra/Pos/Reporting/Metrics.hs
infra/Pos/Slotting/Util.hs
infra/cardano-sl-infra.cabal
node/src/Pos/Block/Logic/Creation.hs
node/src/Pos/Block/Logic/Util.hs
node/src/Pos/Block/Slog/Context.hs
node/src/Pos/Block/Slog/Logic.hs
node/src/Pos/Block/Slog/Types.hs
node/src/Pos/Block/Worker.hs
node/src/Pos/Context/Context.hs
node/src/Pos/GState/Context.hs
node/src/Pos/Generator/Block/Mode.hs
node/src/Pos/Launcher/Resource.hs
node/src/Pos/WorkMode.hs
node/src/Pos/WorkMode/Class.hs
node/test/Test/Pos/Block/Logic/Mode.hs
tools/src/block-gen/Context.hs
wallet/src/Pos/Wallet/Web/Mode.hs

I added three chain quality metrics: for last `k` blocks, overall chain quality and for fixed amount of time (set in `constants.yaml` file).
First two work, the last one doesn't (hence `wip` label).
These metrics use `DistrMonitor` feature added to `Pos.Reporting`.
Another reason why it's WIP is that apparently I needed to change distribution to gauge.

[CSL-1464] Expose chain quality to EKG

---

pkgs/default.nix

Bump default-nix

---

node/cardano-sl.cabal
node/src/Pos/Client/Txp/Util.hs
node/test/Test/Pos/Block/Logic/Mode.hs
node/test/Test/Pos/Client/Txp/Mode.hs
node/test/Test/Pos/Client/Txp/Util.hs
node/test/Test/Pos/Client/Txp/UtilSpec.hs

[CSM-399] Test createTx

---

node/src/Pos/Wallet/Web/ClientTypes/Functions.hs
node/src/Pos/Wallet/Web/ClientTypes/Types.hs
node/src/Pos/Wallet/Web/State/Acidic.hs
node/src/Pos/Wallet/Web/State/State.hs
node/src/Pos/Wallet/Web/State/Storage.hs
pkgs/default.nix
wallet/src/Pos/Wallet/Web/Methods/History.hs
wallet/src/Pos/Wallet/Web/Methods/Payment.hs
wallet/src/Pos/Wallet/Web/Methods/Redeem.hs

Added a flag to `CTx` which indicates, whether given transaction is local i.e. transfers money within same wallet

[CSM-415] Add 'ctIsLocal' flag

---

db/Pos/DB/GState/Common.hs
node/src/Pos/Block/Logic/Header.hs
node/src/Pos/GState/BlockExtra.hs
node/src/Pos/Launcher/Scenario.hs

Now first genesis block hash is printed on node start.

[CSL-1601] Add getFirstGenesisBlockHash info to scenario

---

godtossing/Pos/Ssc/GodTossing/Workers.hs
infra/Pos/Communication/Protocol.hs
infra/Pos/Shutdown/Logic.hs
infra/Pos/Shutdown/Types.hs
infra/Pos/Slotting/Util.hs
lwallet/Pos/Wallet/Light/Launcher/Runner.hs
node/src/Pos/Block/Network/Retrieval.hs
node/src/Pos/Block/Worker.hs
node/src/Pos/Delegation/Worker.hs
node/src/Pos/Launcher/Resource.hs
node/src/Pos/Launcher/Scenario.hs
node/src/Pos/Security/Workers.hs
node/src/Pos/Update/Worker.hs

It's basically #1163 ported to master and also removal of `fork` from `onNewSlot` as was discussed in that PR.

[CSL-1578]  Finish efforts on concurrency code refinement 

---

node/src/Pos/Client/CLI/NodeOptions.hs

They are unused and confusing.

[CSL-1627] Delete --peer-core and --peer-relay

---

node/src/Pos/Wallet/KeyStorage.hs

Issue had place because `addSecretKey` wasn't atomic, now it's fixed.
Tested with daedalus-bridge like in https://issues.serokell.io/issue/CSM-341#comment=96-7110, after fix making 2-4 new wallets concurrently works fine

[CSM-341] Race condition on `newWallet`

---

node/src/Pos/Wallet/Web/State/Acidic.hs
node/src/Pos/Wallet/Web/State/State.hs
node/src/Pos/Wallet/Web/State/Storage.hs
wallet/src/Pos/Wallet/Web/Methods/Backup.hs
wallet/src/Pos/Wallet/Web/Methods/Logic.hs
wallet/src/Pos/Wallet/Web/Methods/Restore.hs
wallet/src/Pos/Wallet/Web/Tracking/Sync.hs

This is WIP because I am still refining the endpoints for wallets that are not ready

[CSM-435] Wallet ready flag

---

pkgs/default.nix
wallet/src/Pos/Wallet/Web/Methods/History.hs

[CSM-455] Remove duplicated txs (cardano-sl-0.6)

---

wallet/src/Pos/Wallet/Web/Methods/History.hs

[CSM-455] Remove duplicated txs (master)

---

tools/src/keygen/Main.hs

Requested by @denisshevchenko.

[CSL-1654] Print full pubkeys in the keygen

---

daedalus/src/Daedalus/BackendApi.purs
daedalus/src/Daedalus/ClientApi.purs
pkgs/default.nix
wallet/src/Pos/Wallet/Web/Api.hs
wallet/src/Pos/Wallet/Web/Methods/Misc.hs
wallet/src/Pos/Wallet/Web/Server/Handlers.hs
wallet/src/Pos/Wallet/Web/Swagger/Description.hs

[CSM-458] Endpoint for postponing the update (version for RC)

---

auxx/src/Command/Run.hs

Fixed an inconvenience encountered by @volhovM.

Import keys from any types of keys

---

default.nix

@domenkozar there is now a profiling option, and hydra will pre-build everything with and without profiling

[DEVOPS-227] enable cardano profiling

---

mainnet-genesis-stub.json

Updated protocol magic, remove 6 testing 1-ADA addresses

Updated genesis mainnet stub

---

node/src/Pos/Client/CLI/Options.hs
pkgs/default.nix
wallet/node/Main.hs
wallet/node/NodeOptions.hs
wallet/src/Pos/Wallet/Web/Server/Launcher.hs
wallet/src/Pos/Wallet/Web/Server/Runner.hs

Required by Bittrex.
Issue here: https://issues.serokell.io/issue/CSM-460

[CSM-460] Expose Daedalus backend IP:PORT via walletAddress flag

---

auxx/src/Command/Parser.hs
auxx/src/Command/Run.hs
auxx/src/Command/Types.hs
core/Pos/Arbitrary/Core.hs
core/Pos/Core/Configuration/Core.hs
core/Pos/Core/Configuration/Protocol.hs
core/Pos/Core/Genesis/Types.hs
core/Pos/Core/Vss.hs
node/configuration.yaml
node/src/Pos/Client/CLI/Util.hs
node/src/Pos/Launcher/Configuration.hs
node/src/node/Main.hs
node/test/Test/Pos/Client/Txp/Mode.hs
txp/Pos/Txp/Toil/Logic.hs

Just a bunch of minor changes not affecting logic.

[CSL-1692] Clean-up after configuration refactoring

---

wallet/src/Pos/Wallet/Web/Methods/Misc.hs

After investigation with Ilya it turned out that `postponeUpdate` endpoint introduced in previous PRs is working as intended, the problem is that it doesn't get called by frontend for some reason. But then we came up with a solution which doesn't depend on frontend, which is filtering info about already installed updates by comparison with current software version.
PR has a WIP flag because it should be tested locally before merge (to avoid similar problems as before).

[CSM-465] Remove obsolete update info when querying `nextUpdate`

---

appveyor.yml
auxx/src/Command/Run.hs
auxx/src/Command/Tx.hs
core/Pos/Core/Constants.hs
core/cardano-sl-core.cabal
default.nix
explorer/scripts/build/cardano-sl.sh
explorer/src/explorer/Main.hs
infra/Pos/Slotting/Impl/Ntp.hs
node/src/Pos/Client/CLI/NodeOptions.hs
node/src/Pos/Client/CLI/Params.hs
node/src/Pos/Client/CLI/Secrets.hs
node/src/Pos/Client/CLI/Util.hs
node/src/Pos/Wallet/Web/Error/Util.hs
pkgs/default.nix
scripts/bench/buildbench.sh
scripts/build/cardano-sl.sh
scripts/common-functions.sh
tools/src/block-gen/Main.hs
tools/src/block-gen/Options.hs
wallet/src/Pos/Wallet/Web/Methods/Restore.hs

* Fix demo script
* Fix block-gen to accept configuration
* Add `use-genesis-secrets` to `block-gen`

[CSL-1666] Fix demo, get rid of dev-mode

---

node/src/Pos/Delegation/Logic/Common.hs

Basically the same as https://github.com/input-output-hk/cardano-sl/pull/1650, but targeting `cardano-sl-1.0`

[CSL-1703] Fix a memory leak in Pos.Delegation.Logic.Common

---

node/configuration.yaml
scripts/launch/connect-to-cluster/explorer-mainnet.sh
scripts/launch/connect-to-cluster/mainnet.sh

- commit mainnet genesis
- add connect script for it

[DEVOPS-373] edgenode mainnet connect script

---

explorer/README.md
explorer/src/Pos/Explorer/Socket/App.hs

needed by main-net. It is based on (original) PR for `master` branch: https://github.com/input-output-hk/cardano-sl/pull/1659

Cherry-pick of [CSE-232] Update cors policies

---

core/Pos/Util/Util.hs
explorer/src/Pos/Explorer/Aeson/ClientTypes.hs
explorer/src/Pos/Explorer/Web/Api.hs
explorer/src/Pos/Explorer/Web/ClientTypes.hs
explorer/src/Pos/Explorer/Web/Server.hs
explorer/src/Pos/Explorer/Web/TestServer.hs
explorer/src/documentation/Main.hs
node/src/Pos/Explorer/Core/Types.hs
node/src/Pos/Explorer/DB.hs
node/src/Pos/Explorer/Txp/Global.hs
node/src/Pos/Explorer/Txp/Local.hs
node/src/Pos/Explorer/Txp/Toil/Class.hs
node/src/Pos/Explorer/Txp/Toil/Logic.hs
node/src/Pos/Explorer/Txp/Toil/Types.hs

**DO NOT MERGE** until we resolve the issue with `scripts/launch/explorer-with-nodes.sh` (see https://serokell.slack.com/archives/G54P1SQCS/p1506639337000099 for details; I haven't been able to test it because this problem).
This is a continuation of https://github.com/input-output-hk/cardano-sl/pull/1639 with all commits cherry-picked and one more (the one which wraps `Micro` in `CAda`) added. Please note that due to the last change we need to re-test this PR.

[CSE-208, CSE-228] Total Ada endpoint

---

lib/configuration.yaml

[CSL-1713] add new field to all node confs

---

default.nix
pkgs/cryptonite-segfault-blake.patch

See upstream issue at https://github.com/haskell-crypto/cryptonite/issues/193

[DEVOPS-393] Fix segfault in cryptonite

---

scripts/set_nixpath.sh

related: https://github.com/NixOS/nixpkgs/issues/30070

temporary workaround for jq bug on darwin

---

daedalus/src/Daedalus/BackendApi.purs

same as #1712 but for the release branch

[CSM-483] Fix stream chunk handling in 'makeRequest'

---

.travis.yml
default.nix
nixpkgs-src.json
pkgs/default.nix
pkgs/generate.sh
pkgs/hfsevents.nix
stack.yaml

This brings in the following improvements with hope to reduce building
times:
- multiple outputs (closure size improvements)
- ld wrapper improvements (~10% faster builds)
https://hydra.iohk.io/jobset/serokell/cardano-pr-1642

[DEVOPS-355] Bump nixpkgs

---

lib/configuration.yaml
lib/src/Pos/Block/Network/Logic.hs
lib/src/Pos/Block/Network/Retrieval.hs
lib/src/Pos/Block/RetrievalQueue.hs
scripts/grep.sh

This is a clone of  #1670 pointed towards master.

[CSL-1706] Rework recovery to skip redundant queue elems

---

node/configuration.yaml
node/mainnet-genesis-dryrun-with-stakeholders.json

1. update dry-run genesis with the actual `rc-staging` `startTime`
2. update configuration.yaml with its hash

staging | configiration, genesis:  update to the actual deployment

---

appveyor.yml

To ship genesis and configuration.yaml files for frontend. Currently frontend hardcodes them, this PR will allow genesis/configuration.yaml changes to propagate via CI.

[DEVOPS-384] Reflect travis-ci changes also for appveyor

---

default.nix
release.nix

- build cardano-sl-wallet on CI
- build whole haskell dependency graph with profiling enabled
Superseeds https://github.com/input-output-hk/cardano-sl/pull/1612 with mergable fixes

[DEVOPS-359] Some fixes to profiling builds

---

appveyor.yml
default.nix
lib/configuration.yaml
lib/mainnet-genesis-dryrun-with-stakeholders.json
release.nix
shell.nix

This includes devops-related changes that bring master back to compilable state (with nix).

Merge csl 1.0 master

---

lib/src/Pos/Block/Network/Logic.hs

There is no 'queryBlocksWorker' anymore.

Remove obsolete comment

---

core/Pos/Binary/Class/TH.hs
explorer/src/Pos/Explorer/Socket/App.hs
explorer/src/Pos/Explorer/Socket/Holder.hs
explorer/src/explorer/Main.hs
godtossing/Pos/Ssc/GodTossing/Toss/Pure.hs
lib/src/Pos/Generator/Block/Payload.hs
lib/src/Pos/Launcher/Resource.hs
lib/src/Pos/Util/Servant.hs
node/Main.hs
pkgs/default.nix
stack.yaml
tools/src/blockchain-analyser/Main.hs
tools/src/keygen/Main.hs
update/Pos/Update/Poll/Pure.hs
wallet/node/Main.hs
wallet/src/Pos/Wallet/Web/Methods/Logic.hs

Since @volhovM told me upgrading to the latest `log-warper` would fix the issue, that's what I did. Well, the good news is that I finished the upgrade, the bad news is that it didn't fix the issue.

[CSL-1769] Use log-warper 1.3.3

---

auxx/src/Command/Rollback.hs
auxx/src/Mode.hs
core/Pos/Util/CompileInfo.hs
default.nix
explorer/src/Pos/Explorer/Web/Transform.hs
infra/Pos/Reporting/Methods.hs
lib/src/Pos/Generator/Block/Logic.hs
lib/src/Pos/WorkMode.hs
lib/test/Test/Pos/Block/Logic/Mode.hs
lib/test/Test/Pos/Block/Logic/VarSpec.hs
lib/test/Test/Pos/Lrc/WorkerSpec.hs
pkgs/default.nix
stack.yaml
tools/src/block-gen/Context.hs
tools/src/launcher/Main.hs
wallet/src/Pos/Wallet/Web/Mode.hs

I've also decided to put git revision into `rBuild` report field so it required me to pass `HasCompileInfo` in several places. Tests and block-gen use fake compile info (default instance) as they never report anything (though using methods that can report).

[CSL-1770] Integrate report server 0.4

---

explorer/cardano-sl-explorer.cabal
explorer/src/Pos/Explorer/Web/Server.hs
lib/src/Pos/Web/Server.hs
pkgs/default.nix
scripts/launch/explorer-with-nodes.sh
scripts/launch/explorer.sh

Also some cosmetics and script updates.
Tested with requests

[CSE-244] Return web logging

---

auxx/cardano-sl-auxx.cabal
auxx/src/Command/Help.hs
auxx/src/Command/Parser.hs
auxx/src/Command/Run.hs
auxx/src/Command/Types.hs
auxx/src/Main.hs
auxx/src/Plugin.hs
auxx/src/Repl.hs
lib/src/Pos/Client/CLI/Params.hs
lib/src/Pos/Client/CLI/Util.hs
lib/src/Pos/Launcher/Param.hs
lib/src/Pos/Launcher/Resource.hs
pkgs/default.nix

it's ready for review, but I'm going to add some documentation a bit later (perhaps tomorrow)
The general idea is that Haskeline UI is running in a separate thread and communicates with `auxxPlugin` via a couple of `MVar`s. The logic of communication is neatly encapsulated in `createAuxxRepl` and the rest of the code doesn't need to deal `MVar`s.

[CSL-744] Haskeline-based REPL

---

scripts/build/cardano-sl.sh

To have demo with wallet working after `b wallet`

Build node along with wallet or explorer

---

CODEOWNERS
auxx/src/Command/BlockGen.hs
auxx/src/Command/Tx.hs
auxx/src/Command/Update.hs
auxx/src/Mode.hs
lib/src/Pos/Client/CLI/Secrets.hs
lib/src/Pos/Client/CLI/Util.hs

I also took the liberty of adding myself as a code owner for `auxx`.

Change 'putText' to 'logInfo', fix -Werror

---

node/src/Pos/Client/Txp/Util.hs
pkgs/default.nix

Partly cancel #1481
Testing showed that now we can actually just partly spend addresses

[CSM-521] Allow to spent addresses not fully

---

auxx/src/Mode.hs
lib/src/Pos/Client/KeyStorage.hs
wallet/src/Pos/Wallet/WalletMode.hs
wallet/src/Pos/Wallet/Web/Account.hs
wallet/src/Pos/Wallet/Web/Methods/Backup.hs
wallet/src/Pos/Wallet/Web/Methods/History.hs
wallet/src/Pos/Wallet/Web/Methods/Logic.hs
wallet/src/Pos/Wallet/Web/Methods/Misc.hs
wallet/src/Pos/Wallet/Web/Methods/Payment.hs
wallet/src/Pos/Wallet/Web/Methods/Redeem.hs
wallet/src/Pos/Wallet/Web/Methods/Reporting.hs
wallet/src/Pos/Wallet/Web/Methods/Restore.hs
wallet/src/Pos/Wallet/Web/Methods/Txp.hs
wallet/src/Pos/Wallet/Web/Mode.hs
wallet/src/Pos/Wallet/Web/Pending/Functions.hs
wallet/src/Pos/Wallet/Web/Pending/Submission.hs
wallet/src/Pos/Wallet/Web/Pending/Worker.hs
wallet/src/Pos/Wallet/Web/Server/Handlers.hs
wallet/src/Pos/Wallet/Web/Server/Launcher.hs
wallet/src/Pos/Wallet/Web/Server/Runner.hs
wallet/src/Pos/Wallet/Web/Sockets/Connection.hs
wallet/src/Pos/Wallet/Web/Sockets/Notifier.hs
wallet/src/Pos/Wallet/Web/State/State.hs
wallet/src/Pos/Wallet/Web/State/Util.hs
wallet/src/Pos/Wallet/Web/Tracking/BListener.hs
wallet/src/Pos/Wallet/Web/Tracking/Sync.hs
wallet/src/Pos/Wallet/Web/Util.hs
wallet/test/Test/Pos/Wallet/Web/Mode.hs

Eventually, it's used only in `Launcher.hs` and `(servant) Handlers.hs`

[CSM-502] Split MonadWalletWebMode

---

pkgs/default.nix
tools/cardano-sl-tools.cabal
tools/src/launcher/Main.hs

Reverts input-output-hk/cardano-sl#1754 which was mistakenly merged without @dcoutts's approval

Revert "[CSL-1747] Various launcher improvements"

---

lib/src/Pos/Block/Logic/VAR.hs

In `applyWithRollback' rollback was done outside `bracketOnError'.
But the idea is that if rollback happens, we want to ensure that
`applyBack' will be called if something goes wrong.
There can be an async exception after rollback and before bracket (AFAIU)
and then `applyBack' won't be called

[CSL-1790] Move rolback into bracket in `applyWithRollback`

---

infra/Pos/Slotting/Util.hs
wallet/src/Pos/Wallet/Web/Methods/Payment.hs
wallet/src/Pos/Wallet/Web/Tracking/BListener.hs

[CSM-407] Wallet-related cosmetics

---

auxx/src/Command/Parser.hs
auxx/src/Command/Run.hs
auxx/src/Command/Types.hs
auxx/src/Command/Update.hs
docs/how-to/push-update-on-mainnet.md
docs/how-to/test-update-system.md
node/src/Pos/Communication/Update.hs
node/src/node/Main.hs
pkgs/default.nix

1. Added `primary` flag for `add-key`
2. Added `vote-all` flag for `propose-update`
To get more information see descriptions of commits.

[CSL-1765] automate update system proposals

---

pkgs/default.nix
stack.yaml

See https://github.com/tibbe/ekg-core/pull/21 for more details.

Fix space leak in Pos.Block.Worker (culprit: System.Metrics.Label.set)

---

core/Pos/Core/Block.hs
core/Pos/Merkle.hs
lib/src/Pos/Block/Core/Genesis/Chain.hs
lib/src/Pos/Block/Core/Main/Chain.hs
pkgs/default.nix
ssc/Pos/Binary/GodTossing/Core.hs
ssc/Pos/Ssc/Core/Functions.hs
ssc/Pos/Ssc/Core/Types.hs
ssc/cardano-sl-ssc.cabal
txp/Pos/Txp/Core/Types.hs

See the last commit message for details.

[CSL-1802] Fix compatibility with mainnet

---

infra/Pos/Slotting/Util.hs
wallet/src/Pos/Wallet/Web/Tracking/BListener.hs

Useful part of #1722 which is yet unmerged

[CSM-491] Add timeout reports in blistener

---

appveyor.yml

Reduces appveyor build times from 45min to 15min.

[DEVOPS-61]  repair Appveyor caching

---

auxx/src/Command/BlockGen.hs
auxx/src/Command/Rollback.hs

I did not test, but the change is trivial

[CSL-1792] Use StateLock in auxx

---

auxx/src/Command/Parser.hs
auxx/src/Command/Run.hs
auxx/src/Command/Types.hs
auxx/src/Command/Update.hs
docs/how-to/push-update-on-mainnet.md

1. I made necessary changes in code to be able to change tx size limit and proposal size limit. For more details see the commit message.
2. Another change is code is allowing to propose an update without any installers.
3. I added description of this process to the relevant document.

CSL-1794 Provide necessary knowledge and code changes to increase tx size limit in cardano-sl-1.0 

---

scripts/build/cardano-sl.sh

We don't have this flag anymore.

Remove everything related to with-explorer flag from the build script

---

node/src/Pos/Launcher/Configuration.hs
pkgs/default.nix
tools/cardano-sl-tools.cabal
tools/src/launcher/Main.hs

**Note:** After this is merged, we should also merge this PR to Daedalus: https://github.com/input-output-hk/daedalus/pull/517. It doesn't have to be done immediately (e.g. no builds would break if the latter PR isn't merged, and Daedalus will continue working), but it still should be merged before the next update.

[CSL-1747] Use log-warper in the launcher (again)

---

core/Pos/Core/Configuration.hs
lib/src/Pos/Client/CLI/Util.hs
node/Main.hs
tools/src/keygen/Dump.hs
tools/src/keygen/KeygenOptions.hs
tools/src/keygen/Main.hs
wallet/node/Main.hs

Commits are self-explaining, I think. We need these features to deploy testnet.

CSL-1807 Add new features to cardano-keygen necessary for testnet 

---

.gitignore
appveyor.yml
explorer/cardano-sl-explorer.cabal
explorer/src/Pos/Explorer/Web/Server.hs
node/src/Pos/Web/Server.hs
pkgs/default.nix
scripts/launch/explorer.sh

of PR #1764 into `cardano-sl-1.0`.
_How to test:_
1. [Build](https://github.com/input-output-hk/cardano-sl/tree/master/explorer/frontend#short-version-of-installation) and [run](https://github.com/input-output-hk/cardano-sl/tree/master/explorer/frontend#4-build-in-development-mode-and-run-w-webpack-dev-server-locally) `Explorer` locally.
1. Run `scripts/launch/explorer-with-nodes.sh` in a `tmux` session.
1. Open http://localhost:3100/ in your browser
1. In root folder of `cardano-sl` you will find following `*.log` files of Explorer: 
* explorer-node.log
* explorer.log
* socket-io.log

[CSE-244] Cherry pick

---

tools/src/launcher/Main.hs

Otherwise it's not absolutely clear (at least at the first glance) whether
those options are about wallet backend or frontend.

Clarify descriptions of wallet options in launcher

---

core/Pos/Crypto/Signing/Safe.hs
core/Pos/Crypto/Signing/Types/Safe.hs
lib/src/Test/Pos/Util.hs
lib/test/Test/Pos/Core/AddressSpec.hs
pkgs/default.nix
wallet/cardano-sl-wallet.cabal
wallet/test/Test/Pos/Wallet/Web/AddressSpec.hs
wallet/test/Test/Pos/Wallet/Web/Methods/PaymentSpec.hs
wallet/test/Test/Pos/Wallet/Web/Tracking/SyncSpec.hs
wallet/test/Test/Pos/Wallet/Web/Util.hs

[CSM-504] Add test on size of getFakeChangeAddress

---

docs/txp.md
txp/Pos/Txp/Toil/Utxo/Functions.hs

I've described the whole algorithm of tx payload verification without delving into implementation details.
It should be reviewed carefully by people familiar with code and also these people should make sure that I indeed didn't forget anything.
I also deleted one redundant check (it was duplicated).

[CSL-1705] Describe transaction processing (txp)

---

.stylish-haskell.yaml
explorer/src/Pos/Explorer/Web/Transform.hs
lib/cardano-sl.cabal
lib/src/Pos/Util/Servant.hs
lib/src/Pos/Web/Server.hs
pkgs/default.nix
stack.yaml
wallet/src/Pos/Wallet/Web/Api.hs
wallet/src/Pos/Wallet/Web/ClientTypes/Instances.hs
wallet/src/Pos/Wallet/Web/ClientTypes/Types.hs
wallet/src/Pos/Wallet/Web/Server/Handlers.hs
wallet/src/Pos/Wallet/Web/Server/Launcher.hs
wallet/src/Pos/Wallet/Web/Server/Runner.hs
wallet/src/Pos/Wallet/Web/Sockets/Notifier.hs
wallet/src/Pos/Wallet/Web/Swagger/Instances/Schema.hs

Feel free to point out extra code and places which lack of explanation

[CSM-563] Bump servant to 0.12

---

scripts/hash-installer.sh

Added `hash-installer.sh`
Usage: `./scripts/hash-installer.sh [filename]`
https://github.com/input-output-hk/cardano-sl/commit/c24db2a739d1215101c5038a12968db476d8684d#commitcomment-25630215

[CSL-1821] Add hash-installer script

---

scripts/build/cardano-sl.sh

A bit hacky workaround to suppress bug from quickcheck-instances.

[CSL-1894] CSL-1894 Modify build script to suppress cabal warning

---

node/configuration.yaml
pkgs/default.nix

We are going to propose an update to version 4. The last confirmed version is 3.

[CSL-1885] Set `applicationVersion: 4' for `csl-daedalus' in staging config

---

scripts/build/cardano-sl.sh

1. Updated the description, it was outdated.
2. Removed obsolete unused stuff (prodMode, bench_mode variables and similar).
3. Removed the logic to treat packages dependent on cardano-sl differently. It
was fairly old logic, which is likely not needed anymore, but leads to
boilerplate and copy-paste when we add a new package.

[CSL-1906] Update build/cardano-sl.sh script

---

auxx/src/Command/Proc.hs
auxx/src/Command/TyProjection.hs
auxx/src/Lang/Lexer.hs
auxx/test/Test/Auxx/Lang/LexerSpec.hs

Auxx fixes I had to make while working on CSL-1688. They are not related to that task directly, and the PR is taking too long to merge, so I separated them.
(also added a command to construct software version from its components)

[CSL-1688] Auxx fixes

---

wallet/src/Pos/Wallet/Web/Swagger/Instances/Schema.hs

[CSL-1899] Document `CFilePath` better in swagger

---

binary/Pos/Binary/Class/Core.hs
binary/Pos/Binary/Class/Numbers.hs
binary/Pos/Binary/Class/Primitive.hs
binary/Pos/Binary/Class/TH.hs
core/Pos/Binary/Core/Block.hs
core/Pos/Binary/Core/Blockchain.hs
core/Pos/Binary/Core/Fee.hs
core/Pos/Binary/Core/Script.hs
core/Pos/Binary/Core/Ssc.hs
core/Pos/Binary/Core/Txp.hs
core/Pos/Binary/Core/Types.hs
core/Pos/Binary/Core/Version.hs
crypto/Pos/Binary/Crypto.hs
infra/Pos/Binary/Infra/DHTModel.hs
infra/Pos/Binary/Infra/Relay.hs
lib/src/Pos/Binary/Communication.hs
lib/src/Pos/Util/Servant.hs
ssc/Pos/Binary/Ssc/Relay.hs
txp/Pos/Binary/Txp/Network.hs
wallet/src/Pos/Util/BackupPhrase.hs

It contains cosmetic changes only. I've basically replicated part of the work of CSL-1399 PR which was closed.

Fix binary codestyle in different components

---

core/Pos/Util/Chrono.hs
crypto/Pos/Crypto/Signing/Signing.hs
infra/Pos/DHT/Real/Real.hs
infra/Pos/DHT/Real/Types.hs
infra/Pos/Network/Yaml.hs
infra/Pos/Util/TimeLimit.hs
lib/cardano-sl.cabal
lib/src/Pos/Client/CLI/NodeOptions.hs
lib/src/Test/Pos/Cbor/Canonicity.hs
lib/src/Test/Pos/Cbor/RefImpl.hs
lib/src/Test/Pos/Helpers.hs
lib/test/Test/Pos/Cbor/CborSpec.hs
tools/src/post-mortem/Main.hs
wallet-new/server/Cardano/Wallet/Server/CLI.hs
wallet/node/Main.hs
wallet/node/NodeOptions.hs
wallet/src/Pos/Wallet/Web/Server/Runner.hs
wallet/src/Pos/Wallet/Web/State/Util.hs

Again, cosmetic changes only (except for one subtle logic change in cbor reference implementation, but it doesn't matter). I wanted to push them as CSL-1399, but it wasn't merged, so here we go. 
cc @pva701

[Cosmetics] Fix more lint/style problems

---

lib/README.md

Fix typo of README.md

---

wallet-new/spec/swagger.json
wallet-new/src/Cardano/Wallet/API/V1/Generic.hs
wallet-new/src/Cardano/Wallet/API/V1/Types.hs
wallet-new/test/MarshallingSpec.hs

@akegalj Hopefully now we are capturing as many things as we were for a `CTx`!

[CSL-1954] Extend transaction type with more info

---

wallet-new/src/Cardano/Wallet/API/V1/Types.hs

Implements: https://iohk.myjetbrains.com/youtrack/issue/CSL-1921

[CSL-1921] Minor cleanups in wallet-new

---

wallet-new/README.md

@akegalj Let me know how you get along with the instructions!

[CSL-1964] Document swagger API testing

---

wallet/src/Pos/Wallet/Web/Account.hs

Summary:
* Updated generateUnique to always generate hardened addresses and removed orM.

[CSL-1955]  Improve `generateUnique` function

---

default.nix

I did the same thing as in PR #1981. Hopefully it'll help.

 Attempt to fix CI by workaround a cabal bug

---

wallet/cardano-sl-wallet.cabal
wallet/src/Pos/Wallet/Web/Backup.hs
wallet/src/Pos/Wallet/Web/ClientTypes/Types.hs
wallet/src/Pos/Wallet/Web/Methods/Backup.hs
wallet/test/Test/Pos/Wallet/Web/Methods/BackupDefaultAddressesSpec.hs
wallet/test/Test/Pos/Wallet/Web/Mode.hs

@gromakovsky I need some help regarding this.

[CSM-567] integration tests for import export of wallet

---

pkgs/default.nix
wallet/cardano-sl-wallet.cabal
wallet/src/Pos/Arbitrary/Wallet/Web/ClientTypes.hs
wallet/src/Pos/Wallet/Web/ClientTypes/Functions.hs
wallet/src/Pos/Wallet/Web/State/State.hs
wallet/src/Pos/Wallet/Web/State/Storage.hs
wallet/src/Pos/Wallet/Web/Tracking/BListener.hs
wallet/src/Pos/Wallet/Web/Tracking/Sync.hs
wallet/test/Test/Pos/Wallet/Web/Tracking/SyncSpec.hs

Tested with outgoing/incoming and a2a transactions

[CSM-503] Optimize change addresses evaluation

---

node/src/Pos/Wallet/Web/Pending/Updates.hs
node/src/Pos/Wallet/Web/State/Acidic.hs
node/src/Pos/Wallet/Web/State/State.hs
node/src/Pos/Wallet/Web/State/Storage.hs
stack2nix-src.json
wallet/src/Pos/Wallet/Web/Api.hs
wallet/src/Pos/Wallet/Web/Methods/Misc.hs
wallet/src/Pos/Wallet/Web/Pending/Util.hs
wallet/src/Pos/Wallet/Web/Pending/Worker.hs
wallet/src/Pos/Wallet/Web/Server/Handlers.hs
wallet/src/Pos/Wallet/Web/Swagger/Description.hs

Same as PR #2017, but with a branch name AppVeyor might be happier about.

[CSL-2007] Revise tx resubmitter logic

---

wallet-new/server/Cardano/Wallet/API/V1/Swagger.hs
wallet-new/server/Cardano/Wallet/Server.hs
wallet-new/spec/swagger.json
wallet-new/src/Cardano/Wallet/API.hs

Rebased from https://github.com/input-output-hk/cardano-sl/pull/1988

[CSL-1963] Remove v0 prefixed version of the API

---

wallet-new/server/Cardano/Wallet/API/V1/Handlers/Wallets.hs

https://iohk.myjetbrains.com/youtrack/issue/CSL-1889
Rebased onto feature/new-wallet.

[CSL-1889] Implement `DELETE /api/v1/wallets/{walletId}` with V0 logic

---

wallet-new/src/Cardano/Wallet/API/V1/Parameters.hs

(Feel free to cherry-pick / close)

Add `hoistServerWithContext` implementation for `WalletRequestParams`

---

wallet-new/server/Cardano/Wallet/API/V1/Handlers/Wallets.hs
wallet-new/src/Cardano/Wallet/API/V1/Migration.hs
wallet-new/src/Cardano/Wallet/Orphans/Aeson.hs
wallet-new/test/MarshallingSpec.hs

[CSL-1890] Add updatePass endpoint

---

appveyor.yml

[CSL-2009]  CardanoSL.zip:  drop frontend build, but retain node-related pieces

---

db/cardano-sl-db.cabal
node/cardano-sl.cabal
pkgs/default.nix
stack.yaml
txp/cardano-sl-txp.cabal
update/cardano-sl-update.cabal

Reverts input-output-hk/cardano-sl#2019 because it's a cardano-sl-1.0 PR

Revert "[CSL-1803] Increase version of 'rocksdb-haskell'"

---

wallet-new/server/Cardano/Wallet/API/V1/Handlers/Accounts.hs
wallet-new/src/Cardano/Wallet/API/V1/Migration.hs

_Task_ https://iohk.myjetbrains.com/youtrack/issue/CSL-1945

[CSL-1945] V1 endpoint handler `updateAccount`

---

wallet-new/server/Cardano/Wallet/API/V1/Handlers/Accounts.hs

_Task_ https://iohk.myjetbrains.com/youtrack/issue/CSL-1946

[CSL-1946] API v1 endpoint handler `deleteAccount`

---

pkgs/default.nix

Bump pkgs.nix

---

wallet/src/Pos/Wallet/Web/ClientTypes/Types.hs
wallet/src/Pos/Wallet/Web/State/Acidic.hs
wallet/src/Pos/Wallet/Web/State/State.hs
wallet/src/Pos/Wallet/Web/State/Storage.hs

Provided doc comments for `Pos.Wallet.Web.State.Storage`
PR is WIP, because `Acidic` and `State` modules should be documented too (though they mostly consist of boilerplate code, so there's less work to do).
Also during documenting I realized that there's _lots_ of old code which is now obsolete in `Pos.Wallet.Web.State.Storage`. I'd like to remove this code instead of documenting it. @adinapoli-iohk what do you think about it?

[CSL-1944] Document `Pos.Wallet.Web.State.Storage`

---

explorer/frontend/src/Explorer/I18n/DE.purs
explorer/frontend/src/Explorer/I18n/EN.purs
explorer/frontend/src/Explorer/I18n/JP.purs
explorer/frontend/src/Explorer/I18n/Types.purs
explorer/frontend/src/Explorer/View/Footer.purs
pkgs/default.nix
scripts/launch/explorer.sh

See https://issues.serokell.io/issue/CSE-253
Including two cherry-picks of https://github.com/input-output-hk/cardano-sl/pull/1843/ to run Explorer locally.

[CSE-253]  Remove link to Cardano Launch

---

wallet-new/server/Cardano/Wallet/API/V1/Handlers/Accounts.hs

_YT task:_ 
https://iohk.myjetbrains.com/youtrack/issue/CSL-1949
Note: As discussed in https://input-output-rnd.slack.com/archives/C819S481Y/p1512644497000127 this PR goes the :hammer: way (which will be improved in future).

[CSL-1949] V1 handler `listAccounts`

---

docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md

Issue: https://github.com/input-output-hk/cardano-sl/issues/2077
tldr; s/cardano-sl-tools-static/cardano-sl-tools
This fixes build instructions.

Fix cardano install instructions

---

appveyor.yml

[CSL-2034]  fix | appveyor:  the OpenSSL package was updated, fix URL

---

docs/proposals/serialization.md

So this is a "proposal" PR. It will only be merged after we agree on proposal document. Proposal document is what is going to determine specification document/implementation later.
Discussions to be held here in comments only. Whenever we come up with a need to change doc, change it.
No force-pushes, please! This is a public branch!

[CSL-1859] Serialization/verification granularity proposal

---

wallet-new/server/Cardano/Wallet/API/V1/Handlers.hs
wallet-new/server/Cardano/Wallet/API/V1/Handlers/Addresses.hs
wallet-new/server/Cardano/Wallet/API/V1/Swagger.hs
wallet-new/src/Cardano/Wallet/API/V1/Addresses.hs
wallet-new/src/Cardano/Wallet/API/V1/Migration/Types.hs
wallet-new/src/Cardano/Wallet/API/V1/Types.hs
wallet-new/src/Cardano/Wallet/Orphans/Aeson.hs
wallet-new/test/MarshallingSpec.hs

[CSL-1961] Implement newAddress endpoint

---

block/src/Pos/Block/Worker.hs

Changes are trivial and are described in code comments.

[CSL-2028] Fix recoveryTriggerWorker

---

ssc/Pos/Binary/Ssc/Types.hs

The issue is very similar to CSL-1802 (#1828). This incompatibility was broken
was 'VssCertificatesMap' became newtype. Previously it was a 'type' alias,
so it was encoded as a 'HashMap'. But 'VssCertificatesMap' newtype is encoded
as a list.
This commit changes serialization format of 'VssCertData' to the old one.
This particular problem issue is less significant than CSL-1802, because
'VssCertData' is stored only in DB, but not in blocks, so it's basically an
implementation detail. That's why it hasn't been noticed for a long time.
Alternative solution would be to stop using old format (which was a bit
stupid) and perform DB migration. I've chosen this one, because DB migration
is hard and inefficiency of the old format is insignificant, because we have
only 7 certificates nowadays …

[CSL-2044] Make 'instance Bi VssCertData' compatible with mainnet's one

---

explorer/frontend/src/Explorer/Api/Http.purs

_YT Task:_ 
https://iohk.myjetbrains.com/youtrack/issue/CSL-2047
Tested on `mainnet` (see screenshot added to YT task ^)

[CSL-2047] Increase limit of block txs

---

explorer/frontend/src/Explorer/Api/Http.purs

to increase limit of block txs. See https://github.com/input-output-hk/cardano-sl/pull/2095 for all details.

[CSL-2047] Cherry pick PR #2095 to master

---

docs/how-to/connect-to-cluster.md
explorer/README.md

Just a record of what I've learned to test #2095 today. It might be helpful for anybody else :)

Update instruction to connect Explorer w/ mainnet

---

pkgs/default.nix
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/server/Cardano/Wallet/API/V1/Handlers/Transactions.hs
wallet-new/server/Cardano/Wallet/API/V1/Swagger/Example.hs
wallet-new/spec/swagger.json
wallet-new/src/Cardano/Wallet/API/Response.hs
wallet-new/src/Cardano/Wallet/API/V1/Migration/Types.hs
wallet-new/src/Cardano/Wallet/API/V1/Transactions.hs
wallet-new/src/Cardano/Wallet/API/V1/Types.hs

_Task_: https://iohk.myjetbrains.com/youtrack/issue/CSL-1940

[CSL-1940] V1 handler `newTransaction`

---

appveyor.yml

Sister PR for https://github.com/input-output-hk/cardano-sl/pull/2125

[DEVOPS-565]  appveyor:  restore Daedalus artifacts delivery

---

scripts/log-templates/log-config-qa.yaml

Total logs size increases to ~10Gb.
Tested those 100Mb files with emacs, it's still alive :)

Increase amount of logs kept

---

explorer/src/Pos/Explorer/Socket/Methods.hs
node/src/Pos/Block/Logic/Header.hs
node/src/Pos/Block/Network/Announce.hs
node/src/Pos/Block/Network/Listeners.hs
node/src/Pos/Client/Txp/History.hs
node/src/Pos/GState/BlockExtra.hs
node/src/Pos/Security/Workers.hs
wallet/src/Pos/Wallet/Web/Tracking/Sync.hs

It's a copy of #2000. It was merged by mistake and then merge was deleted by force-push.

[CSL-1931] Use forward links in getHeadersRange

---

infra/Pos/Communication/Types/Protocol.hs
infra/Pos/Slotting/MemState.hs
infra/Pos/Subscription/Common.hs
infra/Pos/Subscription/Dns.hs
infra/Pos/Util/Timer.hs
infra/cardano-sl-infra.cabal
node/src/Pos/Binary/Communication.hs
node/src/Pos/Block/Network/Retrieval.hs
node/src/Pos/Block/Worker.hs
node/src/Pos/Communication/Limits.hs
node/src/Pos/Communication/Message.hs
node/src/Pos/Context/Context.hs
node/src/Pos/Launcher/Resource.hs
node/src/Pos/Worker.hs

Version of #1852 for cardano-sl-1.0.

[CSL-1676] Send keep-alive like packets after relay subscription

---

auxx/src/Main.hs
core/Pos/Util/Util.hs
core/cardano-sl-core.cabal
explorer/src/explorer/ExplorerOptions.hs
explorer/src/explorer/Main.hs
node/src/Pos/Launcher/Resource.hs
node/src/node/Main.hs
pkgs/default.nix
wallet/node/Main.hs
wallet/node/NodeOptions.hs

Ported #1753 loggerBrackets, and added exception handling and logging.

[CSL-1839] Catch and logs exceptions right after logger initialization 

---

appveyor.yml

Depends on https://github.com/input-output-hk/iohk-ops/pull/221

[DEVOPS-61] appveyor cache

---

appveyor.yml
pkgs/default.nix

master version of https://github.com/input-output-hk/cardano-sl/pull/2166#issuecomment-354123119

[DEVOPS-61] Rewrite appveyor caching

---

delegation/src/Pos/Delegation/Logic/VAR.hs
txp/Pos/Txp/Toil/Logic.hs

Copy of https://github.com/input-output-hk/cardano-sl/pull/2204 to develop branch.

[CSL-2043] Simple apply optimiations for txp/dlg

---

lib/src/Pos/Web/Types.hs

Improving the documentation for webtypes

---

node/src/Pos/Wallet/Web/Util.hs
wallet/src/Pos/Wallet/Web/Account.hs
wallet/src/Pos/Wallet/Web/Methods/Logic.hs

Copy of PR #2195 for cardano-sl-1.0-exchanges branch.

[CSL-2135] New address performance improvement

---

node/configuration.yaml
node/src/Pos/Block/Network/Logic.hs
node/src/Pos/Block/Network/Retrieval.hs
node/src/Pos/Block/RetrievalQueue.hs

a port of #1670 for the exchanges branch

[CSL-1706] Discard duplicate tasks in recovery queue

---

docker.nix
docs/how-to/connect-to-cluster.md
node/src/Pos/Statistics/Ekg.hs
scripts/launch/connect-to-cluster/default.nix

This fixes up Nix bits on top of https://github.com/input-output-hk/cardano-sl/pull/2238

[CSL-2139] hotfix: ekg server: allow 0.0.0.0 as listening address

---

scripts/log-templates/log-config-qa.yaml

https://iohk.myjetbrains.com/youtrack/issue/CSL-2087
Original PR - https://github.com/input-output-hk/cardano-sl/pull/2141

[CSL-2087] hotfix for #2141

---

docs/proposals/block-storage.md
pkgs/default.nix

[Rendered](https://github.com/input-output-hk/cardano-sl/blob/0ea5efa3654f3173cae3df9e4709619fe71aa197/docs/proposals/block-storage.md)

[CSL-1025] Block storage spec

---

infra/Pos/StateLock.hs
txp/Pos/Txp/MemState/Metrics.hs

https://iohk.myjetbrains.com/youtrack/issue/CSL-2135
Original PR - https://github.com/input-output-hk/cardano-sl/pull/2201

[CSL-2135] hotfix for #2201

---

node/src/Pos/Wallet/Web/State/Storage.hs
wallet/src/Pos/Wallet/Web/Methods/Logic.hs
wallet/src/Pos/Wallet/Web/Methods/Redeem.hs
wallet/src/Pos/Wallet/Web/Server/Handlers.hs

This is a rebase of https://github.com/input-output-hk/cardano-sl/pull/2060 against `master`.
It was rebased due to the fact `master` contained only parts of it (e.g. the `Balances` module) but not the rest, and such "rest" is needed to backport some speedup improvements from @Martoon-00 , namely https://github.com/input-output-hk/cardano-sl/pull/2148 and https://github.com/input-output-hk/cardano-sl/pull/2149.

[CSL-1972] Do a single DB and mempool read when computing wallet balance

---

wallet/src/Pos/Wallet/Web/Methods/History.hs

[CSL-2135] Don't log WontApply pending transactions in history

---

pkgs/default.nix
wallet/src/Pos/Wallet/Web/Methods/Payment.hs

6 sec for 1 payment should be fine for us and it should allow other things
going on to keep up.

[CSL-2135] Increase rate limiting delay in newPayment

---

node/src/Pos/Block/Worker.hs

Part of the backport of #2213.

[CSL-2135] Print difference between tip slot and current slot

---

node/src/Pos/Wallet/Web/ClientTypes/Types.hs
pkgs/default.nix
wallet/src/Pos/Aeson/ClientTypes.hs
wallet/src/Pos/Wallet/Web/Api.hs
wallet/src/Pos/Wallet/Web/Methods/Payment.hs
wallet/src/Pos/Wallet/Web/Server/Handlers.hs
wallet/src/Pos/Wallet/Web/Swagger/Description.hs
wallet/src/Pos/Wallet/Web/Swagger/Instances/Schema.hs

Cherry-picked from https://github.com/input-output-hk/cardano-sl/pull/1937

[CSL-1883] [exchanges] Wallet new endpoint for batch payments

---

wallet/src/Pos/Wallet/Web/Methods/Payment.hs

This is cherry-pick of https://github.com/input-output-hk/cardano-sl/commit/f90719e6c135984154d9b0d40f99d506e4c49a0a.
See https://github.com/input-output-hk/cardano-sl/pull/2278 for the full rationale.

[CSL-2087] Search signer by address using map, not list

---

wallet/src/Pos/Wallet/Web/Api.hs
wallet/src/Pos/Wallet/Web/Methods/Misc.hs
wallet/src/Pos/Wallet/Web/Pending/Util.hs
wallet/src/Pos/Wallet/Web/Pending/Worker.hs
wallet/src/Pos/Wallet/Web/Server/Handlers.hs
wallet/src/Pos/Wallet/Web/Swagger/Description.hs
wallet/src/Pos/Wallet/Web/Swagger/Instances/Schema.hs

[CSL-2135] Add endpoint to see pending transactions summary

---

wallet/src/Pos/Wallet/Web/Methods/History.hs

This is cherry pick of https://github.com/input-output-hk/cardano-sl/commit/17a68ec565ba5cdd0d7e8e662bd52294ed9fe5e7
See #2278 for the full rationale.

[CSL-2087] More logs in `getHistory`, remove huge ones

---

node/src/Pos/Wallet/Web/ClientTypes/Functions.hs
node/src/Pos/Wallet/Web/State/Acidic.hs
node/src/Pos/Wallet/Web/State/State.hs
node/src/Pos/Wallet/Web/State/Storage.hs
node/src/Pos/Wallet/Web/Util.hs
pkgs/default.nix
wallet/src/Pos/Wallet/Web/Methods/History.hs
wallet/src/Pos/Wallet/Web/Methods/Payment.hs
wallet/src/Pos/Wallet/Web/Methods/Redeem.hs

[CSL-2087] Do not convert addresses list to Set when viable (#2136)

---

wallet/src/Pos/Wallet/Web/Pending/Submission.hs

Rebase of https://github.com/input-output-hk/cardano-sl/pull/2239.
Supersede https://github.com/input-output-hk/cardano-sl/pull/2252 .

[CSL-2135] Cancel PTX on resubmission after 1h limit

---

block/src/Pos/Block/Network/Retrieval.hs
infra/Pos/Communication/Types/Protocol.hs
infra/Pos/Subscription/Common.hs
lib/src/Pos/Binary/Communication.hs
lib/src/Pos/Communication/Limits.hs
lib/src/Pos/Communication/Message.hs
lib/src/Pos/Launcher/Resource.hs
util/Pos/Util/Timer.hs

Apart from changes to `lib/src/Pos/Communication/Limits.hs` it's basically a cherry-pick of two last commits from #1853.

Port CSL-1676 related patches to develop branch

---

node/src/Pos/Wallet/Web/ClientTypes/Instances.hs
node/src/Pos/Wallet/Web/Pending/Updates.hs
node/src/Pos/Wallet/Web/State/Acidic.hs
node/src/Pos/Wallet/Web/State/State.hs
node/src/Pos/Wallet/Web/State/Storage.hs
pkgs/default.nix
wallet/src/Pos/Wallet/Web/Api.hs
wallet/src/Pos/Wallet/Web/Methods/Misc.hs
wallet/src/Pos/Wallet/Web/Server/Handlers.hs
wallet/src/Pos/Wallet/Web/Swagger/Description.hs

[CSL-2135] Add endpoint to cancel unconfirmed pending transactions

---

tools/src/launcher/Main.hs

Use new types instead of passing three or four element tuples around

CSL-1852 Wrap big tuples in launcher into sensible types 

---

wallet/src/Pos/Wallet/Web/Pending/Submission.hs

Rebase of #2270 .
Alas I couldn't preserve the original commit as cherry picking would case `git` to fail with `fatal: bad object`. I hope that's ok for everybody.

[CSL-2135] Add a newly created tx to the mempool before submitting it

---

node/src/Pos/Wallet/Web/State/State.hs
node/src/Pos/Wallet/Web/State/Storage.hs
node/src/Pos/Wallet/Web/Util.hs
wallet/src/Pos/Wallet/Web/Methods/History.hs
wallet/src/Pos/Wallet/Web/Methods/Logic.hs
wallet/src/Pos/Wallet/Web/Methods/Payment.hs

Backport of https://github.com/input-output-hk/cardano-sl/pull/2149

[CSL-2087] Don't sort addresses when not necessary

---

node/src/Pos/Wallet/Web/ClientTypes/Types.hs
wallet/src/Pos/Aeson/ClientTypes.hs
wallet/src/Pos/Wallet/Web/Api.hs
wallet/src/Pos/Wallet/Web/Methods/Payment.hs
wallet/src/Pos/Wallet/Web/Server/Handlers.hs
wallet/src/Pos/Wallet/Web/Swagger/Description.hs
wallet/src/Pos/Wallet/Web/Swagger/Instances/Schema.hs

Hotfix [CSL-1883]

---

docs/proposals/update-downloader.md

I described all the problems I am aware of and proposed their solutions.
If you know anything else that should be improved, let me know and I'll think about that.

[CSL-1820] Add the document about update downloader design

---

wallet/src/Pos/Wallet/Web/Api.hs
wallet/src/Pos/Wallet/Web/Methods/Misc.hs
wallet/src/Pos/Wallet/Web/Server/Handlers.hs

Same as #2273. Adds endpoint that triggers node shutdown.

[CSL-2144] Add system/shutdown endpoint

---

docs/rollback-reaction.md

It's ready, except one TODO which will be done after I get clarifications.
Comments are welcome.

[CSL-1639] Describe rollbacks handling

---

auxx/src/Command/Update.hs
client/src/Pos/Client/Update/Network.hs
core/Pos/Binary/Core/Block.hs
core/Pos/Binary/Core/Update.hs
core/Pos/Core/Delegation/Util.hs
core/Pos/Core/Genesis/Canonical.hs
core/Pos/Core/Genesis/Helpers.hs
core/Pos/Core/Update/Types.hs
core/Pos/Core/Update/Util.hs
crypto/Pos/Binary/Crypto.hs
crypto/Pos/Crypto/Signing/Check.hs
crypto/Pos/Crypto/Signing/Safe.hs
crypto/Pos/Crypto/Signing/Signing.hs
crypto/Pos/Crypto/Signing/Types/Signing.hs
crypto/cardano-sl-crypto.cabal
delegation/src/Pos/Binary/Delegation.hs
delegation/src/Pos/Delegation/Cede/Logic.hs
delegation/src/Pos/Delegation/DB.hs
delegation/src/Pos/Delegation/Logic/Mempool.hs
lib/src/Pos/Communication/Limits.hs
lib/test/Test/Pos/CryptoSpec.hs
lib/test/Test/Pos/Update/MemStateSpec.hs
update/Pos/Arbitrary/Update/Core.hs
update/Pos/Arbitrary/Update/Network.hs
update/Pos/Update/Logic/Local.hs
update/Pos/Update/MemState/Functions.hs
update/Pos/Update/Network/Listeners.hs
update/Pos/Update/Poll/Logic/Apply.hs
update/Pos/Update/Poll/Logic/Base.hs
update/Pos/Update/Poll/Logic/Normalize.hs

I recommend reviewing each commit individually.

[CSL-2176] Respect some invariants

---

wallet-new/server/Cardano/Wallet/API/V1/Swagger/Example.hs
wallet-new/spec/swagger.json
wallet-new/src/Cardano/Wallet/API/V1/Migration/Types.hs
wallet-new/src/Cardano/Wallet/API/V1/Types.hs

This is the final stepping stone to finalise the merge of this feature branch into `develop`.

[CSL-2216] Update the swagger API and prepare for the merge

---

docs/rollback-reaction.md

In d10479ef57c90153837f1bbfe94b0782ca7652ce there was a strange change.

[CSL-1639] Slightly fix rollback-reaction.md

---

tools/src/launcher/Main.hs

After we successfully apply an update in cardano-launcher we do two things
(apart from logging):
1. Write that update was installed to DB.
2. Remove update file.
The problem is that if `cardano-node` wasn't stopped for some reason (and
unfortunately it's often the case nowadays), we will fail to open DB and
won't remove installer file. It will lead to infinite loop. After user opens
updated Daedalus, they will be prompted to install an update again.
The proper fix of course is to make node exit more reliably when Daedalus
exits. However, various bad things can happen when we want to write to DB and
in any case we want to remove installer file to avoid infinite loop. So using
`finally` to achieve it seems quite reasonable.

[CSL-2078] Delete installer after successful exit more reliably

---

block/src/Pos/Block/Worker.hs

This situation should never happen.

[Awesome PR] Log error instead of warning in one case

---

explorer/src/Pos/Explorer/Socket/App.hs
explorer/src/Pos/Explorer/Socket/Util.hs

This function is very similar to `withAsync`.
I used `withAsync` instead, because it's safer and more conventional.
I also removed `Unless` part from `runPeriodicallyUnless`, because it appeared
useless. That's because accompanion thread will die when main thread dies.

[CSL-2214] Eliminate forkAccompanion

---

block/cardano-sl-block.cabal
db/Pos/DB/Rocks/Functions.hs
db/cardano-sl-db.cabal
delegation/cardano-sl-delegation.cabal
explorer/cardano-sl-explorer.cabal
lib/cardano-sl.cabal
lib/src/Pos/GState/GState.hs
lrc/cardano-sl-lrc.cabal
pkgs/default.nix
ssc/cardano-sl-ssc.cabal
stack.yaml
txp/cardano-sl-txp.cabal
update/cardano-sl-update.cabal

See https://github.com/input-output-hk/cardano-sl/pull/2361 for context

[CSL-1701] rocksdb-haskell-ng to fix segfaults

---

CODEOWNERS

Quite self-explicative, I hope 😁

[CSL-2222] Add Alfredo as CODEOWNER for the old wallet

---

auxx/Main.hs
explorer/src/explorer/Main.hs
lib/src/Pos/Client/CLI/Util.hs
lib/src/Pos/Launcher/Resource.hs
lib/src/Pos/Launcher/Runner.hs
node/Main.hs
util/Pos/Util/Util.hs
wallet-new/server/Main.hs
wallet/node/Main.hs
wallet/src/Pos/Wallet/Web/Server/Launcher.hs
wallet/src/Pos/Wallet/Web/Server/Runner.hs

This logging is needed because in some cases we get
> cardano-node: signalProcess: permission denied (Operation not permitted)
error shortly after start.

[CSL-2167] Additional logging

---

infra/Pos/DHT/Real/Real.hs
infra/Pos/Util/TimeLimit.hs
networking/src/Mockable/Concurrent.hs

This PR simply removes unused code.
I need it for other issues. I'd like to get it merged today.
Note: it's not actual implementation of CSL-2200, it's rather a prerequisite. Issue id in PR title exists to simplify time-tracking for reviewers.

[CSL-2220] Remove various unused code

---

wallet/src/Pos/Wallet/Web/Methods/History.hs
wallet/src/Pos/Wallet/Web/State/State.hs
wallet/src/Pos/Wallet/Web/State/Storage.hs

[CSL-2127] Make getHistoryCache return empty history instead of Nothing

---

wallet-new/server/Cardano/Wallet/Server/Plugins.hs

It so happened that in old wallet, 1. notifier launch and 2. wallets sync were
moved to some other place (from `walletProd` to Main module); in wallet-new Main
got those changes while corresponding `walletBackend` function didn't, thus we
got 1 and 2 executed twice in wallet-new.
`walletBackend` in wallet-new remain outdated even after CSL-2212 where notifier
launcher became blocking operation in order to have control over the
relative thread, this change prevented wallet startup sequence completion.

[CSL-2212] Remove duplicated logic in wallet-new

---

pkgs/default.nix
stack.yaml
tools/cardano-sl-tools.cabal
tools/src/dbgen/CLI.hs
tools/src/dbgen/Lib.hs
tools/src/dbgen/Main.hs
tools/src/dbgen/README.md
tools/src/dbgen/Types.hs
tools/src/dbgen/config.dhall
tools/src/dbgen/config.json

https://iohk.myjetbrains.com/youtrack/issue/CSL-2208
Tested on `mainnet`. Used:
```
stack exec dbgen -- --config ./tools/src/dbgen/config.dhall --nodeDB db-mainnet --walletDB wdb-mainnet --configPath node/configuration.yaml --secretKey secret-mainnet.key --configProf mainnet_full --add-to Ae2tdPwUPEZJHA8wEbVWoT4zgDGuWkXT9vLW6RzLvMt8kYCefkBQ1nixzpX@2147483648 --genFakeUtxo
```
The result(just the last bit, output is too large):
```
{
"cadId": "DdzFFzCqrht9pDX2vt4sZe3NxdDBtMN8QL2sKbAG9ztAgZ7iNACCr8FBDPbRv8kAL6hPSCMbRCheWnHxjdqVbWd9CvBHjm29ubGRbiYd",
"cadAmount": {
"getCCoin": "10000"
},
"cadIsUsed": false,
"cadIsChange": false
},
{
"cadId": "DdzFFzCqrhsyWHF8kPwR7rRENnH7iifEJkLu6zx4MF5vZVoCJnHpdwuaa9w4rCotxcX5aLgRH47Z6pN4UoWVCzcqTbiAixmPDuTancAs",
"cadAmount": {
"getCCoin": "10000"
}, …
```

[CSL-2208] Add fake utxo to dbgen

---

auxx/src/Command/Tx.hs
client/cardano-sl-client.cabal
client/src/Pos/Client/Txp/Network.hs
client/src/Pos/Client/Txp/Util.hs
client/test/Test/Pos/Client/Txp/UtilSpec.hs
core/Pos/Core/Ssc/Vss.hs
generator/src/Pos/Generator/Block/Payload.hs
pkgs/default.nix
wallet-new/server/Cardano/Wallet/API/V1/Handlers/Transactions.hs
wallet-new/test/unit/UTxO/Interpreter.hs
wallet/src/Pos/Wallet/Web/Methods/History.hs
wallet/src/Pos/Wallet/Web/Methods/Payment.hs

this does not conclude the work on CSL-2171, but is separated into an individual PR to ease review

[CSL-2171] Remove 'impureThrow' from wallet, refactor 'getSigner'

---

.gitignore
default.nix
sample-wallet-config.nix
scripts/launch/connect-to-cluster/default.nix

Backport hotfix changes from PR #2423 to `develop`.

[DEVOPS-424] Simplify nix-based exchange workflow (#2423)

---

tools/src/launcher/Main.hs
util/Pos/Util/Util.hs

It can help us understand why it doesn't kill the node on MacOS.

[CSL-2064] Add a bit more logging to `cardano-launcher'

---

pkgs/default.nix
pkgs/generate.sh

That's needed because some PRs want to use Hackage packages which appeared
just recently.

Use newer hackage-snapshot

---

block/src/Pos/Block/Slog/Logic.hs

Clean up obsolete HLint issues and improve comments.

[CSL-1980] Cosmetic changes

---

node/cardano-sl.cabal
node/src/Pos/Wallet/Web/State/Acidic.hs
node/src/Pos/Wallet/Web/State/State.hs
node/src/Pos/Wallet/Web/State/Storage.hs
node/src/Pos/Wallet/Web/State/Transactions.hs
wallet/src/Pos/Wallet/Web/Methods/Backup.hs
wallet/src/Pos/Wallet/Web/Methods/Logic.hs
wallet/src/Pos/Wallet/Web/Methods/Restore.hs
wallet/src/Pos/Wallet/Web/Tracking/Sync.hs

This PR creates transactions for various functionality which
should be done atomically.

Create DB transactions for various atomic operations.

---

scripts/launch/connect-to-cluster/mainnet-staging.sh
tools/src/launcher/launcher-config.yaml

These configs got moved recently.

Update log config paths

---

block/src/Pos/Block/Pure.hs
block/src/Pos/Block/Slog/Logic.hs
docs/block-processing/slog.md

[CSL-1980] Add Slog documentation

---

infra/Pos/Infra/Configuration.hs
infra/Pos/NtpCheck.hs
infra/Pos/Slotting/Impl/Ntp.hs
networking/src/NTP/Client.hs
wallet/src/Pos/Wallet/Web/Methods/Misc.hs

[CSL-2285] Backport NTP fixes to release branch

---

docs/proposals/update-downloader.md
lib/configuration.yaml
pkgs/default.nix
stack.yaml
tools/src/launcher/launcher-config.yaml

Applying #2486 to branch used by https://github.com/input-output-hk/daedalus/pull/701

[DEVOPS-654] ntp fix for staging

---

explorer/src/Pos/Explorer/Web/Server.hs
node/src/Pos/Block/Logic/Creation.hs
node/src/Pos/Client/Txp/Balances.hs
node/src/Pos/Client/Txp/History.hs
node/src/Pos/Explorer/Txp/Local.hs
node/src/Pos/Txp/Network/Listeners.hs
node/src/Pos/Web/Server.hs
tools/src/dbgen/Lib.hs
txp/Pos/Txp/Logic/Local.hs
txp/Pos/Txp/MemState/Class.hs
txp/Pos/Txp/MemState/Holder.hs
txp/Pos/Txp/MemState/Types.hs
wallet/src/Pos/Wallet/Web/Methods/Logic.hs
wallet/src/Pos/Wallet/Web/Methods/Payment.hs
wallet/src/Pos/Wallet/Web/Methods/Redeem.hs
wallet/src/Pos/Wallet/Web/Methods/Restore.hs
wallet/src/Pos/Wallet/Web/Server/Handlers.hs
wallet/src/Pos/Wallet/Web/Tracking/Sync.hs

This PR pushes STM semantics further up the stack in accessing and writing to the mempool.
This PR does not yet do any rewriting into transactions.

[CSL-2196] Mempool consistency

---

scripts/launch/demo.sh
wallet-new/server/Cardano/Wallet/Server/Plugins.hs

Cherry pick to run new wallet in `release/1.1.0.`
It includes:
* https://github.com/input-output-hk/cardano-sl/pull/2420/commits/c6479505e9c66b700f091499ef334b6fe22f9fc3 [CSL-2212] Remove duplicated logic in wallet-new 
*  https://github.com/input-output-hk/cardano-sl/pull/2487/commits/cf7f96e87a598ae3128836f571294084a682fa95 Fix `demo.sh` to support wallet-new

Hotfix CSL-2212

---

wallet-new/docs/spec.tex

Specify how to deal with rollbacks in a relatively simple manner.

Section on rollbacks

---

explorer/src/Pos/Explorer/Socket/Methods.hs
infra/Pos/Reporting/Methods.hs
infra/Pos/Util/LogSafe.hs
wallet/src/Pos/Wallet/Web/Methods/History.hs
wallet/src/Pos/Wallet/Web/Methods/Misc.hs
wallet/src/Pos/Wallet/Web/Pending/Submission.hs
wallet/src/Pos/Wallet/Web/Pending/Types.hs
wallet/src/Pos/Wallet/Web/Pending/Worker.hs
wallet/src/Pos/Wallet/Web/Tracking/BListener.hs
wallet/src/Pos/Wallet/Web/Tracking/Modifier.hs
wallet/src/Pos/Wallet/Web/Tracking/Sync.hs

[CSM-525] More public logs in wallet

---

block/src/Pos/Block/Logic/Creation.hs
block/src/Pos/Block/Logic/Header.hs
block/src/Pos/Block/Logic/Internal.hs
block/src/Pos/Block/Logic/Util.hs
block/src/Pos/Block/Logic/VAR.hs
docs/block-processing/overall.md

* Copy module descriptions from CSL-2073
* Expand on block payloads
* Describe V/A/R cycle
* Add Haddock comments with algorithms for `verifyBlocksPrefix` and `verifyAndApplyBlocks`
* Prettify Markdown in `overall.md` with `pandoc`

[CSLD-157] Describe Pos.Block.Logic

---

tools/src/launcher/Main.hs

If `shouldLog` is `False`, we should always use `Process.NoStream`.

[CSL-2311] Launcher: discard wallet logs when wallet logging is disabled

---

generator/cardano-sl-generator.cabal
generator/test/Test/Pos/Lrc/WorkerSpec.hs
pkgs/default.nix

[CSL-2297] Add a negative test for LRC (less than `k` blocks)

---

block/src/Pos/Block/Configuration.hs
core/Pos/Aeson/Core.hs
core/Pos/Aeson/Core/Configuration.hs
core/Pos/Aeson/Fee.hs
core/Pos/Aeson/Genesis.hs
delegation/src/Pos/Delegation/Configuration.hs
infra/Pos/Infra/Configuration.hs
lib/src/Pos/Client/CLI/NodeOptions.hs
lib/src/Pos/Client/CLI/Util.hs
lib/src/Pos/Configuration.hs
lib/src/Pos/Launcher/Configuration.hs
node/Main.hs
ssc/Pos/Ssc/Configuration.hs
update/Pos/Update/Configuration.hs
wallet-new/server/Main.hs
wallet/node/Main.hs

[CSL-2276] Add a CLI flag for dumping runtime configuration

---

lib/src/Pos/Launcher/Param.hs

Just a minor cleanup I found as I'm perusing the source code.

Clearing a TODO Comment: File to use for JSON logging

---

pkgs/default.nix
stack.yaml

See [below](https://github.com/input-output-hk/cardano-sl/pull/2530#issuecomment-366780468).

[CSL-2167] Bump for acid-state

---

wallet-new/cardano-sl-wallet-new.cabal
wallet-new/test/unit/UTxO/BlockGen.hs
wallet-new/test/unit/UTxO/DSL.hs
wallet-new/test/unit/UTxO/PreChain.hs
wallet-new/test/unit/WalletUnitTest.hs

Discussion in #2466 -- this PR is made from this repository for CI to run :smile:

[CSL-2288] QuickCheck generators for test blockchains

---

core/Pos/Core/Txp.hs

remove mkTxPayloadMerkleTree

---

infra/Pos/Reporting/Methods.hs

Should fix the permission problem. Tested with report server 0.4.9.

[CSL-2305] Use withCompressedFiles and tempDir for tarxz archive

---

lib/configuration.yaml

Bump mainnet wallet `applicationVersion` to 4.

[DEVOPS-638] mainnet_wallet_* applicationVersion: 3->4

---

block/src/Pos/Block/Network/Retrieval.hs

The worker will log and squelch exceptions from block retrieval.
This is the same idea as the patch at int-index/csl-2268
5c33d99a05d649acb4d6e5a433ac1098ac806890
Exception handlers are installed locally, on the IO action that comes
out of the retrieval queue STM transaction: one for recovery mode, one
for normal mode.

[CSL-2268] block retrieval worker exceptions

---

lib/src/Pos/Util/Servant.hs

[CSM-551] Split request and response in servant logs

---

update/Pos/Update/Download.hs
update/Pos/Update/Worker.hs

Improve downloadUpdateDo according to (1) [(https://github.com/input-output-hk/cardano-sl/blob/develop/docs/proposals/update-downloader.md#suggested-improvements)]
Instead of "Do not even start checkForUpdateWorker if the list of servers is empty (which is the case for core nodes)" server list checked for emptiness inside checkForUpdate with noServersProvided function. I made so because It seems that it`s better to check servers of one relevant ConfirmedProposalState (newestCPS) than all NonEmpty ConfirmedProposalState.

[CSL-1602] Improve update downloading logic

---

explorer/frontend/src/Explorer/I18n/EN.purs

YT issue: https://iohk.myjetbrains.com/youtrack/issue/CSE-261

[CSE-261] Fix typo

---

explorer/frontend/src/Lib/Waypoints/Waypoints.js
explorer/frontend/src/Lib/Waypoints/Waypoints.purs

Details https://iohk.myjetbrains.com/youtrack/issue/CSE-260

[CSE-260] Fix `TypeError: ce.destroy(...) is not a function`

---

update/Pos/Update/Download.hs
update/Pos/Update/Worker.hs

(1) and (4) implemented according to https://github.com/input-output-hk/cardano-sl/blob/develop/docs/proposals/update-downloader.md#suggested-improvements

[CSL-1602] Improve downloadUpdateDo and usWorkers logic

---

pkgs/default.nix
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/server/Cardano/Wallet/API/Development/LegacyHandlers.hs
wallet-new/server/Cardano/Wallet/API/V1/Swagger.hs
wallet-new/server/Main.hs
wallet-new/src/Cardano/Wallet/API/Development.hs
wallet-new/src/Cardano/Wallet/API/Request/Pagination.hs
wallet-new/src/Cardano/Wallet/API/Response.hs
wallet-new/src/Cardano/Wallet/API/Response/JSend.hs
wallet-new/src/Cardano/Wallet/API/V1/Types.hs
wallet-new/test/SwaggerSpec.hs

This PR gets the Swagger/Aeson tests working again. The `ValidJSON` type was causing it to miss the tests, and there are some regressions.

[CSL-2339] Get the Swagger/Aeson tests working again

---

networking/src/Node.hs
networking/src/Node/Internal.hs

This should means that a SIGINT will kill all handlers and you won't have to wait.

[CSL-2326] killNode on async exception

---

db/Pos/DB/Rocks/Functions.hs
db/cardano-sl-db.cabal
infra/Pos/Diffusion/Transport/TCP.hs
lib/src/Pos/Launcher/Resource.hs
lib/src/Pos/Launcher/Runner.hs
pkgs/default.nix
tools/src/launcher/Main.hs

[CSL-2326] Some shutdown-related logging

---

wallet-new/test/unit/WalletUnitTest.hs

Fixes https://iohk.myjetbrains.com/youtrack/issue/CSL-2362 .

Don't use 0 amount in transactions

---

wallet-new/server/Cardano/Wallet/API/V1/Swagger.hs

- Add short disclaimer about V1 being in BETA
- Fix License link -> points to github LICENSE file
- Reword notice about disabling TLS
- Fix version number & git revision in API description
- Hotfix oversight extra line return in API descriptions

[CBR-102] Disclaimer & few "hotfixes"

---

wallet-new/docs/spec.tex

This is Duncan's thoughts on input selection, submitted just before going on holidays (cutting it so short he wasn't able to create a PR :grin: ).

Wallet spec input selection

---

docs/PULL_REQUEST_TEMPLATE.md

@domenkozar This adds an initial pull request template -- I'm open to feedback, this is just an initial attempt. 😉

Add initial pull request template

---

default.nix
lib/src/Pos/Client/CLI/NodeOptions.hs
release.nix
scripts/ci/ci.sh

Provides a `daedalus-bridge` derivation which can be used when building the Daedalus installer.

[DEVOPS-673] Build Daedalus bridge with Nix

---

pkgs/default.nix
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/integration/CLI.hs
wallet-new/integration/Error.hs
wallet-new/integration/Functions.hs
wallet-new/integration/Main.hs
wallet-new/integration/Types.hs
wallet-new/src/Cardano/Wallet/API/V1/Types.hs
wallet-new/src/Cardano/Wallet/Client.hs

https://iohk.myjetbrains.com/youtrack/issue/CSL-2341
An example of the idea I had of how to use randomized integration testing.

[CSL-2341] Write logical integration tests.

---

infra/Pos/Communication/Protocol.hs
infra/Pos/Communication/Relay/Logic.hs
infra/Pos/Communication/Types/Protocol.hs
infra/cardano-sl-infra.cabal
lib/src/Pos/Diffusion/Full.hs
lib/src/Pos/Diffusion/Full/Block.hs
networking/src/Network/Broadcast/OutboundQueue.hs
pkgs/default.nix

This is a follow-up to #2598 which exposes the `TVar (PacketStatus t)` in the cardano-sl-infra types.

[CSL-2331] EnqueueMsg shows the TVar PackStatus

---

docs/PULL_REQUEST_TEMPLATE.md

Add "refactoring" as a "type of change" for the PR template.

Add refactoring as a type of change

---

docs/PULL_REQUEST_TEMPLATE.md

As discussed with @adinapoli-iohk in Slack.

Tweak PR template

---

binary/Test/Pos/Cbor/Canonicity.hs

Fix for name shadowing that got through with #2695.

[CBR-49] Fix name shadowing

---

pkgs/default.nix
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/integration/Error.hs
wallet-new/integration/Functions.hs
wallet-new/integration/Main.hs
wallet-new/server/Cardano/Wallet/API/V1/LegacyHandlers/Addresses.hs
wallet-new/src/Cardano/Wallet/API/Indices.hs
wallet-new/src/Cardano/Wallet/API/V1/Types.hs

Implement /api/v1/addresses with V0 logic.
https://iohk.myjetbrains.com/youtrack/issue/CSL-2416
Use a wallet that has existing addresses and then fetch all addresses.

[CSL-2416] Implement /api/v1/addresses with V0 logic.

---

lib/configuration.yaml

There will be new wallet installers proposed on the network.
See also: https://github.com/input-output-hk/internal-documentation/wiki/Daedalus-installer-history

[DEVOPS-758] Bump wallet applicationVersion

---

pkgs/default.nix
stack.yaml

See DEVOPS-739, DEVOPS-743 and DEVOPS-736.

[DEVOPS-739-743-736] Bump report-server

---

explorer/src/documentation/Main.hs
pkgs/default.nix
pkgs/generate.sh
stack.yaml
wallet-new/Makefile
wallet-new/server/Cardano/Wallet/API/V1/LegacyHandlers/Info.hs
wallet-new/server/Cardano/Wallet/API/V1/Swagger/Example.hs
wallet-new/src/Cardano/Wallet/API/V1/Types.hs
wallet-new/test/MarshallingSpec.hs
wallet/src/Pos/Wallet/Web/Methods/Misc.hs
wallet/src/Pos/Wallet/Web/Server/Handlers.hs
wallet/src/Pos/Wallet/Web/Swagger/Instances/Schema.hs

Huh, the template disappeared?
https://iohk.myjetbrains.com/youtrack/issue/CSL-2375

[CSL-2375] Change the NodeInfo response to be more flexible.

---

wallet/src/Pos/Wallet/Web/State/Storage.hs
wallet/test/Test/Pos/Wallet/MigrationSpec.hs

This commit ensures that a version of `wallet-db` produced with the
current version of the wallet can be successfully migrated to this
revision, which incorporates the 'SyncStatistics' as well as the
'WalletSyncState'.
It also extends the 'MigrationSpecs' to make sure we can migrate
backward as well.
I have tested this by restoring a wallet using the version in `develop` and assessing that the node wasn't able to start with the unmigrated code:
```
☁  cardano-sl [feature/CBR-90] stack exec cardano-node -- --topology=docs/network/example-topologies/mainnet-staging.yaml --configuration-key mainnet_dryrun_full --db-path ../staging-db --wallet-db-path ../wallet-db-staging-2018-04-04
Wallet is starting...
[*production*:INFO:ThreadId 4] [2018-04-05 09:51:23.07 UTC] [Attention] Software is built …
```

[CSL-2429] Add proper acid-state migrations

---

wallet-new/cardano-sl-wallet-new.cabal
wallet-new/server/Cardano/Wallet/API/V1/Handlers.hs
wallet-new/server/Cardano/Wallet/Server.hs
wallet-new/server/Cardano/Wallet/Server/Plugins.hs
wallet-new/server/Main.hs
wallet-new/src/Cardano/Wallet/Kernel.hs
wallet-new/src/Cardano/Wallet/Kernel/Mode.hs
wallet-new/src/Cardano/Wallet/WalletLayer.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Legacy.hs
wallet-new/src/Cardano/Wallet/WalletLayer/QuickCheck.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Types.hs

https://iohk.myjetbrains.com/youtrack/issue/CSL-2422
Initial prototype.

[CSL-2422] Create initial prototype for the WalletActiveLayer.

---

wallet-new/docs/references.bib
wallet-new/docs/spec.tex

See commit messages for details.

Additions to the spec

---

CHANGELOG.md
appveyor.yml
auxx/cardano-sl-auxx.cabal
binary/cardano-sl-binary.cabal
block/cardano-sl-block.cabal
client/cardano-sl-client.cabal
core/cardano-sl-core.cabal
crypto/cardano-sl-crypto.cabal
db/cardano-sl-db.cabal
delegation/cardano-sl-delegation.cabal
explorer/cardano-sl-explorer.cabal
generator/cardano-sl-generator.cabal
infra/Pos/Reporting/Methods.hs
infra/cardano-sl-infra.cabal
lib/cardano-sl.cabal
lrc/cardano-sl-lrc.cabal
networking/cardano-sl-networking.cabal
node/cardano-sl-node.cabal
pkgs/default.nix
ssc/cardano-sl-ssc.cabal
stack.yaml
tools/cardano-sl-tools.cabal
tools/src/launcher/Main.hs
txp/cardano-sl-txp.cabal
update/cardano-sl-update.cabal
util/cardano-sl-util.cabal
wallet/cardano-sl-wallet.cabal

Release 1.1.1

---

client/src/Pos/Client/Txp/Util.hs

Just a two character typo change in comments
No issue

Fix typos in comments

---

wallet-new/integration/Functions.hs
wallet-new/integration/Main.hs
wallet-new/integration/Types.hs
wallet-new/server/Cardano/Wallet/API/V1/LegacyHandlers/Accounts.hs
wallet-new/server/Cardano/Wallet/API/V1/LegacyHandlers/Wallets.hs
wallet/src/Pos/Wallet/Web/Methods/Logic.hs

This PR fixes the local state management problems that [CSL-2447](https://iohk.myjetbrains.com/youtrack/issue/CSL-2447)] and [CSL-2446](https://iohk.myjetbrains.com/youtrack/issue/CSL-2446) uncovered.

[CSL-2447] [CSL-2446] Integration test fixes

---

wallet-new/server/Cardano/Wallet/API/V1/Swagger.hs
wallet-new/src/Cardano/Wallet/API/V1/Errors.hs

And add this description to the current Swagger API doc. I've also reviewed a bit how the examples where displayed because I wasn't really satisfied with this long unreadable line ^.^
> NOTE: I've removed the `SomeOtherError { foo , bar }` cosntructor for it wasn't used anywhere. I believe it was an old dev / debug artifact ?
Preview for your (hopefully) mesmerized eyes:

[CBR-181] Describe API errors in a developer-friendly way

---

lib/configuration.yaml

The `applicationVersion` values for `csl-daedalus` need a bump for the staging and mainnet cluster.
...

applicationVersion bumps for the 1.2.0 release

---

pkgs/default.nix
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/API/V1/Migration/Types.hs
wallet-new/src/Cardano/Wallet/WalletLayer.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Error.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Legacy.hs
wallet-new/src/Cardano/Wallet/WalletLayer/QuickCheck.hs
wallet-new/src/Cardano/Wallet/WalletLayer/README.md
wallet-new/src/Cardano/Wallet/WalletLayer/Types.hs

https://iohk.myjetbrains.com/youtrack/issue/CSL-2423

[CSL-2423] Implement WalletActiveLayer for wallets and accounts.

---

CHANGELOG.md

This PR is necessary to avoid invalidating the testing effort in https://github.com/input-output-hk/daedalus/pull/866
~This PR is to overcome https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-801, and allow a Daedalus build: dummy commit to force a Github PR status change in `release/1.2.0`.~

Dummy CI bump commit.

---

lrc/Pos/Lrc/Core.hs

Have come across this function a number of times during investigation of related matters and on every occasion found the existing comments and function name confusing.
N/A
- [!] 🛠 New feature (non-breaking change which adds functionality)
- [!] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [~] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on …

lrc: Document invariants and improve function name

---

lib/bench/Bench/Pos/Criterion/TxSigningBench.hs

Hotfix, tx sign.

---

wallet-new/server/Cardano/Wallet/API/V1/LegacyHandlers/Wallets.hs
wallet-new/server/Cardano/Wallet/Server/Plugins.hs
wallet-new/src/Cardano/Wallet/API/V1/Errors.hs
wallet-new/src/Cardano/Wallet/API/V1/Migration/Types.hs
wallet-new/src/Cardano/Wallet/Client.hs
wallet-new/test/Spec.hs
wallet-new/test/WalletHandlersSpec.hs

This patch prevents operations (creation, restoration) on wallets if the underlying cardano node is not sufficiently synced with the blockchain. "Sufficiently" here means that we are not lagging more than `k` blocks behind, which is a decent compromise between being too lenient or too strict.
On top of that, it also fixes the error & exception handling mechanism for V0 and V1 endpoints, where exceptions were all swallowed into a very generic "Something went wrong" error.
**I'm also opening this against release/1.2.0 as it's effectively a bug fix which could impact exchanges if not merged.**
https://iohk.myjetbrains.com/youtrack/issue/CSL-2484
* Restoring or creating a wallet whilst a node is at a beginning of a sync should throw an error;
* Restoring or creating a wallet whilst a node is …

[CSL-2484] Forbid operations on wallets if a node is not synced

---

docs/exchange-onboarding.md

Minor doc change explaining old v0 `/api/addresses/{address}` does not verify the address exists in a loaded wallet, but rather just validates is a valid address format.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-769

[DEVOPS-769] v0-v1 exchange onboarding doc fixes

---

wallet-new/integration/Functions.hs
wallet-new/src/Cardano/Wallet/API/V1/Migration/Types.hs
wallet-new/src/Cardano/Wallet/API/V1/Types.hs

Computing this balance is an expensive and innacurate operation that we most probably don't
want to support in the future. If needed, it will be 'easy' to re-introduce than to remove
in a non-backward compatible way. Let's therefore remove it before shipping API V1.
> **NOTE** Still need to apply that change to develop which is a bit more tricky since we introduced integration tests that check some invariant based on the address balance. I need to look into that.
[CBR-190](https://iohk.myjetbrains.com/youtrack/issue/CBR-190)

[CBR-190] Remove address balance from wallets' addresses

---

scripts/launch/connect-to-cluster/default.nix
scripts/launch/connect-to-cluster/mainnet-staging.sh
tools/src/launcher/Main.hs
wallet-new/README.md

Force lang locales to UTF-8 to avoid runtime error described in [R120-4](https://iohk.myjetbrains.com/youtrack/issue/R120-4).
I'd like to add a regression test here though I am not sure if it's worth the pain. Ideally, we'd have to start a node with incompatible locales (for instance `LC_ALL=POSIX`) and verify that a request containing out-of-range unicode characters would fail... Sounds quite cumbersome to setup.
Any opinion?
[[R120-4]](https://iohk.myjetbrains.com/youtrack/issue/R120-4)
- We should be able to create, rename and view wallets with names with characters in any unicode ranges (like: 漢字)

R120 4/unicode characters support

---

docs/profiling.md

This document describes how to build and run for profiling. 
Sadly, `stack` doesn't seem to work; the `nix` option does work but there are some questions there too. It would be good to have some other eyes on this.
@adinapoli-iohk can you ping some relevant people?

.md file with profiling instructions

---

scripts/launch/connect-to-cluster/default.nix
scripts/launch/connect-to-cluster/mainnet-staging.sh
tools/src/launcher/Main.hs
wallet-new/README.md

Cf #2810
[[R120-4]](https://iohk.myjetbrains.com/youtrack/issue/R120-4)

Ktor z/r120 4/unicode characters support 1.2.0

---

wallet-new/src/Cardano/Wallet/API/V1/Migration/Types.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Error.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Legacy.hs
wallet-new/src/Cardano/Wallet/WalletLayer/QuickCheck.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Types.hs
wallet/src/Pos/Wallet/Web/State/State.hs
wallet/src/Pos/Wallet/Web/State/Storage.hs

https://iohk.myjetbrains.com/youtrack/issue/CSL-2424
We first need to merge https://github.com/input-output-hk/cardano-sl/pull/2758 in order for this to be reviewed and merged.

[CSL-2424]  Implement WalletActiveLayer for addresses

---

infra/Pos/Diffusion/Types.hs
pkgs/default.nix
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/server/Cardano/Wallet/API/V1/LegacyHandlers.hs
wallet-new/server/Cardano/Wallet/API/V1/LegacyHandlers/Info.hs
wallet-new/server/Cardano/Wallet/API/V1/Swagger/Example.hs
wallet-new/server/Cardano/Wallet/LegacyServer.hs
wallet-new/server/Cardano/Wallet/Server/Plugins.hs
wallet-new/src/Cardano/Wallet/API/V1/Types.hs

Now that we have the diffusion layer give us nice information about the status of the underlying node, we can expose this information in the API.
[[CBR-186]](https://iohk.myjetbrains.com/youtrack/issue/CBR-186)

CBR-186 - Subscription status in node-info

---

.nonsense
fetch-nixpkgs.nix
fetchNixpkgs.nix
nixpkgs-src.json
release.nix

[Devops-729] nix2 reverse compatibility changes

---

wallet-new/cardano-sl-wallet-new.cabal
wallet-new/integration/AddressSpecs.hs
wallet-new/integration/Main.hs
wallet-new/integration/TransactionSpecs.hs
wallet-new/integration/Util.hs
wallet-new/integration/WalletSpecs.hs

This patch splits the deterministic tests into separate modules, so that
new tests can be added easily on them.
I have reached the conclusion that as much as we like having randomised tests, having a nice and ever-growing pool of deterministic tests is the only way to have a _witness_ of testability when it comes to QA testing during each release. Merely saying "for CSL-XXXX we are covering the test bit via fuzzy testing" won't cover it, imho. We should be in the position to say "for CSL-XXXX, we test it by running spec X".
This PR is the stepping stone into that direction.
No linked issue, this spun via self-initiative (but can create one).
- [~] ⚠️ Breaking …

Split deterministic tests into separate modules

---

crypto/Pos/Crypto.hs
crypto/Pos/Crypto/Signing.hs
crypto/Pos/Crypto/Signing/Types.hs
crypto/cardano-sl-crypto.cabal
pkgs/default.nix
util/Pos/Util.hs
util/Pos/Util/QuickCheck.hs
util/cardano-sl-util.cabal
wallet-new/src/Cardano/Wallet/Kernel/Mode.hs

Remove autoexporter.
This is the first PR from Jordan Millar (@Jimbo4350) who was one of the students at the IOHK Haskell training course in Barbados. Jordan isn't a member of the IOHK group yet so can't push to this repo. Working on getting that fixed.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-240

Remove use of autoexporter from util and crypto packages

---

wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/WalletLayer/Error.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Legacy.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Legacy/Transactions.hs
wallet-new/src/Cardano/Wallet/WalletLayer/QuickCheck.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Types.hs

Implement WalletActiveLayer for transactions.
https://iohk.myjetbrains.com/youtrack/issue/CSL-2425

[CSL-2425] Implement WalletActiveLayer for transactions

---

wallet-new/integration/TransactionSpecs.hs
wallet-new/integration/WalletSpecs.hs
wallet-new/server/Cardano/Wallet/API/V1/LegacyHandlers/Transactions.hs
wallet-new/src/Cardano/Wallet/API/V1/Errors.hs
wallet-new/src/Cardano/Wallet/Client/Http.hs

The integration test for fee estimation was broken. I have fixed it.
CSL-2493, sort of, but we closed it out.
Run the integration tests.

Fix integration test

---

fetch-nixpkgs.nix

fix the recent issues with nix2 on buildkite

[DEVOPS-720] fix nix2 on cardano

---

core/Pos/Binary/Core.hs
core/Pos/Core.hs
core/Pos/Core/Block.hs
core/Pos/Core/Block/Genesis.hs
core/Pos/Core/Block/Main.hs
core/Pos/Core/Block/Union.hs
core/Pos/Core/Common.hs
core/Pos/Core/Context.hs
core/Pos/Core/Genesis.hs
core/Pos/Core/Slotting.hs
core/Pos/Core/Ssc.hs
core/Pos/Core/Update.hs
core/cardano-sl-core.cabal
db/Pos/DB.hs
db/Pos/DB/Rocks.hs
infra/Pos/Communication/Relay.hs
infra/Pos/DHT/Model.hs
infra/Pos/DHT/Real.hs
infra/Pos/Discovery.hs
infra/Pos/Ntp.hs
infra/Pos/Reporting.hs
infra/Pos/Shutdown.hs
infra/Pos/Slotting/Impl.hs
infra/Pos/Statistics.hs
pkgs/default.nix

As per title.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-241

Remove more autoexporter

---

delegation/src/Pos/Delegation.hs
delegation/src/Pos/Delegation/Cede.hs
delegation/src/Pos/Delegation/Logic.hs
generator/src/Pos/Generator.hs
generator/src/Pos/Generator/Block.hs
wallet/src/Pos/Wallet/Web.hs
wallet/src/Pos/Wallet/Web/Error.hs
wallet/src/Pos/Wallet/Web/Methods.hs
wallet/src/Pos/Wallet/Web/Pending.hs
wallet/src/Pos/Wallet/Web/Server.hs
wallet/src/Pos/Wallet/Web/Sockets.hs
wallet/src/Pos/Wallet/Web/Swagger.hs
wallet/src/Pos/Wallet/Web/Tracking.hs

Remove autoexporter from delegation generator and wallet
https://iohk.myjetbrains.com/youtrack/issue/CDEC-274

Remove autoexporter

---

wallet-new/README.md

I've seen quite a few people struggling recently with the `415` invalid media-type error returned by the wallet backend when submitting a wrong `Content-Type` or `Accept` header. Each time, it was because the `charset=utf-8` meta part was missing. I believe the error could give a bit more hint about it. 
We could also drop a line in the *Troubleshooting* section of the wallet's README about it as newcomers will likely stumble upon this in the future :) 
[[CBR-223]](https://iohk.myjetbrains.com/youtrack/issue/CBR-223)

[CBR-223] Drop a line about fixing missing charset when getting 415 from the API

---

block/src/Pos/Block/Logic.hs
block/src/Pos/Block/Network.hs
block/src/Pos/Block/Slog.hs
client/src/Pos/Client/Txp.hs
client/src/Pos/Client/Update.hs
ssc/Pos/Binary/Ssc.hs
ssc/Pos/Ssc.hs
ssc/Pos/Ssc/Error.hs
ssc/Pos/Ssc/Logic.hs
ssc/Pos/Ssc/Toss.hs

Remove from client block and ssc packages
https://iohk.myjetbrains.com/youtrack/issue/CDEC-273

Make autoexporter disappear

---

crypto/cardano-sl-crypto.cabal
crypto/test/Spec.hs
crypto/test/Test/Pos/Crypto/CryptoSpec.hs
crypto/test/test.hs
lib/test/Test/Pos/CryptoSpec.hs
pkgs/default.nix

As per title
https://iohk.myjetbrains.com/youtrack/issue/CDEC-244

[CDEC-244] Move tests for crypto package from lib to crypto package

---

.editorconfig

Just starting a discussion here, following-up on a discussion yesterday on Slack. Here's the `.editorconfig` I currently use for cardano-sl, rather simple but at least get me the correct indentation and behavior for haskell files. 
Inputs are welcome, I guess we can add section for bash & nix files at least.

Groom .editorconfig structure

---

util/cardano-sl-util.cabal
util/test/Test.hs
util/test/Test/Pos/Util.hs

The OS X filesystem is case insensitive and two recent PRs aded the
files `test.hs` and `Test.hs` which were actually identical apart from
whitespace.
Supercedes #2857 
N/A

Fix util test directory

---

pkgs/default.nix
stack.yaml
wallet-new/integration/Util.hs
wallet-new/integration/WalletSpecs.hs

Unicode characters cause the API endpoints to die. This PR uses a patched version of `log-warper` that I have branched off of the current version that we are using: https://github.com/input-output-hk/log-warper/pull/2 is the PR, though it should probably live in it's own branch, as the paths have diverged a bit.
I suggest we get the branch into `input-output-hk/log-warper` so that we can more rapidly iterate on that while moving to `katip`.
https://iohk.myjetbrains.com/youtrack/issue/R120-4#comment=93-20912
- …

[R120-4] Use patched log-warper to set utf8 encoding

---

fetch-nixpkgs.nix
fetchNixpkgs.nix
nixpkgs-src.json
pkgs/generate.sh
release.nix

Backport nix 2 compatibility changes so PR's to release don't fail after hydra upgrade
@cleverca22 stated that this is only required to be backported if we make any more changes to cardano-sl before release. Otherwise, this can be dropped.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-720

[DEVOPS-720] nix2 reverse compatibility changes (#2826)

---

lib/test/Test/Pos/Txp/Toil/UtxoSpec.hs
txp/Pos/Txp/Toil/Failure.hs
txp/Pos/Txp/Toil/Logic.hs
txp/Pos/Txp/Toil/Utxo/Functions.hs

All those field accessors are partial functions. They are simply not needed.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-235

[CDEC-235]: Remove field accessors from ToilVerFailure sum type

---

auxx/src/Command.hs
auxx/src/Lang.hs
lib/src/Pos/Launcher.hs
lib/src/Pos/Web.hs
update/Pos/Arbitrary/Update.hs
update/Pos/Binary/Update.hs
update/Pos/Update/Logic.hs
update/Pos/Update/MemState.hs
update/Pos/Update/Network.hs
update/Pos/Update/Poll.hs

Remove use of autoexporter from lib, update and auxx packages
[https://iohk.myjetbrains.com/youtrack/issue/CDEC-275](https://iohk.myjetbrains.com/youtrack/issue/CDEC-275)

Remove use of autoexporter from lib, update and auxx packages

---

lib/cardano-sl.cabal

Compilation on FreeBSD remade. This OS does not understand `systemd`.
not on YT.
- [ x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ x] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [ ~] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [ ~] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any …

successful compilation on FreeBSD; no systemd

---

wallet-new/docs/spec.tex

Sorry @adinapoli-iohk , I had one local commit still in by branch that hasn't been merged yet.

Feedback Niamh abstract

---

client/src/Pos/Client/Txp/Network.hs
client/src/Pos/Client/Txp/Util.hs
wallet-new/server/Cardano/Wallet/API/V1/LegacyHandlers/Transactions.hs
wallet/src/Pos/Wallet/Web/Methods/Payment.hs

Implement handler for /api/v1/transactions/unsigned endpoint
https://iohk.myjetbrains.com/youtrack/issue/CHW-84

[CHW-84] Implement handler for /api/v1/transactions/unsigned endpoint

---

lib/configuration.yaml

Bump the `staging` `applicationVersion` for `csl-daedalus` to `10`.

Devops 828 appver

---

tools/src/keygen/KeygenOptions.hs
tools/src/keygen/Main.hs

Remove field accessors from `KeygenCommand` data type
[https://iohk.myjetbrains.com/youtrack/issue/CDEC-284](https://iohk.myjetbrains.com/youtrack/issue/CDEC-284)

Remove field accessors from `KeygenCommand` data type

---

default.nix
scripts/launch/connect-to-cluster/default.nix
scripts/launch/demo-cluster/default.nix
scripts/test/wallet/integration/default.nix
wallet-new/integration/Functions.hs
wallet-new/integration/TransactionSpecs.hs
wallet-new/integration/Util.hs

[DEVOPS-819] asset-lock integration test and demo cluster support

---

wallet/test/Test/Pos/Wallet/Web/Tracking/SyncSpec.hs

We have a test failure in CI. This is causing spurious build failures, so we are disabling the test for now until development effort can be focused on it.
https://iohk.myjetbrains.com/youtrack/issue/CSL-2473

[CSL-2473] Mark test pending

---

pkgs/default.nix
scripts/launch/demo.sh
util/Pos/Util/Chrono.hs
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/Kernel.hs
wallet-new/src/Cardano/Wallet/Kernel/Actions.hs
wallet-new/src/Cardano/Wallet/Kernel/Mode.hs
wallet-new/src/Cardano/Wallet/WalletLayer.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Legacy.hs
wallet-new/src/Cardano/Wallet/WalletLayer/QuickCheck.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Types.hs
wallet-new/test/unit/WalletUnitTest.hs

(This is an un-botched version of a previous PR)
This adds the "wallet worker", a layer that can asynchronously receive blocks and rollbacks from the block listener and apply them to a wallet. The worker is also responsible for batching related operations together. For example, it will combine a sequence of rollbacks and block applications into a single `switchToFork` operation.
The worker is agnostic about the kind of wallet it is managing; in fact, it does not even have a concept of a wallet. Instead, the worker is configured with a `WalletActionInterp` that describes how to execute basic wallet API functions such as `applyBlocks` and `switchToFork`. This makes it easy to test the wallet worker's behavior in a pure setting, and validate it against simpler operational models (e.g. the …

Apply patch from feature/csl-2388-test-passive-wallet.

---

binary/Pos/Binary/Class.hs
binary/cardano-sl-binary.cabal
pkgs/default.nix
txp/Pos/Binary/Txp.hs
txp/Pos/Txp/Logic.hs
txp/Pos/Txp/MemState.hs
txp/Pos/Txp/Toil/Utxo.hs
wallet-new/bench/Bench/Cardano/Wallet/Config.hs
wallet-new/bench/Client/Cardano/Wallet/Web/Endpoint.hs

Remove use of autoexporter from wallet-new, binary and txp packages
[https://iohk.myjetbrains.com/youtrack/issue/CDEC-276](https://iohk.myjetbrains.com/youtrack/issue/CDEC-276)

Remove use of autoexporter from wallet-new, binary and txp packages

---

explorer/src/Pos/Explorer/Web/Server.hs
infra/Pos/Shutdown/Class.hs
lib/Setup.hs
lib/cardano-sl.cabal
lib/src/Pos/Web/Server.hs
node-ipc/LICENSE
node-ipc/Setup.hs
node-ipc/node-ipc.cabal
node-ipc/server.js
node-ipc/shell.nix
node-ipc/src/Cardano/NodeIPC.hs
pkgs/default.nix
stack.yaml
tools/src/launcher/Main.hs
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/Server/CLI.hs
wallet-new/src/Cardano/Wallet/Server/Plugins.hs
wallet/cardano-sl-wallet.cabal
wallet/src/Pos/Wallet/Web/Server/Launcher.hs
wallet/src/Pos/Wallet/Web/Server/Runner.hs

the primary goal of these changes is to bind the wallet API to a random port, and then advertise it over a the IPC channel node configures when launching cardano
if cardano is told to bind to port 8090 using the existing config flags, these changes should have zero impact on the behavior of cardano
https://iohk.myjetbrains.com/youtrack/issue/CSL-2503

[CSL-2503] implement the node-ipc server

---

auxx/Main.hs
infra/Pos/Reporting/Statsd.hs
lib/src/Pos/Diffusion/Full.hs
lib/src/Pos/Launcher/Runner.hs
lib/src/Pos/Logic/Full.hs
lib/src/Pos/Logic/Types.hs
networking/src/Node.hs
networking/src/Node/Internal.hs

5th installment of the incremental merge of `networking/develop` into `develop`.
Find here:
- Simplification of the full logic layer (one does not "run" it, one only creates it).
- `SendActions` are exposed in the full diffusion layer internals, useful for doing simulations / tests / benchmarks.
- The statsd reporting server is in `IO`, making it simpler to deal with.
- `runFullDiffusionLayer` uses proper concurrency, but is still buggy since we use an old async version (#2745 will fix this).
- Improvements to the monstrous dispatcher thread.
- Outbound queue shutdown fix.

[CDEC-161] 5th instalment of networking/develop merge

---

infra/Pos/Diffusion/Subscription/Common.hs
infra/Pos/Diffusion/Subscription/Dns.hs
infra/Pos/Diffusion/Subscription/Subscriber.hs
infra/cardano-sl-infra.cabal
lib/src/Pos/Diffusion/Full.hs
lib/src/Pos/Logic/Pure.hs

In this final instalment find:
- The subscription mechanism was made more modular: you don't have to use DNS to resolve peers. This is useful for testing/simulation.
- The pure logic layer properly seeds the deterministic key generator.
- Full diffusion layer `OutSpecs` include the subscription stuff even if there's no subscription worker. This should be viewed as a workaround for the weird `OutSpecs` system: if we run a test/simulation setup in which we don't use a "subscription worker" thread (currently taken care of by the full diffusion layer) but instead wish to manually set up the subscription (`withNetworkSubscription`) it would fail because the `OutSpecs` wouldn't be correct.

6th and final instalment of networking/develop merge

---

default.nix
pkgs/default.nix
pkgs/generate.sh

Bump `stack2nix` version to include CDEC-307 and CDEC-308. Also add the `--bench` flag intoduced by CDEC-308 to the `generate.sh` file and regenerate `pkgs/default.nix`.
[CDEC-308](https://iohk.myjetbrains.com/youtrack/issue/CDEC-308)

[CDEC-308] Bump stack2nix and use new --bench flag

---

client/cardano-sl-client.cabal
core/cardano-sl-core.cabal
crypto/cardano-sl-crypto.cabal
explorer/cardano-sl-explorer.cabal
explorer/src/Pos/Explorer/Web/ClientTypes.hs
lib/cardano-sl.cabal
lrc/cardano-sl-lrc.cabal
networking/cardano-sl-networking.cabal
node-ipc/node-ipc.cabal
pkgs/default.nix
tools/cardano-sl-tools.cabal
util/cardano-sl-util.cabal
wallet-new/cardano-sl-wallet-new.cabal

Hoping that doing this would get builds working on OS X again.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-319

[CDEC-319] Remove unneeded build depends from cabal files

---

wallet-new/server/Main.hs

Includes changes suggested by @parsonsmatt in #2932

[CSL-2337] follow up with review changes

---

pkgs/default.nix
stack.yaml
util/Pos/Util/Chrono.hs
util/Pos/Util/Modifier.hs
util/Pos/Util/Orphans.hs
util/test/Test/Pos/Util/ModifierSpec.hs
util/test/Test/Pos/Util/QuickCheck/Property.hs
util/test/Test/Pos/UtilSpec.hs

remove some redundant constraints in util

---

wallet/src/Pos/Wallet/Web/State/Acidic.hs
wallet/src/Pos/Wallet/Web/State/State.hs
wallet/src/Pos/Wallet/Web/State/Storage.hs
wallet/src/Pos/Wallet/Web/State/Transactions.hs

This is a backport of the acid-state backwards compatibility fix in #2942 to the `release/1.2.0` branch.

[R120-17] Ensure backwards compatibility of acid-state databases (#2942)

---

lib/src/Pos/Web/Server.hs
pkgs/default.nix
scripts/launch/demo-cluster/default.nix
scripts/launch/demo.sh
scripts/launch/ui-simulator.sh
scripts/test/wallet/integration.sh
scripts/test/wallet/integration/default.nix
scripts/test/wallet/many-addrs-test.sh
scripts/test/wallet/many-tx-test.sh
stack.yaml
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/integration/CLI.hs
wallet-new/integration/Main.hs
wallet-new/integration/QuickCheckSpecs.hs
wallet-new/src/Cardano/Wallet/Client/Http.hs

I noticed that integration tests are currently running using the HTTP via --wallet-debug option. Integration tests should reproduce the production environment as closely as possible.
The idea here will be to expose smart constructors from Cardano.Wallet.Client.Http to create connection Manager relying on either HTTP or HTTPs.
> **NOTE** /!\ Keep In Sync with #2803 
>
> See https://github.com/input-output-hk/cardano-sl/pull/2803#discussion_r183048392
> Options flags are going to be needed.
See [CSL-2492](https://iohk.myjetbrains.com/youtrack/issue/CSL-2492)

[CSL-2492] Run integration tests through TLS connection 

---

wallet-new/bench/README.md

Complete usage example for wallet API benchmarking

---

infra/Pos/Diffusion/Subscription/Common.hs

Regression introduced in pull request #2925.
One failing subscription would kill the whole program.
Now all synchronous exceptions are squelched.
Fixes #2977

fix subscription exception handling

---

pkgs/default.nix
util/test/Test/Pos/Util/Base16.hs
util/test/cardano-sl-util-test.cabal

Write test utility functions for displaying hexadecimal.
[https://iohk.myjetbrains.com/youtrack/issue/CDEC-327](https://iohk.myjetbrains.com/youtrack/issue/CDEC-327)

[CDEC-327] Write test utility functions for displaying hexadecimal.

---

pkgs/default.nix

Attempt to fix the current CI failure in @avieth's #2745 PR.

[CBR-51] Update pkgs/default.nix

---

tools/Setup.hs
tools/src/launcher/Main.hs
tools/src/launcher/launcher-config.yaml

[CSL-2503] Simplifying tls arguments

---

networking/bench/LogReader/Main.hs
networking/bench/Receiver/Main.hs
networking/bench/Sender/Main.hs
networking/cardano-sl-networking.cabal
networking/src/Bench/Network/Commons.hs
pkgs/default.nix

Formerly #2888 
There's meant to be no significant semantic changes in here. What had to be done:
- Get rid of dodgy uses of state transformers (don't use StateT to express a simple fold).
- Get rid of log-warper transformed-based logging in favour of the Trace interface.
- Get rid of uses of mockable.

[CDEC-313] networking benchmarks compile

---

pkgs/default.nix
txp/test/Test/Pos/Txp/Arbitrary.hs
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec.hs
wallet-new/src/Cardano/Wallet/Kernel/Submission.hs
wallet-new/test/unit/Test/Spec/Submission.hs
wallet-new/test/unit/WalletUnitTest.hs

This work-in-progress PR is a sneak-peek over a possible implementation of the transaction submission mechanism outlined in the wallet spec. It ships with a fully-functional scheduler and a bunch of stock resubmission functions, but this is still not complete because:
https://iohk.myjetbrains.com/youtrack/issue/CBR-245

[CBR-245] Transaction submission according to the wallet spec

---

CHANGELOG.md

Release 1.2.0: Update the Change Log

---

util/Pos/Util/Log.hs
util/Pos/Util/LoggerConfig.hs
util/test/Test/Pos/Util/LogSpec.hs

Messages with lower severity than the minimum acceptable specified must not be logged.

[CBR-274] Added test for severity.

---

pkgs/default.nix
wallet-new/src/Cardano/Wallet/API/V1/Swagger.hs
wallet-new/src/Cardano/Wallet/API/V1/Swagger/Example.hs
wallet/cardano-sl-wallet.cabal
wallet/src/Pos/Util/BackupPhrase.hs
wallet/src/Pos/Util/Mnemonics.hs
wallet/test/Test/Pos/Util/MnemonicsSpec.hs

Some users reported weird money movement on their wallets. It appears that they were using a wallet with a same Id that can be created or restored by submitting an empty mnemonic backup phrase.
This PR prevent this and introduce a couple of tests that were written while trying to track down the issue. Note that I am still unsure about the complete impact on wallet that have already been created or restored using an empty backup phrase. They should continue to operate as normal but won't be recoverable anymore. We probably want to warn all those users about this and tell them to stop using the wallets anyway. 
[[CBR-165]](https://iohk.myjetbrains.com/youtrack/issue/CO-256)

[CBR-165] Bug Wallet Balance

---

wallet-new/test/unit/Test/Infrastructure/Generator.hs
wallet-new/test/unit/Test/Infrastructure/Genesis.hs
wallet-new/test/unit/Test/Spec/Models.hs
wallet-new/test/unit/Test/Spec/Translation.hs
wallet-new/test/unit/UTxO/Generator.hs
wallet-new/test/unit/Wallet/Inductive/Generator.hs

This replaces the fee estimate in the wallet unit tests with a formula derived from the actual serialized size of a `Tx`.
There are a number of supporting changes made to the tests, stemming from two things:
1. The new estimator needs to know the `Coin` amounts in each tx output, not just the total number of tx outputs.
2. The linear size -> fee function has coefficients that are derived from the current configuration, leading to a `HasGenesisBlockVersionData` constraint in a few places.
CBR-262

Hard coded fee estimates

---

wallet-new/docs/spec.tex

Fix two tex references; relax relation between wallet and submission layer.

[CBR-60] Minor fixes to wallet spec

---

scripts/launch/connect-to-cluster/default.nix

Fixes issues with docker container and locales.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-877

[DEVOPS-877] Add LOCALE_ARCHIVE to connect-to-cluster script

---

pkgs/default.nix
stack.yaml

The custom dependency on this package can be removed because the
Hackage version now includes required commit b106470f0a of dns.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-351

[CDEC-351] Use hackage version of dns package

---

default.nix

@avieth pointed out that TCP-based tests of `cardano-sl-networking` were disabled in favor of an in-memory transport.
This would fix test failures due to incompatibilities with our Buildkite environment -- this re-enables the tests.

cardano-sl-networking:  re-enable tests

---

lrc/src/Pos/Lrc/Consumer.hs
lrc/src/Pos/Lrc/Consumer/Delegation.hs
lrc/src/Pos/Lrc/Consumer/Ssc.hs
lrc/src/Pos/Lrc/Consumer/Update.hs
lrc/src/Pos/Lrc/DB/Richmen.hs
lrc/src/Pos/Lrc/DB/RichmenBase.hs
lrc/src/Pos/Lrc/RichmenComponent.hs

The `RichmenComponent` was implemented as a type class with a bunch of `Proxy` parameters, rather than as a simple record type. One pointless type class down...
[CDEC-350](https://iohk.myjetbrains.com/youtrack/issue/CDEC-350)

[CDEC-350] Change RichmenComponent from type class to data

---

docs/rules/rules.tex

Some minor suggested edits to the Core Spec.
N/A
- [~] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [~] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exc …

A few suggested tweaks

---

default.nix
docs/exchange-onboarding.md
docs/how-to/connect-to-cluster.md
docs/tls-authentication.md
nixos-tests/wallet-api.nix
release.nix

[DEVOPS-732] hydra build staging and mainnet docker images

---

appveyor.yml

this combines with https://github.com/input-output-hk/daedalus/pull/943 and will solve the github ratelimiting problems on appveyor PR's

[DEVOPS-864] upload cardanosl.zip to S3

---

default.nix
scripts/launch/connect-to-cluster/default.nix
scripts/launch/demo-cluster/default.nix
scripts/launch/demo-cluster/make-topology.nix
scripts/test/wallet/integration/default.nix

@rvl wanted some of my improvements in the asset locking PR separated out so he could use them sooner.
This contains improvements to how nix handles src attribute for cardano to filter out files that shouldn't cause massive rebuilds. Improvements to demo cluster and connect to cluster scripts.

[DEVOPS-398] Nix caching test improvements

---

lib/configuration.yaml

Bumps applicationVersion for 1.2.1 hotfix

Bump applicationVersion for 1.2.1 release

---

infra/Pos/Infra/Ntp/Configuration.hs
networking/src/Ntp/Client.hs
networking/src/Ntp/Packet.hs

* Fixed ntp drift calculation.
* Take minimum offset, instead of median
https://iohk.myjetbrains.com/youtrack/issue/IOHKS-57

[IOHKS-57] Fixed drift calulation

---

binary/cardano-sl-binary.cabal
binary/src/Pos/Binary/Class/TH.hs
binary/test/Spec.hs
binary/test/Test/Pos/Binary/BiSerialize.hs
binary/test/test.hs
pkgs/default.nix

Currently Pos.Binary.Class defines `deriveSimpleBi` that uses TH to generate binary serialization/deserialization functions.
However it only works on data types with accessors which is fine for structs, but really bad for sum types. For sum types, each field accessor function is partial.
This PR implements a new Bi-instance derivation function which uses integer indices instead of field names. This approach doesn't require Sum types to have partial-function field accessors.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-328
- [~] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, …

[CDEC-328] Implement `deriveIndexedBi`

---

auxx/cardano-sl-auxx.cabal
binary/cardano-sl-binary.cabal
block/cardano-sl-block.cabal
client/cardano-sl-client.cabal
core/cardano-sl-core.cabal
crypto/cardano-sl-crypto.cabal
db/cardano-sl-db.cabal
delegation/cardano-sl-delegation.cabal
explorer/cardano-sl-explorer.cabal
generator/cardano-sl-generator.cabal
infra/cardano-sl-infra.cabal
lib/cardano-sl.cabal
lrc/cardano-sl-lrc.cabal
networking/cardano-sl-networking.cabal
node/cardano-sl-node.cabal
pkgs/default.nix
ssc/cardano-sl-ssc.cabal
tools/cardano-sl-tools.cabal
txp/cardano-sl-txp.cabal
update/cardano-sl-update.cabal
util/cardano-sl-util.cabal
wallet-new/cardano-sl-wallet-new.cabal
wallet/cardano-sl-wallet.cabal

cabal version bump to 1.2.1

---

block/bench/Block.hs
block/cardano-sl-block.cabal
block/test/LICENSE
block/test/Setup.hs
block/test/Test/Pos/Block/Arbitrary.hs
block/test/Test/Pos/Block/Arbitrary/Generate.hs
block/test/Test/Pos/Block/Arbitrary/Message.hs
block/test/cardano-sl-block-test.cabal
explorer/cardano-sl-explorer.cabal
explorer/src/Pos/Explorer/TestUtil.hs
explorer/test/Test/Pos/Explorer/Web/ServerSpec.hs
generator/cardano-sl-generator.cabal
generator/test/Test/Pos/Block/Logic/CreationSpec.hs
lib/cardano-sl.cabal
lib/test/Test/Pos/Block/Identity/SafeCopySpec.hs
lib/test/Test/Pos/Cbor/CborSpec.hs
lib/test/Test/Pos/Types/BlockSpec.hs
pkgs/default.nix
stack.yaml

As it stands, the `Arbitrary` instances for data types in `block` all exist in `block` when they should actually be exposed from a separate package, `block-test`. This PR creates this new package and moves over the `Arbitrary` instances.
[https://iohk.myjetbrains.com/youtrack/issue/CDEC-360](https://iohk.myjetbrains.com/youtrack/issue/CDEC-360)

[CDEC-360] Create block-test package and move Arbitrary instances

---

block/cardano-sl-block.cabal
pkgs/default.nix

This issue stemmed from my solution to CDEC-360 as I didn't ensure that all of the benchmarks built correctly.
[https://iohk.myjetbrains.com/youtrack/issue/CDEC-362](https://iohk.myjetbrains.com/youtrack/issue/CDEC-362)

[CDEC-362] Fix block benchmark build

---

pkgs/default.nix
pkgs/generate.sh
stack.yaml
wallet-new/bench/Bench/Cardano/Wallet/Config/Wallets.hs

use LTS 11.13

---

lib/cardano-sl.cabal
pkgs/default.nix
stack.yaml

The only one we could remove was `cryptonite` which is now on Hackage.
[CDEC-351](https://iohk.myjetbrains.com/youtrack/issue/CDEC-351)

[CDEC-351] Remove custom git dependencies where possible

---

core/test/Test/Pos/Core/Gen.hs
core/test/cardano-sl-core-test.cabal
crypto/test/Test/Pos/Crypto/Gen.hs
pkgs/default.nix

Implement Hedgehog generators for serializable data types in `core`.
[https://iohk.myjetbrains.com/youtrack/issue/CDEC-348](https://iohk.myjetbrains.com/youtrack/issue/CDEC-348)

[CDEC-348] Add Hedgehog generators for data types in core

---

auxx/Main.hs
block/src/Pos/Block/Lrc.hs
client/src/Pos/Client/Txp/History.hs
core/src/Pos/Core/Slotting/LocalSlotIndex.hs
explorer/cardano-sl-explorer.cabal
explorer/src/Pos/Explorer/DB.hs
explorer/src/Pos/Explorer/ExplorerMode.hs
explorer/src/explorer/Main.hs
generator/src/Test/Pos/Block/Logic/Mode.hs
generator/test/Test/Pos/Generator/Block/LrcSpec.hs
lib/bench/Bench/Configuration.hs
lib/bench/Bench/Pos/Criterion/FollowTheSatoshiBench.hs
lib/bench/Bench/Pos/Criterion/TxSigningBench.hs
lib/src/Pos/DB/DB.hs
lib/src/Pos/Launcher/Launcher.hs
lrc/src/Pos/Lrc/DB/Leaders.hs
lrc/src/Pos/Lrc/DB/Lrc.hs
lrc/src/Pos/Lrc/Fts.hs
lrc/src/Pos/Lrc/Genesis.hs
lrc/test/Test/Pos/Lrc/FtsSpec.hs
pkgs/default.nix
tools/src/dbgen/Main.hs
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/server/Main.hs
wallet-new/test/unit/UTxO/Context.hs

Somebody decided to read in the yaml configuration at compile time, and then use it to give reflection configurations `HasConfigurations`. That's ridiculous, so it's been removed. Formerly broken benchmarks now use the `benchProtocolConstants` and `benchProtocolMagic`, values sourced from what they were when read in from `lib/configuration.yaml` `test` section.

make cardano-sl benchmarks compile

---

pkgs/default.nix
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/server/Main.hs
wallet-new/src/Cardano/Wallet/Kernel.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/AcidState.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Create.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Read.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Read.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Update.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Util.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Util/AcidState.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Util/IxSet.hs
wallet-new/src/Cardano/Wallet/Kernel/PrefilterTx.hs
wallet-new/src/Cardano/Wallet/Kernel/Types.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
wallet-new/test/unit/Test/Spec/Kernel.hs
wallet-new/test/unit/Wallet/Inductive/Cardano.hs

Wire up pure wallet to AcidState data layer. 
Includes changes to account-based pre-filtering and dynamic creation of accounts.
https://iohk.myjetbrains.com/youtrack/issue/CBR-238

CBR-238 Use persistent state in data layer

---

infra/test/LICENSE
infra/test/Setup.hs
infra/test/Test/Pos/Infra/Gen.hs
infra/test/cardano-sl-infra-test.cabal
pkgs/default.nix
stack.yaml
util/test/Test/Pos/Util/Gen.hs
util/test/cardano-sl-util-test.cabal

Implement Hedgehog generators for serializable data types in infra.
[https://iohk.myjetbrains.com/youtrack/issue/CDEC-342](https://iohk.myjetbrains.com/youtrack/issue/CDEC-342)

[CDEC-342] Add Hedgehog generators for data types in infra

---

appveyor.yml

Sets system-ghc at global level at beginning of build so all stack commands use the system-ghc instead of downloading one. This makes the `stack path` command that cache-s3 use succeed without having to download ghc again.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-901

[DEVOPS-901] set appveyor stack system-ghc globally

---

block/test/Test/Pos/Block/Arbitrary.hs
block/test/cardano-sl-block-test.cabal
delegation/cardano-sl-delegation.cabal
delegation/test/LICENSE
delegation/test/Setup.hs
delegation/test/Test/Pos/Delegation/Arbitrary.hs
delegation/test/cardano-sl-delegation-test.cabal
generator/cardano-sl-generator.cabal
generator/test/Test/Pos/Block/Logic/CreationSpec.hs
lib/cardano-sl.cabal
lib/test/Test/Pos/Cbor/CborSpec.hs
pkgs/default.nix
stack.yaml

As it stands, the `Arbitrary` instances for data types in `delegation` all exist in `delegation` when they should actually be exposed from a separate package, `delegation-test`. This PR creates this new package and moves over the `Arbitrary` instances.
[https://iohk.myjetbrains.com/youtrack/issue/CDEC-334](https://iohk.myjetbrains.com/youtrack/issue/CDEC-334)

[CDEC-334] Create delegation-test package and move Arbitrary instances

---

auxx/Main.hs
block/cardano-sl-block.cabal
block/src/Pos/Block/Configuration.hs
block/src/Pos/Block/Network/Retrieval.hs
block/src/Pos/Block/Network/Types.hs
block/src/Pos/GState/BlockExtra.hs
block/test/Test/Pos/Block/Arbitrary/Message.hs
explorer/src/explorer/Main.hs
infra/Pos/Infra/Diffusion/Types.hs
lib/bench/Bench/Pos/Diffusion/BlockDownload.hs
lib/bench/Local/Criterion.hs
lib/cardano-sl.cabal
lib/configuration.yaml
lib/src/Pos/Binary/Communication.hs
lib/src/Pos/Communication/Limits.hs
lib/src/Pos/Communication/Message.hs
lib/src/Pos/Diffusion/Full.hs
lib/src/Pos/Diffusion/Full/Block.hs
lib/src/Pos/Launcher/Runner.hs
lib/src/Pos/Logic/Full.hs
lib/src/Pos/Logic/Pure.hs
lib/src/Pos/Logic/Types.hs
lib/test/Test/Pos/Cbor/CborSpec.hs
lib/test/Test/Pos/Diffusion/BlockSpec.hs
pkgs/default.nix
wallet-new/src/Cardano/Wallet/Kernel/Mode.hs
wallet/src/Pos/Wallet/Web/Server/Runner.hs

Implement support for block streaming.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-268
This feature needs to be tested and benchmarked using a client connected to relays with different networking conditions. Tests should be performed with a wiped database and with a partially synced database.

[CDEC-268] Karknu/block streaming2 p

---

binary/test/Test/Pos/Binary/Helpers.hs
crypto/Pos/Crypto/HD.hs
crypto/Pos/Crypto/SecretSharing.hs
crypto/Pos/Crypto/Signing/Signing.hs
crypto/Pos/Crypto/Signing/Types/Signing.hs
crypto/test/Test/Pos/Crypto/Arbitrary/Unsafe.hs
pkgs/default.nix
stack.yaml

The `stack.yaml` file had these settings for most but not all packages. This fxes that and fixing any warnings that arose.

Use -Werror and -fwarn-redundant-constraints on all packages

---

block/bench/cardano-sl-block-bench.cabal
lib/configuration.yaml
pkgs/default.nix

bump versions in preparation of release 1.3.0

---

binary/cardano-sl-binary.cabal
binary/src/Pos/Binary/SafeCopy.hs
crypto/Pos/Crypto/Limits.hs
crypto/Pos/Crypto/SafeCopy.hs
crypto/cardano-sl-crypto.cabal
crypto/test/Test/Pos/Crypto/CborSpec.hs
crypto/test/Test/Pos/Crypto/CryptoSpec2.hs
lib/cardano-sl.cabal
lib/src/Pos/Communication/Limits.hs
lib/src/Pos/SafeCopy.hs
lib/test/Test/Pos/Cbor/CborSpec.hs
lib/test/Test/Pos/CryptoSpec.hs
pkgs/default.nix

Doing this makes code coverage analysis more accurate. This is part 1.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-373

Part 1 of moving crypto tests from lib package to crypto package.

---

wallet-new/cardano-sl-wallet-new.cabal
wallet-new/server/Main.hs
wallet-new/src/Cardano/Wallet/Kernel.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/AcidState.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/InDb.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Update.hs
wallet-new/src/Cardano/Wallet/Kernel/Submission.hs
wallet-new/src/Cardano/Wallet/Kernel/Submission/Worker.hs
wallet-new/src/Cardano/Wallet/Server/Plugins.hs
wallet-new/src/Cardano/Wallet/WalletLayer.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Types.hs
wallet-new/test/unit/Test/Spec/Kernel.hs
wallet-new/test/unit/Test/Spec/Submission.hs

This PR capitalises on CBR-245 by _actually_ threading the submission layer as part of the new wallet.
It also adds a new acid-state update called `evictPending`, which is called whenever we need to evict
transactions from the wallet's pending set.
https://iohk.myjetbrains.com/youtrack/issue/CBR-285
- [~] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [~] If my code deals with exceptions, it follows the …

[CBR-285] Wire submission layer to the wallet

---

wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs

This PR fixes the broken `develop` branch

Remove errant import

---

wallet-new/integration/WalletSpecs.hs
wallet-new/src/Cardano/Wallet/API/V1/Errors.hs
wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers/Wallets.hs
wallet-new/src/Cardano/Wallet/API/V1/Types.hs
wallet/src/Pos/Wallet/Web/Methods/Restore.hs

This PR adds the wallet ID to the `WalletAlreadyExists` error type.
https://iohk.myjetbrains.com/youtrack/issue/CBR-254#tab=Comments
- [] 🐞 Bug fix (non-breaking change which fixes an issue)
- [] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [] 🔨 New or improved tests for existing code
- [] ⛑ git-flow chore (backport, hotfix, etc)

[CBR-254] Implement wallet ID in error

---

auxx/src/Lang/Argument.hs
client/src/Pos/Client/Txp/Util.hs
core/src/Pos/Core/Genesis/NonAvvmBalances.hs
core/src/Pos/Core/Genesis/VssCertificatesMap.hs
core/src/Pos/Core/Genesis/WStakeholders.hs
crypto/Pos/Crypto/Signing/Types/Safe.hs
infra/Pos/Infra/Slotting/Types.hs
pkgs/default.nix
ssc/Pos/Ssc/Toss/Types.hs
stack.yaml
update/src/Pos/Update/Poll/Modifier.hs
util/Pos/Util/Modifier.hs
util/Pos/Util/Util.hs
wallet-new/src/Cardano/Wallet/API/V1/Types.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/BlockMeta.hs
wallet-new/test/unit/Test/Spec/Submission.hs

This should give us a forward compat path
for ghc 8.4+

Semigroup-Monoid-Proposal compat

---

wallet/src/Pos/Util/Mnemonic.hs
wallet/test/Test/Pos/Util/MnemonicSpec.hs

Adding along the way a few golden tests that would have identified the issue :|
\-

Fix genEntropy function from Pos.Util.Mnemonic

---

.editorconfig
.hindent.yaml

Based on feedback in #haskell-best-practices we should keep the col width at 80 to support people working on smaller monitors.

[CDEC-383] Revert to 80 column width

---

block/src/Pos/Block/Network/Retrieval.hs
infra/src/Pos/Infra/Diffusion/Types.hs
lib/bench/Bench/Pos/Diffusion/BlockDownload.hs
lib/src/Pos/Diffusion/Full.hs
lib/src/Pos/Diffusion/Full/Block.hs
lib/test/Test/Pos/Diffusion/BlockSpec.hs

Hide the stream write queue inside streamBlocks.
Move StreamEntry inside Block.hs.
Better types for streamBlocks callback function.

[CDEC-268] Simplify the type for streamBlocks callback function

---

wallet-new/src/Cardano/Wallet/API/V1/Types.hs

This PR refines the type of exceptions that the new wallet API code throws.
https://iohk.myjetbrains.com/youtrack/issue/CBR-312
- [] 🐞 Bug fix (non-breaking change which fixes an issue)
- [] 🛠 New feature (non-breaking change which adds functionality)
- [] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [] ⛑ git-flow chore (backport, hotfix, etc)

[CBR-312] Refined exceptions

---

client/src/Pos/Client/Txp/Util.hs
core/src/Pos/Core/Txp/TxWitness.hs
txp/src/Pos/Aeson/Txp.hs
txp/src/Pos/Txp/Toil/Utxo/Functions.hs
txp/test/Test/Pos/Txp/Arbitrary.hs
txp/test/Test/Pos/Txp/Toil/UtxoSpec.hs

Remove field accessors for `TxInWitness`
https://iohk.myjetbrains.com/youtrack/issue/CDEC-302

Remove field accessors for `TxInWitness`

---

core/src/Pos/Core/Txp/Tx.hs
txp/src/Pos/Aeson/Txp.hs
txp/src/Pos/Txp/Topsort.hs
wallet-new/test/unit/UTxO/Interpreter.hs

Remove field accessors from `TxIn`
https://iohk.myjetbrains.com/youtrack/issue/CDEC-303

Remove field accessors from `TxIn`

---

core/src/Pos/Merkle.hs

Remove field accessors from `MerkleNode a`
https://iohk.myjetbrains.com/youtrack/issue/CDEC-304

Remove field accessors from `MerkleNode a`

---

docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md

This fix some references to cardano-sl-node-static and cardano-sl-tools in build-cardano-sl-and-daedalus-from-source-code.md.
None.

Fix references to non-existant Nix attributes in build instructions

---

docs/style-guide.md

As per discussion [on slack](https://input-output-rnd.slack.com/archives/C48HA39RS/p1530266877000129) about clear rules for strictness annotations,
add clarification on defaults and a suggestion to document deviations
from the norm.

Update style guide regarding strictness

---

wallet-new/test/unit/Test/Spec/CoinSelection.hs
wallet-new/test/unit/Test/Spec/CoinSelection/Generators.hs

This commit attempts to fix the flaky generators for coin selection in a
way that the Utxo & the payees are generated with a bit more context: in
particular, we generate payees where the biggest output is as big as the
smallest available entry in the Utxo, and the number of outputs is
always < (length utxo / 2), to be sure that in tests we can always
perform the coin selection correctly.
CI was failing on some coin selection tests.
https://iohk.myjetbrains.com/youtrack/issue/CO-329
- [~] ⛑ git-flow chore …

[CO-329] Fix flaky coin selection generators

---

scripts/launch/demo.sh

Adds a flag for Daedalus team to disable client cert auth with demo.sh.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-879

[DEVOPS-879] demo flag client auth disable

---

wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/Kernel.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/AcidState.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Read.hs
wallet-new/test/unit/Wallet/Inductive/Cardano.hs

This PR exposes only a single getter for the Kernel, which is the
'getWalletSnapshot' API, explaining library authors and users what they
are expected to do and how to interact with the wallet.
We don't want to have developers pick up bad old habits when it comes to the new data layer. We want to enforce a way to access the data layer internal state in a consistent manner, and in line with what we have done in the past.
https://iohk.myjetbrains.com/youtrack/issue/CBR-315

[CBR-315] Have only pure getters for the Kernel's DB

---

CHANGELOG.md

Add change log for Release 1.3.0

---

core/cardano-sl-core.cabal
core/src/Pos/Core/Slotting/EpochOrSlot.hs
core/src/Pos/Core/Slotting/LocalSlotIndex.hs
core/src/Pos/Core/Slotting/SlotId.hs
core/test/Test/Pos/Core/EnumEmpTest.hs
core/test/test.hs
generator/test/Test/Pos/Block/Logic/CreationSpec.hs
lrc/src/Pos/Lrc/DB/Leaders.hs
pkgs/default.nix
ssc/src/Pos/Ssc/Base.hs

The types `EpochOrSlot`, `LocalSlotIndex` and `SlotId` have a `HasProtocoConstants` constraint as well as `Enum` instances which depend on the `HasProtocoConstants` constraint. Since we want to remove `HasProtocoConstants` the first step is to provide functions that will act like the `Enum` methods, but take an extra parameter for the part they require from `ProtocolConstants`.
Also add property tests that show the equivalence of the two.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-415

CDEC-415 Preprare for removal of `HasProtocolConstants` constraint

---

block/cardano-sl-block.cabal
block/src/Pos/Block/Error.hs
pkgs/default.nix
update/cardano-sl-update.cabal
update/src/Pos/Update/Poll/Modifier.hs
util/Pos/Util/Modifier.hs

Added NFDData instances to support benchmarking of `verifyBlocksPrefix`:
* `VerifyBlocksExceptions`
* `PollModifier`
* `MapModifier`
https://iohk.myjetbrains.com/youtrack/issue/CBR-96

[CBR-96] derive NFData instances

---

block/src/Pos/Block/Error.hs
block/src/Pos/Block/Logic/Integrity.hs
update/src/Pos/Update/Poll/Modifier.hs

This PR just adds a bunch of type signatures that where useful to grasp the code.

[CBR-96] Added some type signatures

---

default.nix
docker.nix
lib.nix
scripts/haskell/update-cabal-versions.sh
scripts/test/stylish.nix
scripts/test/wallet/integration/build-test.nix
scripts/test/wallet/integration/default.nix

This fixes hydra locale warnings.
By adding glibcLocales to buildInputs of any hydra jobs needing it, the setup hook adding LOCALE_ARCHIVE no longer throws warnings. Also, adding the manual export line to the docker init script so we don't break exchanges.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-942

[DEVOPS-942] Fixing locale warnings and renaming walletIntegration

---

infra/src/Pos/Infra/Communication/Types/Protocol.hs
infra/src/Pos/Infra/Diffusion/Subscription/Common.hs
lib/src/Pos/Binary/Communication.hs

[https://iohk.myjetbrains.com/youtrack/issue/CDEC-424](https://iohk.myjetbrains.com/youtrack/issue/CDEC-424)

[CDEC-424] Reunite orphan Bi instances in the lib (cardano-sl) package

---

scripts/haskell/stylish.sh

[DEVOPS-936] re-add stylish.sh for non-nix users

---

pkgs/default.nix
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/API/V1/Handlers.hs
wallet-new/src/Cardano/Wallet/API/V1/Handlers/Addresses.hs
wallet-new/src/Cardano/Wallet/Kernel.hs
wallet-new/src/Cardano/Wallet/Kernel/Actions.hs
wallet-new/src/Cardano/Wallet/Kernel/Addresses.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Create.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Derivation.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Util/IxSet.hs
wallet-new/src/Cardano/Wallet/Kernel/Keystore.hs
wallet-new/src/Cardano/Wallet/Kernel/Types.hs
wallet-new/src/Cardano/Wallet/WalletLayer.hs
wallet-new/src/Cardano/Wallet/WalletLayer/ExecutionTimeLimit.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Legacy.hs
wallet-new/src/Cardano/Wallet/WalletLayer/QuickCheck.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Types.hs
wallet-new/test/unit/Test/Spec/CreateAddress.hs
wallet-new/test/unit/Test/Spec/Kernel.hs
wallet-new/test/unit/Test/Spec/Keystore.hs
wallet-new/test/unit/Test/Spec/WalletWorker.hs
wallet-new/test/unit/WalletUnitTest.hs

This PR delivers the `newAddress` V1 endpoint, implemented using the new data layer. It does so by providing specific `WalletLayer` and `Kernel` functions the relevant handler piggybacks upon.
https://iohk.myjetbrains.com/youtrack/issue/CBR-319

[CBR-319] new address function on the new data layer

---

wallet-new/src/Cardano/Wallet/Kernel.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/AcidState.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/BlockMeta.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/InDb.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Resolved.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Update.hs
wallet-new/src/Cardano/Wallet/Kernel/PrefilterTx.hs
wallet-new/src/Cardano/Wallet/Kernel/Types.hs

Implement BlockMeta as per the wallet spec
https://iohk.myjetbrains.com/youtrack/issue/CBR-304

[CBR-304] Track block metadata during ApplyBlock

---

scripts/haskell/git-pre-commit-hook

* Abort the commit if stylish-haskell returns non-zero.
* Improve documentation at the top of the file.

Tweaks to the pre-commit hook

---

core/src/Pos/Core/Block/Union/Instances.hs

Remove field accessors from the `ComponentBlock` data type.
[https://iohk.myjetbrains.com/youtrack/issue/CDEC-296](https://iohk.myjetbrains.com/youtrack/issue/CDEC-296)

[CDEC-296] Remove field accessors from ComponentBlock

---

lib/configuration.yaml

[DEVOPS-906] Bump staging applicationVersion

---

wallet-new/docs/spec.tex

Literally just changing the date.

Set date of publishing new version

---

auxx/src/AuxxOptions.hs
infra/src/Pos/Infra/Network/Yaml.hs
networking/src/Network/Broadcast/OutboundQueue.hs
networking/src/Network/Broadcast/OutboundQueue/Demo.hs
ssc/src/Pos/Security/Params.hs
wallet-new/test/unit/Test/Spec/Translation.hs
wallet-new/test/unit/Wallet/Inductive/Cardano.hs

Removal of partial record accessors for `AttackTarget`, `AuxxAction`, `Disagreement h a`, `Enqueue` and `EquivalenceViolation` data types.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-398

[CDEC-398] Remove partial field accessors from `AttackTarget`, `AuxxAction`, `Disagreement h a`, `Enqueue` and `EquivalenceViolation` data types.

---

infra/src/Pos/Infra/Recovery/Info.hs
lib/src/Pos/Recovery/Instance.hs

Remove field accessors from the `SyncStatus` data type.
[https://iohk.myjetbrains.com/youtrack/issue/CDEC-440](https://iohk.myjetbrains.com/youtrack/issue/CDEC-440)

[CDEC-440] Remove field accessors from SyncStatus

---

pkgs/default.nix
stack.yaml
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/API/V1/Swagger/Example.hs
wallet/cardano-sl-wallet.cabal
wallet/test/LICENSE
wallet/test/Setup.hs
wallet/test/Test/Pos/Wallet/Arbitrary/Web/ClientTypes.hs
wallet/test/Test/Pos/Wallet/Web/Tracking/SyncSpec.hs
wallet/test/cardano-sl-wallet-test.cabal

As it stands, the `Arbitrary` instances for data types in `wallet` all exist in `wallet` when they should actually be exposed from a separate package, `wallet-test`.
[https://iohk.myjetbrains.com/youtrack/issue/CDEC-437](https://iohk.myjetbrains.com/youtrack/issue/CDEC-437)

[CDEC-437] Move Arbitrary instances from wallet to wallet-test

---

pkgs/default.nix
scripts/launch/demo-with-new-wallet-api.sh
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/API/V1/Handlers.hs
wallet-new/src/Cardano/Wallet/API/V1/Handlers/Addresses.hs
wallet-new/src/Cardano/Wallet/API/V1/Handlers/Wallets.hs
wallet-new/src/Cardano/Wallet/Kernel.hs
wallet-new/src/Cardano/Wallet/Kernel/BIP39.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
wallet-new/src/Cardano/Wallet/Kernel/Wallets.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Legacy.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Types.hs
wallet-new/test/unit/Test/Spec/CreateWallet.hs
wallet-new/test/unit/Wallet/Inductive/Cardano.hs
wallet-new/test/unit/WalletUnitTest.hs

This PR allows the creation of a new wallet via the V1 API. It does so by exposing the relevant functions both in the WalletLayer and in the Kernel.
https://iohk.myjetbrains.com/youtrack/issue/CBR-340

[CBR-340] 'createWallet' implemented with the new data layer

---

core/src/Pos/Core/JsonLog/LogEvents.hs
core/test/Test/Pos/Core/Gen.hs
core/test/Test/Pos/Core/Json.hs
core/test/golden/InvReqDataFlowLog_InvReqAccepted
core/test/golden/InvReqDataFlowLog_InvReqException
core/test/golden/InvReqDataFlowLog_InvReqRejected

Implement ToJSON/FromJSON instances, golden tests and round trip tests for `InvReqDataFlowLog` data type.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-462

[CDEC-462] Implement ToJSON/FromJSON instances, golden tests and round trip tests for `InvReqDataFlowLog` data type

---

scripts/generate-mnemonic.hs

I originally wrote this for my own use, and thought it might help others. This PR adds a script to generate mnemonics.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-959

[DEVOPS-959] mnemonic generator script

---

update/src/Pos/Update/Logic/Local.hs
update/src/Pos/Update/Poll/Failure.hs
update/src/Pos/Update/Poll/Logic/Apply.hs
update/src/Pos/Update/Poll/Logic/Base.hs
update/src/Pos/Update/Poll/Logic/Version.hs

Remove partial field accessors from `PollVerFailure` datatype.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-466

[CDEC-466] Remove partial field accessors from `PollVerFailure` datatype

---

docs/new-dependency-policy.md

Add a policy for adding new package dependencies to Cardano SL. Tried to keep it short and to the point.
Please let me know if i have forgotten anything or anything is unclear.
I do not intend to merge this until the middle of next week, to give people time to review it and comment.

Add new package dependency policy

---

update/test/cardano-sl-update-test.cabal

This PR simply removes `-fno-warn-orphans` from `ghc-options` in `cardano-sl-update-test.cabal`. All other occurrences of `-fno-warn-orphans` in this package are all associated with `Arbitrary` instances (which we've decided to leave as orphans).
[https://iohk.myjetbrains.com/youtrack/issue/CDEC-455](https://iohk.myjetbrains.com/youtrack/issue/CDEC-455)

[CDEC-455] Remove usages of -fno-warn-orphans from update-test

---

appveyor.yml
docker.nix
scripts/launch/connect-to-cluster/default.nix

This fixes exchanges/devops ability to build connectScripts wallets on OSX. This has no QA impact.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-972

[DEVOPS-972] fix connectScripts evaluation on OSX

---

wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/API/V1/Internal.hs
wallet-new/src/Cardano/Wallet/API/V1/Internal/Update.hs
wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers/Internal/Update.hs
wallet-new/src/Cardano/Wallet/API/V1/Types.hs
wallet/Makefile

This PR exposes the internal update API using the legacy handlers.
https://iohk.myjetbrains.com/youtrack/issue/CO-335

[CO-335] Implement legacy functionality

---

fetch-nixpkgs.nix
hackage.json
haskell.json
lib.nix
nixpkgs-src.json
stackage.json

[DEVOPS-974] clean up the fetch functions for most of the source

---

db/src/Pos/DB/Block.hs
pkgs/default.nix
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/server/Main.hs
wallet-new/src/Cardano/Wallet/Kernel.hs
wallet-new/src/Cardano/Wallet/Kernel/Internal.hs
wallet-new/src/Cardano/Wallet/Kernel/MonadDBReadAdaptor.hs
wallet-new/src/Cardano/Wallet/WalletLayer.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
wallet-new/test/unit/Test/Spec/CreateAddress.hs
wallet-new/test/unit/Test/Spec/CreateWallet.hs
wallet-new/test/unit/Test/Spec/Kernel.hs
wallet-new/test/unit/Test/Spec/NewPayment.hs

This provides convenient access to the `MonadDBRead` within the wallet kernel, without polluting it with additional constraints. The tests are unaffected ("rocks DB not available"), and the adaptor is properly initialized when the node starts up, as can be verified by looking at the node logs on start up (both the underlying node and the wallet report the same tip). 
https://iohk.myjetbrains.com/youtrack/issue/CBR-317

Make MonadDBRead available in the wallet kernel

---

appveyor.yml
wallet/src/Pos/Util/Mnemonic.hs
wallet/src/Pos/Wallet/Aeson/ClientTypes.hs
wallet/test/Test/Pos/Util/MnemonicSpec.hs

[CO-342](https://iohk.myjetbrains.com/youtrack/issue/CO-342#tab=Comments)
- [~] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.

[CO-342] Backward-compatiblity parser for V0 CBackupPhrase

---

log-configs/daedalus.yaml

This commit amends the daedalus.yaml logger config file by tuning down
the verbosity of the 'syncWalletWorker', which is the component
responsible for logging wallet restorations.
It spits out lots of DEBUG output and this was saturating rapidly the
end user's filesystem.
This commit reduces the verbosity to Error+.

[RCD-32] reduce logging verbosity

---

wallet-new/cardano-sl-wallet-new.cabal
wallet-new/integration/AccountSpecs.hs
wallet-new/integration/AddressSpecs.hs
wallet-new/integration/CLI.hs
wallet-new/integration/Main.hs
wallet-new/integration/RandomStateWalk.hs
wallet-new/integration/SetupTestEnv.hs
wallet-new/integration/TransactionSpecs.hs
wallet-new/integration/Types.hs
wallet-new/integration/Util.hs
wallet-new/integration/WalletSpecs.hs

The current tests set up a test-net and run all requests against a single node.
It is also desirable to test, e.g.,  a transaction from a wallet on node A to a wallet on node B.
This PR works in that direction and add one new (pending) test case.
* make the test-cases slightly easier to understand for me
* remove the use of unsafePerformIO from test cases
* break up a big 300+ lines top-level declaration into smaller parts
* add type signatures to the parts that have become new top-level declarations
* don't change any details only re-order existing snippets
* rename the module Functions.hs to RandomStateWalk.hs
* also remove use of MVars from tests
* cleanup Main-module

[CHW] Refactor TransactionSpecs.hs

---

default.nix
docs/how-to/demo-cluster.md
scripts/README.md
scripts/launch/connect-to-cluster/default.nix
scripts/launch/demo-cluster/default.nix
scripts/launch/demo-nix.sh

Adds an attribute `demoClusterDaedalusDev` to `default.nix` that frontend testers can use to launch a demo cluster with daedalus.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-978

[DEVOPS-978] Add option to demo cluster to disable client auth

---

scripts/launch/connect-to-cluster/mainnet-staging.sh
scripts/launch/demo.sh

Fixed `./scripts/launch/demo.sh` (not passsing ${nix} to one command) and added --nix parameter to `scripts/launch/connect-to-cluster/mainnet-staging.sh`
This fixes and extends: #3191 
No issue.

Added --nix parameter

---

generator/cardano-sl-generator.cabal
generator/src/Pos/Generator/Block.hs
generator/src/Pos/Generator/Block/Mode.hs
generator/src/Pos/Generator/Block/Orphans.hs
generator/src/Pos/Generator/Block/Payload.hs

In this PR, I've simply removed usages of `-fno-warn-orphans` from `cardano-sl-generator.cabal` as well as created a `Pos.Generator.Block.Orphans` module which only contains one orphan instance that came from `Pos.Generator.Block.Mode`. I did this simply because I didn't think that it was fitting to use `{-# OPTIONS_GHC -fno-warn-orphans #-}` on a module with multiple instances defined within it but only one orphan. If anyone thinks that it was better the way it was, please feel free to let me know.
[https://iohk.myjetbrains.com/youtrack/issue/CDEC-481](https://iohk.myjetbrains.com/youtrack/issue/CDEC-481)

[CDEC-481] Remove usages of -fno-warn-orphans from generator

---

docs/delegation_design_spec.md

There are several typographical errors in the Delegation Design Specification that should be fixed. This PR addresses them.
https://iohk.myjetbrains.com/youtrack/issue/CBR-343
This is a documentation update, hence no tests.
This PR makes a few small typographical error fixes. Proof-reading them will do.

[CBR-343] Fixes a few typographical errors in the Delegation design specification

---

docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md

Fix a documentation formatting bug: https://github.com/input-output-hk/cardano-sl/commit/c631f6252c3d48456cdbdec468b16aff2d40ee8e#r29875679
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-976

[DEVOPS-976] Fix code indentation in Markdown doc

---

lib/configuration.yaml

Bumps mainnet to version 9
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-994

[DEVOPS-994] bump mainnet to version 9

---

infra/cardano-sl-infra.cabal
infra/src/Pos/Infra/Network/CLI.hs
infra/src/Pos/Infra/Network/DnsDomains.hs
infra/src/Pos/Infra/Network/Types.hs
infra/src/Pos/Infra/Network/Yaml.hs
infra/test/Test/Pos/Infra/Gen.hs
infra/test/Test/Pos/Infra/Json.hs
infra/test/cardano-sl-infra-test.cabal
infra/test/golden/NodeMetadata
infra/test/golden/TopologyBehindNAT
infra/test/golden/TopologyP2P
infra/test/golden/TopologyStatic
infra/test/golden/TopologyTraditional
infra/test/test.hs
networking/cardano-sl-networking.cabal
networking/src/Network/Broadcast/OutboundQueue.hs
networking/src/Network/Broadcast/OutboundQueue/Types.hs
pkgs/default.nix

Implement ToJSON instance, golden tests and round trip tests for `Topology` data type.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-474

[CDEC-474]  Remove record accessors, implement ToJSON instance, golden tests and round trip tests for `Topology` data type

---

wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Update.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Read.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Util/AcidState.hs
wallet-new/src/Cardano/Wallet/Kernel/Wallets.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs

This PR addresses some minor comments arose from my previous PR targeting CBR-350.
https://iohk.myjetbrains.com/youtrack/issue/CBR-362

[CBR-362] Address post CBR-350 minor comments

---

docs/PULL_REQUEST_TEMPLATE.md

Taking this from the [Daedalus PR checklist](https://github.com/input-output-hk/daedalus/blame/79a2044038fef62b020a2587ae2f65738020b9d1/.github/pull_request_template.md#L21).

Add PR checkbox for updating the CHANGELOG

---

pkgs/default.nix
scripts/launch/connect-to-cluster/default.nix
stack.yaml
tools/cardano-sl-tools.cabal
tools/src/gencerts/Configuration.hs

Fix parsing of tls config to identify IP addresses and use `AltNameIP` if an IP is detected.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-992

[DEVOPS-992] Fix x509 generator SANs to work with IP addresses

---

scripts/test/wallet/integration/build-test.nix

Adds log capturing when integration tests fail.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-980

[DEVOPS-980] Create build artifact with logs when test fails

---

wallet-new/src/Cardano/Wallet/Kernel.hs
wallet-new/src/Cardano/Wallet/Kernel/Accounts.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/AcidState.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Pending.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Read.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Update.hs
wallet-new/src/Cardano/Wallet/Kernel/Util/Core.hs
wallet-new/test/unit/Test/Spec/Submission.hs

Foreign transactions are transactions from /other/ wallets (such as AVVM
accounts). They don't interact with the wallet state much, except that
* Any outputs to thhe current wallet are included in our `change` and therefore
in the wallets `totalBalance`
* They get submitted by the submission layer.
https://iohk.myjetbrains.com/youtrack/issue/CBR-349

[CBR-349] Add support for foreign transactions

---

pkgs/default.nix
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/integration/Main.hs
wallet-new/src/Cardano/Wallet/API/V1/Errors.hs
wallet-new/src/Cardano/Wallet/Client.hs
wallet-new/src/Cardano/Wallet/Server/Plugins.hs

This PR implements the `wai-middleware-throttle` in the new wallet code. Configuration via the config file will be implemented in a follow-up PR.
https://iohk.myjetbrains.com/youtrack/issue/CO-349

[CO-349] Implement throttling middleware

---

appveyor.yml

(cherry picked from commit 47bb9ad76a3b475a55bb23cd5f58aa7894245fd5)
Fixes failed appveyor builds
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1003

[DEVOPS-1003] Bump appveyor ssl version to 1.0.2q

---

wallet-new/src/Cardano/Wallet/Kernel.hs
wallet-new/src/Cardano/Wallet/Kernel/Accounts.hs
wallet-new/src/Cardano/Wallet/Kernel/ChainState.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/AcidState.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Resolved.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Update.hs
wallet-new/src/Cardano/Wallet/Kernel/PrefilterTx.hs
wallet-new/src/Cardano/Wallet/Kernel/Types.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
wallet-new/test/unit/UTxO/Interpreter.hs
wallet-new/test/unit/Wallet/Inductive/Cardano.hs

This removes the 'ChainBrief' from 'Checkpoint' and replaces it with a simple 'SlotId'. This will give us enough information for recovery, but makes everything else much easier. In particular, there is no need to come up with some kind of 'ChainBrief' value for the initial checkpoint of an account. It does mean that we cannot check the wallet's own DB for things like the current software version or the max tx size, but we can simply ask the underlying node for these values. This is the more pragmatic approach for now, we may revisit this later.
This completely removes the need for the dummy `ChainBrief` value.
@uroboros Before you approve this PR, could you please rebase your own work on this branch and check that the tests now pass, with the right slot IDs? …

[CBR-243] Simplify `Checkpoint`

---

auxx/src/Mode.hs
client/src/Pos/Client/KeyStorage.hs
client/src/Pos/Client/Txp/Network.hs
client/src/Pos/Client/Txp/Util.hs
wallet-new/src/Cardano/Wallet/API/V1/Errors.hs
wallet/src/Pos/Wallet/Web/Mode.hs
wallet/test/Test/Pos/Wallet/Web/Mode.hs

This is second PR for CHW (Cardano Hardware Wallets).
It allows to operate with root public keys (using to identify external wallets) and specifies errors we'll use during work with external wallets (please see next PRs with `[CHW]`).

[CHW] Work with root public key and errors for external wallets.

---

wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/Kernel.hs
wallet-new/src/Cardano/Wallet/Kernel/BListener.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Read.hs
wallet-new/src/Cardano/Wallet/Kernel/Keystore.hs
wallet-new/src/Cardano/Wallet/Kernel/Pending.hs
wallet-new/src/Cardano/Wallet/Kernel/Read.hs
wallet-new/src/Cardano/Wallet/Kernel/Transactions.hs
wallet-new/src/Cardano/Wallet/Kernel/Wallets.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Accounts.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Addresses.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Transactions.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
wallet-new/test/unit/Test/Spec/Addresses.hs
wallet-new/test/unit/Test/Spec/GetTransactions.hs
wallet-new/test/unit/Wallet/Inductive/Cardano.hs

This also does some minor refactoring: most kernel functionality was defined in
submodules, but `applyBlock`, `rollback`, and `newPending` and co where not.
I've moved them to their own submodule now, along with a new .Read module for
read-only access.
This also cleans up some import lists.
https://iohk.myjetbrains.com/youtrack/issue/CBR-341

[CBR-341] Don't iterate over the keystore

---

wallet-new/src/Cardano/Wallet/Kernel/ChainState.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Read.hs
wallet-new/src/Cardano/Wallet/Kernel/NodeStateAdaptor.hs
wallet-new/src/Cardano/Wallet/Kernel/Transactions.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Transactions.hs
wallet-new/test/unit/Test/Spec/Fixture.hs
wallet-new/test/unit/Test/Spec/Kernel.hs

This adds functionality to the node state adaptor to query the current security parameter, slot ID of the tip header, and maximum transaction size. It also makes it partly mockable so that we can still query these parameters also in tests.
https://iohk.myjetbrains.com/youtrack/issue/CBR-376
https://iohk.myjetbrains.com/youtrack/issue/CBR-353

[CBR-376, CBR-353] Make chain parameters available

---

default.nix

[DEVOPS-1004] improve the override structure in cardano

---

db/cardano-sl-db.cabal
db/src/Pos/DB/Epoch/Index.hs
db/test/Test/Pos/DB/Epoch/Index.hs
db/test/test.hs
pkgs/default.nix

This is code to implement the index files for extracting block offsets out of the epoch files. Code for generating and querying epoch files will come in subsequent PRs.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-493

CDEC-492: Add code to handle epoch index files

---

.gitignore
docs/on-the-wire/Makefile
docs/on-the-wire/README.md
docs/on-the-wire/binary.tex
docs/on-the-wire/current-spec.cddl
docs/on-the-wire/latexmkrc
docs/on-the-wire/shell.nix

This document adds a specification for the Cardano on-the-wire format, as well as a bridge between the types in use in Cardano and the abstract types as denoted in "Rule-based specification of the blockchain logic".
As currently written, it:
- Provides a concrete definition of all the types/data structures necessary to work with the Cardano blockchain.
- Gives a CDDL spec for the current encoding of those types, which can be used to validate or potentially generate new bindings.
The plan is to extend this with:
- Adding invariants which must be satisfied by the types.
- Adding other constraints on the serialisation, as derived from e.g. the formal spec or from security concerns.
- Update the binary format to satisfy the various requirements.
However, it's at a stage where the current work …

[CDEC-349] Specification for Cardano on-the-wire format

---

core/src/Pos/Core/Util/LogSafe.hs
lib/cardano-sl.cabal
lib/src/Pos/Util/Servant.hs
networking/src/Ntp/Client.hs
pkgs/default.nix
scripts/build/cardano-sl.sh
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/integration/QuickCheckSpecs.hs
wallet-new/src/Cardano/Wallet/API/V1/Info.hs
wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers/Info.hs
wallet-new/src/Cardano/Wallet/API/V1/Swagger.hs
wallet-new/src/Cardano/Wallet/API/V1/Types.hs
wallet-new/src/Cardano/Wallet/Client.hs
wallet-new/src/Cardano/Wallet/Client/Http.hs
wallet-new/test/MarshallingSpec.hs
wallet/src/Pos/Wallet/Web/Methods/Misc.hs

In some cases, Daedalus needs to force a new NTP check as a previous result gets cached. A typical use-case is after asking a user to fix its system clock.
TODO: tests
https://iohk.myjetbrains.com/youtrack/issue/CO-344
TODO

[CO-344] Force ntp check wallet endpoint

---

wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/FromGeneric.hs
wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/Generic.hs
wallet-new/src/Cardano/Wallet/Kernel/Transactions.hs
wallet-new/test/unit/Test/Spec/NewPayment.hs

newTranaction was using `throwM` to throw some exceptions, rather than
returning them propertly. This fixes that, and cleans up the code using
runExceptT.
Marking this as part of CBR-382 as it is preparatory work.
https://iohk.myjetbrains.com/youtrack/issue/CBR-382

[CBR-382] Don't throw exceptions in newTransaction

---

wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Util/AcidState.hs

The pure queries had quite a bit of duplication with the updates as they could not take advantage of the zoom operators. This generalizes the zoom operators so that they can also be used in queries (they don't yet do that, however. that will be the follow up PR).
https://iohk.myjetbrains.com/youtrack/issue/CBR-382

[CBR-382] Generalize zoom ops to work on queries

---

infra/src/Pos/Infra/Recovery/Info.hs
lib/src/Pos/Logic/Types.hs
networking/src/Ntp/Client.hs
wallet-new/src/Cardano/Wallet/API/Indices.hs
wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers/Transactions.hs
wallet-new/src/Cardano/Wallet/API/V1/Migration/Types.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/TxMeta/Types.hs
wallet-new/src/Cardano/Wallet/Kernel/PrefilterTx.hs
wallet-new/src/Cardano/Wallet/Kernel/Wallets.hs
wallet-new/src/Cardano/Wallet/WalletLayer.hs

This commit turns broken haddock annotations into normal comments.
This commit does not change actual code, only haddock/comments.

fix broken haddock annotations

---

binary/test/Test/Pos/Binary/Helpers.hs
binary/test/test.hs
chain/test/test.hs
core/test/test.hs
crypto/test/test.hs
db/cardano-sl-db.cabal
db/test/test.hs
infra/test/test.hs
pkgs/default.nix
tools/test/Test.hs
util/test/Test/Pos/Util/Tripping.hs
wallet-new/test/Spec.hs

hedgehog uses fancy unicode codepoints to point it's output; this is at odds with non-utf8 charsets and leads to GHC crashing with
<stdout>: commitBuffer: invalid argument (invalid character)
This change sets the stdout/stderr encoding to utf8 prior to running hedgehog tests via the `runTests` function.
The relevant hedgehog issue is hedgehogqa/haskell-hedgehog#110

Set UTF-8 when running hedgehog tests

---

wallet-new/src/Cardano/Wallet/Kernel/NodeStateAdaptor.hs

This adds functionality to the node adaptor to translate from `SlotId` to `Timestamp`. This will be needed when constructing transaction metadata.
https://iohk.myjetbrains.com/youtrack/issue/CBR-387

[CBR-387] Add `getSlotStart` to the node adaptor

---

wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/Kernel/Actions.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Read.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Read.hs
wallet-new/src/Cardano/Wallet/Kernel/Invariants.hs
wallet-new/src/Cardano/Wallet/Kernel/Submission.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
wallet-new/test/unit/Test/Spec/BlockMetaScenarios.hs
wallet-new/test/unit/Test/Spec/Kernel.hs
wallet-new/test/unit/Test/Spec/WalletWorker.hs
wallet-new/test/unit/UTxO/Interpreter.hs
wallet-new/test/unit/Wallet/Abstract.hs
wallet-new/test/unit/Wallet/Inductive/Cardano.hs
wallet-new/test/unit/Wallet/Inductive/ExtWalletEvent.hs
wallet-new/test/unit/Wallet/Inductive/Generator.hs
wallet-new/test/unit/Wallet/Inductive/History.hs
wallet-new/test/unit/Wallet/Inductive/Validation.hs

This tests that the fix for CBR-369 in https://github.com/input-output-hk/cardano-sl/pull/3418  is indeed correct. 
This also extends the tests so where we use `equivalentT` to verify the real implementation against the model, we do this twice: once without the wallet worker (testing rollback directly), and  once with the wallet worker (aggregating rollback/applyBlock events to get switchToFork events). Made a few other changes that were required as a result, including some fixes to the generator. Details in the commit messages.
https://iohk.myjetbrains.com/youtrack/issue/CBR-383

[CBR-383] Test that submission layer is informed after applyBlock/rollback

---

wallet-new/src/Cardano/Wallet/Kernel/BListener.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/AcidState.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Update.hs
wallet-new/src/Cardano/Wallet/Kernel/NodeStateAdaptor.hs

When we apply a block, we should only keep up to k checkpoints, as per the spec.
https://iohk.myjetbrains.com/youtrack/issue/CBR-339

[CBR-339] Only keep k checkpoints

---

wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs

Make sure that comparing addresses compares the root ID only as the last step. This is important when we have a ton of different address IDs that we want to sort, we don't want to be comparing the root ID over and over and over again.
https://iohk.myjetbrains.com/youtrack/issue/CBR-325

[CBR-325] Compare parent IDs last

---

wallet-new/src/Cardano/Wallet/API/Indices.hs
wallet-new/src/Cardano/Wallet/API/Request/Filter.hs
wallet-new/src/Cardano/Wallet/API/Request/Sort.hs
wallet-new/src/Cardano/Wallet/API/Response.hs
wallet-new/src/Cardano/Wallet/API/Response/Filter/IxSet.hs
wallet-new/src/Cardano/Wallet/API/Response/Filter/Legacy.hs
wallet-new/src/Cardano/Wallet/API/Response/Sort/IxSet.hs
wallet-new/src/Cardano/Wallet/API/V1/Handlers/Accounts.hs
wallet-new/src/Cardano/Wallet/API/V1/Handlers/Wallets.hs
wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers/Accounts.hs
wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers/Addresses.hs
wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers/Transactions.hs
wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers/Wallets.hs
wallet-new/src/Cardano/Wallet/API/V1/Types.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Util/IxSet.hs

@KtorZ , @parsonsmatt , marking you guys for review as this mostly touches the V1 code.
We had _two_ `IxSet` wrappers, one introduced by Alfredo, and one introduced by me. Alfredo and I agreed to migrate the code over to the one I introduced, as it is bit more feature complete. The most important improvement that my `IxSet` wrapper introduces is that it doesn't require `Eq` or `Ord` instances for the elements in the set, but instead introduces a concept of a "primary key", and compares primary keys only, for better performance.
This updates the code base to use the (new) `IxSet` wrapper throughout. It still allows for an `IxSet` of V1 addresses, which we really should not do, but that's a problem for a separate PR (and a separate ticket: CBR-356). I will look at that next. …

[CBR-347] Delete `IxSet'`

---

core/src/Pos/Core/Common/Address.hs
pkgs/default.nix
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/API/V1/Migration/Types.hs
wallet-new/src/Cardano/Wallet/API/V1/Types.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs

This is third PR for CHW (Cardano Hardware Wallet) features.
It provides a new types required for external wallets.

[CHW] API v1 types for external wallets.

---

docs/tls-authentication.md
wallet-new/README.md
wallet-new/src/Cardano/Wallet/API/V1/Swagger.hs

The doc was incomplete in some parts or not up-to-date, leading to confusion for newcomers
\-

Add a few lines in the tls-authentication and wallet's README doc

---

wallet-new/cardano-sl-wallet-new.cabal
wallet-new/server/Main.hs
wallet-new/src/Cardano/Wallet/API/V1/Handlers.hs
wallet-new/src/Cardano/Wallet/API/V1/Handlers/Info.hs
wallet-new/src/Cardano/Wallet/API/V1/Handlers/Settings.hs
wallet-new/src/Cardano/Wallet/API/V1/Handlers/Wallets.hs
wallet-new/src/Cardano/Wallet/Kernel/Diffusion.hs
wallet-new/src/Cardano/Wallet/Kernel/Mode.hs
wallet-new/src/Cardano/Wallet/Kernel/NodeStateAdaptor.hs
wallet-new/src/Cardano/Wallet/Server.hs
wallet-new/src/Cardano/Wallet/WalletLayer.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Info.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Settings.hs
wallet-new/test/Cardano/Wallet/WalletLayer/QuickCheck.hs
wallet-new/test/unit/Test/Spec/Accounts.hs
wallet-new/test/unit/Test/Spec/Addresses.hs
wallet-new/test/unit/Test/Spec/Fixture.hs
wallet-new/test/unit/Test/Spec/GetTransactions.hs
wallet-new/test/unit/Test/Spec/Kernel.hs
wallet-new/test/unit/Test/Spec/Wallets.hs

Add `getNodeInfo` and `getNodeSettings` endpoints.
https://iohk.myjetbrains.com/youtrack/issue/CBR-246

[CBR-246] WIP: Implement getInfo and getNodeSettings

---

core/cardano-sl-core.cabal
core/src/Pos/Core/Common/Address.hs
core/src/Pos/Core/Common/Coeff.hs
core/src/Pos/Core/Common/Coin.hs
core/src/Pos/Core/Common/CoinPortion.hs
core/src/Pos/Core/Common/SharedSeed.hs
core/src/Pos/Core/Common/StakeholderId.hs
core/src/Pos/Core/Common/TxFeePolicy.hs
core/src/Pos/Core/Configuration.hs
core/src/Pos/Core/Genesis.hs
core/src/Pos/Core/Genesis/AvvmBalances.hs
core/src/Pos/Core/Genesis/Data.hs
core/src/Pos/Core/Genesis/NonAvvmBalances.hs
core/src/Pos/Core/Genesis/ProtocolConstants.hs
core/src/Pos/Core/Genesis/VssCertificatesMap.hs
core/src/Pos/Core/Genesis/WStakeholders.hs
core/src/Pos/Core/ProtocolConstants.hs
core/src/Pos/Core/Slotting/EpochIndex.hs
core/src/Pos/Core/Slotting/Timestamp.hs
core/src/Pos/Core/Ssc/VssCertificate.hs
core/src/Pos/Core/Update/BlockVersionData.hs
core/src/Pos/Core/Update/SoftforkRule.hs
lib/src/Test/Pos/Helpers.hs
util/Pos/Util/Json/Canonical.hs
util/cardano-sl-util.cabal

`Pos.Core.Genesis.Canonical` doesn't seem to belong in `cardano-sl-core` and would be better placed in the `cardano-sl-util` package. This also assists me with [CDEC-512](https://iohk.myjetbrains.com/youtrack/issue/CDEC-512) as I need access to `SchemaError` from `Test.Pos.Util.Golden` (`cardano-sl-util-test`) for a new function, `goldenTestCanonicalJSON`.
[https://iohk.myjetbrains.com/youtrack/issue/CDEC-513](https://iohk.myjetbrains.com/youtrack/issue/CDEC-513)

[CDEC-513] Move Pos.Core.Genesis.Canonical to Pos.Util.Json.Canonical

---

wallet-new/src/Cardano/Wallet/WalletLayer.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Addresses.hs
wallet-new/test/Cardano/Wallet/WalletLayer/QuickCheck.hs
wallet-new/test/unit/Test/Spec/Addresses.hs

This makes this endpoint useable in more scenarios. After the next release we
may want to extend this or split it for different purposes.
https://iohk.myjetbrains.com/youtrack/issue/CBR-385

[CBR-385] Accept unknown addrs in validateAddress

---

wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/FromGeneric.hs
wallet-new/src/Cardano/Wallet/Kernel/Transactions.hs
wallet-new/src/Cardano/Wallet/Kernel/Util.hs
wallet-new/test/unit/Test/Spec/CoinSelection.hs
wallet-new/test/unit/Wallet/Inductive/Generator.hs

This improves security (makes it harder to guess which are the change outputs).
https://iohk.myjetbrains.com/youtrack/issue/CBR-380

[CBR-380] Shuffle tx outputs after coin selection

---

chain/src/Pos/Chain/Lrc/Genesis.hs

See https://github.com/input-output-hk/cardano-sl/issues/3425.
(I do hope you can forgive me for not filling out ~an immigration form~ this very extensive checklist of yours for a PR that adds a single comment to the code)

Warn about a pitfall in followTheSatoshiUtxo

---

shell.nix

make stylish-haskell and hlint available inside a nix-shell

make stylish-haskell and hlint available inside nix-shell

---

wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/Kernel/DB/AcidState.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/BlockMeta.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Create.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Update.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Util/IxSet.hs
wallet-new/src/Cardano/Wallet/Kernel/Util/StrictList.hs
wallet-new/src/Cardano/Wallet/Kernel/Util/StrictNonEmpty.hs

Although we use a custom strict state monad transformer to update the acid-state DB, this is of course pointless if we don't have strictness annotations all the way down. We should not have _any_ missing links from `DB` all the way down to the leaves:
```haskell
data DB = DB {
...
, dbFoo :: !X
}
data X = X {
...
, xY :: Y  -- missing strictness annotation here!
}
data Y = Y {
...
yZ :: !Z
}    
```
https://iohk.myjetbrains.com/youtrack/issue/CBR-396

[CBR-396] Acid-state strict all the way down

---

wallet-new/cardano-sl-wallet-new.cabal
wallet-new/server/Main.hs
wallet-new/src/Cardano/Wallet/API/Internal.hs
wallet-new/src/Cardano/Wallet/API/Internal/Handlers.hs
wallet-new/src/Cardano/Wallet/API/Internal/LegacyHandlers.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/AcidState.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/InDb.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Updates.hs
wallet-new/src/Cardano/Wallet/Kernel/NodeStateAdaptor.hs
wallet-new/src/Cardano/Wallet/Kernel/Util/StrictList.hs
wallet-new/src/Cardano/Wallet/Kernel/Util/StrictNonEmpty.hs
wallet-new/src/Cardano/Wallet/LegacyServer.hs
wallet-new/src/Cardano/Wallet/Server.hs
wallet-new/src/Cardano/Wallet/WalletLayer.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Internal.hs
wallet-new/test/Cardano/Wallet/WalletLayer/QuickCheck.hs
wallet-new/test/InternalAPISpec.hs

This PR makes a number of changes:
* Rename the old `Cardano.Wallet.API.Internal.Handlers` module to
`Cardano.Wallet.API.Internal.LegacyHandlers`, and introduce a new
`Cardano.Wallet.API.Internal.Handlers` module.
* Add new field to the kernel DB: the updates downloaded by the launcher,
along with the necessary functions to work with this new data.
* A new API endpoint for checking for updates
* `nextUpdate`, `applyUpdate`, `postponeUpdate` and `resetWalletState`
entries in the `PassiveWalletLayer`, along with implementations for the kernel
for all of these except for `resetWalletState` (CBR-393)
* An implementation of the new check-for-update endpoint also for the legacy
implementation.
* New functions in the `NodeStateAdaptor` that can be used to wait for an
update notification from the …

[CBR-250] Support for updates

---

wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/API/Request/Pagination.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Addresses.hs
wallet-new/test/unit/Test/Spec/Addresses.hs

Adding tests for pagination of Servant's `listAddresses` endpoint in `wallet-new`.
These tests check that pagination works fine for multiple addresses within a single account and wallet. Tests that check across multiple accounts and wallet are still missing, and will be submitted in a future pull-request.
CBR-371

[CBR-371] wallet-new: add tests for Servant's listAddresses endpoint

---

wallet-new/server/Main.hs
wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers/Addresses.hs
wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers/Wallets.hs
wallet-new/src/Cardano/Wallet/API/V1/Types.hs
wallet-new/src/Cardano/Wallet/Kernel/Pending.hs
wallet-new/src/Cardano/Wallet/Kernel/PrefilterTx.hs
wallet-new/src/Cardano/Wallet/Server/Plugins.hs
wallet/src/Pos/Wallet/Redirect.hs
wallet/src/Pos/Wallet/Web/Account.hs
wallet/src/Pos/Wallet/Web/Backup.hs
wallet/src/Pos/Wallet/Web/Error/Types.hs
wallet/src/Pos/Wallet/Web/Methods/Logic.hs
wallet/src/Pos/Wallet/Web/Methods/Payment.hs
wallet/src/Pos/Wallet/Web/Methods/Restore.hs
wallet/src/Pos/Wallet/Web/Server/Launcher.hs
wallet/src/Pos/Wallet/Web/State/Acidic.hs
wallet/src/Pos/Wallet/Web/State/State.hs
wallet/src/Pos/Wallet/Web/State/Storage.hs
wallet/src/Pos/Wallet/Web/State/Transactions.hs
wallet/src/Pos/Wallet/Web/Tracking/BListener.hs
wallet/src/Pos/Wallet/Web/Tracking/Decrypt.hs
wallet/test/Test/Pos/Wallet/Web/Tracking/SyncSpec.hs

This is the next PR for CHW (Cardano Hardware Wallets). It provides an implementation of basic handlers for API V1 endpoints, for work with external wallets.

[CHW] Implement basic handlers for work with external wallets.

---

default.nix
nixpkgs-src.json

Phase times metrics for everything!
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1013

[DEVOPS-1013] bump nixpkgs and add enablePhaseMetrics=true

---

wallet-new/src/Cardano/Wallet/Kernel/DB/Resolved.hs
wallet-new/src/Cardano/Wallet/Kernel/Pending.hs
wallet-new/src/Cardano/Wallet/Kernel/Transactions.hs

- adds comments, fixes names for CBR-390
- adds SQlite on disk  CBR-378 (this is WIP)

fixing names and comments

---

wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/FromGeneric.hs
wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/Generic.hs
wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/Generic/Fees.hs
wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/Generic/LargestFirst.hs

This will make it easier to write instances for `CoinSelHardErr`.
https://iohk.myjetbrains.com/youtrack/issue/CBR-374

[CBR-374] Simplify `CoinSelHardErr`

---

wallet-new/integration/Main.hs
wallet-new/integration/TransactionSpecs.hs
wallet-new/integration/Util.hs

The wallet integration tests have been failing with a number of issues. This PR fixes:
1) Incorrectly accessing genesis wallets in `genesisWallet`
2) Too short wait time for confirmations in TransactionSpecs
3) Running the random walk tests before the deterministic tests

Reduce integration test failures by reordering tests

---

wallet-new/test/unit/TxMetaStorageSpecs.hs

This PR aims to solve a bug at a test that could make it fail.
Failures:
```
test/unit/TxMetaStorageSpecs.hs:558:25: 
1) Wallet unit tests, TxMeta storage, pagination sorts meta with the correct address in Inputs or Outputs (SQL: union, sorting, pagination)
Falsifiable (after 2 tests):
expected: 2
but got: 3
```
The test can fail if the random generator creates 2 times the same address.
The equality check on 2 is stronger than it should. It should be at least 2.

Fixes failing test

---

.buildkite/nightly.yml
default.nix
lib.nix
scripts/launch/connect-to-cluster/default.nix
scripts/launch/demo-cluster/default.nix
scripts/test/acceptance/default.nix

Adds a test case which starts the wallet and does a full blockchain sync from both mainnet and testnet.
This is run nightly (midnight UTC) on the develop branch.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1016
- New or improved tests for existing code.
https://buildkite.com/input-output-hk/cardano-sl-nightly

[DEVOPS-1016] Nightly acceptance test

---

wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/API.hs
wallet-new/src/Cardano/Wallet/API/V1/Handlers/Wallets.hs
wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers/Wallets.hs
wallet-new/src/Cardano/Wallet/API/V1/Wallets.hs
wallet-new/src/Cardano/Wallet/API/WIP.hs
wallet-new/src/Cardano/Wallet/API/WIP/Handlers.hs
wallet-new/src/Cardano/Wallet/API/WIP/LegacyHandlers.hs
wallet-new/src/Cardano/Wallet/Client/Http.hs
wallet-new/src/Cardano/Wallet/LegacyServer.hs
wallet-new/src/Cardano/Wallet/Server.hs

This PR moves the CHW endpoints to a new path: /unimplemented.
New CHW features can be added to the /unimplemented endpoint with any danger of
interference with api/V1 features man later be moved to api/V1.

move CHW endpoints to a new the new path: /unimplemented

---

.gitignore
wallet-new/server/Main.hs
wallet-new/src/Cardano/Wallet/Kernel.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Sqlite.hs
wallet-new/src/Cardano/Wallet/Server/CLI.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
wallet-new/test/unit/Test/Spec/Fixture.hs
wallet-new/test/unit/Test/Spec/Kernel.hs
wallet-new/test/unit/Test/Spec/TxMetaScenarios.hs

This PR allows acid-state and sqlite to be persisted on disk rather than being in memory. A configurable setting is provided to switch to the in-memory vs on-disk setting.
@parsonsmatt This is really your PR rebased against `develop` and extended with:
1. The proper threading of the `walletDbOptions` to use the right `FilePath` for the DBs;
2. An extension to the Beam migration code to deal with the fact that now we are actually persisting the DB on disk. This is mostly band-aid and we should fix everything properly as part of CBR-403.
@edsko I would like to deliver the "periodic acid-state checkpoints" as part of a separate PR, after I do merge @KtorZ 's CBR-377, as that PR is reshuffling the plugins and it makes sense for it to go in first. …

[CBR-365] Allow on-disk databases

---

wallet-new/src/Cardano/Wallet/Kernel/Keystore.hs
wallet-new/src/Cardano/Wallet/Kernel/Wallets.hs
wallet-new/test/unit/Test/Spec/Keystore.hs

This commit address some atomicity considerations that @edsko brought up
during a code review. In particular, 3 functions have been amended:
- createHdWallet
- updateWalletPassword
- deleteHdWallet
For those, proper comments have been put to address any atomicity
concerns and the new function 'compareAndReplace' have been added to the
Keystore.
https://iohk.myjetbrains.com/youtrack/issue/CBR-363

[CBR-363] Review atomicity in some kernel operations

---

pkgs/default.nix
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/API/WIP/LegacyHandlers.hs
wallet-new/src/Cardano/Wallet/LegacyServer.hs
wallet-new/test/unit/Test/Spec/Keystore.hs

Somehow I manged to break the develop branch in PR 3498.
This is the quick-fix to make develop buildable again.

quickfix for a build-error introduced in 1622c6c28846d21818caab18f

---

auxx/Main.hs
db/src/Pos/DB/Rocks/Functions.hs
db/src/Pos/DB/Rocks/Types.hs
explorer/src/explorer/Main.hs
lib/src/Pos/Launcher/Launcher.hs
lib/src/Pos/Launcher/Resource.hs
lib/src/Pos/Launcher/Runner.hs
node/Main.hs
node/cardano-sl-node.cabal
tools/src/dbgen/Main.hs
wallet-new/server/Main.hs

Just a few clean ups and plumbing the `Core.Config` type through to `bracketNodeResources.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-495

CDEC-495: Preparation for hooking up block consolidation

---

wallet-new/src/Cardano/Wallet/API/Internal.hs
wallet-new/src/Cardano/Wallet/API/Internal/Handlers.hs
wallet-new/src/Cardano/Wallet/API/Internal/LegacyHandlers.hs
wallet-new/src/Cardano/Wallet/API/V1/Handlers/Wallets.hs
wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers/Wallets.hs
wallet-new/src/Cardano/Wallet/API/V1/Migration/Types.hs
wallet-new/src/Cardano/Wallet/API/V1/Types.hs
wallet-new/src/Cardano/Wallet/Kernel/Keystore.hs
wallet-new/src/Cardano/Wallet/WalletLayer.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Internal.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Transactions.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
wallet-new/test/Cardano/Wallet/WalletLayer/QuickCheck.hs
wallet-new/test/unit/Test/Spec/Accounts.hs
wallet-new/test/unit/Test/Spec/Addresses.hs
wallet-new/test/unit/Test/Spec/Wallets.hs

This PR implements the internal endopoint `POST /api/internal/import-wallet`, which is the last endpoint missing from the list Nikola had.
**Caveat emptor:** Although this piggybacks on the existing machery to restore a wallet, I haven't tested it. I will do so once I manage to spin up a local cluster with the new data layer (so that I can import the genesis wallet) _or_ manage to use Daedalus directly to operate the wallet against the staging cluster.
https://iohk.myjetbrains.com/youtrack/issue/CBR-407

[CBR-407] internal endpoint: import wallet from file

---

wallet-new/src/Cardano/Wallet/API/WIP/LegacyHandlers.hs
wallet-new/src/Cardano/Wallet/LegacyServer.hs
wallet/src/Pos/Wallet/Web/Methods/Logic.hs
wallet/src/Pos/Wallet/Web/Methods/Restore.hs

This is the next PR for CHW (Cardano Hardware Wallets). It provides an ability to restore and check external wallet.
[CHW-54]

[CHW] Restore and check external wallet, handlers.

---

wallet-new/src/Cardano/Wallet/API/Internal/LegacyHandlers.hs
wallet-new/src/Cardano/Wallet/LegacyServer.hs

This commit fixes the borked develop branch by adding the genesisData to
the internal handlers.

Fix borked develop

---

wallet-new/src/Cardano/Wallet/Kernel.hs
wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/FromGeneric.hs
wallet-new/src/Cardano/Wallet/Kernel/NodeStateAdaptor.hs
wallet-new/src/Cardano/Wallet/Kernel/Transactions.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Active.hs
wallet-new/test/unit/Test/Infrastructure/Generator.hs
wallet-new/test/unit/Test/Infrastructure/Genesis.hs
wallet-new/test/unit/Test/Spec/CoinSelection.hs
wallet-new/test/unit/Test/Spec/NewPayment.hs
wallet-new/test/unit/UTxO/Generator.hs
wallet-new/test/unit/UTxO/Interpreter.hs
wallet-new/test/unit/UTxO/Verify.hs
wallet-new/test/unit/Wallet/Inductive/Generator.hs

There is a sporadic test failure in the wallet unit tests. I noticed that one problem is in the test generator, and fixed that, but after I put in that fix, I realized that fee estimation is wrong. 
https://iohk.myjetbrains.com/youtrack/issue/CBR-405

[CBR-405] Fix bug in unit tests

---

auxx/src/Command/Update.hs
wallet/src/Pos/Wallet/Web/Tracking/Sync.hs

cleanup to the codebase needed by transition to structured logging based on 'katip'
CBR-275
- [~] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on …

[CBR-275] cleanup interface required for structured logging

---

pkgs/default.nix
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/Kernel/DB/AcidState.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Create.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Delete.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Read.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Update.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Read.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Update.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Updates.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Util/AcidState.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Util/IxSet.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Util/Zoomable.hs
wallet-new/src/Cardano/Wallet/Kernel/Util/StrictStateT.hs

This cleans up the zooming code and brings it in line with a write up that I will publish shortly.
Note that this is just one commit; the first few are https://github.com/input-output-hk/cardano-sl/pull/3516 .
The changes are also quite limited; it looks like a big change because I had to change the order of the type arguments to `Update'` and `Query'` so that the error type comes first.

Simplify the zooming code

---

auxx/src/Lang/DisplayError.hs
auxx/src/Lang/Lexer.hs
infra/src/Pos/Infra/DHT/Real/Real.hs
lib/src/Pos/Util/Servant.hs
tools/src/gencerts/Main.hs

The `RecordWildCards` extension makes it very difficult to discern where values come from. This is especially the case when the type is imported from outside the `cardano-sl` repository. If the type is not explicitly imported, this makes it more difficult to figure out where the type came resulting in time wasted and additional overhead.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-524

[CDEC-524] Remove `RecordWildCards` accessors of types defined outside of the `cardano-sl` repo

---

chain/bench/block-bench.hs
chain/cardano-sl-chain.cabal
db/cardano-sl-db.cabal
db/test/Test/Pos/DB/Epoch/Index.hs
pkgs/default.nix
stack.yaml
tools/cardano-sl-tools.cabal

And fix the warnings generated.

Add some missing -Wall compiler flags

---

CHANGELOG.md
db/src/Pos/DB/Block.hs
db/src/Pos/DB/Block/Epoch.hs
lib/cardano-sl.cabal
lib/src/Pos/Launcher/Resource.hs
pkgs/default.nix

As per title.
I want to kick this pretty hard so please let me merge it when we decide the time is right.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-495
I have a full node (from `wallet-new`) and the simple node (from `node`) set up and have done the following with each:
* Run the new version on an existing fully synced DB, and watched it consolidate existing epochs.
* Run it after deleteing the DB so it had to sync from the start.
* Stopped (control-C) and re-started the node during sync.
Happy to get any suggestions on what else I should test.

CDEC-495: Hook up block consolidation

---

default.nix
docker.nix
release.nix

Update `default.nix` to include attributes for building docker containers that run `explorer`.
https://github.com/input-output-hk/cardano-sl/issues/3547
- [~] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on …

nix: Add dockerImages configuration for explorer

---

docs/git/cheat-sheet.md
docs/git/getting-started.md

Happy to get suggestions for improvements, additions, corrections etc.

Add beginnings of Cardano specific git documentation

---

wallet-new/src/Cardano/Wallet/API/V1/Handlers/Accounts.hs
wallet-new/src/Cardano/Wallet/Kernel/Accounts.hs
wallet-new/src/Cardano/Wallet/Kernel/Addresses.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
wallet-new/src/Cardano/Wallet/Kernel/Transactions.hs
wallet-new/src/Cardano/Wallet/WalletLayer.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Accounts.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Addresses.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
wallet-new/test/unit/Test/Spec/Accounts.hs
wallet-new/test/unit/Test/Spec/Wallets.hs

This PR ensures that when we create a new wallet, it comes with a single fresh associated account at index `firstHardened`, and that such account has a fresh address associated with it.
@edsko This is the quickest thing I could come up for. However, looking at this, I cannot help but wonder if this requires a dedicated acid-state transaction to make sure we create this triplet `(wallet, account, address)` atomically. Open question if we can handle this as part of CBR-388.
https://iohk.myjetbrains.com/youtrack/issue/CBR-413

[CBR-413] Use default predictable account number when creating a wallet

---

wallet-new/src/Cardano/Wallet/Kernel.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/AcidState.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Sqlite.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/TxMeta.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/TxMeta/Types.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Updates.hs
wallet-new/src/Cardano/Wallet/Kernel/Restore.hs
wallet-new/src/Cardano/Wallet/Kernel/Submission.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Internal.hs
wallet-new/test/unit/TxMetaStorageSpecs.hs

This PR wires the endpoint to clear the state of the wallet. 
This can be used for Daedalus testing. 
https://iohk.myjetbrains.com/youtrack/issue/CBR-393

[CBR-393] reset wallet state

---

pkgs/default.nix
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/server/Main.hs
wallet-new/src/Cardano/Wallet/Kernel.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Util/IxSet.hs
wallet-new/src/Cardano/Wallet/Server/CLI.hs
wallet-new/src/Cardano/Wallet/Server/Plugins.hs
wallet-new/src/Cardano/Wallet/Server/Plugins/AcidState.hs
wallet-new/test/MarshallingSpec.hs

This PR _almost_ delivers CBR-365, by making a start on adding a plugin to create periodic acid-state checkpoints, as well as pruning old ones (which is something that the old wallet did). This is an incomplete PR which can hopefully be picked up by @parsonsmatt when he's back from 🚴 . Here is what needs to be done in order to close of CBR-365:
```haskell
instance SafeCopy a => SafeCopy (IxSet a) where
getCopy = error "getCopy for IxSet wrapper"
putCopy = error "putCopy for IxSet wrapper"
```
Not necessary to do this as part of CBR-365 (Can be done as part of CBR-305, but it will cause the plugin to fail).
https://iohk.myjetbrains.com/youtrack/issue/CBR-365

[CBR-365] Make a start on the periodic acid-state plugin

---

wallet-new/src/Cardano/Wallet/WalletLayer.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
wallet-new/test/Cardano/Wallet/WalletLayer/QuickCheck.hs
wallet-new/test/unit/Test/Spec/Addresses.hs
wallet-new/test/unit/Test/Spec/Wallets.hs

This PR fixes an embarrassing bug I have left when working on CBR-413. I did all that work to refactor things away to allow the `WalletLayer.Wallets.createWallet` function to reuse the `WalletLayer.Accounts.createHdAccount` function, but I didn't actually _plug it_.
Note that this PR (and that part of code) suffers from the same maladies @edsko reported in the original PR. I have opened CBR-416 to tackle that specifically.
https://iohk.myjetbrains.com/youtrack/issue/CBR-413

[CBR-413] rely on WalletLayer.createHdAccount in wallet creation

---

wallet-new/src/Cardano/Wallet/API/V1/Swagger.hs

Define a combinator to drill into a swagger schema and adjust properties (such as description) on specific endpoints.
Also added small usage examples for the internal endpoints.

Swagger Drill Combinator

---

tools/src/launcher/Main.hs
tools/src/launcher/launcher-config.yaml

After #3553, this will help for the cases where launcher is not run through Daedalus, e.g. by demo.sh. 
https://iohk.myjetbrains.com/youtrack/issue/CBR-391
1. Run `cardano-launcher --config tools/src/launcher/launcher-config.yaml` and verify that it doesn't fail on `workingDir`.
2. Run `scripts/launch/demo.sh` and check that it successfully starts.

[CBR-391] launcher: provide default workingDir

---

LICENSE
auxx/LICENSE
binary/LICENSE
binary/test/LICENSE
chain/LICENSE
chain/test/LICENSE
client/LICENSE
core/LICENSE
core/test/LICENSE
crypto/LICENSE
crypto/test/LICENSE
db/LICENSE
db/test/LICENSE
generator/LICENSE
infra/LICENSE
infra/test/LICENSE
networking/LICENSE
node/LICENSE
tools/LICENSE
util/LICENSE
util/test/LICENSE
wallet-new/LICENSE
wallet/LICENSE
wallet/test/LICENSE

Replaces https://github.com/input-output-hk/cardano-sl/pull/3411

Updated LICENCE file

---

wallet-new/src/Cardano/Wallet/API/V1/Handlers/Accounts.hs
wallet-new/src/Cardano/Wallet/Kernel/Accounts.hs
wallet-new/src/Cardano/Wallet/Kernel/Addresses.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/AcidState.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Create.hs
wallet-new/src/Cardano/Wallet/Kernel/Restore.hs
wallet-new/src/Cardano/Wallet/Kernel/Transactions.hs
wallet-new/src/Cardano/Wallet/Kernel/Wallets.hs
wallet-new/src/Cardano/Wallet/WalletLayer.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Accounts.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Addresses.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
wallet-new/test/unit/Test/Spec/Accounts.hs
wallet-new/test/unit/Test/Spec/Addresses.hs
wallet-new/test/unit/Test/Spec/NewPayment.hs
wallet-new/test/unit/Wallet/Inductive/Cardano.hs

This PR reshuffles a bit the work I did on CBR-413 and tries to fix the problem at the root: now we have our `createHdWallet` transaction enforce the invariant that, when we create a new wallet, it always come with a fresh account and a fresh address.
This will ensure that also restoration now behaves uniformly with the wallet creation.
https://iohk.myjetbrains.com/youtrack/issue/CBR-419
https://iohk.myjetbrains.com/youtrack/issue/CBR-416

[CBR-419][CBR-416] Fresh account (and address) on wallet restoration

---

scripts/launch/demo.sh

Running `scripts/launch/demo-with-wallet-api.sh` with
`WALLET_CLIENT_AUTH_DISABLE=1` was crashing because mutiple nodes
were trying to access the same wallet. Fix that by adding a unique
`--wallet-db-path` for each node.
https://iohk.myjetbrains.com/youtrack/issue/CO-364

CO-364: Add wallet-db-path command line param

---

scripts/test/wallet/integration/default.nix
wallet-new/README.md
wallet-new/integration/AccountSpecs.hs
wallet-new/integration/AddressSpecs.hs
wallet-new/integration/CLI.hs
wallet-new/integration/Functions.hs
wallet-new/integration/Main.hs
wallet-new/integration/TransactionSpecs.hs
wallet-new/integration/WalletSpecs.hs
wallet-new/test/unit/Test/Spec/Addresses.hs

Adding options:
--match which would behave exactly like Hspec's --match allowing us to run only a subset of tests;
--seed so that we can pass an external, predictable seed to the test runner.
Also remove all occurrences of generate in favor of prop, monadicIO, run, and pick.
https://iohk.myjetbrains.com/youtrack/issue/CBR-408
```nix-build -A walletIntegrationTests -o launch_integration_tests```
```./launch_integration_tests --match 'Address'```

[CBR-408] Remove generate and add seed/match options

---

lib/src/Pos/Util/UserSecret.hs
wallet-new/src/Cardano/Wallet/Kernel/Keystore.hs
wallet-new/test/unit/Test/Spec/Keystore.hs

This commit ensures that after every destructive keystore operation, we
invoke the 'writeRaw' function which works under the assumption we hold
the lock for this keystore (which is true as we are within an MVar) and
ensure that the file on disk is always kept up-to-date and not just at
the exit of the cardano-node.
https://iohk.myjetbrains.com/youtrack/issue/CBR-316

[CBR-316] Keystore consistency improvements

---

wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/API/V1/ReifyWalletError.hs
wallet-new/src/Cardano/Wallet/Kernel/Accounts.hs
wallet-new/src/Cardano/Wallet/Kernel/Addresses.hs
wallet-new/src/Cardano/Wallet/Kernel/Wallets.hs
wallet-new/src/Cardano/Wallet/Server/Plugins.hs
wallet-new/src/Cardano/Wallet/WalletLayer.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Accounts.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
wallet-new/test/Cardano/Wallet/WalletLayer/QuickCheck.hs
wallet-new/test/unit/Test/Spec/Accounts.hs
wallet-new/test/unit/Test/Spec/Wallets.hs

Translate all new wallet exceptions to WalletError
https://iohk.myjetbrains.com/youtrack/issue/CBR-409

[CBR-409] Translate all Kernel exceptions to WalletError

---

wallet-new/cardano-sl-wallet-new.cabal
wallet-new/server/Main.hs
wallet-new/src/Cardano/Wallet/Kernel.hs
wallet-new/src/Cardano/Wallet/Kernel/Migration.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs

This PR builds up on the one @kderme provided to polish a bunch of things up and allowing the migration to actually take place. There were a bunch of subtleties needed attention but the work had already been paved by Kostas. This works on my machine, at least from the very basic tests I have done: I have created a wallet (with some balance) using the old data layer, and after the migration I ended up with the same wallet I started with.
- https://iohk.myjetbrains.com/youtrack/issue/CBR-309
- https://iohk.myjetbrains.com/youtrack/issue/CBR-27

[CBR-309][CBR-27] Seamless migration of the legacy data layer

---

nixpkgs-src.json

When passing arguments to the linker, nix injects `-L$out/lib` flags for each dependency independent of the usefulness of such an injection. In the case of haskell, these injections are useless and eat up quite a bit of the max argument size.
The nixpkgs change allows to control the inclusion of `-L$out/lib` into the `LDFLAGS` by creating  `$out/nix-support/bintools-no-addLDVars`. This will prevent the packages `$out/lib` from being included into `LDFLAGS`.

[DEVOPS-1050] bump nixpkgs

---

default.nix

remove some now redundant overrides and reduce duplicate builds

---

tools/src/Pos/Tools/Dbgen/Lib.hs
wallet-new/src/Cardano/Wallet/Action.hs
wallet-new/src/Cardano/Wallet/Kernel/Transactions.hs
wallet/src/Pos/Wallet/Web/Methods/Restore.hs

Fix errors from `stack haddock --no-haddock-deps`
[CDEC-585](https://iohk.myjetbrains.com/youtrack/issue/CDEC-585)

[CDEC-585] Fix Haddock errors

---

explorer/frontend/default.nix

(cherry picked from commit a4782325ea3ba828d3f68cd6878c465c9adef434)
this solves the problem of hydra taking over an hour to eval every build

[DEVOPS-916] hydra: Fix cardano-sl-explorer-frontend eval

---

default.nix
log-configs/daedalus.yaml
tools/src/launcher/Main.hs

fix several bugs found when updating daedalus to the latest develop

---

wallet-new/src/Cardano/Wallet/Kernel/Transactions.hs

Fix a bug where TxMeta didnt add the change outputs.
This should only fix the visualisation of outputs of the Tx to the user. Not the amount being wrong.
https://iohk.myjetbrains.com/youtrack/issue/CBR-441

[CBR-441] Fix a bug where TxMeta didnt add the change outputs

---

wallet-new/src/Cardano/Wallet/Action.hs
wallet-new/src/Cardano/Wallet/Kernel.hs
wallet-new/src/Cardano/Wallet/Server/Plugins/AcidState.hs
wallet-new/test/unit/Test/Spec/Addresses.hs

- Adds the --wallet-rebuild-db option for new data layer.
- Cleans tests for addresses listing.
https://iohk.myjetbrains.com/youtrack/issue/CBR-435
https://iohk.myjetbrains.com/youtrack/issue/CBR-436

[CBR-436][CBR-435] Adds --wallet-rebuild-db option and cleans some tests

---

default.nix

this will aid in debugging why tests on darwin take 4+ days

fix showing the networking test logs

---

docs/how-to/connect-to-cluster.md

Closed ` (backtick)
- [ ~ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ~ ] 🛠 New feature (non-breaking change which adds functionality)
- [ ~ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ~ ] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [ ~ ] 🔨 New or improved tests for existing code
- [ ~ ] ⛑ git-flow chore (backport, hotfix, etc)
- [ ~ ] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [ ~ ] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md). …

Small markdown correction

---

tools/src/launcher/Main.hs

Backport of [DDW-380](https://iohk.myjetbrains.com/youtrack/issue/DDW-380) from `release/1.3.1` to `develop`.

 [DDW-380] Configure launcher to read/write safe mode parameter (backport from release 1.3.1)

---

default.nix
scripts/launch/demo-cluster/default.nix
scripts/launch/demo-nix.sh

Disables running wallet with demoClusterDaedalus since daedalus is running it's own wallet now with IPC changes.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1062

[DEVOPS-1062] Disable wallet running with demo-nix.sh

---

utxo/src/UTxO/IntTrans.hs
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/Kernel.hs
wallet-new/src/Cardano/Wallet/Kernel/Actions.hs
wallet-new/src/Cardano/Wallet/Kernel/BListener.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/AcidState.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Compression.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Delete.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Read.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Update.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Util/AcidState.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Util/IxSet.hs
wallet-new/src/Cardano/Wallet/Kernel/Internal.hs
wallet-new/src/Cardano/Wallet/Kernel/Migration.hs
wallet-new/src/Cardano/Wallet/Kernel/Restore.hs
wallet-new/src/Cardano/Wallet/Kernel/Util/NonEmptyMap.hs
wallet-new/src/Cardano/Wallet/Kernel/Util/StrictStateT.hs
wallet-new/src/Cardano/Wallet/Orphans.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Internal.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
wallet-new/test/unit/Test/Spec/WalletWorker.hs
wallet-new/test/unit/UTxO/ToCardano/Interpreter.hs
wallet-new/test/unit/Wallet/Abstract.hs
wallet-new/test/unit/Wallet/Inductive/Cardano.hs
wallet-new/test/unit/Wallet/Inductive/ExtWalletEvent.hs

This is a 6-hands, 4 brains PR which distills weeks of hacking mostly from @matt-noonan , with minor fixes from me and @uroboros . It improves quite a bit on the wallet restoration & catch-up process, hopefully making the process more resilient and stable in presence of rollbacks but also able to cope with resuming restoration after you shut down a node and also (potentially) coping with multiple restorations at the same time, which is important for our seamless migration.
There are still a number of lingering small bugs to address, but as this is more than 1000 lines of code at this point, this is the groundwork we are starting from, which is now fairly solid.
https://iohk.myjetbrains.com/youtrack/issue/CBR-244
https://iohk.myjetbrains.com/youtrack/issue/CBR-243

[CBR-244][CBR-243] Wallet restoration and catch up

---

wallet-new/src/Cardano/Wallet/Kernel/Pending.hs
wallet-new/test/unit/Test/Spec/GetTransactions.hs
wallet-new/test/unit/Test/Spec/NewPayment.hs

txAmount of a Tx should reflect how this Tx changes the balance of the Wallet that created it. To compute this, we used the existing allOurs function found in Cardano.Wallet.Kernel.Pending. Unfortunately the way this function was used, it checked for all the wallets in the backend. This means that if the Tx was between two wallets found in the same backend, the txAmount would only reflect the fees and not the amount transfered. This pr fixes this bug.
TODO: add tests for this.
https://iohk.myjetbrains.com/youtrack/issue/CBR-441

[CBR-441] fix txAmount of a newPending Tx, when there are multiple wallets

---

wallet-new/src/Cardano/Wallet/Kernel/Pending.hs
wallet-new/test/unit/Test/Spec/GetTransactions.hs

When a Tx is directed to an explicitly created account (not the one which comes with the wallet) it failed with a timeout. This pr tries to fix it.
https://iohk.myjetbrains.com/youtrack/issue/CBR-441

[CBR-441] Payment to explicitely created account fail fix

---

pkgs/default.nix
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/integration/AccountSpecs.hs
wallet-new/integration/Util.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Pending.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Read.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Update.hs

We treat (and represent) foreign transactions the same way as pending transactions. When we receive a new block, we currently remove from our pending and foreign sets transactions based on their inputs.  When we receive a `PrefilteredBlock`, it contains a set of inputs related to the wallet and we use it to filter out our pending and foreign transactions.
However, foreign transactions' inputs aren't related to our wallet, they come from somewhere else! We in this case, we want to filter out based on the UTxO of that prefiltered block.
[[CO-395]](https://iohk.myjetbrains.com/youtrack/issue/CO-395)

[CO-395] Redeem Ada Fix Pending

---

wallet-new/integration/AccountSpecs.hs

postTransaction test was adapted to
(i) the fact that in new data layer newly created accounts DO NOT have automatically created addresses - in contrast to old data layer. In the new data layer the invariant that an account comes with a fresh address only if we create a new wallet is enforced. It was done to accommodate frontend requirements of having a “fully usable” wallet upon creation without having invariants scattered all across the place.
(ii) test postTransaction not only to automatically created accounts but also to newly created accounts>
https://iohk.myjetbrains.com/youtrack/issue/CO-398
```
nix-build -A walletIntegrationTests -o launch_integration_tests
./launch_integration_tests --match "Accounts
```

[CO-398] Fixing accounts specs

---

wallet-new/src/Cardano/Wallet/API/V1/Swagger.hs

[[CO-406]](https://iohk.myjetbrains.com/youtrack/issue/CO-406)

[CO-406] Remove swagger import

---

wallet-new/src/Cardano/Wallet/API/V1/Types.hs
wallet-new/src/Cardano/Wallet/Kernel/Decrypt.hs
wallet-new/src/Cardano/Wallet/Kernel/Pending.hs
wallet-new/src/Cardano/Wallet/Kernel/PrefilterTx.hs

WIP
TODO:
[CO-402](https://iohk.myjetbrains.com/youtrack/issue/CO-402)

[CO-402] Remove dependency on `Pos.Wallet.Web.Tracking.Decrypt`

---

wallet-new/src/Cardano/Wallet/Server/CLI.hs

This commit fixes a silly bug (for which I take the shame) which was
setting as the default wait time for the acid state cleanup worker what
we thought was 12 minutes, but I was treating the field as if it was
in seconds. Therefore, I was waiting (12 * 60) to trigger a cleanup
every 12 minutes without realising I was setting up a cleanup to run
every 720 minutes!
This commit fixes it, and also sets the default value to 5 minutes.
https://iohk.myjetbrains.com/youtrack/issue/CBR-459

[CBR-459] Take acid-state checkpoints every 5 minutes

---

pkgs/default.nix
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/Kernel/BListener.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/BlockContext.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Update.hs
wallet-new/src/Cardano/Wallet/Kernel/Util/Strict.hs
wallet-new/test/MarshallingSpec.hs
wallet-new/test/unit/UTxO/ToCardano/Interpreter.hs
wallet-new/test/unit/Wallet/Inductive/Cardano.hs

This commit replaces all the occurrencies of Maybe types used in the `DB` data structure with their strict variant, to make sure that we never (or we try as hard as we can) write stuff which is not in `whnf` in the `DB`.
https://iohk.myjetbrains.com/youtrack/issue/CBR-442

[CBR-442] Replace Maybe with Strict.Maybe for DB types

---

wallet-new/src/Cardano/Wallet/Kernel/DB/Sqlite.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/TxMeta/Types.hs
wallet-new/test/unit/TxMetaStorageSpecs.hs

This improves some part of TxMeta like:
- adds implicit sorting to be: descenting by creation time.
- adds tests for the above.
- fixes some tests that could fail.
- fixes and improves stray comments.

refactoring TxMeta storage

---

pkgs/default.nix
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/Kernel.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/InDb.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Pending.hs
wallet-new/src/Cardano/Wallet/Kernel/Internal.hs
wallet-new/src/Cardano/Wallet/Kernel/Keystore.hs
wallet-new/src/Cardano/Wallet/Kernel/Submission.hs
wallet-new/src/Cardano/Wallet/Kernel/Types.hs
wallet-new/src/Cardano/Wallet/Kernel/Util/Strict.hs

This commit replaces most of the usages of 'MVar' and 'modifyMVar' in the
Kernel with their strict counterparts, to make sure that when we apply
the update function 'f', this is not left unapplied as a lazy thunk.
https://iohk.myjetbrains.com/youtrack/issue/CBR-444
No big changes in memory (which is good, at least this PR is not making things worse, hehe):

[CBR-444] Use strict MVar in the Kernel

---

wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/API/V1/Types.hs
wallet-new/src/Cardano/Wallet/Kernel/Decrypt.hs
wallet-new/test/DecryptSpec.hs
wallet-new/test/Spec.hs

A bit unsure about this
[CO-408](https://iohk.myjetbrains.com/youtrack/issue/CO-408)

[CO-408] Tests and minor fixes related to Cardano.Wallet.Kernel.Decrypt

---

CHANGELOG.md

After CBR-401 got merged, we forgot to update the CHANGELOG with a transcript of what changed and why.
[[CBR-449]](https://iohk.myjetbrains.com/youtrack/issue/CBR-449)

[CBR-449] Update CHANGELOG.md about CBR-401's changes (oversight)

---

faucet/cardano-sl-faucet.cabal
pkgs/default.nix

drop text-format from faucet, its not used

---

wallet-new/src/Cardano/Wallet/Kernel/BListener.hs

Tiny changes to follow up the 'backfilling' PR, e.g.  
* change log message that marks the beginning of backfilling from INFO to WARNING
https://iohk.myjetbrains.com/youtrack/issue/CBR-453

[CBR-453] Backfilling bug fix (follow up)

---

pkgs/hfsevents.nix
wallet-new/src/Cardano/Wallet/API/V1/Handlers/Transactions.hs
wallet-new/src/Cardano/Wallet/API/V1/ReifyWalletError.hs
wallet-new/src/Cardano/Wallet/API/V1/Types.hs
wallet-new/src/Cardano/Wallet/API/WIP.hs
wallet-new/src/Cardano/Wallet/API/WIP/Handlers.hs
wallet-new/src/Cardano/Wallet/API/WIP/LegacyHandlers.hs
wallet-new/src/Cardano/Wallet/Client.hs
wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/FromGeneric.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
wallet-new/src/Cardano/Wallet/Kernel/Transactions.hs
wallet-new/src/Cardano/Wallet/WalletLayer.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Active.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs
wallet-new/test/Cardano/Wallet/WalletLayer/QuickCheck.hs
wallet-new/test/unit/Test/Spec/CoinSelection.hs

Moving handlers for API V1 (for external wallets) from legacy wallet to the new one.
https://iohk.myjetbrains.com/youtrack/issue/CO-391

[CO-391] API WIP-handlers for external transactions.

---

sample-wallet-config.nix

Some 3rd parties are accustomed to running without the client cert
authentication feature. This advertises the option to disable it in
the sample wallet config.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-978
1. checkout this feature branch
2. copy `sample-wallet-config.nix` to `custom-wallet-config.nix` and uncomment the `disableClientAuth = true;` line in the custom config file
3. build wallet connect script according to `docs/exchange-onboarding.md` and run it
4. confirm `curl -k -X GET "https://127.0.0.1:8090/api/v1/node-info" -H "accept: application/json;charset=utf-8"` responds with JSON that includes sync progress info (as opposed to any errors about certificate authentication)

[DEVOPS-978] Expose disableClientAuth in sample-wallet-config.nix

---

wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/FromGeneric.hs
wallet-new/test/unit/Test/Spec/CoinSelection.hs

See  https://github.com/input-output-hk/cardano-sl/pull/3723#pullrequestreview-162773560 for the rationale.
[CBR-465]

Always sort payees by amount

---

infra/cardano-sl-infra.cabal
infra/default.nix
infra/src/Pos/Infra/InjectFail.hs
infra/src/Pos/Infra/Shutdown/Logic.hs
infra/src/Pos/Infra/Shutdown/Types.hs
lib/default.nix
lib/src/Pos/Client/CLI/NodeOptions.hs
lib/src/Pos/Client/CLI/Params.hs
lib/src/Pos/Launcher/Param.hs
lib/src/Pos/Launcher/Resource.hs
lib/src/Pos/Launcher/Runner.hs
node-ipc/src/Cardano/NodeIPC.hs
pkgs/default.nix
release.nix
tools/src/dbgen/Main.hs
util/default.nix
wallet-new/README.md
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/src/Cardano/Wallet/Action.hs
wallet-new/src/Cardano/Wallet/Kernel.hs
wallet-new/src/Cardano/Wallet/Kernel/Internal.hs
wallet-new/src/Cardano/Wallet/Server/Middlewares.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Internal.hs
wallet-new/test/unit/Test/Spec/Fixture.hs
wallet-new/test/unit/Test/Spec/Kernel.hs
wallet-new/test/unit/Test/Spec/TxMetaScenarios.hs
wallet/test/Test/Pos/Wallet/Web/Mode.hs

Implement failure injection for a subset of the wallet API, to support Daedalus testing.
The faults to inject can be specified:
1. Statically, on the command line (https://github.com/input-output-hk/cardano-sl/tree/fault-injection/wallet-new#fault-injection)
2. At runtime, using the `SetFInject FInject Bool` message of `node-ipc`.
3. `--allow-fault-injection` has to be passed to allow any injections to be processed at all.
4. The `node-ipc` has been massaged a bit, splitting the `Packet` type into `Request` and `Response`.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1086

Wallet API failure injection

---

docs/exchange-onboarding.md
sample-wallet-config.nix

Update exchange documentation with examples for legacy wallet and setting up TLS correctly.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1087

[DEVOPS-1087] Update exchange documentation for TLS authentication and legacy wallet

---

docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md
docs/nix.md

Updates/adds some more docs about using Nix and correctly setting up the binary cache.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1083
- Documentation

[DEVOPS-1083] docs: Update nix building and configuration

---

cluster/test/Main.hs

Previously the test program would terminate on the first failure.

cluster tests: Print all failures

---

infra/src/Pos/Infra/InjectFail.hs

This adds logging for fault injection state transitions -- that is enablement / disablement of particular injections.

[DEVOPS-1086]  fault injection:  log injection state changes

---

CHANGELOG.md

The correct behaviour comes with the new wallet layer. Breaking change though.
https://iohk.myjetbrains.com/youtrack/issue/CSL-2524

[CLS-2524] Update changelog about fixed wallet 404

---

wallet-new/src/Cardano/Wallet/Kernel/DB/Sqlite.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/TxMeta/Types.hs
wallet-new/test/unit/TxMetaStorageSpecs.hs

This PR:
- fixes a bug, that caused SQlite to not roll-back when there was an error in an SQlite transaction.
- removes suchThat, which can cause tests to take too long.
About the SQLite bug: The bug was caused because we used `Sqlite.runDBAction` inside `Sqlite.withTransaction`. This first function caught any real exceptions and turned them into typed exception (Left ...). This meant that the transaction-monad never actually failed and we never rolled-back. From the SQlite trace we can see the difference:
Before the fix: we can see even if the 3rd insert fails, the transaction is commited:
```
"BEGIN TRANSACTION"
"INSERT INTO \"tx_metas_outputs\"(\"meta_id\", \"output_index\", \"output_address\", \"output_coin\") VALUES (0, 0, '', 0), (0, 1, '', 0)"
"INSERT INTO \"tx_metas\"(\"meta_id\", …
```

[CBR-472] SQlite rollback and tests fix

---

pkgs/default.nix
x509/cardano-sl-x509.cabal
x509/src/Data/X509/Extra.hs

Backporting https://github.com/input-output-hk/cardano-sl/pull/3773 
[[CBR-470]](https://iohk.myjetbrains.com/youtrack/issue/CO-434)

[CBR-470] ensure mode 600 x509

---

scripts/launch/demo-cluster/default.nix

integration tests do not run locally as syncing problem occurs:
```
[pawel@arch cardano-sl]$ nix-build -A walletIntegrationTests -o launch_integration_tests --arg useStackBinaries true
/nix/store/8vk208q9fg9zq5jfhm4cmqcjl880lm8x-integration-tests
[pawel@arch cardano-sl]$ ./launch_integration_tests
Launching a demo cluster...
/nix/store/9kjc35br66wa5p2lp1ckzy8kjgqisfj4-demo-cluster: line 25: cardano-sl-cluster-demo: command not found
Blockchain Syncing: %
Blockchain Syncing: %
Blockchain Syncing: %
Blockchain Syncing: %
```
Small nix fix is adopted to work again
https://iohk.myjetbrains.com/youtrack/issue/CO-437
Make sure you have the latest demo cluster (and of course wallet-new) built:
```
$ stack build cardano-sl-cluster
$ ./scripts/build/cardano-sl.sh wallet-new
```
And then run wallet …

[CO-437] Make wallet integration tests working locally

---

wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
wallet-new/src/Cardano/Wallet/Kernel/DB/Spec.hs
wallet-new/src/Cardano/Wallet/Kernel/Util/Core.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs

Backporting from https://github.com/input-output-hk/cardano-sl/pull/3742
[[CBR-466]](https://iohk.myjetbrains.com/youtrack/issue/CBR-466)

[CBR-466] fix address reported as unused during restoration

---

pkgs/default.nix
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/integration/HardwareWalletSpecs.hs
wallet-new/integration/Main.hs
wallet-new/integration/TransactionSpecs.hs
wallet-new/integration/Util.hs

* Add the module HardwareWalletSpecs.
This module exports HSpec tests for the following endpoints :
postUnsignedTransaction  -- retrieve an unsigned transaction from the wallet
postSignedTransaction    -- post an externally signed transaction
The tests take a seed::Integer as argument.
This seed is used to create new unique wallets as needed.
* Add the module MainHardwareWalletSpecs.
Convenience functions for stand-alone running the tests from a REPL
(outside of Main).
* Add unsafeProtocolMagic as a new top level declaration to Main.
Hard-coding ProtocolMagic in Main is a hack that should be fixed !
ProtocolMagic is needed in the tests to compute crypto function
(simulating an external ledger device).
The ProtocolMagic should be passed in from the CLI or read from the defining config …

[CO-424] Add integration tests for Cardano Hardware Wallets

---

generator/app/VerificationBench.hs
generator/bench/Bench/Pos/Criterion/Block/Logic.hs
lib/src/Pos/Launcher/Resource.hs
networking/bench/LogReader/Main.hs
networking/bench/Receiver/Main.hs
networking/bench/Sender/Main.hs
networking/src/Bench/Network/Commons.hs
networking/test/Test/Network/Broadcast/OutboundQueueSpec.hs
tools/src/keygen/Main.hs
tools/src/launcher/Main.hs
util/src/Pos/Util/Wlog.hs
util/src/Pos/Util/Wlog/Compatibility.hs

(cherry picked from commit 0f41c67139ba7718f427f106e8249f1d9cdb09b6)

[CBR-477] Close scribes before terminating.

---

lib/src/Pos/Client/CLI/Options.hs
wallet-new/src/Cardano/Wallet/Action.hs
wallet-new/src/Cardano/Wallet/Server/CLI.hs
wallet-new/src/Cardano/Wallet/Server/Plugins.hs

(cherry picked from commit cf68c04a1cc89156b3f367d707e4c80ecd11a234)

[DEVOPS-1099] make the wallet documentation optional, and default it to off

---

nix/overlays/required.nix
nixpkgs-src.json
release.nix

Splits builds and test suites into separate derivations so test suites can be ran in parallel.
This does not include hydra changes to run tests yet.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1041

[DEVOPS-1041] Split build and test derivations for cardano-sl

---

core/test/Test/Pos/Core/Arbitrary.hs
wallet-new/src/Cardano/Wallet/API/V1/ReifyWalletError.hs
wallet-new/src/Cardano/Wallet/WalletLayer.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Active.hs
wallet-new/test/unit/Test/Spec/CoinSelection/Generators.hs
wallet-new/test/unit/Test/Spec/NewPayment.hs

Currently, one can attempt to construct and send transactions to addresses which are of a different network via the wallet-new V1 API. Even though the nodes reject this transaction since it's invalid (as a result of #3775), an error should be returned by the API in order to prevent users from even attempting this.
[https://iohk.myjetbrains.com/youtrack/issue/RCD-40](https://iohk.myjetbrains.com/youtrack/issue/RCD-40)

[release/2.0.0] [RCD-40] Address discrimination not enforced when sending transactions

---

tools/src/launcher/Main.hs

[DDW-480] Fix error message show user for x509 regeneration failures

---

nix/stack2nix.nix
wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/FromGeneric.hs
wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/Generic.hs
wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/Generic/Fees.hs
wallet-new/src/Cardano/Wallet/Kernel/Transactions.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Active.hs
wallet-new/test/unit/Test/Spec/CoinSelection.hs
wallet-new/test/unit/Test/Spec/GetTransactions.hs
wallet-new/test/unit/Test/Spec/NewPayment.hs

https://github.com/input-output-hk/cardano-sl/pull/3815

[CSL-2526] update changes after covering remaining fees

---

tools/src/launcher/Main.hs

Ddw 480 fix error msg release

---

lib/src/Pos/Node/API.hs
lib/src/Pos/Util/Servant.hs
node/cardano-sl-node.cabal
node/src/Cardano/Node/API.hs
pkgs/default.nix
wallet-new/src/Cardano/Wallet/API/Response.hs

This PR implements the handlers for the `node` information and settings API. The update API handlers have not been implemented yet.

Implement the node API without referencing `wallet-new`

---

pkgs/default.nix
tools/post-mortem/cardano-sl-tools-post-mortem.cabal
tools/post-mortem/src/Main.hs
tools/post-mortem/src/Statistics/Chart.hs

A large delay is added in the execution of `post-mortem` because `times.svg` is being created. As the same graph can be produced by the script in https://github.com/input-output-hk/iohk-ops/blob/master/benchmarks/scripts/plots.r#L353 it was decided not to create it through `post-mortem`.
[PB-96](https://iohk.myjetbrains.com/youtrack/issue/PB-96)

[PB-96] Cleanup post-mortem.

---

faucet/cardano-sl-faucet.cabal
faucet/src/Cardano/Faucet/Init.hs
faucet/src/Cardano/Faucet/Types/Config.hs
mnemonic/LICENSE
mnemonic/README.md
mnemonic/cardano-sl-mnemonic.cabal
mnemonic/generate-mnemonic/Main.hs
mnemonic/src/Cardano/Mnemonic.hs
mnemonic/test/Cardano/MnemonicSpec.hs
mnemonic/test/Main.hs
pkgs/default.nix
stack.yaml
wallet-new/cardano-sl-wallet-new.cabal
wallet-new/integration/HardwareWalletSpecs.hs
wallet-new/src/Cardano/Wallet/API/V1/Types.hs
wallet-new/src/Cardano/Wallet/Kernel/Wallets.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
wallet-new/test/unit/Test/Spec/Wallets.hs

WIP. We want to remove the wallet and dependencies of it in the cardano-sl repo. `BIP39` is needed for `faucet`, so we move it to its own package.
Todo:
[input-ouput-hk/cardano-wallet#55](
https://github.com/input-output-hk/cardano-wallet/issues/55)

Move BIP39 module to separate package

---

release.nix

[DEVOPS-1136] Add all tests to required hydra attr

---

lib/configuration.yaml

(cherry picked from commit 6b6e22bb2089324b46ce0d05b7f031ceb026ab76)

[DEVOPS-1130] bump versions

---

.buildkite/windows.ps1
lib/configuration.yaml

Updates applicationVersion for the testnet wallet so that an update proposal of this branch can be made on testnet.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1141
- Configuration update
- Build fix

[DEVOPS-1141] Bump applicationVersion for testnet_wallet

---

pkgs/default.nix
stack.yaml

[DEVOPS-1134]  Bump report-server for ZD tickets defaulting to New

---

appveyor.yml

appveyor:  bump OpenSSL to 1.0.2q, as build for 1.0.2p is no longer available

---

lib/src/Pos/Launcher/Launcher.hs

Fix the acceptance tests: EKG is already being started in Pos.Launcher.Runner.

launcher:  EKG already started in Launcher/Runner

---

bors.toml

enable bors for release 2.0.0

---

docs/exchange-onboarding.md

Fix a typo about building testnet docker image
Fix a typo of [docs/exchange-onboarding.md](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exchange-onboarding.md#method-2-build-and-run-a-docker-image) about building testnet docker image.
No issue related.
Send the message `bors …

docs: fix a typo in `docs/exchange-onboarding.md`

---

docs/nix.md
nix/iohk-binary-cache.nix

Update docs based on questions received in GitHub issues.
- #3485
- #3850 (I think)
- Documentation

docs: Small fixes for nix.md

---

wallet/src/Pos/Wallet/Web/State/Storage.hs

The previous incarnation of `addWAddress` had a bug: in case of new
accounts (like the ones we could find as part of a restoration) it
wouldn't add the relevant address to the DB, because the old code was
using a lens traversal with 'ix' which notoriously does nothing if the
key (in this case the account index) was not there.
This commit fixes it.

[DEVOPS-1151] Extend addWAddress to support newly-found accounts

---

pkgs/default.nix
stack.yaml

Experiment on `staging` shows that the status for a new ticket is indeed `New`:
```
$ curl -v -F payload='{
"application" : "cardano-node", "build":"lol",
"version" : "0.0.1",
"os" : "Linux 4.9.2 NixOS",
"logs" : [""],
"date" : "2018-05-03T00:00:00",
"magic" : 2000000000,
"type" : { "type" : "customreport", "email" : "iohk.zendesk.test@gmail.com", "subject" : "foo", "problem" : "none" }
}' http://staging-report-server.awstest.iohkdev.io:8080/report | jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 18.197.75.233...
* TCP_NODELAY set
* Connected to staging-report-server.awstest.iohkdev.io (18.197.75.233) port 8080 (#0)
> POST …
```

[DEVOPS-1143]  Bump report-server to drop setting of Assignee field in fresh tickets

---

.buildkite/pipeline.yml

buildkite legacy windows instance

---

lib/src/Pos/Util/Servant.hs
lib/src/Pos/Web/Server.hs
node/cardano-sl-node.cabal
node/src/Cardano/Node/API.hs
pkgs/default.nix
wallet-new/src/Cardano/Wallet/API/V1/Headers.hs

This PR brings the Node API into compliance with JSend error format. On unknown exceptions, we print out the same error message as the other API. In debug mode, we print everything out.

Node API Jsend errors

---

.buildkite/pipeline.yml
sample-wallet-config.nix
scripts/launch/connect-to-cluster/default.nix

This allows to use the wallet with port forwarding AND TLS authentication enabled.

[DEVOPS-1149]  Make generated TLS certificates fully configurable in Nix

---

lib/configuration.yaml

Update applicationVersion for an update proposal on testnet.
https://github.com/input-output-hk/internal-documentation/wiki/Daedalus-installer-history
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1112
- Configuration

[DEVOPS-1112] Bump applicationVersion 2 -> 3 for testnet

---

lib/configuration.yaml

fix application version

---

.buildkite/windows.ps1

cleanup tmp on every buildkite windows build

---

lib/src/Pos/Diffusion/Full/Block.hs

If we read windows updates from a node it is reachable and we should
keep sending data to it.

RCD-43: Clear failure on win update

---

cluster/cardano-sl-cluster.cabal
pkgs/default.nix

Oopsie :upside_down_face: 
input-output-hk/cardano-wallet#65

Actually remove the 'cardano-wallet' dep from 'cardano-sl-cluster' -_-'

---

lib/README.md

Fix reference to unexisting README file.

---

lib/configuration.yaml

Bump applicationVersion for staging update proposal of 2.0.0 RC7.
https://github.com/input-output-hk/internal-documentation/wiki/Daedalus-installer-history
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1112
- Configuration change

[DEVOPS-1112] Bump staging applicationVersion 17 → 18

---

scripts/ci/check-hydra.sh

`jq` can't successfully run `doCheck` on macOS. As such the whole script fails to build.

Fix check-hydra on macOS

---

infra/src/Pos/Infra/Diffusion/Subscription/Dns.hs
lib/src/Pos/Diffusion/Full.hs
lib/src/Pos/Diffusion/Full/Block.hs

The keep-alive timer where incorrectly shared among all
nodes a client subscribed to which rendered them ineffective
during rolling restarts.
https://iohk.myjetbrains.com/youtrack/issue/CBR-494
0. Setup two private, p-0 and p-1, relays and one public relay. The public relay should subscribe to both private relay at the same time (dynamic-subscribe: [ [ { "host":"p-0.cardano"} ], [ {"host":"p-1.cardano"} ] ] ).
1. Start a fresh block sync from a client that connects to the public relay.
2. Restart p-0
3. Wait 4 minutes
4. Restart p-1
5. Verify that it was possible to restart both nodes without any visible interruption in the client.
[`docs/how-to/bors.md`](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/h …

[CBR-494] Per node keep-alive timers

---

sample-wallet-config.nix
scripts/launch/connect-to-cluster/default.nix

This is a squashed version of PR #3895

[DEVOPS-1149]  Make generated TLS setup configurable

---

.stack-to-nix.cache
cluster/test/Main.hs
nix/.stack.nix/cardano-crypto.nix
nix/.stack.nix/inspector.nix
pkgs/default.nix
stack.yaml

This should fix
- nix-tools.tests.x86_64-pc-mingw32-cardano-crypto.cardano-crypto-golden-tests.x86_64-linux
- nix-tools.tests.x86_64-pc-mingw32-cardano-sl-cluster.cardano-sl-cluster-test.x86_64-linux

[DEVOPS-1177] Windows cross test failures

---

db/cardano-sl-db.cabal
db/src/Pos/DB/Block/Epoch.hs
db/src/Pos/DB/Rocks/Functions.hs
lib/src/Pos/Diffusion/Full/Block.hs
nix/.stack.nix/cardano-sl-db.nix
pkgs/default.nix

Cherry pick RCD-43 fixes from release/2.0.0.
https://iohk.myjetbrains.com/youtrack/issue/RCD-43
- [*] ⛑ git-flow chore (backport, hotfix, etc)

RCD-43 cherry picks

---

.stack-to-nix.cache
nix/.stack.nix/cardano-crypto.nix
pkgs/default.nix
stack.yaml

Fixes deriveXPub: bip32 hd wallet public key derivation
https://github.com/input-output-hk/cardano-crypto/pull/52
This is a bump of `cardano-crypto` bug https://github.com/input-output-hk/cardano-crypto/pull/52 . It was discovered as a part of a task on `cardano-wallet` https://github.com/input-output-hk/cardano-wallet/issues/41
https://github.com/input-output-hk/cardano-wallet/issues/41

Bump cardano-crypto

---

node/src/Cardano/Node/Client.hs

The PR adding `nextUpdate` testing to the cardano-wallet repo ([here](https://github.com/input-output-hk/cardano-wallet/pull/210)) demonstrated a bug in the way the Node client was handling 404 errors. As these typically don't have response bodies, it was failing them in a way that was really awkward to check.
This PR provides a special case that should make the program work better.

Special case 404 errors with empty bodies

---

lib/configuration.yaml

[DEVOPS-1203] configuration.yaml: Bump applicationVersion

---

nix/config.nix
nix/patches/ghc/MR95--ghc-pkg-deadlock-fix.patch

We've observed `ghc-pkg` hanging on our builders; while building packages.  @rvl managed to isolate the case, and Ticket [#16147](https://ghc.haskell.org/trac/ghc/ticket/16147) on the GHC issue tracker. And subsequently believed to be resolved in [GHC Merge Request 95](http://gitlab.haskell.org/ghc/ghc/merge_requests/95). 
This change adds the relevant patch to our GHC.

[DEVOPS-1206] fix ghc-pkg deadlock

---

default.nix
release.nix

[DEVOPS-1209] Build benchmarks as well

---

networking/src/Network/Broadcast/OutboundQueue.hs

We would always log when a message is enqueued nowhere by exception: it
was supposed to reach some target but the queue decided to drop it. Now
we also log (notice level) when the policy ignores it.

log when message is enqueued nowhere by policy

---

CHANGELOG.md
wallet/src/Cardano/Wallet/Kernel/CoinSelection/FromGeneric.hs
wallet/src/Cardano/Wallet/Kernel/CoinSelection/Generic.hs
wallet/src/Cardano/Wallet/Kernel/CoinSelection/Generic/Fees.hs
wallet/src/Cardano/Wallet/Kernel/Transactions.hs
wallet/src/Cardano/Wallet/WalletLayer/Kernel/Active.hs
wallet/test/unit/Test/Spec/CoinSelection.hs
wallet/test/unit/Test/Spec/CoinSelection/Generators.hs
wallet/test/unit/Test/Spec/GetTransactions.hs
wallet/test/unit/Test/Spec/NewPayment.hs

Backporting https://github.com/input-output-hk/cardano-sl/pull/3993 onto `develop`. This needs to be part of the 1.5 release and we won't be merging `cardano-wallet` back onto develop for `1.5`. So, this change is currently in `cardano-sl/release/2.0.1` and in `cardano-wallet/develop` but not in `cardano-sl/develop`.

[CO-446] Fee Sanity Check (→develop)

---

lib/configuration.yaml

[DEVOPS-1203] csl-daedalus appversion bump

---

CHANGELOG.md

CHANGELOG.md needs an update for CDEC-658
https://iohk.myjetbrains.com/youtrack/issue/CDEC-658

[CDEC-658] Updated CHANGELOG.md file

---

CHANGELOG.md

Update CHANGELOG.md file.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-658
https://iohk.myjetbrains.com/youtrack/issue/CDEC-659

[CDEC-658][CDEC-659] Updated CHANGELOG.md with [CDEC-658] and [CDEC-659]

---

.stack-to-nix.cache
nix/.stack.nix/cardano-crypto.nix
pkgs/default.nix
stack.yaml

Updates cardano-crypto with the recent addition from input-output-hk/cardano-crypto#54 which adds support for a new XPrv generation method using a raw entropy from mnemonic words and PBKDF hashing to generate the master key.

Update 'cardano-crypto' extra-dependency to 45e1a0ea (support for XPrv generation with pbkdf)

---

core/src/Pos/Core/Common/Address.hs

tiny little PR to get rid of a TODO

Fix a TODO

---

CHANGELOG.md

Corrected link to the PR in CHANGELOG.md
https://iohk.myjetbrains.com/youtrack/issue/CDEC-658

[CDEC-658] Change PR link in CHANGELOG.md

---

lib/configuration.yaml

[DEVOPS-1219] remove systemTag override

---

nix/.stack.nix/cardano-sl-tools.nix
tools/cardano-sl-tools.cabal
tools/src/launcher/Main.hs

RCD-52 changes
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1211

[RCD-52] Cherry picks from release

---

cluster/README.md

Added troubleshooting section in `README.md` file for cluster.

Added troubleshooting section in cluster/README.md

---

docs/nix.md

Document one way to build using nix with IOHK caches, by way of command line arguments rather than configuration files.

add command-line options to nix.md

---

CHANGELOG.md

Move CHANGELOG.md entry to `Next` section
https://iohk.myjetbrains.com/youtrack/issue/CDEC-659

[CDEC-659] CHANGELOG.md

---

wallet/src/Cardano/Wallet/API/V1/Swagger.hs

Mirroring input-output-hk/cardano-wallet#263
input-output-hk/cardano-wallet#263

Remove redundant [] in backupPhrase doc example

---

release.nix

[DEVOPS-1208] package cardano sl mingw32

---

release.nix

[DEVOPS-1223] allow hydra to cache the regen script

---

CHANGELOG.md
wallet/src/Cardano/Wallet/API/V1/Addresses.hs
wallet/src/Cardano/Wallet/API/V1/Handlers/Addresses.hs
wallet/src/Cardano/Wallet/API/V1/Swagger.hs
wallet/src/Cardano/Wallet/API/V1/Types.hs
wallet/src/Cardano/Wallet/Client.hs
wallet/src/Cardano/Wallet/Client/Http.hs
wallet/src/Cardano/Wallet/Kernel/Addresses.hs
wallet/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
wallet/src/Cardano/Wallet/Kernel/Decrypt.hs
wallet/src/Cardano/Wallet/Kernel/Wallets.hs
wallet/src/Cardano/Wallet/WalletLayer.hs
wallet/src/Cardano/Wallet/WalletLayer/Kernel.hs
wallet/src/Cardano/Wallet/WalletLayer/Kernel/Addresses.hs
wallet/test/unit/Golden/golden/api-layout.txt

Backporting input-output-hk/cardano-wallet#259 to 1.5.0

Batch Import Addresses to 1.5.0

---

appveyor.yml
nix/.stack.nix/cardano-sl-tools.nix
nix/daedalus-bridge.nix
release.nix
tools/cardano-sl-tools.cabal
tools/src/wallet-extractor/Main.hs

[DEVOPS-1195] add a tool to rearrange secrets.key

---

lib/src/Pos/Node/API.hs
lib/src/Pos/Util/Servant.hs
wallet/integration/QuickCheckSpecs.hs
wallet/src/Cardano/Wallet/API/Internal.hs
wallet/src/Cardano/Wallet/API/Types.hs
wallet/src/Cardano/Wallet/API/V1/Accounts.hs
wallet/src/Cardano/Wallet/API/V1/Addresses.hs
wallet/src/Cardano/Wallet/API/V1/Settings.hs
wallet/src/Cardano/Wallet/API/V1/Transactions.hs
wallet/src/Cardano/Wallet/API/V1/Wallets.hs

As a follow-up from the discussion in https://github.com/input-output-hk/cardano-wallet/issues/151#issuecomment-454317532, we will add a proper disclaimer in the documentation about the internal endpoints. 
input-output-hk/cardano-wallet#228

Internal Endpoints Disclaimer

---

db/src/Pos/DB/Block/Slog/Logic.hs

CBR-499: Remove duplicated SetLastSlots

---

node/src/Cardano/Node/Manager.hs

Motivated by force_ntp_check timeouts
This is the link to the wallet integration tests : https://github.com/input-output-hk/cardano-sl/blob/c14c018c815732459e8025d5c16dba3bdc186c09/cluster/src/Cardano/Cluster/Environment.hs#L388
This should affect both the wallet and the node monitoring api.
Maybe this shouldn't be merged before 1.5?
input-output-hk/cardano-wallet#279

Increase HTTPS client timeout settings

---

shell.nix

Make it easier for exchanges/developers to get correct version of jq/curl.

[DEVOPS-1231] add curl/jq to shell.nix

---

lib/configuration.yaml

[DEVOPS-1211] bump applicationVersion

---

wallet-new/src/Cardano/Wallet/API/V1/Addresses.hs
wallet-new/src/Cardano/Wallet/API/V1/Handlers/Addresses.hs
wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers/Addresses.hs
wallet-new/src/Cardano/Wallet/API/V1/Swagger.hs
wallet-new/src/Cardano/Wallet/Client.hs
wallet-new/src/Cardano/Wallet/Client/Http.hs
wallet-new/src/Cardano/Wallet/Kernel/Addresses.hs
wallet-new/src/Cardano/Wallet/WalletLayer.hs
wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Addresses.hs
wallet-new/test/Cardano/Wallet/WalletLayer/QuickCheck.hs
wallet-new/test/golden/api-layout.txt

Backport of #4069
Actually, we were sort-of ignoring it already and the endpoint was
misleading.  Cardano addresses embed their corresponding account index
inside them, therefore, when importing addresses, we only care about the
root master key (and therefore, the root id). The account ix comes from
the address anyway

Do not require an account id for importing addresses

---

docs/exchange-onboarding.md

[DEVOPS-1229] new data layer migration docs

---

nix/pkgs.nix
release.nix

[DEVOPS-1236] Add benchmarks to required jobset

---

nix/.stack.nix/cardano-sl-x509.nix
pkgs/default.nix
x509/cardano-sl-x509.cabal
x509/src/Cardano/X509/Configuration.hs
x509/test/Main.hs
x509/test/Test/Cardano/X509/Configuration.hs

i needed to turn a `TLSConfiguration` back into an aeson `Value`

[DEVOPS-1131] add ToJSON instance to TLSConfiguration

---

nix/daedalus-bridge.nix
release.nix

[DEVOPS-970] include the version in the cross-daedalus-bridge as well

---

db/src/Pos/DB/Update/Logic/Global.hs

Remove some excessively chatty debug.

db: Drop un-needed logDebug

---

CHANGELOG.md
lib/src/Pos/Node/API.hs
node/src/Cardano/Node/API.hs
wallet/src/Cardano/Wallet/Kernel/NodeStateAdaptor.hs
wallet/test/unit/Test/Spec/TxMetaScenarios.hs

Backporting #4099 to `release/3.0.0`
[[CBR-505]](https://iohk.myjetbrains.com/youtrack/issue/CBR-505)

[CBR-505] Extend LocalTimeInformation in node-info API (release/3.0.0)

---

lib/configuration.yaml

staging/testnet applicationVersion bumps

---

bors.toml
lib/configuration.yaml

Bumps staging block version to 1.0.0 to enter OBFT era

obft: bump staging block version to 1.0.0

---

explorer/frontend/yarn.lock

tar dependency needs to be updated
https://iohk.myjetbrains.com/youtrack/issue/CSE-265

[CSE-256] Updated explorer tar dependency

---

.stack-to-nix.cache
nix/.stack.nix/stylish-haskell.nix
pkgs/default.nix
stack.yaml

Closes: https://github.com/input-output-hk/cardano-sl/issues/4165

stack.yaml: Update stylish-haskell

---

CHANGELOG.md

CHANGELOG: fix missing paren

---

explorer/frontend/yarn.lock

update explorer frontend deps

---

lib/src/Pos/Diffusion/Full/Delegation.hs
lib/src/Pos/Diffusion/Full/Update.hs

The update proposals and votes, and the heavyweight delegation certificates are currently labelled as MsgTransaction for the purpose of the network routing policy.
This means we can currently submit such objects from any node and they will be forwarded to the core nodes. They are of course validated at every hop.
For the purpose of the byron/shelley transition it will be simpler if these objects are only submitted directly to the federated core nodes and not via the relays.
So this patch changes the policy so that these objects are not forwarded by the relays. It does this by changing their label so that the existing network routing policy treats them differently. So rather than being
labelled as `MsgTransaction` they are labelled as `MsgMPC`. The existing policy for the MPC label is that …

Change network policy label for the update proposals/votes and heavyweight delegation certificates

---

lib/configuration.yaml

appVersion bumps

---

default.nix

fix hydra caching

---

.gitignore
lib/configuration.yaml

applicationVersion bump: 23 -> 24

---

default.nix
nix/acceptance/default.nix
nix/scripts.nix

Adds acceptanceTests back into default.nix to fix nightly tests

acceptanceTests added back into default.nix

---

default.nix

add cardanoConfig to default.nix result

---

explorer/cardano-sl-explorer.cabal
explorer/src/Pos/Explorer/Socket/Methods.hs
explorer/src/Pos/Explorer/Txp/Global.hs
explorer/src/Pos/Explorer/Txp/Toil/Logic.hs
explorer/src/Pos/Explorer/Web/Server.hs

While debugging an issue with the explorer I came up with these minor fixes which improve readability/maintainability/debugability.
As a final test I am going to run the explorer built from this branch on mainnet.

Minor cleanup of explorer code

---

explorer/frontend/shell.nix
explorer/frontend/yarn.lock

explorer frontend yarn security vulnerability fixes

---

lib/configuration.yaml
lib/testnet-genesis.json

New genesis for testnet with existing protocol magic.

restart testnet from genesis with old protocol magic

---

lib.nix

path and hash is necessary to run cardano-node clusters.
DEVOPS-1261

Add path and hash of genesis file for each env.

---

explorer/frontend/src/Test/MockFactory.purs

fix explorer test

---

lib.nix

switch relays for testnet back from relays.new -> relays

---

CHANGELOG.md

Updates CHANGELOG PR link for nix-tools task.

changelog fix for 3.0.3

---

explorer/python-api/explorer_python_api/ExplorerDumper.py
explorer/python-api/explorer_python_api/__init__.py
explorer/python-api/explorer_python_api/db-tables.sql
explorer/python-api/explorer_python_api/db.py
explorer/python-api/explorer_python_api/pgtune.txt

Optimizations and exception handling.

Python api optimizations

---

explorer/python-api/explorer_python_api/ExplorerDumper.py

Minor fix to allow dumper to continue after failed imports
https://iohk.myjetbrains.com/youtrack/issue/CBR-530

unlock dumper on exception

---

lib/configuration.yaml

testnet applicationVersion: 1 -> 2

---

lib/configuration.yaml

bump testnet and staging application versions for update proposals

applicationVersion bumps: testnet and staging

---

lib/configuration.yaml
lib/shelley-staging-short-genesis.json

changing shelley-staging-short start time to now

---

nix/iohk-nix-src.json
nix/pkgs.nix
nix/update-iohk-nix.sh

This shrinks the linux installer for daedalus.
https://iohk.myjetbrains.com/youtrack/issue/CBR-532

enable separate data output

---

lib.nix
lib/configuration.yaml
lib/shelley-staging-short-genesis.json

Restarts shelley_staging_short from genesis. Adds pbft param to lib.nix

shelley-staging-short: restart from genesis

---

lib/configuration.yaml
lib/shelley-staging-short-genesis.json

resets shelley-staging short chain with fresh genesis

shelley_staging_short: reset chain

---

default.nix

fixes acceptance test to pass environment to the test.

fix acceptance tests usage of args

---

.buildkite/nightly.yml

Bumping the buildkite timeout to 4 hours as the jobs are taking longer and otherwise successful jobs are failing.
None.

Bumped the timeout to 4 hours

---

.buildkite/nightly.yml

nightly: only run on buildkite agents with production tag

---

CHANGELOG.md

Corrected Cardano SL 3.0.3 change category. Also added section for unreleased  changes
https://iohk.myjetbrains.com/youtrack/issue/RCD-62

RCD-62 Correct Cardano SL 3.0.3 change category

---

.buildkite/nightly.yml

Update csl-nightly buildkite job

---

CHANGELOG.md
default.nix
lib.nix
nix/iohk-nix-src.json
nix/scripts.nix

Moves environment information out of cardano-sl to iohkNix.
This allows us to modify configuration.yaml and genesis files in a central location for cardano-sl, cardano-byron-proxy, cardano-node and cardano-explorer.

move environments to iohk-nix

---

CHANGELOG.md

Release 1.7.0: define the next Cardano SL version as 3.1.0

---

CHANGELOG.md

PR #4243 does not belong to Cardano SL 3.1.0
