- src/Pos/DHT/Real/Real.hs
The closers are cleared only when the DHT is stopped. So remembering the
closer for each 'sendToNode' is a memory leak. It seems these closers
aren't necessary in practice, for when the DHT is stopped, the main
thread comes to an end and all threads will die anyway. If a set of
threads must be killed at a certain point, I recommend using a safer
abstraction like async.
> KademliaDHT: do not add closer on sendToNode

- .travis.yml
- shell.nix
- stack.yaml
1) builds the app on three different versions of OSX
- El Captain using xcode 7
- El Captain using xcode 8
- Sierra using xcode 8.2 
2) bumps default compiler to GHC 8.0.2-rc2 **when using Nix**
- this is required for some OSX problems (adds support for OSX Sierra)
- [support for using `stack --fast`](https://ghc.haskell.org/trac/ghc/ticket/12076)
- supports parallel Nix builds
- faster Nix compilation times than with GHC 8.0.1 due to `-split-sections` over `-split-objs`
- further improvements will come to 8.0.2
> travis-ci: build also OSX

- cardano-sl.cabal
- src/Pos/Util/UserSecret.hs
Before calling `BSL.readFile` we must ensure the `secret.key` file exists.
Using `Turtle.Prelude.touch` is too aggressive because it changes the existing
file's timestamp metadata and therefore acquires a write lock. However, doing
the same thing as `Turtle.Prelude.touch`, except handling pre-existing secret
files as a no-op works, regardless of whether `secret.key` exists.
> CSLA-25: Fix hanging process when reading secret.key file on Windows

- src/Pos/Binary/Merkle.hs
* serialize as a list, since the length of the list is enough
information to reconstruct the same merkle tree.
* no need to distinguish node | leaf, saving one tag
* no need to distinguish empty | tree on root, as the size of the list of 0 is enough.
> Improve Merkle tree serialization.

- cardano-sl.cabal
- src/Pos/Binary/Coin.hs
- src/Pos/Binary/Types.hs
- src/Pos/Types/Arbitrary.hs
- src/Pos/Types/Coin.hs
- src/Pos/Types/Types.hs
- test/Test/Pos/BinarySpec.hs
- test/Test/Pos/Types/TxSpec.hs
Not currently passing test due to the overflowTx
The optimisation rely on the fact that `NNNN0000` is a common value
> Coin restriction and binary serialization optimisation

- scripts/common.sh
- src/Pos/Communication/Util.hs
- src/Pos/Launcher/Param.hs
- src/Pos/Launcher/Runner.hs
- src/Pos/Ssc/Extra/Holder.hs
- src/Pos/Wallet/Launcher/Runner.hs
- src/Pos/Wallet/Web/Server/Full.hs
- src/node/Main.hs
- src/node/NodeOptions.hs
- src/smart-generator/Main.hs
- src/wallet/Main.hs
- stack.yaml
The custom network-transport, network-transport-tcp, and time-warp-ntbranches chosen in stack.yaml fix some potentially very bad problemswith bidirectional connections: a handler can hang indefinitely in casethe connection is lost to the peer before the ACK is received. Butthat's fixed now. The nt-tcp branch is also patched to deliverConnectionClosed events always, even if the connection is lost of theendpoint is brought down. This makes it easier to clean up inputchannels. The dispatcher remains defensive, though, and will plug inputchannels on end point closed and connection lost events, even though itshouldn't ever have to.
> Use EKG to monitor, custom nt, nt-tcp, tw-nt

- src/launcher/Main.hs
As explained in the commented TODO item, printing the logPath crashes cardano
when it includes unicode characters. Until a safe, reliable way is found to
print unicode from Haskell keep this commented out.
Already verified this fixes the problem using the temporary `diagnose/old-master` branch. [This installer](https://ci.appveyor.com/project/IOHK/daedalus/build/0.1.319/artifacts) includes the change from that prior test.
> [DAEF-12] Don't print logPath

- scripts/build-daedalus-bridge.sh
This PR adds `--nix` argument for building Cardano SL, introduces cleanup before the build and npm linking for the bridge.
> Update daedalus bridge build script to use nix

- src/Pos/Block/Network/Listeners.hs
- src/Pos/Block/Network/Retrieval.hs
- src/Pos/Communication/Protocol.hs
- src/Pos/Communication/Types/Protocol.hs
- src/Pos/Communication/Util.hs
- src/Pos/DHT/Model/Neighbors.hs
- src/Pos/Launcher/Runner.hs
- stack.yaml
Uses the new `time-warp-nt` feature of queueing disciplines (`QDisc`) to limit the rate at which incoming messages are queued for processing.
The interface of `time-warp-nt` changed slightly while `QDisc`s were introduced, and this Pull requests makes the changes to `cardano-sl` that are necessary to adapt to the new API. In particular, `ConversationActions` no longer has a field that gives the `PeerData`)
> [CSL-767] Use backpressure

- appveyor.yml
Appveyor shares the same cache space per-project rather than per-project-branch,
so changes in one branch can affect build results in another branch. To avoid
that, %STACK_ROOT% now includes the branch name.
Pull requests can corrupt the cache for the target branch. To prevent that the
cache isn't touched for pull request builds. This is accomplished by reassigning
%STACK_ROOT% to a different directory.
This change also temporarily disables the cache on the project's local
.stack-work directory. If these changes work as expected it should be renamed to
include the branch as well.
> [CSL-789] Partition Appveyor cache by branch

- appveyor.yml
The latest build on `cardano-sl-0.2` broke, presumably because the recent caching changes for CSL-789 caused excessively long paths.
Rather than using the branch-namespaced cache directory directly, at the beginning of the build this copies to `%STACK_ROOT%` (`C:\sr`) and at the end it copies back to the namespaced cache dir.
Additionally, pull requests shouldn't share a cache across all target branches. Instead this change gives pull requests read access to the target branch's cache, but prevents them from writing changes back to the cache.
> [CSL-789] Shorten %STACK_ROOT% path length and improve PR caching

- appveyor.yml
Now it's also branch-namespaced and therefore less susceptible to corruption.
> [CSL-789] Add .stack-cache back to Appveyor build cache

- appveyor.yml
- daedalus/package.json
- stack.yaml
Using GHC 8.0.2 with LTS-7.16 made it difficult to install some
packages (namely intero).
> Move to LTS Haskell 8.2

- cardano-sl.cabal
- src/Pos/Ssc/GodTossing.hs
- src/Pos/Ssc/GodTossing/LocalData/Logic.hs
- src/Pos/Ssc/GodTossing/Toss/Base.hs
- src/Pos/Ssc/GodTossing/Toss/Failure.hs
- test/Test/Pos/Ssc/GodTossing/ComputeSharesSpec.hs
This commit covers the 'computeSharesDistr' function with tests,
making some necessary changes to the codebase.
The contents of the
'Toss' submodule in 'Pos/Ssc/GodTossing' were not being exported,
so it was added to the re-export list in 'Pos/Ssc/GodTossing.hs'.
However, this caused conflicts with the functions 'hasOpening',
'hasCommitment' and 'hasShares' from 'Pos.Ssc.GodTossing.Functions'.
To solve this, their counterparts from 'Pos.Ssc.GodTossing.Toss.Base'
were renamed.
Not many tests are present in this commit, I'll continue adding them in the ongoing sprint.
> [CSL-728] Add tests to 'computeSharesDistr'

- src/Pos/Launcher/Runner.hs
- stack.yaml
A separate bind port patch was merged into network-transport-tcp master with
a slightly different interface than what @georgeee originally implemented. This
updates the `stack.yaml` and the `Runner` to use it.
Also bumped network-transport(-tcp) to bring in a recent fix from @kantp
> Update for network-transport changes

- cardano-sl.cabal
- core/Pos/Core.hs
- core/Pos/Core/Block.hs
- core/Pos/Core/Class.hs
- core/Pos/Core/Slotting.hs
- core/Pos/Core/Types.hs
- core/Pos/Util/Util.hs
- core/cardano-sl-core.cabal
- src/Pos/Block/Network/Retrieval.hs
- src/Pos/Block/Types.hs
- src/Pos/Types.hs
- src/Pos/Types/Block/Functions.hs
- src/Pos/Types/Block/Instances.hs
- src/Pos/Update/Logic/Global.hs
- src/Pos/Update/Logic/Local.hs
- src/Pos/Update/Poll/Logic/Apply.hs
- src/Pos/Update/Poll/Logic/Base.hs
- src/Pos/Update/Poll/Logic/Normalize.hs
- src/Pos/Util.hs
In this PR:
* Created classes `IsHeader`, `IsMainHeader` and `IsGenesisHeader`
* Removed dependency on `MainBlockHeader` in `Pos.Update.Poll.Logic.*`
The rest will be done after this PR is merged because I don't want to have to keep up with `master` endlessly.
@gromakovsky should I move `Pos.Update.Poll.Logic` to `update/` in this PR? If yes, pick a module name. (`Pos.Update.Core.Poll.Logic`?)
> [WIP] Removing dependency on headers in Pos.Update

- infra/Pos/Communication/Types/Protocol.hs
- src/Pos/Binary/Communication.hs
- test/Test/Pos/Arbitrary/Infra/Communication.hs
The problem was in two things:
1. `Arbitrary` for `UnknownHandler` was having wrong range of first byte.
2. `decodeOrFail` was used instead of `decodeFull` in `HandlerSpec` binary instance.
I've also replaced `get/putWithLength` to `get/putSmallWithLength` because it saves us 2-3 bytes per message and also length of handler won't be bigger than 2^14 (which is upper bound for "small" lists).
> [CSL-886] Fix handlerspec

- util-scripts/clean.sh
This PR improves `clean.sh` util script which should fix this issue:
```
Unable to find a suitable version for purescript-eff, please choose one by typing one of the numbers below:
1) purescript-eff#^1.0.0 which resolved to 1.0.0 and is required by purescript-console#1.0.0, purescript-eff-functions#1.0.0, purescript-exceptions#1.0.0, purescript-now#1.0.0, purescript-refs#1.0.0, purescript-st#1.0.0, purescript-var#0.2.0, purescript-websocket-simple#0.5.0
2) purescript-eff#^2.0.0 which resolved to 2.0.0 and is required by purescript-console#2.0.0, purescript-eff-functions#2.0.0, purescript-exceptions#2.0.0, purescript-now#2.0.0, purescript-refs#2.0.0, purescript-refs#2.0.0, purescript-st#2.0.0, purescript-var#1.0.0, purescript-websocket-simple#1.0.1
Prefix the choice with ! to persist it to …
```
> Improve clean util script

- stack.yaml
1. Issue in serokell-util has been fixed in 0.1.5.0.
2. wreq-0.5.0.0 is in LTS-8.5.
> Actualize stack.yaml

- daedalus/src/Daedalus/ClientApi.purs
Fixes 
`VPyMsOqAnRJoqCv40OWHfUDLRXDiTsg6WuINDxwyli8=` -> false
`HSoXEnt9X541uHvtzBpy8vKfTo1C9TkAX3wat2c6ikg=` -> true
> [CSM-122] Fix adaRedeem validation

- src/Pos/Block/Network/Logic.hs
- src/Pos/Block/Network/Retrieval.hs
This fixes a bug where nodes would enter recovery mode when receiving a new block.
> [CSL-921] Keep nodes from entering recovery mode

- infra/Pos/Util/TimeWarp.hs
- src/Pos/CLI.hs
- src/Pos/Launcher/Runner.hs
- src/node/NodeOptions.hs
- src/smart-generator/GenOptions.hs
- src/wallet/WalletOptions.hs
- stack.yaml
A node must not advertise its external address as 0.0.0.0.
First, because the host at which it is reached is assumed by time-warp
to match the host at which it claims to be reachable (the one in the
EndPointAddress).
Second, because with an upcoming patch to network-transport-tcp, any
EndPoint's reported host must match the host which its peer determines
from the TCP connection. This is a security measure, to prevent an easy
DOS attack where any node can deny service to another by claiming the
other's host.
> [TW-134] 0.0.0.0 is neither default nor valid host

- core/Pos/Binary/Class.hs
Fix for CSL-928: allow only unambigious varint decode/encode
> [CSL-928] Make UnsignedVarInt decode fail for non-normalized varints

- .travis.yml
`.travis.yml` depends on this variable, so it would help to see its value in each build.
> Travis CI: Inspect $TRAVIS_OS_NAME

- util-scripts/build.sh
* `--ram` to increase build speed on computers with lots of RAM (at least 2–3 free GBs)
* `--prod` to build in production mode
Also it probably fixes `build.sh` on macOS, but not sure.
> Add some flags to util-scripts/build.sh

- .travis.yml
- update_wallet_web_api_docs.sh
- enables macOS builds but makes them not obligatory to pass (since they do sometimes time out)
- fixes S3 upload
> [CLSA-50] Separate bridge files based on OS/branch

- core/Pos/Binary/Crypto.hs
> [CSL-951] Fix a memory leak when decoding hashes with Bi

- daedalus/src/Daedalus/ClientApi.purs
Remove constraint that base58 paper vend redeem code should be 44 chars long
@volhovM and I thought it should be 44 chars long which is wrong (we have 43 chars codes)
> [CSM-151] Fix paper vend redeem validation

- src/node/Main.hs
It will enable access to genesis funds for testing in dev mode in much simpler way than it was before.
> [CSM-197] Add genesis key to the set of spending keys in dev mode

- src/Pos/Block/Logic.hs
- src/Pos/Txp/Logic/Global.hs
- src/Pos/Txp/Settings/Global.hs
- src/Pos/Txp/Toil/Failure.hs
- src/Pos/Txp/Toil/Logic.hs
- src/Pos/Txp/Toil/Utxo/Functions.hs
- src/Pos/Types/Block/Functions.hs
There was some mess with unknown data checks. Some checks were done in `Txp`, some checks in `Pos.Types.Block.Functions`. Currently they are all done in `Txp` and are configured by a single boolean flag in `VTxContext`. They are performed if we are verifying block and our software is aware of adopted protocol version. Also they are performed when we are verifying transaction in isolation (received through relay). They are not performed if adopted version is not fully known to our software.
I have also fixed a predicate to determine whether we know protocol version. There is a big comment which explains this stuff.
Some final notes:
1. I cherry-picked a commit by @neongreen from CSL-976 branch because there are some changes which overlap with my changes and I don't want to do an unpleasant …
> [CSL-861] Sort out unknown data checks

- db/Pos/DB/GState/Balances.hs
- src/Pos/DB/GState/GState.hs
- src/Pos/Lrc/Logic.hs
- src/Pos/Lrc/Worker.hs
- src/Pos/Txp/DB/Balances.hs
- src/Pos/Txp/Toil/DBTxp.hs
Now there are two versions of functions which get balances from DB with
different names: with `effective` word in name and with `real` word in name.
Real corresponds to stake which is modified by transactions and is stored
in DB.
Effective is same is real if we are not in bootstrap era, otherwise it's taken
from predefined constants.
This commit also fixes a bug where effective stake was used is 'MonadBalances'
implementation.
> [CSL-993] Sort out work with balances (aka stakes)

- src/Pos/Wallet/Web/ClientTypes.hs
- src/Pos/Wallet/Web/Server/Methods.hs
- src/Pos/Wallet/Web/State/State.hs
- src/Pos/Wallet/Web/State/Storage.hs
Fixed - https://issues.serokell.io/issue/CSM-201
Also made `CProfile` not optional.
Before:
```haskell
data WalletStorage = WalletStorage
{
_wsWalletMetas  :: !(HashMap CAddress (CWalletMeta, TransactionHistory))
, _wsProfile      :: !(Maybe CProfile)
, _wsReadyUpdates :: [CUpdateInfo]
, _wsHistoryCache :: !(HashMap CAddress (HeaderHash, Utxo, [TxHistoryEntry]))
}
```
After:
```haskell
, _wsProfile      :: !CProfile
```
> [CSM-201] getLocale is broken after testReset

- daedalus/src/Daedalus/BackendApi.purs
- daedalus/src/Daedalus/ClientApi.purs
The bug was because new wallets (and restored wallets) weren't actually created (restored) with empty passphrases.
> [CSL-1016] Fix bug with sending transactions from newly created wallets

- cardano-sl.cabal
This PR uses `gold` linker for `cardano-sl` (should speed up build time).
Details in the answer to this question: 
http://stackoverflow.com/questions/43243322/how-to-link-with-the-gnu-gold-linker-instead-of-ld-in-haskell/43243323#43243323
> [CSL-1002] Link project with gold linker

- infra/Pos/Slotting/Ntp.hs
It doesn't make any sense to have it there.
`ntpSingleShot' waits exactly this amount of time internally.
> [CSL-1019] Remove delay after ntpSingleShot in mkNtpSlottingVar

- README.md
This commit simply adds one line into `README.md` about the fact that we're using `universum` here. According to SRK-53 this fact should be mentioned in every project that uses `universum`
> [SRK-53] Add note about default prelude

- core/Pos/Util/Util.hs
- src/Pos/Util.hs
Adds `Buildable` instance to prepare better for migration onto [`fmt`](https://github.com/aelve/fmt).
Also cleans functions a little in utility modules.
> [SRK-3] Some minor cleaning and additions in utility modules

- appveyor.yml
Since build 0.4.4258 the artifact zip hasn't included all the
assets. When paths were restructured to account for Windows' path
length limit, the artifact target path was missed.
> Fix AppVeyor artifact path

- lrc/Pos/Lrc/Fts.hs
- lrc/cardano-sl-lrc.cabal
This is a rewrite of the `followTheSatoshiM' procedure.
* Now it doesn't rely on mutual recursion, so it's easier to understand.
* It uses more appropriate types (`CoinIndex` instead of `Coin`, `LocalSlotId` instead of `Int`).
* Additionally I documented the algorithm, with an example of execution.
> [CSL-1037] Rewrite FollowTheSatoshi with StateT

- cardano-sl.cabal
- core/cardano-sl-core.cabal
- db/cardano-sl-db.cabal
- infra/cardano-sl-infra.cabal
- lrc/cardano-sl-lrc.cabal
- src/Pos/Block/Logic.hs
This commit also sets version to 0.4.3, because:
1. It's a potentially critical bugfix.
2. We already have 0.4.2 tag even though .cabal version is 0.4.3 (facepalm) which
is ridiculous but true :(
> [CSL-1057] Fix TxpUndo construction

- infra/Pos/Slotting/Ntp.hs
It significantly decreases amount of time needed for node to start operating.
> [CSL-1020] Wait for NTP responses only 1 second at the beginning

- daedalus/src/Daedalus/ClientApi.purs
Added spending passwor field as a last argument in:
* send
* sendExtend
* newWallet
* restoreWallet
* restoreWalletIgnoreChecksum
Issue: https://issues.serokell.io/issue/CSM-229
> [CSM-229] Activate spending password

- cardano-sl.cabal
- stack.yaml
Reference:
bug/csl982-mem-optimization
https://issues.serokell.io/issue/CSL-982
> Upgrade to cryptonite-0.23 (fixes 4GB alloc issue)

- src/Pos/Block/Logic.hs
- src/Pos/Block/Network/Announce.hs
- src/Pos/DB/Block.hs
- src/Pos/DB/DB.hs
- src/Pos/Delegation/Logic.hs
- src/Pos/Ssc/Extra/Logic.hs
- src/Pos/WorkMode.hs
This is an auxiliary part of https://github.com/input-output-hk/cardano-sl/pull/304 that simply migrates two functions to avoid an issue with circular imports.
Also a couple of cosmetic changes (removed redundant parentheses).
Should be merged before https://github.com/input-output-hk/cardano-sl/pull/304.
> [CSM-224] Avoid circular imports

- src/Pos/Txp/DB/Utxo.hs
Does not _need_ to be merged before https://github.com/input-output-hk/cardano-sl/pull/304, but it makes things more consistent.
> [CSM-224] Append slash to init flag & refactor

- cardano-sl.cabal
- stack.yaml
Older version doesn't work with modern openssl.
> Use cryptonite-openssl-0.6

- src/Pos/Launcher/Scenario.hs
I came across this while working on something else.
`waitForPeers` wasn't doing anything useful, just logging periodically.
> Remove waitForPeers

- src/Pos/Util/UserSecret.hs
- src/Pos/Wallet/Web/Account.hs
- src/Pos/Wallet/Web/Error.hs
- src/Pos/Wallet/Web/Server/Methods.hs
- test/Test/Pos/CryptoSpec.hs
This contains some things regarding passphrase changing feature which didn't fit into `csl931-hd-wallets` branch.
1. I assume that passphrase doesn't change wallet set address - now it's being checked in tests
2. Separated two kinds of wallet errors - internal errors and request errors (see description below). This is done because this feature is complex and may cause errors which shouldn't be show to user, ideally
> [CSM-236] Passphrase change feature complection

- infra/Pos/Communication/Relay/Class.hs
- infra/Pos/Communication/Relay/Logic.hs
- infra/Pos/Communication/Types/Protocol.hs
- infra/cardano-sl-infra.cabal
- src/Pos/Client/Txp/History.hs
- src/Pos/Explorer/Txp/Local.hs
- src/Pos/Launcher/Param.hs
- src/Pos/Ssc/GodTossing/Listeners.hs
- src/Pos/Txp/Logic/Local.hs
- src/Pos/Txp/MemState/Types.hs
- src/Pos/Txp/Network/Listeners.hs
- src/Pos/Txp/Worker.hs
- src/Pos/Update/Network/Listeners.hs
- src/Pos/Util/JsonLog.hs
- stack.yaml
When the mempool is modified to include a transaction, the provenance of that transaction is given: either from some peer (their PeerId is given) or due to the client history system.
Also included a bump of time-warp-nt to tip of master.
> Benchmarking: include transaction provenance

- .travis.yml
- cardano-sl.cabal
- src/Pos/Wallet/Web/Api.hs
- src/Pos/Wallet/Web/Error.hs
- src/Pos/Wallet/Web/Server/Methods.hs
- src/wallet-web-api-swagger/Main.hs
Allows to apply `catchWalletError` only in single place
> [CSM-260] Catch from wallet endpoints automatically

- infra/Pos/Util/TimeLimit.hs
Until now, if the node received an asynchronous exception between
the use of `async` and the use of `waitAny` + `finally` (which
called `cancel`), the cancel operation would never be run, and the
two threads would run potentially indefinitely in the background.
> [CSL-1094] Use `race` instead of `async` to avoid race condition.

- infra/Pos/Communication/Protocol.hs
- src/Pos/Block/Worker.hs
- src/Pos/Context/Functions.hs
- src/Pos/Lrc/Worker.hs
- src/Pos/Ssc/GodTossing/Workers.hs
- src/Pos/Update/Worker.hs
- src/Pos/Worker.hs
- src/node/Main.hs
* Don't run `onNewSlot` workers when node is in recovery mode
> [CSL-1042] Do not treat exceptions like UnknownBlockForLrc or OutdatedSlottingData as errors while we're in recovery

- cardano-sl.cabal
Without this fix, explorer doesn't compile due to a bug in GHC
> Disable library gold linking when build for explorer

- infra/Pos/Communication/Protocol.hs
- infra/Pos/Slotting.hs
- infra/Pos/Slotting/Class.hs
- infra/Pos/Slotting/Impl.hs
- infra/Pos/Slotting/Impl/Ntp.hs
- infra/Pos/Slotting/Impl/Simple.hs
- infra/Pos/Slotting/Impl/Sum.hs
- infra/Pos/Slotting/Impl/Util.hs
- infra/cardano-sl-infra.cabal
- src/Pos/Context/Context.hs
- src/Pos/Launcher/Launcher.hs
- src/Pos/Launcher/Runner.hs
- src/Pos/Launcher/Scenario.hs
- src/Pos/Wallet/Web/Server/Full/Common.hs
- src/Pos/Wallet/Web/Server/Full/R.hs
- src/Pos/WorkMode.hs
- src/Pos/WorkMode/Class.hs
- src/Pos/Worker.hs
- src/node/Main.hs
- src/smart-generator/Main.hs
Previously we had slotting implementation based on `ReaderT (Bool, NtpSlottingVar)`. It was bad for two reasons:
• `(Bool, NtpSlottingVar) doesn't make sense, it should be `Maybe NtpSlottingVar` or something equivalent.
• We couldn't use simple slotting separately. But we want to use it in tests.
Also it was strange to see simple slotting in NTP module.
In order to fix it I've chosen approach similar to `Discovery` implementations. So we have different transformers and we have a wrapper which stores sum of all contexts and chooses the appropriate one. Also I removed workers from type class, because otherwise I wouldn't be able to get all workers without monadic context and because workers require much more constraints. There is a function which chooses appropriate workers based on …
> [CSL-1105] Split slotting implementations akin to Discovery

- src/Pos/Launcher/Resource.hs
During refactoring I accidentally put logging initialization into two places.
> [CSL-775] Fix double initialization of logging

- src/Pos/Block/Logic/Internal.hs
- src/Pos/Client/Txp/History.hs
- src/Pos/Explorer/Txp/Local.hs
- txp/Pos/Txp/Logic/Local.hs
- txp/Pos/Txp/MemState/Class.hs
- txp/cardano-sl-txp.cabal
Backported from `feature/csl-971-build-simpler-benchmark`, but uses bracket instead of calling takeMVar/putMVar directly to be more robust.
I'd use MonadMask (since it's used in other places), but unfortunately there is also usage of ExceptT, and these two are incompatible.
> [CSL-1201] Guard the state modifying STM action with a mutex

- src/Pos/Wallet/Web/Server/Methods.hs
Issue here https://issues.serokell.io/issue/CSM-303
Details:
Previous implementation would take second parameter as spending password to unlock `importWallet`.
New implementation will use second parameter as spending password to setup while using `importWallet`.
Examples:
```
importWallet(path, "bla") // this will set up importedWallet from path and set "bla" as its spending password
importWallet(path, null) // this will set up importedWallet from path and set null (no-password) as its spending password
```
This implements last requirement from Daedalus UI team list https://github.com/input-output-hk/daedalus/pull/326 :
> Add spending password on import from a key wallet screen 
and it changes `importWallet` requirements for this PR https://github.com/input-output-hk/daedalus/pull/329
> Change importWallet implementation 

- .travis.yml
The OSX CI was made obligatory by the commit 13e2771c6bb3a41989657603ac676e73bdcdc182 named WIP. I don't know the reason but several PRs can't be merged because OSX CI is broken.
> [CSL-1231] Bring back optional macos travis

- src/Pos/Wallet/Web/Server/Methods.hs
- stack.yaml
New version of `cardano-crypto`, where bug with password changing has been fixed, is used.
Cumbersome workaround with copying the wallet is removed as redundant.
Testing via CLI in dev mode has shown that CSM-314 has been fixed by this too, but more profound testing with Daedalus is planned.
> [CSM-317] Fix changing password

- src/Pos/Block/Worker.hs
* Full leader list is shown once per epoch with INFO
* Every other slot s we show [s-10..s+10] window of leaders with DEBUG verbosity
> [CSL-1239] Show full leaders list only once

- scripts/build/daedalus-bridge.sh
`npm link` generally requires root privileges to install things under `/usr/lib/`.
Installing in a system-wide location is not always desirable, and the documentation does not mention the need of `sudo`. Furthermore, the docs describe `npm link` as a separate step entirely. Hence I believe it is better to remove it from the build script.
> Remove `npm link` from daedalus-bridge build script

- scripts/launch/demo-with-wallet-api.sh
Apparently, the file `demo-without-wallet-api.sh` was renamed to just `demo.sh`. This PR updates the `demo-with-wallet-api.sh` script with that change.
> Fix launch script

- core/Pos/Core/Genesis/Types.hs
Old version was invalid. One of 'Monoid' rules is that
`mempty <> a == a`.
> [CSL-1288] Fix 'instance Monoid StakeDistribution'

- src/Pos/Wallet/Web/Account.hs
- src/Pos/Wallet/Web/Server/Methods.hs
- src/Pos/Wallet/Web/State/Storage.hs
- src/Pos/Wallet/Web/Tracking.hs
Wallet itself has been created deterministically from backup phrase, but underlying account and addresses were for some reason generated using random seed, which is completely wrong. This PR fixes it.
> [CSM-328] Wallet restore is not working

- src/Pos/Lrc/DB/Richmen.hs
It was using 'GenesisUtxo' to determine richmen. I have no idea how it could
work. I fixed it to use `GenesisStakes' instead.
> [CSL-1285] Fix 'prepareLrcRichmen'

- core/Pos/Core/Timestamp.hs
- infra/Pos/Slotting/Util.hs
- src/Pos/Client/Txp/History.hs
- src/Pos/Wallet/Web/Server/Methods.hs
- src/Pos/Wallet/Web/State/Storage.hs
Initialise the transaction history metadata for a particular wallet, if it didn't exist previously.
> [CSM-148] All transactions have the same date and time

- src/Pos/Block/Logic/Header.hs
- src/Pos/Block/Network/Announce.hs
This fixes were needed to make cluster with `slot: 15s, k: 5000, recoveryMessageHeaders: 10000` to work.
Issue was that cluster node first responded with it's tip `T`, wallet requested block range from 0th epoch genesis to `T`, node (due to bug) responded in turn not with only `T`, but with also `T'` -- new tip, which appeared in meanwhile. Wallet received chain with `T'` and was rejecting it because it requested chain up to `T`, not `T'` and also is not in recovery mode.
> [CSL-1258] Fix block header communication

- core/Pos/Core/Timestamp.hs
- infra/Pos/Slotting/Util.hs
- src/Pos/Client/Txp/History.hs
When it cannot be precisely determined from the blockchain. The extrapolation will be accurate as long as the slot duration doesn't change.
> [CSM-335] Extrapolate transaction timestamp

- cardano-sl.cabal
- src/Pos/Block/Network/Listeners.hs
- src/Pos/Block/Network/Logic.hs
- src/Pos/Block/Network/Retrieval.hs
- src/Pos/Block/RetrievalQueue.hs
- src/Pos/Context/Context.hs
To be honest, I couldn't reproduce the issue in the exact way it was reported. In particular, I didn't get the "Header c3f52eb6 potentially represents good alternative chain, requesting more headers" message at all, and "Action Recv from NodeId 34.249.78.18:3000:0 in conversation took more than 4s" were not grouped.
Furthermore, I see errors like this in the log: "Error in conversation to NodeId 192.169.1.38:3001:0: NoParse".
Anyway, I don't know whether this is something wrong with the code or my testing setup. I've implemented the changes as discussed with @georgeee, but I'm hoping someone else could verify that they help (and don't break anything).
> [CSL-1295] Request missing headers in a worker

- src/Pos/Wallet/Web/State/Storage.hs
Make `getWallets` endpoint sort wallets by creation order (oldest first)
> [CSM-338] Sort wallets on order of creation on fetch from db

- godtossing/Pos/Ssc/GodTossing/Workers.hs
- infra/Pos/DHT/Workers.hs
- infra/Pos/Recovery/Info.hs
- src/Pos/Block/Worker.hs
- src/Pos/Lrc/Worker.hs
- src/Pos/Update/Worker.hs
- src/Pos/Worker.hs
- src/node/Main.hs
Previously 'recoveryCommGuard' was totally misused in «on new slot workers».
Specifically, it was checking whether we are doing recovery only once: before
the worker is actually launched. But we want to do it for each tick of the
worker.
> [CSL-1298] Fix misused 'recoveryCommGuard'

- infra/Pos/Communication/Relay/Logic.hs
Bug was really stupid: code was written as copypaste of invReq listener, however it makes no sense for mempool. We didn't return anything (and ogic was that we simply close connection), but instead of closing we just waited for next `MempoolMsg`
> [CSL-1312] Fix tx mempool (0.5-rc)

- scripts/build/daedalus-bridge.sh
Now we can pass an argument to `scripts/build/daedalus-bridge.sh`, and this argument will be passed to internal script `scripts/build/cardano-sl.sh` as build mode.
> [CSL-1321] Improve scripts/build/daedalus-bridge.sh.

- update/Pos/Update/Poll/Logic/Base.hs
There we check that proposed script version is greater than the adopted one by
one.
That was our initial understanding, but recently George Agapov told us that
it's also legal to have the same script version as the adopted one.
> [CSL-1326] Fix 'verifyNextBVMod'

- src/Pos/Wallet/Web/Server/Methods.hs
Because we got rid of initial blockchain traversal for new wallets, it happened on first `getHistory` call. Now empty history cache is initialized on new wallet creation
> [CSM-348] Initialize empty history cache for new wallet

- src/Pos/Client/Txp/History.hs
This error is most likely emerged because transactions from mempool weren't topsorted before history derivation. This is fixed here
> [CSL-1331] No input addresses in tx

- src/Pos/Wallet/Web/Server/Methods.hs
- src/Pos/Wallet/Web/State/Acidic.hs
- src/Pos/Wallet/Web/State/State.hs
- src/Pos/Wallet/Web/State/Storage.hs
When wallet is deleted, wallet history metadata and cache are not. This causes bugs when wallet is deleted and restored/imported again. This PR fixes it.
> [CSM-353] Remove history cache when deleting wallet

- src/Pos/Block/Logic/Creation.hs
- src/Pos/Explorer/Txp/Local.hs
- src/Pos/Launcher/Runner.hs
- src/Pos/Wallet/Web/Server/Full/Common.hs
- src/Pos/Web/Server.hs
- src/Pos/WorkMode.hs
- txp/Pos/Txp/Logic/Local.hs
- txp/Pos/Txp/MemState/Class.hs
- txp/Pos/Txp/MemState/Metrics.hs
- txp/Pos/Txp/MemState/Types.hs
- txp/cardano-sl-txp.cabal
Ports the following:
- 3c5f59b4037ee71ce168279c94e50223ca30175c
- 25c83d7b09935fd5194ed37bf93cf0b4c721c81c
- 9cad0c00bebba638002e8cbe59ab29356b4d8195
For the record, subsequent related patches (I think):
- 7db4653736e759f5bcd0c5be357c7e67a6736553
- da6250fc87cc5d731a99050e4efe9069c4fd6579
- 72d219b2e3f7590a92e23b52494964946b5465e0
- b549bd139c35f6ebf2658e02047317322da84f22
But these deal with JSON logging and trying to incorporate these currently leads to circular dependency (as json logging is in cardano-sl, cardano-sl depends on cardano-sl-txp, but cardano-sl-txp also wants to log).
> Port more EKG stuff

- src/Pos/Explorer/BListener.hs
https://issues.serokell.io/issue/CSE-162
Fixing paging, since now the first page has 9 rows and the rest have 10. It's not a huge issue, but still something that can be fixed.
How it should work:
```
Blocks 1 - 10 - Page 1
Blocks 11 - 20 - Page 2
Blocks 21 - 30 - Page 3
...
```
GHCI:
```
Prelude> ((0 - 1) `div` 10) + 1
0
Prelude> ((1 - 1) `div` 10) + 1
1
Prelude> ((2 - 1) `div` 10) + 1
1
Prelude> ((10 - 1) `div` 10) + 1
1
Prelude> ((11 - 1) `div` 10) + 1
2
Prelude> ((20 - 1) `div` 10) + 1
2
Prelude> ((21 - 1) `div` 10) + 1
3
Prelude> ((11 - 1) `div` 10) + 1
2
Prelude> ((20 - 1) `div` 10) + 1
2
Prelude> ((21 - 1) `div` 10) + 1
3
Prelude> ((30 - 1) `div` 10) + 1
3
Prelude> ((31 - 1) `div` 10) + 1
4
Prelude> ((0 - 1) `div` 10) + 1
0
Prelude> ((1 - 1) `div` 10) + 1
1
Prelude> ((10 - 1) `div` …
```
> CSE-162 Explorer slow blocks, fix (first page) paging.

- scripts/generate/certificates.sh
- launchable by Nix to provide correct dependencies
- automate postvend-app building (should probably be moved to the post-vend-app so we would just call `make`)
- other smaller changes for readability
- shellcheck only complains about unknown shebang
> [DEVOPS-100] Automate redemption certificate generation

- src/Pos/Explorer/BListener.hs
- txp/Pos/Txp/MemState/Class.hs
https://issues.serokell.io/issue/CSE-178
Now the order is correct.
> CSE-178 Reverse DB block order.

- core/Pos/Core/Arbitrary.hs
- core/Pos/Core/Genesis.hs
- core/Pos/Core/Genesis/Types.hs
- src/Pos/Genesis.hs
- src/Pos/Wallet/Web/Server/Methods.hs
- tools/cardano-sl-tools.cabal
- tools/src/keygen/KeygenOptions.hs
- tools/src/keygen/Main.hs
Now you can pass a list of addresses that will be stakeholders instead of just taking testnet/rich. 
I also did some changes related to future stakes weight integration, see CSL-1351.
> CSL-1315 Support explicit boot stakeholders in keygen

- core/Pos/Util/Util.hs
- db/Pos/DB/Class.hs
- src/Pos/Client/Txp/History.hs
- src/Pos/Client/Txp/Util.hs
- src/Pos/Communication/Tx.hs
- src/Pos/Wallet/Web/Error/Util.hs
- src/Pos/Wallet/Web/Server/Methods.hs
- src/Pos/Wallet/Web/Util.hs
- stack.yaml
- txp/Pos/Txp/Toil/Failure.hs
Sending transactions weren't working due to changes in txp processing related to bootstrap era logic. This is solved by explicitly stating that there's no bootstrap era in dev mode. Also error handling in `Pos.Communication.Tx` and related is rewritten to simplify things and avoid ignoring txp verification errors on API level.
In addition, in this PR LTS version of purescript-bridge is used (CSM-322). Didn't make another PR because it's minor change and it's unnecessary to run CI separately for that.
> [CSM-359] Fix not working sending tx + CSM-322 Check whether we can use purescript-bridge from LTS 

- src/Pos/Aeson/Types.hs
Fixes https://issues.serokell.io/issue/CSM-362 . This introduces breaking change for UI as it has to take into account another Object nesting:
* before `getChainDifficulty: 2`
* now `getChainDifficulty: { getBlockCount: 2 } `
```
> api.syncProgress().then(console.log)
Promise {
<pending>,
domain: 
Domain {
domain: null,
_events: { error: [Function: debugDomainError] },
_eventsCount: 1,
_maxListeners: undefined,
members: [] } }
> { _spPeers: 0,
_spNetworkCD: { getChainDifficulty: { getBlockCount: 2 } },
_spLocalCD: { getChainDifficulty: { getBlockCount: 2 } } }
```
cc @darko-mijic
> [CSM-362] Sync progress changed datatype - fix api

- src/Pos/DB/Block.hs
- test/Test/Pos/Block/Logic/Mode.hs
Subj. Now pure db is used in block test mode. 
Another way would be to modify `InitContextMode`, but i tried it and it didn't work out.
> [CSL-1317] Integrate pure db into tests

- test/Test/Pos/Block/Logic/VarSpec.hs
Later we will use it smarter. For now I just want it to be used somehow to protect us from some very stupid errors (e. g. broken genesis).
> [CSL-1379] Enable block generation in tests

- lwallet/Command.hs
- lwallet/Main.hs
- lwallet/cardano-sl-lwallet.cabal
We'll want to use the transaction generator in the light wallet for
performance and stress-tests.
> Port transaction generator to master

- godtossing/Pos/Ssc/GodTossing/GState.hs
- godtossing/Pos/Ssc/GodTossing/LocalData/Logic.hs
- godtossing/Pos/Ssc/GodTossing/Toss/Base.hs
- godtossing/Pos/Ssc/GodTossing/Toss/Class.hs
- godtossing/Pos/Ssc/GodTossing/Toss/Logic.hs
- godtossing/Pos/Ssc/GodTossing/Toss/Pure.hs
- godtossing/Pos/Ssc/GodTossing/Toss/Trans.hs
- godtossing/Pos/Ssc/GodTossing/Workers.hs
- godtossing/cardano-sl-godtossing.cabal
- ssc/Pos/Ssc/Class/LocalData.hs
- ssc/Pos/Ssc/Class/Storage.hs
- ssc/Pos/Ssc/Extra/Logic.hs
- ssc/Pos/Ssc/NistBeacon.hs
- test/Test/Pos/Ssc/GodTossing/ComputeSharesSpec.hs
- test/Test/Pos/Ssc/GodTossing/Toss/BaseSpec.hs
- test/Test/Pos/Ssc/GodTossing/VssCertDataSpec.hs
- update/Pos/Update/Poll/Logic/Apply.hs
- update/Pos/Update/Poll/Logic/Normalize.hs
There were three places overall where genesis constants were used wrongly.
The first commit deals with two places in `update`. The first commit is small and easy.
The second commit deals with `computeSharesDistr`. The second commit is fat and introduces a new monad class and a new newtype. I don't like `computeSharesDistr`.
---
Questions:
1. Is it okay that `generateAndSetNewSecret` uses block version data for current slot and not the slot it was passed?
2. I used `MonadGState` instead of `MonadDBRead` in some places because I wasn't sure about adding an `cardano-sl-update` dependency for `cardano-sl-ssc`. I can change that if needed.
3. I use `getAdoptedBVData` from `MonadPollRead` in the first commit, but `gsAdoptedBVData` from `MonadGState` in the second commit. Since I don't …
> [CSL-1281] Use constants from database, not genesis constants

- .travis.yml
A few hours ago we started seeing the following error in Travis
builds:
cat: /etc/nix/nix.conf: No such file or directory
In some cases the file exists, but not always. This change bypasses
the issue.
The dependency on /etc/nix/nix.conf was introduced ~15 days ago for
Hydra.
cc @cleverca22
> Attempt to fix Travis-on-nix builds

- src/Pos/Wallet/Web/Server/Methods.hs
- src/Pos/Wallet/Web/Tracking.hs
There were two problems:
1) Couldn't import wallets, if some of them were already present - fixed by checking every wallet for existense
2) Wallet was imported with 0 ADA - fixed by starting a wallet sync after metadata initialization, not before (which was incorrect)
> [CSM-363, CSM-364] Fix bugs in JSON import/export 

- stack.yaml
This one has a fix to prependLength which checks for overflow. It's in
mainline master but we use a fork.
> [TW-154] bump network-transport revision

- appveyor.yml
Explicitly installs and uses OpenSSL 1.0.2l rather than using the version installed by AppVeyor. Prompted by AppVeyor recently upgrading to OpenSSL 1.1.0f which isn't backwards compatible.
> [DEVOPS-210] AppVeyor: Use OpenSSL 1.0.2L

- godtossing/Pos/Ssc/GodTossing/GState.hs
- godtossing/Pos/Ssc/GodTossing/LocalData/Logic.hs
- godtossing/Pos/Ssc/GodTossing/Seed.hs
- godtossing/Pos/Ssc/GodTossing/Toss/Base.hs
- godtossing/Pos/Ssc/GodTossing/Toss/Class.hs
- godtossing/Pos/Ssc/GodTossing/Toss/Pure.hs
- godtossing/Pos/Ssc/GodTossing/Workers.hs
- lrc/Pos/Lrc/Arbitrary.hs
- lrc/Pos/Lrc/Consumer.hs
- lrc/Pos/Lrc/Core.hs
- lrc/Pos/Lrc/Types.hs
- src/Pos/Delegation/Logic/Mempool.hs
- src/Pos/Delegation/Logic/VAR.hs
- src/Pos/Lrc/DB/Richmen.hs
- src/Pos/Lrc/Logic.hs
- ssc/Pos/Ssc/Class/LocalData.hs
- ssc/Pos/Ssc/Class/Storage.hs
- ssc/Pos/Ssc/Extra/Logic.hs
- ssc/Pos/Ssc/RichmenComponent.hs
- test/Test/Pos/Ssc/GodTossing/ComputeSharesSpec.hs
- test/Test/Pos/Ssc/GodTossing/Toss/BaseSpec.hs
1. Old 'Richmen' type was bad. It assumed that there is always at least
one richman, but I don't think we can rely on it. Even if we could, it would
be better to throw error in 'MonadThrow' rather than use 'error'. Also
you almost always need to do lookup, so list is not good.
2. 'RichmenStake' was renamed to 'RichmenStakes' because it makes more sense.
> [CSL-1408] Rework LRC types

- appveyor.yml
Following work on CSL-781 the AppVeyor artifact zip no longer included `cardano-node.exe`. This change builds it and confirms that it and the other exe files will be archived in the `CardanoSL.zip` artifact.
> [DEVOPS-217] AppVeyor: build and package cardano-node.exe

- src/Pos/Wallet/Web/Account.hs
- src/Pos/Wallet/Web/Server/Methods.hs
- src/Pos/Wallet/Web/State/Acidic.hs
- src/Pos/Wallet/Web/State/State.hs
- src/Pos/Wallet/Web/State/Storage.hs
- src/Pos/Wallet/Web/Tracking.hs
- src/Pos/Wallet/Web/Util.hs
This allows not to recalculate mempool accounts modifier (which is somewhat expensive) many times for given request, but rather fixate it once and pass implicitly around
> [CSM-324] Call `txMempoolToModifier` once per api request

- appveyor.yml
We need to temporarily disable `Block.Logic.Var` tests in appveyor because they are very slow, it leads to timeouts, we can't merge new PRs and the proper solution is not easy.
> [CSL-1435] Disable VarSpec in appveyor

- src/Pos/Wallet/Web/ClientTypes.hs
- src/Pos/Wallet/Web/Server/Methods.hs
This is crucial fix since it fixes CSM-392 as well
> [CSM-352] Rewrite `mkCTxs` without `isRedemptionTx` flag

- core/Pos/Core/Types.hs
- src/Pos/Client/Txp/Balances.hs
- src/Pos/Wallet/Web/Server/Methods.hs
Testing results:
* Money sending on pubkey addresses still works
* Money sending to random redeem addresses generated in ghci fails
* Same thing for txFee endpoint
> [CSM-391] Throw error on sending money to redeem address

- .gitignore
- scripts/haskell/dependencies.sh
Hi all,
I have been working on a script to complement the information `stack dot` produces under the form of a Graphviz graph (which @domenkozar already showed me). This script enumerates all the dependencies in cardano (by piggybacking on `stack list-dependencies --test --bench` and also tracks the direct & indirect dependencies (mostly relying on `ghc-pkg field`). It finally produces a table like this (which we can customise later):
I have deliberately filtered the cardano-* project family from the reverse dep list (thus some packages has a 0 in the `rev deps` section) so actually focus a bit better (in the future it's easy to add an option like `--exclude-cardano` and by default show everything). The game would be to start from the top (the table is sorted by number of direct deps) and …
> Handy script to analyse the project dependencies

- core/Pos/Binary/Class/Core.hs
- core/cardano-sl-core.cabal
- stack.yaml
- test/Test/Pos/CborSpec.hs
Fix for decoding of (Hash)Maps and (Hash)Sets that would allow different encodings to deserialize to the same object.
> Make (Hash)Map and (Hash)Set decoding stricter

- src/Pos/SafeCopy.hs
- stack.yaml
This commit adds some serialization instances for the 'Byte' type.
They were removed from 'serokell-util' because the 'cereal' dependency
(among others) has been removed.
> [CSL-1453] Add 'Serialize/SafeCopy' instances for 'Byte'

- src/Pos/Client/Txp/History.hs
- src/Pos/Wallet/Web/BListener.hs
- src/Pos/Wallet/Web/Tracking.hs
This PR is to display most of the logs produced by wallet tracker, in order to facilitate further debugging with user-provided logs.
It also adds some missing info.
> [CSM-400] Display logs of wallet tracker

- src/Pos/Util/JsonLog.hs
It used to be derived in time-warp-nt, but was removed along with the
dependency on ether.
> derive CanJsonLog (TaggedTrans tag t m) instance

- stack.yaml
#1116 used a feature branch, but we just brought that into master.
It's not tip of master, as tip of master has breaking changes [CSL-849]
> Use master time-warp-nt revision

- core/Pos/Binary/Crypto.hs
- core/Pos/Crypto/SafeSigning.hs
- src/Pos/Wallet/Web/ClientTypes.hs
The initial idea was to get rid of `instance Bi PassPhrase` altogether and move its code into `FromCType` / `ToCType`. However, this instance is used in several other places. In all of these cases the only reason for why `Bi PassPhrase` is needed is that `hash` is called on passphrases, and internally `hash` calls `serialize'`. So, in fact, only `encode` is ever used. However, I don't know how to get rid of `instance Bi PassPhrase` without splitting `Bi` into `encode` and `decode` and changing the constraint on the current `hash` function to only require `encode` to be implemented.
There is some (albeit small) code duplication. I was thinking whether it could be extracted and put into separate functions, but I'm not sure where I could put it. An obvious candidate is `Pos.Binary.Crypto`, …
> [CSM-401] Fix wallet password deserialization

- lwallet/cardano-sl-lwallet.cabal
- tools/cardano-sl-tools.cabal
This is a low-hanging fruit I've spotted. We don't seem to be using `lifted-async` anymore, but yet its dep was lurking in the manifests of `cardano-sl-lwallet` and `cardano-sl-tools`. I've tried to manually build those projects with:
```
stack build cardano-sl-tools
stack build cardano-sl-lwallet
```
as well as grepping for `Lifted`, but it looks like we should be OK.
> [CSL-1453] Drop unused lifted-async dep

- core/Pos/Binary/Core/Address.hs
This PR fixes [CSL-1447](https://issues.serokell.io/issue/CSL-1447) by restoring the CRC check inside the `decode` function in the `Bi Address` instance.
The only thing I had to watch out was to avoid the infinite loop which I've explained in the comment. I learnt the hard way why the pilgrim fathers of Cardano originally separated the `Address` encoding in the [previous serialisation revision](https://github.com/input-output-hk/cardano-sl/blob/1a345036d95647aa7ea00d182013ee822995e577/core/Pos/Binary/Core/Address.hs#L48) 😂  😂
> [CSL-1447] Restore CRC for Address serialisation

- core/Pos/Binary/Class/Core.hs
- core/Pos/Binary/Class/Primitive.hs
- core/Pos/Binary/Core/Block.hs
- core/Pos/Binary/Core/Script.hs
- core/Pos/Binary/Crypto.hs
- infra/Pos/Binary/Infra/Relay.hs
- infra/Pos/Communication/BiP.hs
- lwallet/Command.hs
- src/Pos/Binary/Block/Core.hs
- src/Pos/Util/BackupPhrase.hs
This PR brings back some functionality of the old `Bi` implementation, which is the possibility of "annotate" deserialisation failures via a `label` which would pinpoint the type we tried to decode back from the network.
This PR is mostly complete although we might need to improve what we have currently by adding even more precise error reporting exploiting the newly-added `label`. So far, there is already improvement. This is an example, real-world failure which is now more informative:
Before:
```
*** Exception: Failed to read genesis: DeserialiseFailure 2554 "expected list len"
```
After:
```
*** Exception: Failed to read genesis: decodeFull failed for GenesisCoreData: DeserialiseFailure 2554 "expected list len"
```
The PR, in brief, works by adding a `Typeable` constraint to `Bi`, so …
> [CSL-1445] Restore "label" in Bi decoding

- src/Pos/Wallet/Web/Account.hs
- src/Pos/Wallet/Web/BListener.hs
- src/Pos/Wallet/Web/Backup.hs
- src/Pos/Wallet/Web/Server/Methods.hs
Redundant legacy of strange `changeWalletPassphrase` endpoint
> [CSM-319] Remove searches both by id and passphrase in sk storage

- cardano-sl.cabal
- infra/Pos/Reporting/Methods.hs
- infra/cardano-sl-infra.cabal
- tools/cardano-sl-tools.cabal
It turned out to be quite easy to do, as we were using `wreq` in just one module. I have then run my `dependencies.sh` script to indeed prove `wreq` is now gone:
```
☁  iohk  cat deps_master.txt | grep wreq | wc -l
0
```
> [CSL-1453] Drop wreq from the stack

- stack.yaml
See https://issues.serokell.io/issue/CSL-1478 for context.
As `cborg` has been officially released on the 1st of August and such release includes the work @arybczak committed in the previously-used revision (commit SHA: `a1770a6ab0a6f457fe56269fb684a9f8dad0da17`) we might just as well use a proper Hackage release.
> [CSL-1478] Switch to use upstream revision of cborg

- scripts/common-functions.sh
- src/Pos/CLI.hs
- src/Pos/Launcher/Param.hs
- src/node/NodeOptions.hs
- src/node/Params.hs
They're all deprecated in favour of the kademlia yaml configuration
(specified by the --kademlia option)
> Remove unused DHT-related NodeOptions

- src/Pos/Launcher/Param.hs
- src/Pos/Launcher/Resource.hs
- src/node/NodeOptions.hs
- src/node/Params.hs
This can be used to delay initialization of the node until a certain
time (but after the node has initialized its network interface, so that
other nodes can connect to it).
This is useful to avoid the network layer deciding that it cannot reach
other nodes (because they have not yet finished booting up) and putting
them on in failure mode, and subsequently refusing to send messages to
them for a while.
> Add `--init-delay` command line arg

- scripts/bench/runbench.sh
- scripts/launch/demo-with-wallet-api.sh
- scripts/launch/demo.sh
Distribution is still `rich-poor` when running benchmark scripts.
> Make flat stake distribution default in dev mode

- cardano-sl.cabal
- core/Pos/Util/Chrono.hs
- db/Pos/DB/Pure.hs
- src/Pos/Generator/BlockEvent.hs
- src/Pos/Generator/BlockEvent/DSL.hs
- test/Test/Pos/Block/Logic/Event.hs
- test/Test/Pos/Block/Logic/Mode.hs
- test/Test/Pos/Block/Logic/VarSpec.hs
This PR introduces the tree-based block event generator and a DSL for using it, making it possible to model forks.
Features include:
* Snapshot management (manual and semi-automatic)
* Building the blockchain tree from paths
* Generator of diverse apply/rollback sequences with forks
* Pretty-printing block event sequences with paths or block hashes
* Reasonably efficient implementation that takes advantage of laziness
* <s>Superb path naming scheme: `kek/rekt/mems`.</s>
> [CSL-1417] Modify block event type

- src/Pos/Launcher/Param.hs
- src/Pos/Launcher/Resource.hs
- src/node/NodeOptions.hs
- src/node/Params.hs
Reverts input-output-hk/cardano-sl#1318
After discussing this with @georgeee , it seems the `--system-start` command flag already satisfies this purpose; see https://github.com/input-output-hk/cardano-sl/blob/master/src/Pos/Launcher/Scenario.hs#L93 .
Pinging @dcoutts .
> Revert "Add `--init-delay` command line arg"

- infra/Pos/Network/Types.hs
- src/Pos/Launcher/Scenario.hs
- src/Pos/Worker.hs
When joining the kademlia network, failing to contact any listed peers is not fatal for relay nodes (it *is* fatal for p2p nodes).
TODO: the kademlia configuration must accept host names, but resolve them before using them.
> [DEVOPS-246] fixes for kademlia on relay nodes

- core/Pos/Core/Genesis.hs
- src/Pos/Client/Txp/Util.hs
- src/Pos/Generator/Block/Payload.hs
- src/Pos/Genesis.hs
- txp/Pos/Txp/Toil/Failure.hs
- txp/Pos/Txp/Toil/Logic.hs
* `genesisSplitCoin` doesn't fail when asked to split coin less then `bootDustThd`
* Transaction outputs wth value less then `bootDustThd` are now considered valid.
> [CSL-1458] Allow txs with outputs less then bootDustThd

- infra/Pos/Network/CLI.hs
- infra/Pos/Network/Policy.hs
- infra/Pos/Network/Types.hs
- infra/Pos/Subscription/Dht.hs
- infra/Pos/Subscription/Dns.hs
- infra/cardano-sl-infra.cabal
- pkgs/default.nix
- stack.yaml
The Peers datatype has changed along with the interface for updating a
bucket. Now static routing variants core/relay get the directory of all
known peers, even those to which they do not route traffic, and keep it
so that they can classify those peers, which *may* send traffic inbound.
Other noise in this pull request is the migration of policies from
tiem-warp-nt to here in Pos.Network.Policy
> [CSL-1505] update for time-warp change

- infra/Pos/Network/Policy.hs
- run/policy_core.yaml
- run/policy_edge_exchange.yaml
- run/policy_edge_nat.yaml
- run/policy_edge_p2p.yaml
- run/policy_relay.yaml
This PR sets the max-ahead for requests for blocks to be one higher than the request for block headers, because the request for blocks will happen concurrently with the request for blocks during recovery.
Note that for nodes where the max-ahead for the request for block headers is 1 (because there is some other higher priority messsage that may be ahead of it), I've set the max-ahead for blocks to 2 (to allow for that higher priority message _and_ the request for block headers).
> Fix policy so we can exit recovery mode

- src/Pos/Client/Txp/Util.hs
- src/Pos/Generator/Block/Payload.hs
- wallet/src/Pos/Wallet/Web/Methods/Payment.hs
This fixes possible bug when output distributions change after fee is computed, which change transaction size and may possibly invalidate computed fee.
Tested manually via `daedalus-bridge` (acceptance tests in master are not working currently due to not yet merged fix for webpack issue)
> [CSM-411] Override distributions in boot era before counting fees

- docs/network-policy.md
- infra/Pos/Network/Policy.hs
- infra/Pos/Network/Yaml.hs
- node/src/Pos/Block/Network/Logic.hs
- node/src/Pos/Block/Network/Retrieval.hs
- pkgs/default.nix
- run/policy_core.yaml
- run/policy_edge_nat.yaml
- run/policy_edge_p2p.yaml
- run/policy_relay.yaml
- stack.yaml
Use a ~~(currently non-master)~~ time-warp-nt revision which includes a fix in the outbound queue, and a change to the `MsgRequestBlockHeaders` constructor. When requesting headers for an alternate chain in the block retrieval worker, use the `MsgRequestBlockHeaders` constructor, because that's in fact what the conversation does.
> [TW-161] MsgRequestBlockHeaders parameter

- scripts/ci/update-cardano-sl-readme.sh
@gromakovsky said:
> The thing is that `README.md` was moved into `node` directory, while root of the repository now contains a symlink to that file. I guess it shouldn't matter, but I don't know in which cases something that work with a normal file doesn't work with a symlink to that file
> [CSLD-125] Correct script for README.md generation

- node/src/Pos/Generator/BlockEvent.hs
Only a marginal improvement, but an improvement nonetheless.
Things that were prominent during profiling but not anymore:
* comparisons of `Text` (due to unnecessary rebuilding of `Map`s)
* cryptography (due to unnecessary TX payload generation)
> [CSL-1525] Optimize BlockEvent generator

- core/Pos/Arbitrary/Core.hs
- core/Pos/Binary/Core/Genesis.hs
- core/Pos/Core/Genesis/Types.hs
- explorer/src/explorer/Params.hs
- lwallet/Main.hs
- node/src/Pos/Client/CLI/Options.hs
- node/src/Pos/Client/CLI/Params.hs
- node/src/Pos/Genesis.hs
- scripts/bench/runbench.sh
- scripts/launch/demo.sh
- tools/src/block-gen/Main.hs
- wallet/node/Params.hs
Now boot stakeholders generation (for dev/tests/bench) matches on real distribution. Which in turn gives possibility to set `genesisStakeholders` to rich in `richPoor` distribution. Before this, implementation gave stake to everybody thus producing huge stakeholders weights and `bootDustThd` which led to a bunch of problems.
I also removed support for bitcoin distribution as it's not used by anyone and can be emulated by `CustomStakes`.
> [CSL-1502] Match on stake distr in generateWStakeholders

- core/Pos/Core/Timestamp.hs
- src/Pos/Wallet/Web/Server/Methods.hs
- src/Pos/Wallet/Web/Tracking.hs
In tracking, when get transactions from new block, in general we have no idea about order of those transactions. Only wallet db may know that, since it stores tx timestamps - I use them to achieve correct order.
_I didn't run DAT because they work unevenly (_
> [CSM-405] Sort transactions on timestamp if known

- infra/Pos/Network/Types.hs
Noticed that when the static routes were mis-configured and nodes did not know about each other, they were falling back to presuming unknown peers were edge nodes, and so were failing to ask for blocks from each other.
The correct policy for fallback in these cases is relay.
> Adjust the fallback node types to match the policy.

- node/src/Pos/Block/Network/Logic.hs
- node/src/Pos/Block/Network/Retrieval.hs
It was always assumed that the application was in control of who would
be contacted, but since TW-148 and the outbound queue, enqueueing a
message doesn't mean it will actually go through. The retrieval worker
is updated to handle those cases.
> Eliminate retrieval deadlock if no peers available

- explorer/src/explorer/Params.hs
- infra/Pos/Communication/Types/Protocol.hs
- infra/Pos/DHT/Real/Param.hs
- infra/Pos/DHT/Real/Real.hs
- infra/Pos/Network/CLI.hs
- infra/Pos/Network/Yaml.hs
- node/src/Pos/Client/CLI/NodeOptions.hs
- node/src/Pos/Client/CLI/Params.hs
- node/src/Pos/Launcher/Resource.hs
- scripts/bench/buildbench.sh
- scripts/common-functions.sh
- wallet/node/Params.hs
If a `--listen` or `--address` command-line argument is given, but the node is in behind-nat mode and therefore won't use these parameters, an exception is thrown.
If a topology file giving a static routing table is given, but no `--kademlia` flag is present, then a sensible default kademlia configuration is derived from the topology: every node which runs kademlia is included as an initial peer, and the bind address is chosen to be `0.0.0.0` on the default port.
~~This has broken the demo script because `--address` and `--listen` are always passed. Will fix this.~~
> Infer kademlia configuration from static topology; warn about unnecessary net address

- pkgs/default.nix
Due to a cabal file revision in hackage, stack2nix output was invalidated. Builds on master will fail until this is updated.
> Update nix expression output by stack2nix

- appveyor.yml
They were temporarily disabled when they were kinda broken. Now they should be ok.
> Enable disabled tests in appveyor

- infra/Pos/Network/Policy.hs
- pkgs/default.nix
- stack.yaml
This is to use time-warp-nt at https://github.com/serokell/time-warp-nt/pull/96
CI on that pull request keeps timing out. Will go to a master revision as soon as that's sorted.
> [CSL-1549] policy update, time-warp-nt revision bump

- infra/Pos/Network/CLI.hs
- infra/Pos/Network/DnsDomains.hs
- infra/Pos/Network/Yaml.hs
See here for the full context: https://issues.serokell.io/issue/CSL-1540
With the new code, now trying to use a hostname instead of an IP address in the `addr` field would result in:
Conversely, trying to use an IP address in the `host` field...
> [CSL-1540] Make Topology Yaml parser less lenient

- default.nix
- scripts/ci/travis.sh
- remove filterSource2 as it's not needed anymore
- compile cardano-node and cardano-launcher statically
- check that executables are self contained and pass --help
> [DEVOPS-278] Fix daedalus bridge generation

- infra/Pos/Network/Policy.hs
We were observing errors in the logs of the form
Rejected alternative as it has 0 messages ahead and 1 messages in
flight, which total more than the maximum 0` for
`MsgAnnounceBlockHeader`, from core to relay.
This is due to the fact that block requests and header announcements had the same precedence. So this change bumps the precedence of header announcements up to highest.
We originally had them at different levels because we want to start sending headers to other core nodes before sending them to relay nodes but this is not a big deal since they can all happen concurrently and there is a low limit on concurrency.
> Tweak network policy slightly for MsgAnnounceBlockHeader

- core/Pos/Util/Concurrent/LockedTVar.hs
- core/cardano-sl-core.cabal
- node/src/Pos/Block/Slog/Logic.hs
- update/Pos/Update/Logic/Global.hs
This PR does two things:
1. It introduces `LockedTVar` type which can be used to synchronize in-memory data and data stored in DB. For more context this issue description and CSL-1560. However, it's currently not used, because I decided to leave its usages for CSL-1560 and because it's not really necessary for CSL-1529.
2. It moves slotting data update from Slog to Update and changes the way it's done. I left a comment which explains why desynchronization of in-memory data and data from DB is ok. Apart from desynchronization problem (which would be substantial if we updated memory state after updating DB), it solves two other problems:
• previously data was read from DB and put into memory state before it was written to DB. It somehow worked because we apply genesis block separately and …
> CSL-1529  Change the way data is updated in SlottingVar 

- appveyor.yml
This follows best practices[1] on making `stack setup` stop killing everyone's machines on Appveyor.
-- 
1. https://github.com/commercialhaskell/stack/blob/master/appveyor.yml#L20
> appveyor:  try to reduce noise

- core/constants.yaml
- minimal fees are set to zero, since otherwise the transactions from
the generator will be invalid (they are balanced)
- increased k to 6 -- with k=2, it was too easy to go into recovery
mode, or to end up with an unacceptable chain quality end stop the
system.
> Fix benchmark constants

- core/Pos/System/Metrics/Constants.hs
- core/cardano-sl-core.cabal
- infra/Pos/Network/Types.hs
- node/cardano-sl.cabal
- node/src/Pos/Launcher/Runner.hs
- node/src/Pos/Util/Monitor.hs
- pkgs/default.nix
- stack.yaml
- txp/Pos/Txp/MemState/Metrics.hs
This PR correctly namespace IOHK's metrics by the "cardano" namespace, for which I have added a smart "constructor" inside a new module called `Pos.System.Metrics.Constants` within `core`.
Note this PR is not complete as we need to modify `timewarp-nt` so that `registerQueueMetrics` can take an optional namespace (will do this in parallel):
https://github.com/serokell/time-warp-nt/blob/40f4235cda65c746c6edc2a3455242d96d7175bf/src/Network/Broadcast/OutboundQueue.hs#L607
Last but not least, now the time-based queues are parametrised by their unit of measures, microseconds in `txp` case. (maybe one of the devops like @deepfire or @domenkozar  could tell us if `statsd` will choke if non-ASCII chars are passed to it). This is the result so far:
> [CSL-1585] Namespace cardano EKG metrics

- release.nix
- scripts/ci/travis.sh
- platform is now an attribute suffix
- explorer and report server are now built only for linux
> [DEVOPS-302] release.nix: simplify and allow setting the platform

- node/test/Test/Pos/Network/Windows/DnsDomainsSpec.hs
@ksaric has found a way to avoid warnings on non-Windows platforms without
suppressing them. So I think we should suppress it anymore.
> Unsuppress warning in DnsDomainsSpec

- core/Pos/Util/Concurrent/PriorityLock.hs
- node/src/Pos/Delegation/Class.hs
- node/src/Pos/Delegation/Listeners.hs
- node/src/Pos/Delegation/Logic/Common.hs
- node/src/Pos/Delegation/Logic/Mempool.hs
- node/src/Pos/Delegation/Logic/VAR.hs
- txp/Pos/StateLock.hs
This uses newly introduced global `StateLock` instead of old (dlg-specific) synchronization mechanism.
> [CSL-1559] Refactor locking in delegation

- explorer/src/Pos/Explorer/Socket/Methods.hs
- explorer/src/Pos/Explorer/Socket/Util.hs
- godtossing/Pos/Ssc/GodTossing/Toss/Trans.hs
- infra/Pos/Communication/Relay/Logic.hs
- infra/Pos/DHT/Real/Real.hs
- infra/Pos/Reporting/Methods.hs
- infra/Pos/Slotting/Util.hs
- infra/cardano-sl-infra.cabal
- node/src/Pos/Block/Logic/Creation.hs
- node/src/Pos/Block/Logic/Internal.hs
- node/src/Pos/Block/Logic/VAR.hs
- node/src/Pos/Block/Network/Retrieval.hs
- node/src/Pos/Client/Txp/Util.hs
- node/src/Pos/Delegation/Worker.hs
- node/src/Pos/Generator/Block/Mode.hs
- node/src/Pos/Security/Workers.hs
- node/test/Test/Pos/Block/Logic/Event.hs
- pkgs/default.nix
- stack.yaml
- tools/src/keygen/Main.hs
- wallet/src/Pos/Wallet/Web/Sockets/Notifier.hs
- wallet/src/Pos/Wallet/Web/Tracking/BListener.hs
The idea behind `reportingFatal` is that we want to catch some types of exceptions every time they happen and send to report server. I did few changes:
1. I removed `reportingFatal` from functions like block creation which don't have any forking or exception handling inside and aren't special at all with respect to thread management and exception handling. Having this logic there isn't useful at all, it doesn't help us to achieve the main goal: catch fatal errors everywhere.
2. After (1) all usages of `reportingFatal` started having the following pattern:
```
reportingFatal action `catchAll` handler
```
So we have a handler inside `reportingFatal` which rethrows an exception and this exception is then caught by `handler` (which catches everything).
I find it more reasonable to have one …
> [CSL-1579] Revise 'reportingFatal'

- pkgs/default.nix
- stack.yaml
This PR simply uses the latest revision of `timewarp-nt` so we can benefit from https://github.com/serokell/time-warp-nt/pull/98
> [TW-162] Use latest revision of timewarp-nt

- .travis.yml
- default.nix
- explorer/src/explorer/Main.hs
- node/src/Pos/Constants.hs
- node/src/Pos/Update/Download.hs
- node/src/Pos/Update/Worker.hs
- node/src/node/Main.hs
- update/Pos/Update/Constants.hs
- update/Pos/Update/Context.hs
- update/Pos/Update/DB.hs
- wallet/src/Pos/Wallet/Redirect.hs
1. Previously 'checkForUpdate' was downloading all new updates for our
application one-by-one. It was useless because we only need to the latest one.
It's also useless because after we download one update, we won't download
anymore until the application is restarted.
Now 'checkForUpdate' downloads only the newest update.
2. It's no longer possible to download multiple updates concurrently.
Previously it was possible, but it didn't make any sense. After one
download is started, another one will not start at all (if the first one
has already created a file) or will do some stuff and fail slightly later
(again, due to check that the file with an update doesn't exist) or in the
case there will be a race condition between two downloads with unpredictable
results.
3. If we have already …
> [CSL-1592] First step towards reworking software update downloading

- core/Pos/Util/Concurrent.hs
These functions are bad, because they don't take asynchronous exceptions
into account. Read carefully and you'll see it.
Also they are not used at all.
If someone wants these functions, it's usually better to use STM instead.
> [CSL-619] Delete broken 'MVar' functions

- explorer/cardano-sl-explorer.cabal
- explorer/src/documentation/Main.hs
- explorer/src/mock/Main.hs
- pkgs/default.nix
https://issues.serokell.io/issue/CSE-210
Fixed as @denisshevchenko proposed.
Tested with:
`cardano-explorer-swagger`:
```
$ stack exec -- cardano-explorer-swagger -h    
Cardano SL Explorer web API docs generator.
Usage: cardano-explorer-swagger [--version]
Generate Swagger specification for Explorer web API.
Available options:
-h,--help                Show this help text
--version                Show version.
This program runs during 'cardano-sl' building on Travis CI. Generated file
'explorer-web-api-swagger.json' will be used to produce HTML documentation. This
documentation will be published at cardanodocs.com using
'update-explorer-web-api-docs.sh'.
$ stack exec -- cardano-explorer-swagger --version
cardano-swagger-0.2.0
```
`cardano-explorer-mock`:
```
$ stack exec -- …
```
> CSE-210 Add help info to executable(s).

- godtossing/Pos/Ssc/GodTossing/Workers.hs
- node/src/Pos/Block/Logic/Creation.hs
- node/src/Pos/Block/Logic/VAR.hs
Nobody will run it for us, we should do it by ourselves.
I also removed redundant 'waitLrc' in one place.
'lrcActionOnEpochReason' does 'waitLrc' internally.
We don't need to catch 'UnknownBlocksForLrc' because 'shouldCreate'
guarantees it.
> [CSL-1618] Run LRC before creating genesis block

- explorer/src/explorer/ExplorerOptions.hs
- explorer/src/explorer/Params.hs
- infra/Pos/DHT/Real/Param.hs
- infra/Pos/Network/CLI.hs
- infra/Pos/Network/DnsDomains.hs
- infra/Pos/Network/Policy.hs
- infra/Pos/Network/Types.hs
- infra/Pos/Network/Windows/DnsDomains.hs
- infra/Pos/Network/Yaml.hs
- lwallet/Pos/Wallet/Light/Launcher/Runner.hs
- node/src/Pos/Client/CLI/NodeOptions.hs
- node/src/Pos/Client/CLI/Options.hs
- node/src/Pos/Client/CLI/Params.hs
- node/src/Pos/Launcher/Param.hs
- node/src/Pos/Launcher/Resource.hs
- scripts/common-functions.sh
- scripts/launch/explorer.sh
- wallet/node/Params.hs
* Moved `tcpAddr` to `NetworkConfig`.
* Removed `TransportConfig` as it was holding `tcpAddr` only.
* Changed binding CLI logic:
* Bind address is unchanged
* External address is taken from cli or taken as bind address if absent (no need to specify same address twice explicitly)
* If kademlia external address is not equal to CLI external address, exception is thrown
* Removed a bunch of useless parameters in explorer.
* Formatted `Pos.Network` according to the style guide.
> [CSL-1598] Fix kademlia/topology/address/listener CLI mess

- wallet/src/Pos/Wallet/Web/Methods/Payment.hs
Valid errors while calculating transaction fees (like `NotEnoughMoney`) weren't properly processed in `getTxFee` endpoint. This PR fixes it
> [CSM-448] Rewrap errors during tx fee calculating

- infra/Pos/StateLock.hs
- node/src/Pos/Launcher/Resource.hs
- node/src/Pos/Launcher/Scenario.hs
`StateLock` is now filled in `newStateLock`, not in `initSemaphore`, so it' properly initialized in auxx.
> [CSL-1637] Initialize StateLock in creation

- core/Pos/Binary/Class/Primitive.hs
- core/Pos/Binary/Core/Address.hs
- pkgs/default.nix
This PR correctly computes & store CRC for the `Address` type, as well as adding the usual "tag 24" encoding to `AddrSpendingData`.
Reviewed and mostly live-coded with @dcoutts 
Ps. small rant, I really liked having one single file (which was `CborSpec`) to be able to thoroughly test out the serialisation layer without running `stack test` in full (`ghci` worked wonderfully). Hehe. /endOfRant.
> [CSL-1568] Improve Address serialisation

- core/Pos/Aeson/Genesis.hs
- core/Pos/Arbitrary/Core.hs
- core/Pos/Core/Address.hs
- core/Pos/Core/Genesis.hs
- core/Pos/Core/Genesis/Canonical.hs
- core/Pos/Core/Genesis/Types.hs
- core/Pos/Crypto/RedeemSigning.hs
- core/cardano-sl-core.cabal
- node/cardano-sl.cabal
- node/test/Test/Pos/Genesis/CanonicalSpec.hs
- node/test/Test/Pos/Util.hs
- stack.yaml
I added ToJSON and FromJSON instances for GenesisData (and all subtypes).
There is a test for their correctness.
They all have been written manually. Format should be reasonable, but maybe someone will tell me something should be changed there. For now I was focused only on implementing correct instances, not necessary the most reasonable.
I think this PR should be open until CSL-1617 is finished.
> [CSL-1647] Add canonical JSON instances for GenesisData

- core/Pos/Core/Constants/Raw.hs
- core/constants.yaml
- godtossing/Pos/Ssc/GodTossing/LocalData/Logic.hs
- node/src/Pos/Delegation/Logic/Mempool.hs
- txp/Pos/Txp/MemState/Metrics.hs
- txp/Pos/Txp/Toil/Class.hs
- txp/Pos/Txp/Toil/Failure.hs
- txp/Pos/Txp/Toil/Logic.hs
- txp/Pos/Txp/Toil/Trans.hs
- txp/Pos/Txp/Toil/Types.hs
- update/Pos/Update/Logic/Local.hs
It's what's relevant for processing time, and directly limiting the
number of transactions in the mempool is more predictable.  Also, this
removes a lot of unnecessary work serialising transactions over and
over again to get their serialised size.
Set the limit of transactions in the mempool to 200.  This ensures
fast block application, while still allowing transaction rates of up
to 10 Hz.  We will want to relax this bound in the future, but for
Byron I suggest erring on the side of caution.
The Godtossing and Deletion pools were also limited to the size of the
transaction mempool, which seems rather arbitrary. I've set the limit
to the block limit.  We might want to revisit the limits on those
pools at some point.
> [CSL-1662] Define mempool limit in terms of number of transactions

- infra/Pos/Network/Policy.hs
- increase the MaxAhead for messages to 200, to match the current
mempool size
- set the rate limiting towards core nodes to 3 Hz
These settings led to a decent throughput of ~6 transactions per
second, while keeping the core network running stably even when the
relays were exposed to higher transaction rates.
> [CSL-1672] Set relay networking policy

- core/Pos/Core/Constants/Raw.hs
- core/Pos/Util/Util.hs
- core/cardano-sl-core.cabal
- core/constants.yaml
- node/src/Pos/Util/BackupPhrase.hs
- node/src/Pos/Util/Servant.hs
- node/src/Pos/Wallet/Web/ClientTypes/Instances.hs
- node/src/Pos/Wallet/Web/ClientTypes/Types.hs
- node/src/Pos/Web/Server.hs
- pkgs/default.nix
- wallet/cardano-sl-wallet.cabal
- wallet/src/Pos/Wallet/Web/Api.hs
- wallet/src/Pos/Wallet/Web/Swagger/Description.hs
This PR enables manually written logging of incoming requests and responses based on servant-api. Please note that it's _really_ eassential to have in mainnet, it allows to understand user's operations flow, and testnet experience showed that we hardly benefit from user logs without requests logged if that user has problem on middleware.
Key points:
* `Buildable` instances are used for logging, and `instance Buildable` for all sensitive info (passwords and mnemonics) masks the content
* Now request bodies and responses are also logged. Responses are truncated where possible to save logging space
* Raw logging of http requests (which is/will be disabled in another PR) is totally removed
Testing:
* Daedalus acceptance tests pass in dev mode, which means that endpoints required for the …
> [CSM-451] Safe servant logging

- core/Pos/Binary/Crypto.hs
- core/Pos/Crypto/HD.hs
- core/Pos/Crypto/SafeSigning.hs
- core/Pos/Crypto/Scrypt.hs
- core/cardano-sl-core.cabal
- node/test/Test/Pos/CryptoSpec.hs
- pkgs/default.nix
- wallet/src/Pos/Wallet/Web/Methods/Logic.hs
We need to keep a hash of password in secret key to check whether password matches.
This PR switches from `blake256` hashing to `scrypt` with [secure-] randomly generated salt.
> [CSL-969] Use `scrypt` for passphrases hashing

- daedalus/src/Daedalus/BackendApi.purs
- daedalus/src/Daedalus/ClientApi.purs
- pkgs/default.nix
- wallet/src/Pos/Wallet/Web/Api.hs
- wallet/src/Pos/Wallet/Web/Methods/Misc.hs
- wallet/src/Pos/Wallet/Web/Server/Handlers.hs
- wallet/src/Pos/Wallet/Web/Swagger/Description.hs
This endpoint should be triggered when postponing the update until restart to avoid stale data about update remaining in `wallet-db` (which causes update notifications to appear again after restart, even though update has been already applied).
> [CSM-458] Endpoint for postponing the update

- core/Pos/Core/Configuration.hs
- core/Pos/Core/Configuration/Core.hs
- core/Pos/Core/Configuration/GenesisHash.hs
- core/Pos/Core/Constants.hs
- node/configuration.mainnet.yaml
Previously it was hardcoded as 'genesisDataDigest', but it wasn't convenient
for some people. Now this hash is taken from configuration file if 'genesis'
is specified as 'src', not as 'spec'.
For format see changes in 'configuration.mainnet.yaml' file.
> [CSL-1678] Make genesis hash part of configuration

- auxx/src/Command/Run.hs
- auxx/src/Command/Tx.hs
- pkgs/default.nix
- tools/src/launcher/Main.hs
Now it doesn't need configuration to process command line options, so
one can use `--help` without configuration.
I tried to eliminate this constraint further, but it's needed for 'sendReport'
function and then I stopped.
> [CSL-1681] Make cardano-launcher depend on configuration not so much

- node/src/Pos/Client/CLI/Options.hs
- tools/cardano-sl-tools.cabal
- tools/src/launcher/Main.hs
Now cardano-launcher has options to set configuration path and key.
It also passes their values to node, unless they are explicitly specified
with '-n'.
> [CSL-1683] Add configuration options to launcher, propagate to node

- node/src/Pos/Wallet/Web/ClientTypes/Functions.hs
- node/src/Pos/Wallet/Web/ClientTypes/Instances.hs
- node/src/Pos/Wallet/Web/ClientTypes/Types.hs
- wallet/src/Pos/Wallet/Web/Methods/History.hs
Displays coins attached to inputs and outputs of transaction.
Tested
* with postman on A -> A and foreign transactions, and with case when multiple transactions send money to same address, when whole this address is depleted (inputs should be displayed merged).
* daedalus-bridge works
New format of `CTx` is the following
> [CSM-463] Expose tx inputs and outputs with according amounts

- node/src/Pos/Block/Logic/Header.hs
- node/src/Pos/Block/Logic/VAR.hs
- node/src/Pos/Block/Network/Logic.hs
- node/src/Pos/Block/Network/Retrieval.hs
- node/src/Pos/Block/Pure.hs
- node/src/Pos/Block/Slog/Logic.hs
- node/src/Pos/Delegation/Cede/Class.hs
- node/src/Pos/Delegation/Cede/Holders.hs
- node/src/Pos/Delegation/Cede/Logic.hs
- node/src/Pos/Delegation/Cede/Types.hs
- node/src/Pos/Delegation/Logic/Mempool.hs
- node/src/Pos/Delegation/Logic/VAR.hs
- node/test/Test/Pos/Types/BlockSpec.hs
Pre-story. Say you have headers `[h1,h2]` (`h2` is more difficult than `h1`) and you want to verify their signatures. Let `h1` be signed with `BlockSignature`: we match stakeholder id with related field in the header and check signature. And we're done. Then assume that `h2` is signed with `BlockPSignatureHeavy`, and `d` has the right to issue block according to `psk`. But then also assume that `psk` got into blockchain in block having header `h1`. So it is literally impossible to verify block signature of more than one header at once given using current delegation scheme.
What this PR does is:
* Delegation logic got abstracted (added some methods to `Cede`, removed duplicated code).
* As a result, found one missing check in the old mempool checker.
* `classifyNewHeader` now checks proxy …
> [CSL-1152] verifyHeaders check more predicates

- core/Pos/Util/Util.hs
- node/src/Pos/Explorer/Core/Types.hs
- node/src/Pos/Explorer/DB.hs
- node/src/Pos/Explorer/Txp/Global.hs
- node/src/Pos/Explorer/Txp/Local.hs
- node/src/Pos/Explorer/Txp/Toil/Class.hs
- node/src/Pos/Explorer/Txp/Toil/Logic.hs
- node/src/Pos/Explorer/Txp/Toil/Types.hs
Track current utxo sum in the Explorer DB.
Note that utxo sum is stored as `Integer` and not `Coin` because we want it to provide correct data even in the unlikely case where someone manages to create utxo out of thin air and thus utxo sum overflows `maxBound :: Coin`.
> [CSE-208] Track utxo sum

- core/Pos/Aeson/Core.hs
- core/Pos/Core/Configuration/Core.hs
- pkgs/default.nix
Before Configuration refactoring this value was treated as seconds, but it
was broken during the refactoring.
It solves (1) and (2) from CSL-1687. I have no idea why overall chain quality is 0 there. Most likely that's just another consequence of this misconfiguration. I couldn't reproduce it locally. I can try to understand it if I have logs, but probably it's not useful to do it, it's better to check whether this fix helps (it most likely does) first.
> [CSL-1687] Treat fixedTimeCQ value as seconds

- node/src/Pos/Client/Txp/Util.hs
Cause of the CSM-464 bug: `txFee` endpoint formed a transaction identical to one formed by calling `newPayment` endpoint, but then it calculated _minimal allowed fee_ for given transaction size. But in edge cases (like sending almost all money a user have) minimal possible transaction fee is not equal to minimal allowed transaction fee for given transaction size.
This PR changes how `txFee` endpoint calculates fee: now returned value is calculated by definition, as difference between total input amount and total output amount.
> [CSM-464] Fix inconsistent fee calculation

- pkgs/default.nix
- wallet/src/Pos/Wallet/Redirect.hs
Now we do not try to return any exact network difficulty if last header is
unknown.
Previous logic was unsafe, because under some curcimstances it may
return network difficulty as known and equal to local difficulty at the very
start of the node (before `knownLeader` gets initialized) and client would
suggest the node to be synced.
Tested: in dev mode with daedalus.
At first `networkDifficulty=null` (even if it's not the first launch of the node but with `NO_REBUILD` set) and daedalus patiently waits till sync
> [CSM-469] Fix sync logic

- pkgs/default.nix
- stack.yaml
This PR updates time-warp-nt to its latest revision, which comes with 2 useful improvements:
* The fix to `removePeer`
* It drops the node name from the namespace, to make the metric more predictable.
> [CSL-1702] Update to latest time-warp-nt

- pkgs/default.nix
- stack.yaml
This PR bumps `log-warper` to 1.2.2 in order to benefit from the memory leak fix @avieth found & fixed.
> [CSL-1708] Update to latest version of log-warper to fix leaks

- explorer/src/Pos/Explorer/Web/Server.hs
- explorer/test/Test/Pos/Explorer/Web/ClientTypesSpec.hs
https://issues.serokell.io/issue/CSE-231
So we need to merge another change suggested/found by @Pastafarianist  which allows RSCoin addresses to be used too - now we can use only Cardano addresses. My bad.
This PR contains the changes we need - https://github.com/input-output-hk/cardano-sl/pull/1644
It's almost identical to the one we merged but retains the checks for 32-byte addresses *in case of RSCoin addresses*.
So:
- RSCoin address == 32 bytes 
- Cardano address >= 34 bytes
@Pastafarianist comments - AFAIU base58 can be decoded as base64 as long as it has as many characters that `[num of characters]*6 % 8 == 0`.
@gromakovsky commented - Address contains: one hash (28 bytes), a tag (1 byte), attributes (it seems to me that attributes can take only 1 byte).
So it seems to me address …
> [CSE-231] 'Address does not exist' error for existing addresses.

- core/Pos/Core/Configuration/Core.hs
- godtossing/Pos/Ssc/GodTossing/LocalData/Logic.hs
- node/configuration.yaml
- node/src/Pos/Delegation/Logic/Mempool.hs
- txp/Pos/Txp/MemState/Metrics.hs
- txp/Pos/Txp/Toil/Class.hs
- txp/Pos/Txp/Toil/Failure.hs
- txp/Pos/Txp/Toil/Logic.hs
- txp/Pos/Txp/Toil/Trans.hs
- txp/Pos/Txp/Toil/Types.hs
- update/Pos/Update/Logic/Local.hs
This cherry-picks the implementation of CSL-1662 (limit the mempool to 200 transactions) to the `cardano-sl-1.0` branch.
> Cherrypick csl 1662

- infra/Pos/Network/DnsDomains.hs
- infra/Pos/Network/Types.hs
- infra/Pos/Subscription/Dns.hs
- node/src/Pos/Worker.hs
Previously there were unused valency and fallbacks parameters, and the
worker would choose a relay according not to the structure of the list
given in the topology yaml file, but according to recent failures,
time of discovery, and in one common case, to the lexicographic ordering
of its resolved address.
This patch makes the dynamic-subscribe work like static-routes: it's a
conjunction of disjunctions, implicitly giving the valency and number of
fallbacks. The worker will attempt to subscribe to one peer from each of
the conjuncts (outer list) concurrently. If/when all of the disjuncts in
that list have failed (subscription attempted/broken) it will delay
according to the current slot duration before resolving all of the names
and trying again.
Each thread will update the outbound …
> [CSL-1700] rework DNS subscription worker

- auxx/src/Command/Tx.hs
- infra/Pos/Recovery/Info.hs
- node/configuration.yaml
- node/src/Pos/Block/Logic/Creation.hs
- node/src/Pos/Block/Logic/Util.hs
- node/src/Pos/Block/Worker.hs
- node/src/Pos/Recovery/Instance.hs
- node/src/Pos/Worker.hs
- scripts/bench/runbench.sh
- scripts/launch/auxx.sh
- txp/Pos/Txp/Core/Tx.hs
The task was to test block-gen and rollback tools.
Results can be found in comments to CSL-1710.
During the testing I found some bad things and fixed them. The most important fix is topological sort in `send-from-file` command.
It's probably better to review this PR per commit, all of them are rather small and self-contained.
> CSL-1710 Test block-gen and rollback tools

- explorer/frontend/src/Explorer/Update.purs
- explorer/frontend/src/Explorer/Util/Time.Test.purs
- explorer/frontend/src/Explorer/View/Blocks.purs
- explorer/frontend/src/Explorer/View/Transaction.purs
- explorer/frontend/src/Explorer/View/blocks.css
- explorer/src/Pos/Explorer/Web/Server.hs
These changes are temporary until `CSE-236` will be fixed: https://issues.serokell.io/issue/CSE-236
Note: Because `scripts/launch/explorer-with-nodes.sh` does not work with branch `cardano-sl-1.0` locally I had have to test UI changes with mock server. And without a running `scripts/launch/explorer-with-nodes.sh` I could not test disabled endpoint of `api/search/epoch/{n}`.  
PS.: This PR includes a cherry pick of 2caa8f2652be81e6d38f8150967a9cba26f2f57a to have all front-end tests green :green_apple:
> [CSE-236] Disable epoch search

- node/src/Pos/Wallet/Web/Util.hs
- wallet/src/Pos/Wallet/Web/Tracking/Modifier.hs
- wallet/src/Pos/Wallet/Web/Tracking/Sync.hs
On block applying txs are sorted before being added to tx history.
On rollback we expect transactions to be removed from history in opposite
order, so transactions of rollbacked block should be sorted as well to
allow us properly drain them from the top of current history.
Tested with artificially made rollback, only after this fix error stops to be thrown
> [CSM-475] Sort transaction history to remove on tracked rollback

- node/configuration.yaml
- node/src/Pos/Configuration.hs
- node/src/Pos/Launcher/Runner.hs
Optional `conversationEstablishTimeout` key in the node section of configuration. Default is 30 seconds. It's in milliseconds like the network connection timeout.
Really this belongs in the infra configuration, and so does the network connection timeout, but I kept the two in the same area rather than doing that refactor.
> [CSL-1713] time-warp ack timeout configurable

- core/Pos/Crypto/Hashing.hs
- godtossing/Pos/Ssc/GodTossing/Workers.hs
- infra/Pos/DHT/Real/Real.hs
- infra/Pos/Util/LogSafe.hs
- node/src/Pos/Block/Logic/Creation.hs
- node/src/Pos/Util/Servant.hs
- wallet/src/Pos/Wallet/Web/Methods/Backup.hs
- wallet/src/Pos/Wallet/Web/Methods/History.hs
- wallet/src/Pos/Wallet/Web/Methods/Payment.hs
- wallet/src/Pos/Wallet/Web/Pending/Submission.hs
- wallet/src/Pos/Wallet/Web/Pending/Worker.hs
- wallet/src/Pos/Wallet/Web/Tracking/BListener.hs
- wallet/src/Pos/Wallet/Web/Tracking/Sync.hs
We don't print the following messages to the public logs anymore:
1. Logs about creating a block by ourselves
2. Our DHT-key
3. CHash of addresses in wallet tracking
4. Servant's logs
5. Resubmitter's logs
6. Wallet's history logs
7. GodTossing logs
> [CSL-1655] Ensure public logs contain no sensitive data

- node/src/Pos/Wallet/Web/ClientTypes/Instances.hs
... till the day we allow unicode symbols in logging library.
I assume that there is no need to hide redeeming seed because if user passes invalid key with unicode chars endpoint will just throw a strange error
> [CSM-477] Hide wallet/account names from logs

- wallet/src/Pos/Wallet/Web/Methods/History.hs
It occurred that tx history fetching time linearly depends on number of addresses.
Measurements:
Before
3000 transactions + 5 addresses -> 7 sec
3000 transactions + 1000 addresses -> 40 sec
Now
3000 transactions + 5 addresses -> 7 sec
3000 transactions + 1000 addresses -> 12 sec
Current estimated duration for bittrex is 32 sec.
As it was noticed, there is a space for optimizing related request to database, but for now it doesn't play significant role. We will perform this work in master
> [CSM-485] Fasten tx history endpoint

- scripts/set_nixpath.sh
applying #1707 to the `cardano-sl-1.0` branch as well
> temporary workaround for jq bug on darwin

- node/src/Pos/Wallet/Web/State/Acidic.hs
- node/src/Pos/Wallet/Web/State/State.hs
- node/src/Pos/Wallet/Web/State/Storage.hs
- scripts/launch/connect-to-cluster/mainnet-exchange.sh
- scripts/launch/demo.sh
- wallet/node/Main.hs
- wallet/node/NodeOptions.hs
- wallet/src/Pos/Wallet/Web/Tracking/Sync.hs
1) This provides a mechanism for restoring corrupted history and UTXO cache from blockchain
2) A fix which prevents error leading to db corruption from arising is introduced
Wallet flush and restore is tested on environment with 1000 addresses and 1000 transisactions. `getAccounts` and `getHistory` endpoints return identical data before and after flush & restore.
_Should be tested via simulated rollback_
> [CSL-1738] Wallet rollback fix

- node/src/Pos/Wallet/Web/State/Acidic.hs
- node/src/Pos/Wallet/Web/State/State.hs
- node/src/Pos/Wallet/Web/State/Storage.hs
- wallet/src/Pos/Wallet/Web/Methods/History.hs
- wallet/src/Pos/Wallet/Web/Methods/Logic.hs
- wallet/src/Pos/Wallet/Web/Methods/Payment.hs
- wallet/src/Pos/Wallet/Web/Methods/Redeem.hs
- wallet/src/Pos/Wallet/Web/Tracking/Sync.hs
Call `addHistoryTx` only for mempool transactions, it should reduce number of writing to db, also do it as one acidic transaction. To save correctness we also set `CTxMeta` for blocks from blockchain in `BListener` callback.
> [CSM-485] Calling api/txs/histories takes a lot of time

- core/Pos/Arbitrary/Core.hs
- core/Pos/Core/Genesis/Generate.hs
These checks aren't useful at all nowadays, because mpc threshold considers
stakes, while this function generates balances.
And they are a bit annoying when one needs to generate proper inititializer.
This changed allowed me to simplify 'TestnetBalanceOptions' generation and
fix rarely failing tests.
> [CSL-1744] Remove mpc threshold checks from 'genTestnetDistribution'

- auxx/src/Mode.hs
- infra/Pos/Communication/Protocol.hs
- infra/Pos/DHT/Workers.hs
- infra/Pos/Network/Types.hs
- infra/Pos/Reporting/Methods.hs
- infra/Pos/Slotting/Util.hs
- node/src/Pos/Client/Txp/History.hs
- node/src/Pos/Explorer/Txp/Local.hs
- node/src/Pos/Generator/Block/Mode.hs
- node/src/Pos/WorkMode.hs
- node/src/Pos/WorkMode/Class.hs
- node/test/Test/Pos/Block/Logic/Mode.hs
- ssc/Pos/Ssc/Mode.hs
- txp/Pos/Txp/Logic/Local.hs
- update/Pos/Update/Logic/Local.hs
- update/Pos/Update/Mode.hs
- wallet/src/Pos/Wallet/Web/Mode.hs
I introduced 'HasNodeType' class which allows the node to know its type.
The type is determined by network config for normal node and is hardcoded for
tests, block-gen, etc.
The essential change is in 'reportMisbehaviour', other changes are related to
new type class, propagating proper constraints and defining instances.
P. S. I believe it should go to 1.0 branch to decrease load on reporting server.
> [CSL-1725] Report misbehavior from core nodes only

- pkgs/default.nix
- stack.yaml
> Use transformers-0.5.5.0 to fix space leak in Pos.Wallet.Web.Sockets.Notifier

- appveyor.yml
this solves the `C:\s\snapshots\6dde1a60\pkgdb\package.cache: openBinaryFile: permission denied (Permission denied)` error that happens when installing `happy` and `cpphs`
upstream issue: https://github.com/commercialhaskell/stack/issues/2617
> also allow retrying when installing happy and cpphs

- auxx/src/Command/Parser.hs
- auxx/src/Command/Run.hs
- auxx/src/Command/Types.hs
- auxx/src/Command/Update.hs
- update/Pos/Update/Core/Types.hs
* added a propose-unlock-stake-epoch command to auxx that sends an update proposal with a new value of unlockStakeEpoch
* added a print-bvd command auxx in order to monitor the current BlockVersionData
* fixed the name of puIdx (there was a TODO about it)
> [CSL-1734] Add a command to auxx for sending an update proposal

- appveyor.yml
- node/src/Pos/Client/Txp/History.hs
- node/src/Pos/Wallet/Web/ClientTypes/Functions.hs
- node/src/Pos/Wallet/Web/ClientTypes/Types.hs
- node/src/Pos/Wallet/Web/State/Acidic.hs
- node/src/Pos/Wallet/Web/State/State.hs
- node/src/Pos/Wallet/Web/State/Storage.hs
- node/src/Pos/Wallet/Web/Util.hs
- scripts/set_nixpath.sh
- wallet/src/Pos/Wallet/Web/Methods/History.hs
- wallet/src/Pos/Wallet/Web/Methods/Payment.hs
- wallet/src/Pos/Wallet/Web/Methods/Redeem.hs
- wallet/src/Pos/Wallet/Web/Methods/Restore.hs
- wallet/src/Pos/Wallet/Web/Tracking/Sync.hs
Branch (& PR) to combine and test the following fixes:
These existing PRs need to be rebased on this branch (so on top of the history cache representation change). My recommendation is to merge in the order above. In particular #1722 also changes the DB transactions and that could be simplified slightly by merging next.
Then we need:
We can test between merging #1722 and #1726 or just at the end.
> Merge CSM-489 CSM-485 and CSM-491 to exchanges branch

- node/cardano-sl-node.cabal
- pkgs/default.nix
To be the same as other packages' versions.
> Bump version of cardano-sl-node

- scripts/launch/demo.sh
I chose `15s` as minimal time which gives minimal number of error (from time-warp) in logs
> [CSL-1519] Decrease waiting time in demo.sh to 15 sec

- pkgs/default.nix
- tools/cardano-sl-tools.cabal
- tools/src/launcher/Main.hs
This PR is supposed to go into cardano-sl-1.0. It contains the following changes:
* The launcher now has pretty logs with timestamps.
* The launcher can be configured to put logs into a folder. This is nice because now if the node doesn't start or can't be killed or something, we'll find out.
* On Linux and macOS, the launcher sends SIGKILL if the node doesn't respond to SIGTERM.
If this PR is merged, we will have to change the launcher command-line arguments in Daedalus:
* Set `--node-timeout` to 30 seconds instead of 5 seconds (sigkilling the node after 5 seconds is cruel)
* Set `--launcher-logs-prefix` appropriately (e.g. `%appdata%\Daedalus\logs\pub`)
> [CSL-1747] Various launcher improvements

- lib/src/Pos/Explorer/Txp/Local.hs
- lib/src/Pos/Explorer/Txp/Toil/Logic.hs
- pkgs/default.nix
- txp/Pos/Txp/Logic/Local.hs
- txp/Pos/Txp/MemState/Class.hs
- txp/Pos/Txp/Toil/Logic.hs
- txp/cardano-sl-txp.cabal
Summary of changes:
1. `LocalToilMode` has `WithLogger`
2. `[E]ProcessTxMode` is over `NamedPureLogger Identity` instead of just `Identity`
3. `lib/src/Pos/Explorer/Txp/Toil/Logic.hs` no longer discards log from `updateAddrBalances`
AFAIK we don't need this in `cardano-sl-1.0`, it's not urgent.
> [CSE-179] Do not discard log

- appveyor.yml
- explorer/scripts/build/cardano-sl.sh
- lib/cardano-sl.cabal
- scripts/build/cardano-sl.sh
It was used only to disable gold linker options in cardano-sl library.
I think it only adds unnecessary mess, because we almost always build with
wallet and/or explorer flags (they are default).
> [CSL-1771] Get rid of with-wallet flag

- lib/src/Pos/DB/Block.hs
Possible bug causing CSL-1784 is the fact that `putData` wasn't flushing handle, so this scenario was possible:
1. We write block and put info about it in gstate, we update it.
2. System IO doesn't flush the data, so it's not yet on the disk.
3. Somebody turns machine off.
> [CSL-1784] Force flush on block write

- core/Pos/Arbitrary/Core.hs
- lib/src/Pos/Generator/Block/Payload.hs
Whenever utxo size is 1 we can't select tx outputs (since outputs must be different from inputs) and thus form transaction. This PR makes sure that we always have >=2 secret keys in `genesisSecrets`.
> [CSL-1741] Ensure utxo size is big enough to create tx in payload.hs

- auxx/src/Mode.hs
- core/Pos/Aeson/Genesis.hs
- core/Pos/Binary/Core/Genesis.hs
- core/Pos/Core/Address.hs
- core/Pos/Core/Genesis.hs
- core/Pos/Core/Genesis/Canonical.hs
- core/Pos/Core/Genesis/Helpers.hs
- core/Pos/Core/Genesis/Types.hs
- core/Pos/Util/Arbitrary.hs
- core/cardano-sl-core.cabal
- lib/src/Pos/Client/Txp/Addresses.hs
- lib/src/Pos/Client/Txp/Util.hs
- lib/src/Pos/Generator/Block/Mode.hs
- lib/test/Test/Pos/Client/Txp/Mode.hs
- lib/test/Test/Pos/Core/AddressSpec.hs
- wallet/src/Pos/Wallet/Web/Methods/Payment.hs
Previous implementation was using one of output addresses as a fake
change address. But it can happen that 'getNewAddress' generates an address
which is longer than the fake change address, which in turn will lead to
tx fee being too small and invalid tx will be created.
Note that this problem is quite important already, even though we can only
create bootstrap era addresses with HD payload. For more details about it
please see my comment in CSL-1740.
The solution is a bit hacky, but it seems there is no better way to resolve
problem. 'getFakeChangeAddress' was added to 'MonadAddresses' which must
create an address with size greater than or equal to maximal possible size of
address generated by 'getNewAddress'. An address generated by
'getFakeChangeAddress' is used to create a fake …
> [CSL-1740] Ensure that fake change address is always long enough

- .gitignore
- .hindent.yaml
- .stylish-haskell.yaml
Motivation:
* now nobody will have to pull serokell-util to get a new version of the config
* there are other contributors who might not even know about serokell-util (or be bothered to symlink the config)
> Put stylish-haskell and hindent configs into the repo

- pkgs/default.nix
- stack.yaml
Includes space leak fix from https://github.com/serokell/time-warp-nt/pull/110 (the time-warp-nt commit is just 630b23847ea39778f5616134a4f416b473639a15 + the PR).
Also, `pkgs/generate.sh` bumped a couple of other packages by itself :(
> Include space leak fix for time-warp-nt

- lib/src/Pos/Client/Txp/History.hs
- lib/src/Pos/GState/BlockExtra.hs
- wallet/src/Pos/Wallet/Web/Tracking/Sync.hs
Previously we'd always pull in the entire block and undo, even when
only the headers were needed (serving a get headers request).
Pulling in the block is quite expensive, because deserializing it
requires re-serializing the transactions it contains, as part of
deserializing the TxPayload, which re-builds a merkle tree. That's a
separate issue.
> [CSL-1772] more efficient header fetching

- auxx/src/Command/BlockGen.hs
- lib/src/Pos/Generator/Block/Logic.hs
- lib/src/Pos/Generator/BlockEvent.hs
- lib/src/Test/Pos/Block/Logic/Util.hs
- wallet/test/Test/Pos/Wallet/Web/Util.hs
`catMaybes <$> mapM genBlock [startEOS .. finishEOS]` caused the entire list of blocks to be retained.
Instead of constructing the list of blocks, some value of a monoid `t` is strictly constructed according to some injector `Maybe (Blund SscGodTossing) -> t`. Using `const ()` means the blocks will never be retained. `genBlock` writes them out to disk, which is all we want for the block generator application.
> [CSL-1767] fix block generator leak

- core/Pos/Binary/Class/Core.hs
- core/Pos/Binary/Class/Primitive.hs
- core/Pos/Binary/Class/TH.hs
- core/Pos/Binary/Core/Address.hs
- lib/cardano-sl.cabal
- lib/test/Test/Pos/BinarySpec.hs
- lib/test/Test/Pos/Cbor/Canonicity.hs
- lib/test/Test/Pos/Cbor/CborSpec.hs
- lib/test/Test/Pos/Cbor/ReferenceImplementation.hs
- lib/test/Test/Pos/Communication/Identity/BinarySpec.hs
- lib/test/Test/Pos/CryptoSpec.hs
- lib/test/Test/Pos/Helpers.hs
- lib/test/Test/Pos/Txp/Identity/BinarySpec.hs
- lib/test/Test/Pos/Types/Identity/BinarySpec.hs
- lib/test/Test/Pos/Update/Identity/BinarySpec.hs
- pkgs/default.nix
- stack.yaml
- txp/Pos/Binary/Txp/Core.hs
- update/Pos/Binary/Update.hs
As in title.
Additional info:
* Reference implementation is from test suite of `serialise` package.
* Encoding format did not change, except for NaNs - they were previously serialized as-is bit by bit, now all of them are serialized to the same, unique value and if canonical decoding version is used, it's the only one accepted form (half precision float, 0x7e00 as per https://tools.ietf.org/html/rfc7049#section-3.9). Having said that, `Float` serialization is only used for `PrimData` from PlutusCore. Can someone confirm that NaNs do not appear there?
> [CSL-1724] Test that serializable data structures have canonical cbor encodings

- lib/src/Pos/DB/Block.hs
In the buggy version `throwM …` was equivalent to `Nothing` (i. e. monad
was `Maybe`). In new version it's clearly `IO`.
> [CSL-1141] Fix 'getData' function

- core/Pos/Util/Modifier.hs
- node/src/Pos/Client/Txp/Balances.hs
- node/src/Pos/SafeCopy.hs
- node/src/Pos/Wallet/Web/State/Acidic.hs
- node/src/Pos/Wallet/Web/State/State.hs
- node/src/Pos/Wallet/Web/State/Storage.hs
- pkgs/default.nix
- txp/Pos/Txp/Toil/Types.hs
- txp/Pos/Txp/Toil/Utxo/Util.hs
- wallet/src/Pos/Wallet/Web/Methods/Logic.hs
- wallet/src/Pos/Wallet/Web/Server/Handlers.hs
- wallet/src/Pos/Wallet/Web/Tracking/Sync.hs
At least one problem was we computed balance for an address via iterating over utxo. Now we store hashmap `Address -> Coin` corresponding to wallet utxo.
I tested on old database, migration works. A number of addresses and transactions = 500, time was reduced from 6sec to 0.2sec. Result JSONs for `/api/wallets` and `/api/accounts/` before and after fix are same.
Tested with n = 3000, ~2 secs.
There is still what can be optimized, but I suppose it's enough for now and we should get a response from Richie for the current version.
**UPD**: tested on both version of wallet-db: initial and version in `cardano-sl-1.0-exchange`
> [CSM-494] `/api/wallets` (as well as `/api/accounts`) works for a long time

- explorer/src/Pos/Explorer/Socket/App.hs
- godtossing/Pos/Ssc/GodTossing/Toss/Pure.hs
- pkgs/default.nix
- stack.yaml
- update/Pos/Update/Poll/Pure.hs
This PR upgrades the dependency stack to depend on the latest pre-3.x revision of `log-warper`, which includes @neongreen 's work on directories plus the memory improvements, which should result in a more stable and less heavy memory footprint.
The migration was almost painless, apart from a couple of places where I had to deal with the fact I have now removed the spurious constraints on a `PureLogger` inside `log-warper` (for which we were using `UndecidableInstances` before). This means I had to either reshuffle some monadic stack around (in a trivial way) or had to create trivial `newtype` wrappers (like in the explorer case).
Please let me know if any of what I have done looks fishy!
> [CSL-1708] Use latest version of log-warper

- node/configuration.yaml
We are going to propose and vote for an update to block version 0.1.0.
We will also need to set application version to 3 for csl-daedalus.
Previosuly cardano-sl software was launched with version 2, but it was by
mistake, because last confirmed version was 0. This mistake didn't have any
impact though. I changed it to 0 to be correct.
Wallet configs now don't reuse `mainnet_base_update`, but instead define
all versions explicitly, because the previous solution was error-prone.
> [CSL-1794] Update versions in configuration

- txp/Pos/Txp/Logic/Local.hs
- wallet/cardano-sl-wallet.cabal
- wallet/src/Pos/Wallet/Redirect.hs
- wallet/src/Pos/Wallet/Web/Methods/History.hs
- wallet/src/Pos/Wallet/Web/Methods/Logic.hs
- wallet/src/Pos/Wallet/Web/Methods/Payment.hs
- wallet/src/Pos/Wallet/Web/Methods/Redeem.hs
- wallet/src/Pos/Wallet/Web/Mode.hs
- wallet/src/Pos/Wallet/Web/Tracking/Decrypt.hs
- wallet/src/Pos/Wallet/Web/Tracking/Sync.hs
- wallet/test/Test/Pos/Wallet/Web/Methods/PaymentSpec.hs
- wallet/test/Test/Pos/Wallet/Web/Mode.hs
- wallet/test/Test/Pos/Wallet/Web/Util.hs
First steps to modify wallet state when new tx received.
In this PR wallet does update tx meta when tx received instead of when tx history requested.
**UPD**: I decided to write test for this change (now we CAN do it).
> [CSM-516] React to mempool changes via `MonadTxpListener`

- appveyor.yml
- scripts/ci/travis.sh
this ensures that both windows and darwin builds have a commit-id and also adds a ci-url, because the travis build id doesn't map directly to a url
> [DEVOPS-441] display cardano rev in daedalus CI logs

- core/Pos/Arbitrary/Crypto/Unsafe.hs
- core/Pos/Crypto/Signing/Signing.hs
Sk/pk instances were using wrong arbitrary string sizes, which led to failure in benches. I've also removed `unsafeArbitrary` instance for `Signature` because it wasn't used anywhere #noweeds.
> [CSL-1836] Fix unsafeArbitrary instances of sk/pk

- infra/Pos/Communication/Types/Protocol.hs
- infra/Pos/Subscription/Common.hs
- infra/Pos/Subscription/Dns.hs
- infra/Pos/Util/Timer.hs
- infra/cardano-sl-infra.cabal
- lib/src/Pos/Binary/Communication.hs
- lib/src/Pos/Block/Network/Retrieval.hs
- lib/src/Pos/Block/Worker.hs
- lib/src/Pos/Context/Context.hs
- lib/src/Pos/Launcher/Resource.hs
- lib/src/Pos/Worker.hs
That should take care of [CSL-1676](https://issues.serokell.io/issue/CSL-1676).
The only issue is that I'm not sure how to test that change  - running `demo.sh` doesn't trigger subscription worker on any of the nodes.
> [CSL-1676] Send keep-alive like packets after relay subscription

- pkgs/default.nix
- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/server/Cardano/Wallet/API/V1/Handlers/Accounts.hs
- wallet-new/server/Cardano/Wallet/API/V1/Handlers/Addresses.hs
- wallet-new/server/Cardano/Wallet/API/V1/Handlers/Wallets.hs
- wallet-new/server/Cardano/Wallet/API/V1/Swagger.hs
- wallet-new/spec/swagger.json
- wallet-new/src/Cardano/Wallet/API/Types.hs
- wallet-new/src/Cardano/Wallet/API/V1/Parameters.hs
- wallet-new/src/Cardano/Wallet/API/V1/Types.hs
- wallet-new/stack.yaml
- wallet-new/test/APISpec.hs
Investigation on whether or not pagination parameters can be grouped led to the following results:
1. Pagination parameters can indeed be grouped
2. Pagination parameters can have default values which are passed to API handlers automatically, which looks way more convenient than dealing with `Maybe`s in each handler.
3. As long as `extended` query parameter (which I dared to rename to `response_type`, because it seems more self-explanatory) and `Daedalus-Response-Format` header serve the same purpose, their values can be combined in single value, which is then passed to handlers.
Besides of that, I couldn't resist doing small refactorings here and there. 
These solutions are not final, but they clearly show that we can do interesting things with our API, keeping our handlers neat and tidy …
> [CSM-550] Group pagination parameters in one datatype

- appveyor.yml
- pkgs/default.nix
- wallet/node/NodeOptions.hs
Default paths for wallet tls files are wrong
If we run demo scripts and ommit to add some of
the tls param filepaths default ones get used.
Problem was that default settings search for files
in the root folder while they are actually in the
/scripts/tls-files
> [CSM-495] Change the default path to tls files

- wallet/src/Pos/Wallet/Aeson/ClientTypes.hs
- wallet/src/Pos/Wallet/Web/Api.hs
- wallet/src/Pos/Wallet/Web/Methods/Backup.hs
- wallet/src/Pos/Wallet/Web/Methods/History.hs
- wallet/src/Pos/Wallet/Web/Methods/Logic.hs
- wallet/src/Pos/Wallet/Web/Methods/Misc.hs
- wallet/src/Pos/Wallet/Web/Methods/Payment.hs
- wallet/src/Pos/Wallet/Web/Methods/Redeem.hs
- wallet/src/Pos/Wallet/Web/Methods/Reporting.hs
- wallet/src/Pos/Wallet/Web/Methods/Restore.hs
- wallet/src/Pos/Wallet/Web/Swagger/Spec.hs
This slightly-invasive PR switch from `()` to `NoContent` for endpoints which do not return a result. This was necessary to avoid `servant-swagger` generating invalid specs.
Prior to this PR, it was not possible to validate the spec generated:
After this PR, we can:
`NoContent` is a type defined in `Servant.API.ContentTypes` which is then erased by response bodies but at the same time ensures our Swagger spec validates correctly.
If you guys can think of a less-invasive way to support this, I'm all ears (one possibility would be to `fmap NoContent` each unit-returning endpoint inside `servantHandlers`, but if feels conceptually cleaner to give each handler a proper return type directly in its definition).
> [CSM-555] Switch from () to NoContent for endpoints with no result

- wallet/src/Pos/Wallet/Web/ClientTypes/Instances.hs
- wallet/src/Pos/Wallet/Web/ClientTypes/Types.hs
- wallet/src/Pos/Wallet/Web/Methods/History.hs
- wallet/src/Pos/Wallet/Web/Pending/Functions.hs
- wallet/src/Pos/Wallet/Web/Pending/Submission.hs
- wallet/src/Pos/Wallet/Web/Pending/Types.hs
- wallet/src/Pos/Wallet/Web/State/Acidic.hs
- wallet/src/Pos/Wallet/Web/State/State.hs
- wallet/src/Pos/Wallet/Web/State/Storage.hs
This is important, because if we remember it once transaction creation is done,
then creation may complete only after the moment when transaction gets to
blocks and then gets detected by tracker, so effectively tracker misses the tx.
Solution is to add new pending transaction status, `PtxCreating`. which
is not to display to frontend, and such transaction may be removed if
full cycle of transaction creation finishes with fatal error (unlike
`PtxApplying`).
Transaction remembered with this status still caries all pending meta info,
so tracker can successfully update status of that transaction.
Tested on:
* Normal creation
* Slot-length artificial delay between transaction submission over network and local application (original issue case)
* Fatal and non-fatal failure scenarios
* Start …
> [CSM-500] Remember pending transaction from the very beginning

- lib/src/Pos/Block/Worker.hs
This comment is obsolete and was removed long ago, but then was accidentally
restored during merge (PR #1876).
> [CSL-1843] Remove obsolete comment

- wallet/src/Pos/Wallet/Web/ClientTypes/Instances.hs
We don't want to throw decoding error, just return `False` if address is invalid
> [CSM-557] Fix `instance FromHttpApiData (CId w)`

- daedalus/package.json
- daedalus/src/redemption_key_validation.js
- pkgs/default.nix
This PR implements https://issues.serokell.io/issue/CSM-552 - it rewrites `isValidRedemptionKey` and `isValidPaperVendRedemptionKey` into js.
`isValidPaperVendRedemptionKey` is tested with samples from https://cardanodocs.com/technical/wallet-frontend/#redeem-valid-paper-vend : 
```
$ node
> var bla = require('./src/redemption_key_validation.js')
undefined
> bla.isValidPaperVendRedemptionKey('lwIF94R9AYRwBy0BkVVpLhwtsG3CmqDvMahlQr3xKEY=')
false
> bla.isValidPaperVendRedemptionKey('CUUCxbH5pPc6RC1dvJKetJPVTG7X4WKPmBsoeZMbiQok')
true
```
`isValidPaperVendRedemptionKey` is tested:
```
> bla.isValidRedemptionKey('lwIF94R9AYRwBy0BkVVpLhwtsG3CmqDvMahlQr3xKEwm')
false
> bla.isValidRedemptionKey('lwIF94R9AYRwBy0BkVVpLhwtsG3CmqDvMahlQr3xKEw=')
true
> …
```
> [CSM-552] purs to js migration

- pkgs/default.nix
- tools/src/keygen/Dump.hs
This caught people off-guard numerous times.
Seems like humans are better trained to deal with natural numbers.
> [DEVOPS-157] naturalise cardano-keygen:  number generated key files from 0, instead of 1

- pkgs/default.nix
- tools/src/launcher/Main.hs
The following was happening:
* Daedalus sends a shutdown signal to the node
* The node exits faster than Daedalus
* Launcher treats it as node crash and doesn't restart Daedalus
> [CSL-1782] Restart wallet when node exits first

- lib/configuration.yaml
Merge was performed with `-s ours', because all those changes are already in master.
> Merge cardano-sl-1.0

- scripts/grep.sh
I noticed that `grep.sh' didn't work correctly for explorer source code and
decided that it's better to use version which doesn't require enumerating all
folders.
Initially it was proposed by @sectore and I slightly modified it.
> Rework grep.sh

- appveyor.yml
- core/Pos/Util/Util.hs
- infra/Pos/Reporting/Exceptions.hs
- infra/Pos/Reporting/Methods.hs
- infra/cardano-sl-infra.cabal
- pkgs/default.nix
- shell.nix
- tools/src/launcher/Main.hs
This PR introduces support for sending `tar.lzma` archives to reporting server.
Changes that were made:
* Report server can now accept binary files: https://github.com/input-output-hk/cardano-report-server/pull/7
* Reporting `Methods` was restructured to support this change.
* Before sending memory logs (from the node itself), we write it to file and tar.lzma this single file. After it's send, archive is deleted. Compression level is maximum.
* When node fails from launcher point of view, we do the same, though logs number is more than one (that's where tar is being actually used).
> [CSL-1732] Compress logs

- pkgs/default.nix
- wallet/src/Pos/Wallet/Web/Methods/Backup.hs
Before default address was created only together with default account, if no accounts were specified in JSON backup. This PR introduces logic of creating default addresses for accounts which were specified in backup, but don't have any addresses in Utxo or transaction history.
> [CSM-553] Create default address for each account during JSON wallet import

- lib/src/Pos/Client/KeyStorage.hs
- pkgs/default.nix
- wallet/src/Pos/Wallet/Web/Account.hs
- wallet/src/Pos/Wallet/Web/Methods/Logic.hs
- wallet/src/Pos/Wallet/Web/Methods/Misc.hs
I actually wanted to modify our wallet creating endpoints so that, instead of
`makeWallet emptyPassphrase >> changePassphrase emptyPassphrase userPassphrase`
they do the same in one hope (for security purposes).
But then I saw that only `importWallet` endpoint suffers from that, so just an other little change is here
> [CSM-523] Get rid of nonatomic deletions in key storage

- auxx/src/Command/Proc.hs
- auxx/src/Lang/Argument.hs
- auxx/src/Lang/Command.hs
- auxx/src/Lang/Interpreter.hs
This PR has no associated issue id because I implemented this feature in my free time (so that @dcoutts doesn't mind that we spend more time on auxx than needed).
It allows using type information about arguments to avoid specifying keyword options. For instance, in `propose-update` we know that if some input has type `SoftwareVersion`, it's supposed to be passed as `software-version:~software~cardano-sl:1`, but now `software-version:` key can be omitted.
The design is such that only *more* programs are accepted, so positional arguments are not affected negatively (as one could think), they are just a little bit less positional.
> Type-directed keyword annotations in auxx

- node/README.md
1. ~~Add `scripts/build/cardano-sl.nix.sh` which builds any package from the Cardano's package set (and defaults to `cardano-sl-static`, if no output is provided)~~
2. ..and actually, it uses the IOHK binary cache, so most of the time the build will fetch the binaries from `hydra.iohk.io`
3. Document ~~this new script~~ the Nix-based build procedure in `README.md`: https://github.com/input-output-hk/cardano-sl/tree/devops-268-iohk-cache/node#building-cardano-with-nix
> [DEVOPS-268] iohk cache

- node/configuration.yaml
`Devnet` configuration didn't have explicit `update` part and was reusing one from
mainnet_base, which corresponds to real mainnet and has `lastKnownBlockVersion`
set to 0.1.0. Because of that, nodes didn't create blocks (in devnet).
> [DEVOPS-157] Fix devnet configuration

- auxx/src/Command/Proc.hs
- docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md
- docs/how-to/push-update-on-mainnet.md
- docs/how-to/test-update-system.md
`push-update-on-mainnet.md` is updated according to the new auxx interface, as well as the rest of the documentation.
`bvm` argument in `propose-update` command is now optional for convinience.
> [CSL-1819] Update `push-update-on-mainnet.md`

- docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md
@nh2 found that running `stack setup` breaks Nix, since it mixes glibc with system one.
```
[pid 24854] execve("/home/syd/.stack/programs/x86_64-linux-nix/ghc-8.0.2/bin/ghc", ["/home/syd/.stack/programs/x86_64"..., "--make", "-fbuilding-cabal-package", "-O", "-static", "-dynamic-too", "-dynosuf", "dyn_o", "-dynhisuf", "dyn_hi", "-outputdir", ".stack-work/dist/x86_64-linux-ni"..., "-odir", ".stack-work/dist/x86_64-linux-ni"..., "-hidir", ".stack-work/dist/x86_64-linux-ni"..., ...], [/* 71 vars */] <unfinished ...>
...
[pid 24854] open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
```
>  [DEVOPS-522] Docs: don't mention stack setup when using Nix

- docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md
Remove `$` characters which should not be added to the file.
> Minor tweak to how-to-build doc

- scripts/build/cardano-sl.sh
After recent changes `stack` no longer producess warnings for
`servant-quickcheck` package. And I didn't update `stack`. So apparently
our workaround is no longer necessary.
> [CSL-2017] Remove workaround for stack warning

- generator/test/Test/Pos/Block/Logic/VarSpec.hs
- lib/configuration.yaml
MacOS CI still fails too often. I am decreasing some values and hope it
will make all or almost all builds pass now.
DEVOPS-562 and CSL-1966 may improve the situation, then we can restore bigger
values.
> [CSL-1966] Decrease testing constants even further

- auxx/Main.hs
- block/src/Pos/Block/Network/Announce.hs
- block/src/Pos/Block/Network/Logic.hs
- block/src/Pos/Block/Network/Retrieval.hs
- block/src/Pos/Block/Worker.hs
- block/src/Pos/Lrc/Worker.hs
- core/Pos/Core/Common/Types.hs
- explorer/src/explorer/Main.hs
- lib/src/Pos/Client/CLI/Params.hs
- lib/src/Pos/Client/CLI/Util.hs
- lib/src/Pos/Launcher/Param.hs
- lib/src/Pos/Launcher/Resource.hs
- lib/src/Pos/Launcher/Runner.hs
- lib/src/Pos/Launcher/Scenario.hs
- log-config-prod.yaml
- node/Main.hs
- pkgs/default.nix
- scripts/log-templates/log-config-qa.yaml
- scripts/log-templates/log-template-demo.yaml
- scripts/log-templates/update-log-config.yaml
- stack.yaml
- tools/src/launcher/Main.hs
- update/Pos/Update/Network/Listeners.hs
- wallet-new/server/Main.hs
- wallet/node/Main.hs
- wallet/src/Pos/Wallet/Web/Pending/Worker.hs
There are various changes related to logging: what we log, which severity messages have, how logging is configured, etc.
Commit history is descriptive, imo. Most commits have few sentences of explanation.
I've almost finished, the only missing thing is to review middleware logs, will do it soon.
> [CSL-1822] Refine logging

- scripts/common-functions.sh
- scripts/launch/demo.sh
* use `rm -rf` in case when the `$out_dir` does not exists (fresh run)
* create `./run` directory if it does not exists
> Fixes for demo.sh

- node/test/Test/Pos/Client/Txp/UtilSpec.hs
Added tests for both grouped and ungrouped input selection policies.
Each transaction creation test is now tested with both grouped and ungrouped selection policy.
Note: this PR directly depends on #1826
> [CSM-527] Add tests on ungrouped inputs picking in tx creation

- explorer/src/Pos/Explorer/Socket/Methods.hs
- node/src/Pos/Block/Logic/Header.hs
- node/src/Pos/Block/Network/Listeners.hs
- node/src/Pos/Client/Txp/History.hs
- node/src/Pos/GState/BlockExtra.hs
- node/src/Pos/Security/Workers.hs
- wallet/src/Pos/Wallet/Web/Tracking/Sync.hs
This should speed up `MsgBlock` listener on the server side.
I've also fixed a recovery worker that wasn't triggered when we were not in recovery, though too late (it was a bug, apparently).
> [CSL-1931] Use forward links in getHeadersRange

- scripts/common-functions.sh
Current auxx requires to have either `./` or `/` in the beginning of the file path, otherwise fails with a parse error.
> [CSL-1981] Fix auxx arguments in common-functions.sh

- appveyor.yml
This attempts to work around the out-of-memory on AppVeyor, that happens during the `xcopy` updating the branch cache.
> [DEVOPS-565]  appveyor:  disable branch cache updates

- wallet-new/docs/updates.md
@georgeee Third time lucky?
(Follows old summary)
Here is the proposed new revision for the update API for V1, which includes the new endpoints to propose & vote for an update. You might notice the API is quite different from the one @domenkozar  originally proposed and that I proposed as part of [this PR](https://github.com/input-output-hk/cardano-sl/pull/1884). This is because I have had time to think about @georgeee 's review and I am now much more happy of how the API looks & feels as it's way more RESTful in my opinion, and all the custom ad-hoc actions (except for one, hehe) are gone.
[Play with the rendered API here!](https://editor.swagger.io/?url=https://gist.githubusercontent.com/adinapoli-iohk/b8d54d04101e60e83166cb32dfa9d8ff/raw/2e8193777aea781d01c0aa5ac96f50d9ef79d640/updates_ …
> [CSL-1927] Update V1 new revision with George's feedback

- appveyor.yml
- node/src/Pos/Wallet/Web/State/Acidic.hs
- node/src/Pos/Wallet/Web/State/State.hs
- node/src/Pos/Wallet/Web/State/Storage.hs
- pkgs/default.nix
- wallet/src/Pos/Wallet/Web/Methods/History.hs
- wallet/src/Pos/Wallet/Web/Methods/Logic.hs
- wallet/src/Pos/Wallet/Web/Methods/Payment.hs
- wallet/src/Pos/Wallet/Web/Mode.hs
- wallet/src/Pos/Wallet/Web/Server/Runner.hs
Improves performance of `newPayment`, `getWallets` and `getTxHistory`  endpoints.
Detected problems:
1. `newPayment` need to create change address in the process, and `newAddress` endpoint did some extra work, which now removed.
2. Addresses are kept in database as `CId Addr` strings, and mentioned endpoints require to deserialize them all. As simple solution we keep cache with `Map (CId Addr) Address`. Proper database migration will be performed as part of moving to wallet-new.
Now we get following times in local demo when creating 60k addresses artificially:
* `newPayment` - ~1 second
* `getTxHistory` - < 1 second
* `getWallets` - 1-2 seconds
Tested with:
* Basic testing (create transactions, see at tx history and wallets info)
* Daedalus acceptance tests
> [CSL-2087] Primary endpoints speedup

- wallet-new/server/Cardano/Wallet/Server/CLI.hs
This trivial PR allows `wallet-new` to use `wallet-db` as the default DB.
> [CSL-2086] Use wallet-db as default db.

- scripts/launch/demo-with-new-wallet-api.sh
- scripts/launch/demo-with-wallet-api.sh
- wallet-new/cardano-sl-wallet-new.cabal
- wallet/cardano-sl-wallet.cabal
https://iohk.myjetbrains.com/youtrack/issue/CSL-1952
As discussed with @adinapoli-iohk - we need to eventually completely replace the calls, renaming the old to simply cardano-node-old and the new as cardano-node would do the trick and I think we should go for it, but then we shouldn’t merge the PR until this one is merged - #1986
This is because we want master to incorporate the current wallet-new whilst it's still not invoked. Then once we port completely the API we merge this PR and on the next merge of alfredo/wallet-new into master we should be in the position of start using wallet-new as if it was “the normal wallet”.
> [CSL-1952] Rename 'wallet-new-server' into 'cardano-node'.

- wallet/src/Pos/Wallet/Web/Methods/History.hs
- wallet/src/Pos/Wallet/Web/Methods/Logic.hs
- wallet/src/Pos/Wallet/Web/Methods/Payment.hs
- wallet/src/Pos/Wallet/Web/Pending/Submission.hs
This PR removes some huge logging of all addresses in `newPayment` and all transactions from blocks in `getHistory` (which is compensated with logging of last 100 transactions).
Also some logs added which report stage of endpoint execution, so that we can better understand timings of all stages.
> [CSL-2087] Improve logging of primary endpoints

- lib/bench/Bench/Pos/Criterion/FollowTheSatoshiBench.hs
- lib/bench/Local/Criterion.hs
- lib/cardano-sl.cabal
This benchmark target wouldn't compile due to changes elsewhere in
the tree.
> cardano-sl: Fix broken cardano-bench-criterion target

- block/src/Pos/Block/Logic/Header.hs
- block/src/Pos/Block/Logic/Util.hs
- block/src/Pos/Block/Worker.hs
- infra/Pos/Recovery/Info.hs
I've generalized `needRecovery` and related functions. I've also added a probabilistic preventive recovery triggering in case we're stuck >3 slots before current tip, but nobody sends us blocks.
> [CSL-2038] More recovery heuristics

- auxx/src/Command/Tx.hs
- node/src/Pos/Client/Txp/Util.hs
- node/src/Pos/Communication/Tx.hs
- node/src/Pos/Generator/Block/Payload.hs
- node/test/Test/Pos/Client/Txp/UtilSpec.hs
- wallet/src/Pos/Wallet/Web/Methods/Payment.hs
This PR delivers what can be called a "high throughput" policy for UTXO input selection by passing a list of `PendingTx` to the functions which picks the UXTO inputs, in a way that only confirmed addresses (i.e addresses associated to an already-confirmed transaction) will be picked, if available.
> [CSL-2083] High throughput policy for UTXO input selection

- .gitignore
- .stylish-haskell.yaml
It's hard to modify content of cardano-sl-1.0 branch
since it doesn't have stylish-haskell config and by default
styler uses root config which is (already) very different
from what is used in cardano-sl-1.0 branch. So I add
explicit config having style we need.
> Introduce stylish haskell config

- tools/src/block-gen/Main.hs
- tools/src/block-gen/Options.hs
Yes, blockgen works in master already, but using it in this branch
still does make sense:
1. Switching branches (master/release) is expensive and time consuming.
2. Blockgen interface in cardano-sl-1.0 is somewhat more straight-forward.
> [CSL-2043] Fix block generator in cardano-sl-1.0

- wallet-new/cardano-sl-wallet-new.cabal
The main file for this build target is called `Spec.hs` so the module `Spec` doesn't need to be listed in `other-modules`.
> wallet-new: Remove duplicate entry in cabal file

- auxx/src/Plugin.hs
- node/cardano-sl.cabal
- node/src/Pos/Binary/Communication.hs
- node/src/Pos/Block/Network/Listeners.hs
- node/src/Pos/DB/Block.hs
- pkgs/default.nix
- stack.yaml
Block deserialization is skipped when sending.
Loading headers performance improved (slightly).
It's a real pain, but I've managed to verify the improvements locally.
Block generator in cardano-sl-1.0 generated a chain of poor quality!
I couldn't figure out how to get the system start time right so that
the test nodes wouldn't immediately jump into recovery mode.
Anyway, since the test node was always in recovery mode, I
noticed that the recovery mode block headers server also suffers
from the block deserialization inefficiency: it will load headers
"up" using `GS.loadHeadersUpWhile`, which in fact loads more than
just the header, it deserializes the block with undo. We can fix that
later, as our relays are probably not going to be in recovery mode (I
hope not!) so it won't affect us.
> [CSL-1869] Improve block(header) server performance

- docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md
- docs/how-to/run-explorer-web-ui.md
- docs/how-to/send-requests-to-wallet-api.md
Related to https://github.com/input-output-hk/cardanodocs.com/pull/65 and https://iohk.myjetbrains.com/youtrack/issue/CSLD-147. The reason is https://github.com/input-output-hk/cardano-sl/pull/2022.
> [CSLD-147] Remove docs related to PureScript bridge.

- default.nix
- release.nix
the node binary was moved to its own cabal project, and this updates the nix to follow it
> fix the static node reference

- log-config-prod.yaml
- pkgs/default.nix
This rounding sometimes makes debugging too hard and it's not important
with regards to privacy.
Note that currently used log-warper version doesn't support more granular
timestamps (1 second is maximal precision).
> Remove rounding from end users' public logs

- log-config-prod.yaml
- scripts/log-templates/log-config-greppable.yaml
- scripts/log-templates/log-config-qa.yaml
- scripts/log-templates/log-template-demo.yaml
Latest log-warper version uses a different structure for its configuration files.
Note: I removed `termSeverity` from all configuration files because the default log-warper behavior writes everything except errors to stdout and errors to stderr. If that needs to be changed, please comment on it, and I'll change that.
> [CSL-2114] Update log configuration files for new log-warper version

- infra/Pos/StateLock.hs
- node/cardano-sl.cabal
- node/configuration.yaml
- node/src/Pos/Block/Worker.hs
- node/src/Pos/Configuration.hs
- node/src/Pos/DB/Block.hs
- node/src/Pos/Wallet/Web/ClientTypes/Instances.hs
- node/src/Pos/Wallet/Web/Pending/Functions.hs
- node/src/Pos/Wallet/Web/Pending/Updates.hs
- node/src/Pos/Wallet/Web/State/Acidic.hs
- node/src/Pos/Wallet/Web/State/State.hs
- node/src/Pos/Wallet/Web/State/Storage.hs
- node/src/Pos/Wallet/Web/Util.hs
- wallet/node/Main.hs
- wallet/node/NodeOptions.hs
- wallet/src/Pos/Wallet/Web/Api.hs
- wallet/src/Pos/Wallet/Web/Methods/History.hs
- wallet/src/Pos/Wallet/Web/Methods/Misc.hs
- wallet/src/Pos/Wallet/Web/Methods/Payment.hs
- wallet/src/Pos/Wallet/Web/Mode.hs
- wallet/src/Pos/Wallet/Web/Pending/Submission.hs
- wallet/src/Pos/Wallet/Web/Pending/Util.hs
- wallet/src/Pos/Wallet/Web/Pending/Worker.hs
- wallet/src/Pos/Wallet/Web/Server/Handlers.hs
- wallet/src/Pos/Wallet/Web/Swagger/Description.hs
- wallet/src/Pos/Wallet/Web/Swagger/Instances/Schema.hs
**a,b.** Added options to config to disable hazard endpoints and disable transactions creation. Log values at beginning of wallet run.
**c.** Added endpoint to see pending (or canceled) transactions summary
Example of output: ~https://pastebin.com/Y72HTs2H~ https://pastebin.com/80Bp1Uya
**d.** Cherry-picked `fea9971` with endpoint to reset pending transaction (from CSL-2020) and added endpoint to cancel unconfirmed transactions
**5a.** Add endpoint to reform cancelled transactions
Correctness testing:
> [CSL-2135] Tricks with resubmission logic

- node/src/Pos/Wallet/Web/Util.hs
- wallet/src/Pos/Wallet/Web/Account.hs
- wallet/src/Pos/Wallet/Web/Methods/Logic.hs
There are two improvements:
1. Checking existence of an account in `newAddress` is done much faster. Previously it was done by calling `getAccount`, which collects all addresses, deserialize them and it's extremely slow.
2. Generating unique address is optimized. For each generated address we derived it even this address already existed in db or was hardened, now we check it at first and then derive
I haven't generated 80k addresses like binance contains, but for 1k addresses, the first improvement showed much better performance
> [CSL-2113] Binance new address performance improvement

- wallet/src/Pos/Wallet/Web/Methods/Logic.hs
- wallet/src/Pos/Wallet/Web/Methods/Payment.hs
Do now gather info about addresses in `newAddress` when not necessary.
Measures:
Before: 6.97 - 9.42 sec (rarely 12.96)
After: 6.10 - 8.8 sec
(there is a performance regression in before result comparing to measures I reported a couple of days ago (on commit X), I don't understand why it so happens, but the same regression happens even if I try to measure right at commit X, so it seems to be caused by my machine)
> [CSL-2087] Don't do extra work for change address creation

- node/src/Pos/Wallet/Web/State/State.hs
- node/src/Pos/Wallet/Web/State/Storage.hs
- node/src/Pos/Wallet/Web/Util.hs
- wallet/src/Pos/Wallet/Web/Methods/History.hs
- wallet/src/Pos/Wallet/Web/Methods/Logic.hs
- wallet/src/Pos/Wallet/Web/Methods/Payment.hs
Sort addresses only when they are to be displayed to user.
Measures:
Before: 6.97 - 9.42 sec (rarely 12.96)
After: 4.95 - 8.88 sec
(there is a performance regression in `before` result comparing to measures I reported a couple of days ago (on commit X), I don't understand why it so happens, but the same regression happens even if I try to measure right at commit X, so it seems to be caused by my machine)
> [CSL-2087] Don't sort addresses when not necessary

- node/src/Pos/Wallet/Web/ClientTypes/Functions.hs
- node/src/Pos/Wallet/Web/State/Acidic.hs
- node/src/Pos/Wallet/Web/State/State.hs
- node/src/Pos/Wallet/Web/State/Storage.hs
- node/src/Pos/Wallet/Web/Util.hs
- wallet/src/Pos/Wallet/Web/Methods/History.hs
- wallet/src/Pos/Wallet/Web/Methods/Payment.hs
- wallet/src/Pos/Wallet/Web/Methods/Redeem.hs
Avoid conversion `HashMap (CId Addr) a` to `Set (CId Addr)` when viable.
Measures:
Before: 6.97 - 9.42 sec (rarely 12.96)
After: 5.93 - 9.48 sec
(there is a performance regression in before result comparing to measures I reported a couple of days ago (on commit X), I don't understand why it so happens, but the same regression happens even if I try to measure right at commit X, so it seems to be caused by my machine)
> [CSL-2087] `newPayment` improvements

- node/configuration.yaml
- node/src/Pos/Configuration.hs
- node/src/Pos/Wallet/Web/Util.hs
- wallet/node/Main.hs
- wallet/src/Pos/Wallet/Web/Methods/Misc.hs
- wallet/src/Pos/Wallet/Web/Methods/Payment.hs
- wallet/src/Pos/Wallet/Web/Pending/Submission.hs
- wallet/src/Pos/Wallet/Web/Pending/Worker.hs
This is a backport to master of [this particular commit](https://github.com/input-output-hk/cardano-sl/pull/2213/commits/5d57aaa86ef4a76df75ea7df4ab78861b6a29ef5).
It has been cherry-picked and includes [this other commit](https://github.com/input-output-hk/cardano-sl/pull/2213/commits/f515bcb1e65ebc61df9fdf0a5d3020a26066b7b0) as well, as per plan.
> [CSL-2135] Add options to disable tx creation and hazard endpoints

- pkgs/default.nix
- wallet/src/Pos/Wallet/Web/Methods/Payment.hs
- wallet/src/Pos/Wallet/Web/Pending/Submission.hs
This is done in order to revent race condition when we receive our transaction
as part of a block before we use 'saveTx' (in which case 'saveTx' fails).
More elaborate explanation will be provided by @pva701.
@pva701's explanation:
In this PR we reorder sending a transaction to network and saving it at the `submitAndSave` and `submitAndSavePtx` functions.
Previously it might cause a situation when a transaction was sent to network, then appeared in a block, block came to the wallet and the transaction was considered as invalid because the block with this transaction had been already applied.
Now we save a tx to mempool first and then send it to network to avoid such situation.
As part of this PR we describe wallet-db and mempool changes. There are three things which can be changed:
1. …
> [CSL-2135] Add a newly created tx to the mempool before submitting it

- scripts/build/cardano-sl.sh
We have `--ram` flag, but we need RAM-limit flags as well.
> Limit RAM during building.

- scripts/log-templates/log-config-qa.yaml
Backport of #2131 to `master`.
_Note: There is not a related YT issue to original PR._
> Hotfix PR 2131

- node/src/Pos/Wallet/Web/State/Acidic.hs
- node/src/Pos/Wallet/Web/State/State.hs
- node/src/Pos/Wallet/Web/State/Storage.hs
- pkgs/default.nix
- wallet/src/Pos/Wallet/Web/Methods/History.hs
- wallet/src/Pos/Wallet/Web/Methods/Logic.hs
- wallet/src/Pos/Wallet/Web/Methods/Payment.hs
- wallet/src/Pos/Wallet/Web/Mode.hs
- wallet/src/Pos/Wallet/Web/Server/Runner.hs
Backport of #2122 to `master`.
https://iohk.myjetbrains.com/youtrack/issue/CSL-2087
As noted in our spreadsheet:
- commits 7cc245e9a0d5e165aeb6ede59dbd8a1f1c16c86f and c5cc56275db1da52be8d564eeabb9ebe98284cda have been squashed into one commit
- backport of commit 07e12e1fbf1376064ab07e7f43e808880fb6ef69 is postponed and not part of this PR.
> Hotfix CSL-2087

- docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md
All steps from Stack-way of building was tested yesterday on the clean macOS.
Some of details are taken from https://github.com/input-output-hk/cardano-sl/pull/2242.
> Complete building instruction, with 'pure Stack' way.

- docs/exceptions.md
Rendered: https://github.com/input-output-hk/cardano-sl/blob/int-index/csl-1842/docs/exceptions.md
> [CSL-1842] Write the guidelines for exception handling

- scripts/launch/connect-to-cluster/default.nix
I don't have openssl on my PATH, so the Cardano web server wasn't starting for me.
> Use Nix' openssl in connect-to-cluster

- scripts/launch/connect-to-cluster/default.nix
A typo in the check for existence of the TLS certificate directory
causes the server cert to be re-generated every time the script is
called. This little patch fixes the situation.
> Fix connect-to-mainnet generator

- explorer/src/Pos/Explorer/ExtraContext.hs
Unless there is a valid reason to keep `ExtraContext` lazy, I'm adding a strictness annotation as is done throughout Cardano.
> Add strictness to ExtraContext

- lib/test/Test/Pos/Ssc/Toss/PureSpec.hs
This commit introduces a correction to a 'PureToss' test that caught a bug
(test failure here:
https://travis-ci.org/input-output-hk/cardano-sl/jobs/315346651)
in the way the generation of arbitrary sequences of actions in the
'PureToss' monad works.
In particular, the 'Test.Pos.Ssc.Toss.PureSpec.putDelCommitment' test
generates a prefix of 'PureToss' actions in which there are no actions
that insert the same signed commitment in the state (https://github.com/input-output-hk/cardano-sl/commit/d55ad660224b27b27540bcc659a61a8ecbc40053#diff-6687dba169eab6172cb5a6deaa9c433bR131)
as the one generated for the test (see the comment for an explanation).
The problem with the previous code is that a `SignedCommitment` is a
tuple, and comparing tuples for equality means only one of the components …
> [CSL-2068] Fix 'PureToss' test

- lib/README.md
Since Travis CI is no longer used in 'cardano-sl' (having been replaced
by Buildkite) this PR updates the CI status badge shown in the
'README.md' to point to the latest build in the latter service instead.
> Remove Travis CI status badge

- default.nix
- docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md
- pkgs/default.nix
- pkgs/generate.sh
- scripts/ci/ci.sh
- scripts/launch/connect-to-cluster/default.nix
- stack.yaml
- tools/cardano-sl-tools.cabal
- tools/src/dbgen/CLI.hs
- tools/src/dbgen/Lib.hs
- tools/src/dbgen/Main.hs
- tools/src/dbgen/QueryMethods.hs
- tools/src/dbgen/README.md
- tools/src/dbgen/Rendering.hs
- tools/src/dbgen/Stats.hs
- tools/src/dbgen/Types.hs
- tools/src/dbgen/config.dhall
https://iohk.myjetbrains.com/youtrack/issue/CSL-2185
Adding https://github.com/adinapoli-iohk/dbgen to `cardano-sl` because of the GHC linker bug https://ghc.haskell.org/trac/ghc/ticket/13810
Example usage: `stack exec dbgen -- --config ./tools/src/dbgen/config.dhall --nodeDB db-mainnet --walletDB wdb-mainnet --configPath node/configuration.yaml --secretKey secret-mainnet.key --configProf mainnet_full`
Using current `mainnet.sh` script on `cardano-sl` root:
```
#!/usr/bin/env bash
set -eo pipefail
readonly CLUSTER=mainnet
if [[ "$1" == "-c" ]]; then
shift
rm -Rf                \
db-${CLUSTER}       \
wdb-${CLUSTER}      \
secret-$CLUSTER.key \
logs/$CLUSTER
fi
echo "Launch a single node and connect it to '${CLUSTER}' cluster..."
readonly TMP_TOPOLOGY_YAML=/tmp/topology.yaml
printf …
```
> [CSL-2185] Add dbgen to tools.

- infra/Pos/NtpCheck.hs
- infra/Pos/Slotting/Impl/Ntp.hs
- networking/src/NTP/Client.hs
- networking/src/NTP/Example.hs
I slightly modified some logic to make it possible.
I think this code is still not perfect and there are other things
to improve, but within this issue I am only concerned about `forkIO` usages.
Notable changes (other than actual eliminating `forkIO`):
1. I removed stop button, because it's not needed anymore.
2. I removed `ncClosed`, because it seems to be not needed, because
with current interface it seems to be impossible to access `NtpClient` after
it's closed.
3. I moved `modifyLoggerName` to `spawnNtpClient` and it allowed to remove
ad-hoc `log` and `log'` functions.
> [CSL-2184] Get rid of forks in NTP.Client

- networking/bench/LogReader/Main.hs
- networking/bench/Sender/Main.hs
- networking/cardano-sl-networking.cabal
- networking/test/Test/Util.hs
It turned out that remaining forks are only in tests and benches (there are
a few in OutboundQueue demo which in turn is used only in tests).
So I didn't put much effort into it and left some forks.
I eliminated those which were easy to eliminate.
I've also fixed compilation of some benchmarks.
> [CSL-2200] Get rid of some forks in cardano-sl-networking

- pkgs/default.nix
- wallet-new/server/Cardano/Wallet/Server/Plugins.hs
- wallet-new/server/Main.hs
- wallet/cardano-sl-wallet.cabal
- wallet/node/Main.hs
- wallet/src/Pos/Wallet/Web/Pending/Worker.hs
- wallet/src/Pos/Wallet/Web/Server/Launcher.hs
- wallet/src/Pos/Wallet/Web/Server/Runner.hs
- wallet/src/Pos/Wallet/Web/Sockets/Notifier.hs
All usages of `forkIO` and similar functions in wallet were replaced by functions from `async`.
It's better to review each commit separately, I provided brief explanations in commit messages.
> CSL-2212 Eliminate `forkIO` usages in wallet 

- docs/launcher.md
- docs/network/example-topologies/mainnet-staging.yaml
- scripts/launch/connect-to-cluster/mainnet-staging.sh
- tools/src/launcher/Main.hs
- tools/src/launcher/launcher-config.yaml
There is one thing I am not sure about. Both the old documentation for CLI parameters and the newer `docs/launcher.md` state that not specifying `nodeLogPath` cause launcher to create a temporary file where node output is redirected. After reviewing the code I couldn't find anything resembling that. Instead, apparently the output simply gets passed through to `stdout`/`stderr`. See [here](https://github.com/input-output-hk/cardano-sl/blob/2d23da907fa49436dcdd5911ae712f8aee99bc86/tools/src/launcher/Main.hs#L555) for more details.
> [CSL-1918] Update launcher documentation

- infra/Pos/Network/CLI.hs
- infra/Pos/Network/Types.hs
- lib/src/Pos/Worker.hs
Now monitoring is launched as a separate worker.
I had to make `m` in `StaticPeers` concrete, because otherwise GHC panics.
It should be ok, because we know that it's always IO-based anyway.
Monad abstractions are not essential now, because big refactoring of
monadic approach is coming.
> [CSL-2213] Eliminate fork in Pos.Network.CLI.monitorStaticConfig

- appveyor.yml
Switch cache-s3 base branch to develop, because feature branches are usually closer to it rather than master, in other words a fresh build for a custom branch will fallback on cache for `develop` branch, rather than `master`, thus reducing the delta and completing the build faster.
Also disable `cache-s3` whenever AWS credentials are not available, for example when PR comes from a forked repository.
> Switch cache-s3 base branch to develop

- block/src/Pos/Block/Worker.hs
- infra/Pos/Communication/Protocol.hs
- infra/Pos/DHT/Workers.hs
- infra/Pos/NtpCheck.hs
- infra/Pos/Slotting/Util.hs
- networking/src/Mockable/Concurrent.hs
- networking/src/NTP/Client.hs
- pkgs/default.nix
- ssc/Pos/Ssc/Worker.hs
- update/Pos/Update/Worker.hs
- wallet/src/Pos/Wallet/Web/Pending/Worker.hs
`onNewSlot` worker now takes `ActionTerminationPolicy` as an argument.
Parameters are wrapped in `OnNewSlotParams` type.
`ActionTerminationPolicy` allows to cancel running action when new slot starts.
This feature is used in two workers: block creator and `Update.processNewSlot`.
The detailed analysis was performed here:
https://github.com/input-output-hk/cardano-sl/pull/1163#issuecomment-318136810
In particular it allowed us to avoid `fork` in block creator.
Ideally we also want to separate actual block creation and network stuff which
happens afterwards, but I think it's minor, so it hasn't been done.
> CSL-1606 Find better approach for long running actions passed no 'onNewSlot' 

- appveyor.yml
This will print the contents of log files after the build finishes. Helps with diagnosing build failures.
> [DEVOPS-640] ci: show more logs in windows appveyor build

- block/src/Pos/Block/BlockWorkMode.hs
- docs/exceptions.md
- generator/src/Test/Pos/Block/Logic/Emulation.hs
- infra/Pos/Communication/Types/Protocol.hs
- infra/Pos/DHT/Workers.hs
- lib/src/Pos/Client/CLI/Params.hs
- lib/src/Pos/Diffusion/Full/Types.hs
- lib/src/Pos/Launcher/Runner.hs
- networking/src/Mockable/Concurrent.hs
- networking/src/Mockable/Monad.hs
- networking/src/Mockable/Production.hs
- networking/src/Network/Broadcast/OutboundQueue.hs
- networking/src/Network/Broadcast/OutboundQueue/Demo.hs
- networking/src/Node.hs
- networking/src/Node/Internal.hs
- wallet/src/Pos/Wallet/Web/Methods/Misc.hs
- wallet/src/Pos/Wallet/Web/Mode.hs
Some functions from `Mockable` (`async`, `asyncWithUnmask`, `cancelWith`, `cancel`, `wait`, `waitAny`, `link`, `fork`, `throwTo`) were moved into separate mocks which are not part of `MonadMockable`, because [they usually should be avoided](https://docs.google.com/document/d/1ueuoII0UIkHbj_8eozJ_3InkLTRc0wTSBvu7g6RcrOk/edit#heading=h.4ybdz5elh6jm).
Now it's clearer which code uses these functions.
I also reviewed usages of `async` function, they look safe, except two places for which I created https://iohk.myjetbrains.com/youtrack/issue/CSL-2230.
> CSL-2220 Make it hard to use unsafe functions from Mockable 

- block/src/Pos/Block/Logic/VAR.hs
- block/src/Pos/Lrc/Worker.hs
- core/Pos/Core/Slotting/Types.hs
In lots of cases we have code that goes like this:
```
build (NoRichmen epoch) =
bprint ("no richmen for epoch"%build) epoch
("slogVerifyBlocks: there are no leaders for epoch " %build)
logInfo ("Downloading blockchain dump for epoch "+|epoch|+"")
("Calculated seed for epoch "%build%" successfully")
bprint ("stake distribution for epoch "%build%" is unknown") epoch
```
In all those cases the resulting message says “epoch epoch #N”. Mda.
> Show epochs as “#1”, not “epoch #1”

- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/test/unit/UTxO/Bootstrap.hs
- wallet-new/test/unit/UTxO/DSL.hs
- wallet-new/test/unit/UTxO/Interpreter.hs
- wallet-new/test/unit/UTxO/PreChain.hs
- wallet-new/test/unit/UTxO/Translate.hs
- wallet-new/test/unit/Wallet/Spec.hs
- wallet-new/test/unit/WalletUnitTest.hs
This introduces module `Wallet.Spec`, which is a fairly direct translation of
Duncan's pure wallet specification. The idea is that we should be able to use
this to unit test the "real" wallet later.
This also makes a few minor additional changes:
* The 'isBootstrapTransaction' now just checks if the set of inputs is empty
(that's what it should have done in the first place..)
* Few additional operations on the UTxO in the DSL, including a definition
of equality.
* A 'PreChain' now gets the actual boot transaction rather than its hash,
so that we inspect it to generate arbitrary valid ledgers. (We may have
to add a monad parameter to 'PreChain' though.)
> First version of the pure wallet

- appveyor.yml
Apply new `cache-s3` version that properly handles unicode file names
> Upgrade cache-s3 on AppVeyor

- auxx/Main.hs
- auxx/src/Command/Proc.hs
- auxx/src/Mode.hs
- infra/Pos/Network/Policy.hs
- infra/Pos/Network/Types.hs
- lib/src/Pos/Diffusion/Full.hs
- lib/src/Pos/Diffusion/Full/Delegation.hs
- lib/src/Pos/Diffusion/Full/Ssc.hs
- lib/src/Pos/Diffusion/Full/Txp.hs
- lib/src/Pos/Diffusion/Full/Update.hs
- networking/src/Network/Broadcast/OutboundQueue.hs
The health status was appropriate for relays: if they're at max subscriber capacity, then they're unhealth, and the amazon health status check will reflect that. For other types of nodes, this doesn't fit. An edge node should not be considered unhealthy just because it has 0 subscribers out of 0. 
The auxx topology policies are updated so that MPC messages are actually sent out.
> [CSL-2258] health status determined by topology, auxx topology policies

- infra/Pos/Infra/Configuration.hs
- infra/Pos/NtpCheck.hs
- infra/Pos/Slotting/Impl/Ntp.hs
- networking/src/NTP/Client.hs
- wallet/src/Pos/Wallet/Web/Methods/Misc.hs
See commits' descriptions.
Tested with `api/time/difference` and `/api/v1/node-info` endpoints, now they don't hang.
> [CSL-2184] Fixes in NTP logic after switching to `async`s

- stack.yaml
This is needed to avoid issues like [this](https://github.com/input-output-hk/cardano-sl/pull/2456#issuecomment-364087101).
> Build wallet-new with -Werror

- block/src/Pos/Arbitrary/Block.hs
- block/src/Pos/Arbitrary/Block/Message.hs
- block/src/Pos/Block/Logic/Creation.hs
- block/src/Pos/Block/Logic/Header.hs
- block/src/Pos/Block/Pure.hs
- core/Pos/Binary/Core/Block.hs
- core/Pos/Binary/Core/Blockchain.hs
- core/Pos/Binary/Core/Common.hs
- core/Pos/Core/Block/Genesis/Instances.hs
- core/Pos/Core/Block/Main/Instances.hs
- core/Pos/Core/Block/Union/Instances.hs
- core/Pos/Core/Block/Union/Types.hs
- core/Pos/Core/Common/Types.hs
- core/cardano-sl-core.cabal
- explorer/src/Pos/Arbitrary/Explorer.hs
- lib/src/Pos/Communication/Limits.hs
- lib/src/Pos/Diffusion/Full/Block.hs
- lib/src/Pos/Logic/Pure.hs
- tools/src/blockchain-analyser/Rendering.hs
- update/Pos/Arbitrary/Update/Poll.hs
- wallet-new/test/unit/UTxO/Context.hs
- wallet-new/test/unit/UTxO/Interpreter.hs
- wallet/src/Pos/Wallet/Web/Tracking/BListener.hs
- wallet/src/Pos/Wallet/Web/Tracking/Sync.hs
* remove `BlockHeaderStub` — it was an awkward hack to resolve module cycles, I used a more principled technique
* rewrite `BlockHeader` as an ADT — previously it was an `Either`, and I had plans to refactor it for a long time, but now I simply had to, as `BlockHeader` is now a data family (a type family wouldn't work because we need to declare instances for `Hash BlockHeader`)
> [CSL-2266] Remove BlockHeaderStub

- networking/src/Node/Internal.hs
- pkgs/default.nix
This doesn't appear in actual deployments because the EKG / statsd servers force these values periodically. I noticed it while profiling a special setup which doesn't run these servers.
> [CSL-2145] fix memory leak in time-warp stats

- lib/src/Pos/Launcher/Runner.hs
- lib/src/Pos/Launcher/Scenario.hs
- scripts/launch/ui-simulator.sh
- tools/src/launcher/Main.hs
The node now exits with exit code 20 after a shutdown as it is supposed to.
Launcher exit code handling was refactored a little bit, we do not restart the node if it didn't exit code 20 or was forcefully killed.
> [CSL-1855] Move exitWith to runServer, refactor lancher exit code handling

- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/test/unit/UTxO/DSL.hs
- wallet-new/test/unit/Wallet/Abstract.hs
- wallet-new/test/unit/Wallet/Incremental.hs
- wallet-new/test/unit/WalletUnitTest.hs
This also improves the invariance infrastructure we had for testing, based now
on an abstract notion of a wallet, and then also uses that same infrastructure
for doing comparisons between wallet implementations.
> Introduce incremental version of the pure wallet

- block/src/Pos/Block/Logic/Header.hs
- block/src/Pos/Block/Logic/Util.hs
- block/src/Pos/Block/Network/Logic.hs
- block/src/Pos/Block/Network/Retrieval.hs
- block/src/Pos/GState/BlockExtra.hs
- explorer/src/Pos/Explorer/Socket/Methods.hs
- lib/src/Pos/Diffusion/Full/Block.hs
- lib/src/Pos/Logic/Full.hs
- lib/src/Pos/Logic/Pure.hs
- lib/src/Pos/Logic/Types.hs
This PR attempts to cleanup some things that became redundant after diffusion layer was merged, also it tries to fix several important bugs that were not noticed at the review stage.
At the time of writing, I've pushed two commits. One removes copy-pasted logic that was moved to the diffusion layer, but wasn't cleaned up from `Block.Networking`. Second fixes exception handling that violate the exceptions guideline (`docs/exceptions.md`). It also renames some things and removes `getChainFrom` (which must be implemented in a completely different way and wasn't used anywhere). 
As for bugs, there are two of them:
1. `getHashesRange` is used without `depthLimit` in diffusion layer. This means everybody can query the whole blockchain at once, which is an easy way to attack the node. This …
> [CSL-2089] Fix diffusion layer

- auxx/src/Mode.hs
- block/src/Pos/Block/Slog/Logic.hs
- block/src/Pos/DB/Block.hs
- db/Pos/DB/BlockIndex.hs
- db/Pos/DB/Class.hs
- explorer/src/Pos/Explorer/ExplorerMode.hs
- generator/src/Pos/Generator/Block/Mode.hs
- generator/src/Test/Pos/Block/Logic/Mode.hs
- lib/src/Pos/Launcher/Mode.hs
- lib/src/Pos/Web/Mode.hs
- lib/src/Pos/WorkMode.hs
- tools/src/launcher/Main.hs
- wallet-new/src/Cardano/Wallet/Kernel/Mode.hs
- wallet/src/Pos/Wallet/Web/Mode.hs
- wallet/test/Test/Pos/Wallet/Web/Mode.hs
Copying from YT:
I've managed to speed up application by 30%. I was connecting local node to the mainnet directly, built with -O2 --no-asserts, of course. For the default 2.1k blocks batch it was about 530ms, now it's 390ms. I don't think I can optimize further here, the main bottleneck seems to be the fact we store blocks in files instead of rocksdb. I must admit though, that for now the biggest problem seems to be the server side. Average main retrieval loop length is 36sec, of which verification (850ms) and application (450ms) plus extra related local thing takes about 1.4s. other 34.5 sec are diffusion.getblocks. My networking is good, so i suppose the thing is that server nodes are terribly slow.
> [CSL-2132] Optimize slog apply by batching

- tools/src/launcher/Main.hs
Exit code 20 means graceful shutdown, it shouldn't be reported as a crash.
> [CSL-2309] Launcher: do not report node crash when exit code is 20

- lib/configuration.yaml
That's the version from `1.1.0-staging` branch. After this PR is merged, `1.1.0-staging` won't be needed.
> [DEVOPS-646]  staging wallet:  bump applicationVersion to 6

- auxx/src/Mode.hs
- block/src/Pos/Block/Configuration.hs
- block/src/Pos/Block/Logic/Util.hs
- block/src/Pos/Block/Network/Logic.hs
- block/src/Pos/Block/Slog/Context.hs
- block/src/Pos/Block/Worker.hs
- core/Pos/Core/Configuration/Core.hs
- explorer/src/Pos/Explorer/Web/Transform.hs
- lib/configuration.yaml
- lib/src/Pos/Client/CLI/Util.hs
- lib/src/Pos/Configuration.hs
- lib/src/Pos/Launcher/Configuration.hs
- lib/src/Pos/Launcher/Resource.hs
- lib/src/Pos/WorkMode.hs
- lib/src/Test/Pos/Configuration.hs
- pkgs/default.nix
- txp/Pos/Txp.hs
- txp/Pos/Txp/Configuration.hs
- txp/Pos/Txp/MemState/Class.hs
- txp/Pos/Txp/Toil/Logic.hs
- txp/cardano-sl-txp.cabal
- wallet-new/src/Cardano/Wallet/Kernel/Mode.hs
- wallet/src/Pos/Wallet/Web/Mode.hs
Some options were misplaced, some were obsolete. I recommend reviewing per-commit.
@avieth do you know anything about why `propagationQueueSize` and `defaultPeers` are unused? Is it a bug?
> [CSL-2193] Fix misplaced configuration options

- docs/exceptions.md
There are two reasons to avoid `ExceptT` over `IO`:
* it creates a separate exception handling mechanism overlapping with `IO` exceptions
* it doesn't have a `MonadMask` instance, so `bracket` cannot be used with it
The first reason can be mitigated by making the sets of `ExceptT` and `IO` exceptions disjoint:
* `throwError` must be used only with types that have a `TypeError "Not an exception" => Exception e` instance (requirement of our guidelines)
* `throwM` and `throwIO` require a working `Exception e` instance
This means that the two mechanisms are not in conflict, but actually complement each other. One is useful for checked exceptions and general control flow, while the other — for unchecked exceptions.
As to `MonadMask`, this will be fixed in the next `exceptions` release.
> [CSL-2117] Allow careful usage of ExceptT over IO

- scripts/launch/demo-with-legacy-new-wallet-api.sh
- scripts/launch/demo-with-new-wallet-api.sh
- scripts/launch/demo.sh
- wallet-new/src/Cardano/Wallet/Kernel/Mode.hs
The existing demo-with-new-wallet-api script was starting the new wallet in "legacy mode", where it's no more than a thin wrapper around the old wallet code. The new wallet in legacy mode was just there as a proof of concept. I've renamed that script now to demo-with-legacy-new-wallet-api. The demo-with-new-wallet-api script now runs the new wallet starting the _actual_ new wallet. In order to do this I needed to add the possibility to demo.sh to pass additional arguments to the wallet executable.
This also adds some logging to the BListener hooks so that we can verify that they get called; the log will contain entries such as
```
node3.log:[*production*:ERROR:ThreadId 68] [2018-02-16 16:22:32.01 UTC] walletApplyBlocks not implemented
```
@georgeee , requesting review from you just to …
> Script to run the new wallet with new impl

- delegation/src/Pos/Delegation/Cede/Holders.hs
- delegation/src/Pos/Delegation/Cede/Logic.hs
- delegation/src/Pos/Delegation/Cede/Types.hs
- delegation/src/Pos/Delegation/Logic/Common.hs
- delegation/src/Pos/Delegation/Logic/Mempool.hs
- delegation/src/Pos/Delegation/Logic/VAR.hs
- update/Pos/Update/Logic/Global.hs
- update/Pos/Update/Logic/Local.hs
- update/Pos/Update/Poll/Logic/Apply.hs
- update/Pos/Update/Poll/Logic/Base.hs
Verification for an average mainnet 2100b batch now takes about 0.5-0.6s, which was about 1s before. I've lowered the delegation component overhead by adding the cache into `CedeModifier`, but other optimizations were helpful as well. Update component should be a little bit quicker also now, but it's something like 10%, not much. The bottleneck in update component is still there (every time we apply a block, we call `applyImplicitAgreement`, `applyDepthCheck` and also record block issuance, this is very expensive), and it's really hard to fix (more of an update system design drawback), so I doubt we need to do it right now.
> [CSL-2134] Block verification optimizations

- pkgs/default.nix
- stack.yaml
The bug could cause asynchronous exceptions to be squelched and, for
instance, a fatal exception to not kill the program.
The fix was merged into log-warper-1.8.10, but that includes many new
dependency versions which are not compatible with cardano-sl's current
stack configuration. This patch points to a backport of the log-waprer
fix.
> use log-warper with important bug fix

- infra/Pos/Diffusion/Subscription/Common.hs
- infra/Pos/Diffusion/Subscription/Dns.hs
- infra/Pos/Network/Types.hs
Without this, the subscription thread would die if it tries to resolve
when there's no internet connection.
> [CSL-2301] handle IOExceptions in DNS resolve

- tools/src/launcher/Main.hs
Tested on my mac using staging installer with locally built `cardano-launcher`. It works fine.
> [CSL-2306] Propagate report-server option from launcher to node

- tools/src/launcher/Main.hs
We don't want launcher to crash if reporting fails, it's not fatal.
If exceptions are not caught, launcher will not restart during update
if reporting throws an exception.
> [CSL-2308] Do not crash launcher if node crash reporting fails

- core/Pos/Util/Chrono.hs
- util/Pos/Util/Util.hs
I was using `tMeasure` function in my local tests and decided it's actually pretty nice to have it in master. I've also added usages to some critical places -- LRC, recovery, headers/blocks/txp listeners.
> [CSL-2043] Add tmeasure to critical places

- infra/Pos/DHT/Real/CLI.hs
- infra/Pos/HealthCheck/Route53.hs
- infra/Pos/Network/CLI.hs
- infra/Pos/Statistics/Ekg.hs
- infra/Pos/Statistics/Statsd.hs
- lib/src/Pos/Client/CLI/Options.hs
- networking/bench/Sender/SenderOptions.hs
- pkgs/default.nix
- util/Pos/Util/OptParse.hs
- util/cardano-sl-util.cabal
Replace `fromParsec` function from `serokell-util` into the `cardano` util according the following issue:
https://github.com/serokell/serokell-util/issues/34
> [SRK-91] optimizing dependecies in serokell-util

- appveyor.yml
- node/README.md
- scripts/ci/update-cardano-sl-readme.sh
Required for #2499
* Appveyor account change
* Change appveyor secrets for CI cache
* Remove Slack notification because the encrypted API token won't work.
* Update cache-s3 version
* Add check to not use cache-s3 if aws credentials are missing
> [DEVOPS-679] appveyor account/secrets change (#2595)

- auxx/Main.hs
- auxx/src/Plugin.hs
- auxx/src/Repl.hs
Read from MVar on each print. I expect the overhead to be negligible, but it makes the types simpler.
> Simplify WithCommandAction in auxx

- scripts/launch/demo-with-legacy-new-wallet-api.sh
- scripts/launch/demo-with-new-wallet-api.sh
- wallet-new/README.md
- wallet-new/cardano-sl-wallet-new.cabal
This was needed due to limit on paths size in Windows, and e.g.
`.w\dist\ca59d0ab\build\cardano-node-new\cardano-node-new.exe`
was too long for linker and caused appveyor to fail.
Example of failed build:
https://ci.appveyor.com/project/jagajaga/cardano-sl/build/1.0.21472
> [CSL-2344] Rename `cardano-node-new` executable to `cardano-new`

- appveyor.yml
- node/src/Pos/Wallet/Web/ClientTypes/Functions.hs
- node/src/Pos/Wallet/Web/State.hs
- node/src/Pos/Wallet/Web/State/State.hs
- node/src/Pos/Wallet/Web/State/Storage.hs
- node/src/Pos/Wallet/Web/State/Transactions.hs
- node/src/Pos/Wallet/Web/Util.hs
- pkgs/default.nix
- tools/src/dbgen/Main.hs
- wallet/cardano-sl-wallet.cabal
- wallet/src/Pos/Aeson/Storage.hs
- wallet/src/Pos/Wallet/Web/Account.hs
- wallet/src/Pos/Wallet/Web/Methods/History.hs
- wallet/src/Pos/Wallet/Web/Methods/Logic.hs
- wallet/src/Pos/Wallet/Web/Methods/Payment.hs
- wallet/src/Pos/Wallet/Web/Mode.hs
- wallet/src/Pos/Wallet/Web/Server/Runner.hs
- wallet/src/Pos/Wallet/Web/Tracking/Modifier.hs
- wallet/src/Pos/Wallet/Web/Tracking/Sync.hs
- wallet/test/Migrations.hs
- wallet/test/Test.hs
This PR removes the use of the encoded `CId Addr` from the wallet DB, replacing it with the core type `Address`.
As a consequence, a number of encoding/decoding steps are removed, and we can additionally drop the address cache layer, which further means certain functions can become pure where previously they were effectful.
> Remove the use of encoded Address in the wallet DB

- CODEOWNERS
1. `wallet/purescript` and `genesis-info` folders do not exist anymore.
2. Ownership of whole `wallet/` was passed to wallet developers (e. g.
`cardano-sl-wallet.cabal` previously was owned by me, now it is not).
3. 'Wallet/' entry was removed. Previously some Wallet code was in `lib/`, now
it is not.
> Slightly update CODEOWNERS

- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/src/Cardano/Wallet/Client.hs
- wallet-new/src/Cardano/Wallet/Client/Http.hs
This PR implements a client abstraction for the wallet.
The implementation is left as a stub to be picked up in `CSL-2342`.
The ticket `CSL-2341` can now be implemented in terms of this wallet abstraction, while the actual implementation of the HTTP client can be done in parallel. Testing functions can be written as:
```haskell
testSomeInvariant :: (MonadIO m) => WalletClient m -> m ()
testSomeInvariant wc = ...
```
> [CSL-2340] Implement a client DSL for testing the wallet

- sample-wallet-config.nix
Fixed ekgListen localhost IP to not have an extra octet
> [DEVOPS-713] Fix ekgListen IP address typo in sample wallet config

- tools/src/launcher/Main.hs
- tools/src/launcher/launcher-config.yaml
This makes launcher to pass its log prefix to the node, and use it when it tries to pack log files after node crash.
Note: this requires to change launcher config files accordingly: rename `launcherLogPrefix` to just `logPrefix` and change it's value from `pub` directory to the actual log prefix directory)
> [CSL-2296] Pass launcher's log prefix to the node

- docs/proposals/csl-2104-crypto-scheme-changes-in-address.md
[Rendered](https://github.com/input-output-hk/cardano-sl/blob/37b54d6a8798b367897fb4da7329e88b6ec77b1e/docs/proposals/csl-2104-crypto-scheme-changes-in-address.md) 
This is the first revision of the proposal to modify how we encode & decode the `HDAddressPayload` to take into account needed changes to the crypto scheme, as per @vincenthz 's request.
@georgeee You will notice how I have not introduced a new attribute. I did this because when we spoke about this very same issue with @dcoutts he seemed to prefer to go down this route to avoid any increase in the address size which could cause problems for the short addresses workstream. Happy to discuss with you all contingency plans or amendments to the following proposals.
Let me know what you think!
> [CSL-2104] Propose plan to migrate crypto schemes without breaking backward compatibility

- scripts/common-functions.sh
- scripts/launch/connect-to-cluster/default.nix
- scripts/launch/connect-to-cluster/mainnet-staging.sh
- tools/src/launcher/launcher-config.yaml
Building `connectScripts.mainnetWallet` using `nix-build` results in a binary that won't start because of invalid parameter `--web`. This pull request removes it from the default.nix and all other places I saw it being used with a `git grep "\-\-web" command.
> [DEVOPS-712] removing --web parameter from shell scripts and default.nix

- wallet-new/server/Main.hs
`logException` was used in old `cardano-node`, but for some reason is not used in new `cardano-node`.
> [CSL-2343] Add missing logException to cardano-node

- README.md
This used to be symlink to the file `lib/README.md` so when that changed so did this.
The two files are now different.
> Restore top level README

- core/Pos/Util/Modifier.hs
- node/src/Pos/Wallet/Web/State/State.hs
- wallet/src/Pos/Wallet/Web/Methods/Logic.hs
This PR slightly changes the way which we compute balances, instead of getting wallet's accounts and then summing, the following approach was implemented:
1. take wallet's accounts
2. union their addresses
3. sum coins on these addresses using balance map, which is already presented in `WalletStorage`
> [CSL-2150] Speed up 'getWallet'

- auxx/Main.hs
- explorer/src/explorer/Main.hs
- infra/Pos/Communication/Listener.hs
- infra/Pos/Diffusion/Subscription/Common.hs
- infra/Pos/Diffusion/Subscription/Dht.hs
- infra/Pos/Diffusion/Subscription/Dns.hs
- infra/Pos/Network/CLI.hs
- infra/Pos/Network/Types.hs
- lib/cardano-sl.cabal
- lib/src/Pos/Diffusion/Full.hs
- lib/src/Pos/Launcher/Runner.hs
- lib/src/Pos/Util/OutboundQueue.hs
- networking/cardano-sl-networking.cabal
- networking/src/Network/Broadcast/OutboundQueue.hs
- networking/src/Network/Broadcast/OutboundQueue/ConcurrentMultiQueue.hs
- networking/src/Network/Broadcast/OutboundQueue/Demo.hs
- networking/test/Test/Network/Broadcast/OutboundQueueSpec.hs
- pkgs/default.nix
- wallet-new/src/Cardano/Wallet/Kernel/Mode.hs
- wallet/src/Pos/Wallet/Web/Server/Runner.hs
Previously: when enqueueing the caller gets a `Map NodeId (m (Either SomeException t))` as soon as the outbound queue has completed _enqueueing_. The `m`s in that map will block until the relevant conversation (to the given `NodeId`) has been dequeued and completed.
1. It's impossible to abort an enqueued conversation before it is dequeued.
2. It's impossible to get a hold of the conversation's thread id and, for instance, throw exceptions to it, or link it to another thread in the `Async` style.
This implements the improved interface:
```
enqueue
:: OutboundQ msg nid buck
-> MsgType nid
-> msg a
-> IO [(nid, TVar (PacketStatus a))]
data PacketStatus a = InFlight (Async a) | Pending | Aborted
-- Abort a pending enqueued thing. No-op if it's already in flight.
-- [Not implemented in this …
```
> [CSL-2331] improve synchronisation / communication between outbound queue threads and client threads

- explorer/src/Pos/Explorer/Web/Transform.hs
- infra/Pos/Network/Types.hs
- lib/cardano-sl.cabal
- lib/src/Pos/Util/Mockable.hs
- networking/cardano-sl-networking.cabal
- networking/src/Network/Broadcast/OutboundQueue.hs
- networking/src/Network/Broadcast/OutboundQueue/Demo.hs
- pkgs/default.nix
- util/Pos/Util/Orphans.hs
- util/Pos/Util/Trace.hs
- util/cardano-sl-util.cabal
Purpose: we can use one of these instead of demanding a
`WithLogger`/`HasLoggerName` constraint thereby forcing
us not to use `IO`.
Had to shuffle the Pos.Util.Orphans module around: it defined Mockable
stuff which was dependent upon cardano-sl-networking. My solution is
still awful but the plan is to gradually dump Mockable anyway.
> Pos.Util.Trace module defined

- block/bench/Block.hs
- block/src/Pos/Arbitrary/Block.hs
- block/src/Pos/Arbitrary/Block/Generate.hs
- block/src/Pos/Block/Base.hs
- core/Pos/Arbitrary/Core.hs
- core/Pos/Core/Block/Blockchain.hs
- core/Pos/Core/Slotting/Util.hs
- core/Pos/Core/Txp.hs
- crypto/Pos/Arbitrary/Crypto.hs
- crypto/Pos/Crypto/Signing/Signing.hs
- generator/test/Test/Pos/Block/Logic/CreationSpec.hs
- lib/test/Test/Pos/Types/BlockSpec.hs
- ssc/Pos/Arbitrary/Ssc.hs
- ssc/Pos/Ssc/Base.hs
- txp/Pos/Arbitrary/Txp.hs
- txp/Pos/Txp/Toil/Utxo/Functions.hs
- update/Pos/Arbitrary/Update/Core.hs
- wallet-new/test/unit/UTxO/Context.hs
You can give your ProtocolMagic and ProtocolConstants as regular plain
old vanilla first class values!
The block benchmarks now don't need all of that tedious configuration
stuff.
> [CSL-2328] generate block without configurations

- scripts/check-stack2nix.sh
DEVOPS-752 fix cardano-sl stack2nix job due to loss of anonymous gist creation
https://blog.github.com/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/
> [DEVOPS-752] fix the stack2nix job

- infra/Pos/Reporting/Methods.hs
- tools/src/launcher/Main.hs
If any of the hypthetical log file paths (determined purely from a
LoggerConfig) do not point to existing files, compressLogs will throw an
exception and the real reason for "crashing" will not be apparent: the
program will crash because it could not report the actual crash.
"crashing" for a client apparently means that the node thread finished
before the wallet thread, which is a very loose characterisation... what
if they both finished normally?
> [CSL-2374] ensure log files exist before compressing

- infra/Pos/Util/LogSafe.hs
- infra/cardano-sl-infra.cabal
- lib/src/Pos/Util/Servant.hs
- pkgs/default.nix
- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/server/Cardano/Wallet/API/V1/Swagger.hs
- wallet-new/server/Cardano/Wallet/Server/Plugins.hs
- wallet-new/spec/swagger.json
- wallet-new/src/Cardano/Wallet/API.hs
- wallet-new/src/Cardano/Wallet/API/Indices.hs
- wallet-new/src/Cardano/Wallet/API/Request.hs
- wallet-new/src/Cardano/Wallet/API/Request/Filter.hs
- wallet-new/src/Cardano/Wallet/API/Request/Pagination.hs
- wallet-new/src/Cardano/Wallet/API/Request/Sort.hs
- wallet-new/src/Cardano/Wallet/API/Response.hs
- wallet-new/src/Cardano/Wallet/API/Response/JSend.hs
- wallet-new/src/Cardano/Wallet/API/Types.hs
- wallet-new/src/Cardano/Wallet/API/V1/Parameters.hs
- wallet-new/src/Cardano/Wallet/API/V1/Types.hs
- wallet-new/test/RequestSpec.hs
- wallet/src/Pos/Util/BackupPhrase.hs
- wallet/src/Pos/Wallet/Web/Api.hs
- wallet/src/Pos/Wallet/Web/ClientTypes/Types.hs
- wallet/src/Pos/Wallet/Web/Tracking/Modifier.hs
This is attempt to use same logging mechanism as one we have in old wallet.
Old logging was implemented following such principles:
* Automatic logging - no need to print anything explicitly in implementation.
* No secret info should be revealed (like password) - thus logging requires `instance Buildable` for all types used in API, they should mask content where appropriate.
* No sensitive info should go to public logs (like address) - thus logging in addition requires `instance Buildable (SecureLog ...)` for your type, which masks potentially de-anonymazing info.
* Parameters of request are logged to secret/public logs with `Buildable / Buildable (SecureLog)` instances accordingly. However, responses are not logged at all into public logs (we didn't have time to solve this appropriately …
> [CSL-2347] Add logging of servant requests in wallet new

- binary/Pos/Binary/Class/Core.hs
- binary/Pos/Binary/Class/Primitive.hs
- binary/Test/Pos/Cbor/Canonicity.hs
- binary/Test/Pos/Cbor/RefImpl.hs
- lib/test/Test/Pos/Cbor/CborSpec.hs
- pkgs/default.nix
- stack.yaml
Fixes https://iohk.myjetbrains.com/youtrack/issue/CBR-49.
Details:
- Uses cborg revision with fixes for errors found by auditors
- Completes canonicity checks during decoding of Integer and adds tests for them
- Extends canonicity tests with testing length encoding of collections, strings etc.
> [CBR-49] Fix CBOR decoding issues

- wallet-new/server/Cardano/Wallet/API/V1/LegacyHandlers.hs
- wallet-new/server/Cardano/Wallet/API/V1/LegacyHandlers/Wallets.hs
- wallet-new/src/Cardano/Wallet/API/V1.hs
- wallet-new/src/Cardano/Wallet/API/V1/Accounts.hs
- wallet-new/src/Cardano/Wallet/API/V1/Wallets.hs
- wallet-new/src/Cardano/Wallet/Client/Http.hs
Accounts endpoints were accessible on:
`/wallets/accounts/{{walletId}}/{{accountId}}`
instead of
`/wallets/{{walletId}}/accounts/{{accountId}}`
which is rather unconventional. I believe it was not intended and happened during a refactoring of the routes when creating the Servant client if I am not mistaken. If it's done on purpose, I am curious to know why ^.^ ?
Note that to keep server & client declaration simple, I've introduced a bit of duplication in the routes declarations. It's a small repetition within a same file for a greater good. 
I recall [a nice blog post](http://www.parsonsmatt.org/2018/03/14/servant_route_smooshing.html) on the topic ;), but in the immediate future, we need a fix.
> Fix /accounts endpoints not accessible because of param inversion

- explorer/scripts/launch/qa.sh
- explorer/scripts/launch/staging.sh
- networking/src/Ntp/Client.hs
- tools/src/launcher/launcher-config.yaml
* remove `--no-ntp` from some more scripts
* `NtpDrift` should hold time difference rather than absolute value of it, added some doc strings to `NtpStatuts`.
> [CSL-2346] remove no-ntp & NtpDrift

- appveyor.yml
The `.stack-work` cache was expanding with stale data.
The `cache-s3 --max-size` option prevents build failures when upload volumes exceed AppVeyor limits.
> [DEVOPS-754] AppVeyor: use cache-s3 --max-size=1600MB

- wallet-new/Setup.hs
- wallet-new/default.nix
See `wallet-new/default.nix` documentation.
> wallet-new: Add Setup.hs and default.nix files for easing Cabal usage

- appveyor.yml
- pkgs/default.nix
- util/Pos/Util/Util.hs
- wallet-new/server/Cardano/Wallet/API/V1/LegacyHandlers/Wallets.hs
- wallet-new/server/Cardano/Wallet/API/V1/Swagger/Example.hs
- wallet-new/src/Cardano/Wallet/API/Types/UnitOfMeasure.hs
- wallet-new/src/Cardano/Wallet/API/V1/Migration/Types.hs
- wallet-new/src/Cardano/Wallet/API/V1/Types.hs
- wallet-new/test/MarshallingSpec.hs
- wallet/src/Pos/Wallet/Aeson/Storage.hs
- wallet/src/Pos/Wallet/Web/State/Acidic.hs
- wallet/src/Pos/Wallet/Web/State/State.hs
- wallet/src/Pos/Wallet/Web/State/Storage.hs
- wallet/src/Pos/Wallet/Web/Tracking/Sync.hs
This PR (which is being opened against `feature/CBR-90` is virtually a feature-complete incarnation of CBR-90. *The only thing missing are DB migrations, which will be delivered with CSL-2429. This doesn't hold up the Daedalus team from start integrating the feature, as the V1 API provided here won't change*.
This PR builds upon CSL-2246 (for which the reader is encouraged to defer review up until a PR for `feature/CBR-90` won't land, to get the full picture). In a nutshell we extend the `WalletInfo` section of the `WalletStorage` to keep around some `SyncStatistics` which can be used by the V1 API to compute interesting numbers about a wallet `syncState`, for example:
- `SyncState` (Syncing? Restoring? etc)
- `SyncPercentage` (0 .. 100%)
- `EstimatedCompletionTime` (in milliseconds)
- …
> [CSL-2247] Extend the V1 API to report restoration progress

- docker.nix
The docker init script expects `/wallet` to be the volume the wallet is in. If a user creates a custom wallet config to override the `stateDir`, this ensures that relative `stateDir` will be created within /wallet so state is properly stored in the `/wallet` volume.
> [DEVOPS-719] docker: run cardano-node inside /wallet

- pkgs/default.nix
- scripts/test/wallet/integration.sh
- wallet-new/integration/Error.hs
- wallet-new/integration/Functions.hs
- wallet-new/integration/Main.hs
- wallet-new/integration/Types.hs
- wallet-new/server/Cardano/Wallet/Server/Plugins.hs
- wallet-new/src/Cardano/Wallet/API/V1/Errors.hs
- wallet-new/src/Cardano/Wallet/Client.hs
This PR fixes behaviour of `guard` in integration tests. Previously `guard` was using implementation of `Alternative IO` which would fail : 
```haskell
-- | @since 4.9.0.0
instance Alternative IO where
empty = failIO "mzero"
(<|>) = mplusIO
```
and now integration tests are wrapped with `MaybeT` which returns `Nothing` if `guard` fails and thus implements correct behaviour for our use case - which is: "Ignore actions which don't satisfy `guard`". We can simply achieve this with `catMaybes` or similar.
Issue: https://iohk.myjetbrains.com/youtrack/issue/CSL-2433
_Note that PR will be merged to `feature/csl2398-integration-ci` branch and the goal of this PR is to have isolated place to review yt issue and discuss things._
> [CSL-2433] Wrap actions with MaybeT to enable gaurds to exit gracefully

- lib/configuration.yaml
_Contents_
0. We now have a Linux wallet -- which needs its own configuration keys.  Add them.
0. ~Mainnet now runs with block minor version 1 -- set that as baseline.~
> [DEVOPS-13] Linux wallet configuration key

- docs/code-organisation-guidelines.md
For the last 4 weeks I have been helping the people doing the formal specifications figure out what the cardanol-sl code currently does. This task has been made much more difficult than it should have been due to the somewhat disorganised nature of the current code base. The code organisation guidelines in this PR is a result of thinking about what would have made my code forensics work easier and reflecting on what code organisation practices have worked on other projects I have been involved in.
This is totally up for for discussion. I seek feedback.
> Add code organisation guidelines document

- wallet-new/integration/Functions.hs
The actual problem was because invariant:
```haskell
checkInvariant
(txAmount result == expectedAmount)
(InvalidTransactionState result)
```
was assuming `txAmount` field in `Transaction` type will be equal to money we were planning to send - but actually `txAmount` will be sum of amounts in sources addresses. System is spending full amount from sources addresses and returning extra money to the sources (via outputs). In this case `txAmount` will match sources amount, not amount that we planned to send.
Example: We have account X with Y amount of money. We would like to send Z to Bob, from account X. In this example we assumed that `txAmount` will be equal to `Z`. But actually `txAmount` will be equal to Y. 
Invariant was changed so that now it calculates and checks is fee amount …
> [CSL-2443] Fix PostTransaction test invariant

- .gitignore
- pkgs/default.nix
- wallet-new/integration/Main.hs
- wallet-new/server/Cardano/Wallet/API/V1/LegacyHandlers/Transactions.hs
- wallet-new/src/Cardano/Wallet/API/V1/Errors.hs
- wallet/cardano-sl-wallet.cabal
- wallet/src/Pos/Wallet/Web/Methods/Payment.hs
- wallet/src/Pos/Wallet/Web/State/State.hs
- wallet/src/Pos/Wallet/Web/State/Storage.hs
- wallet/test/Test/Pos/Wallet/Web/Methods/PaymentSpec.hs
This PR builds on top of the work I did as part of `feature/CBR-90` to disallow making new payments whilst the _source_ wallet is being restored. This extends what we have been doing already in the frontend to the backend, to prevent exchanges from shooting on their feets.
It doesn't assume prior knowledge over the work on CBR-90, thus is suitable for reviewing in a black-box fashion by chaps like @KtorZ and @parsonsmatt . 
You will notice how there are no tests worth their name for the V1 API. Reason is twofold:
- We need proper support in the `deterministicTests`, for which I have logged CBR-184.
- The implementation for the V1 piggybacks on V0 (for which we have tests), therefore it should be enough to assess by code audit that the V1 shim does the right thing, and in terms of testing …
> [CSL-2442] Prevent the backend from making payments whilst a wallet is restoring

- explorer/src/Pos/Explorer/Web/Server.hs
While waiting for a better design / design revision, this will most likely fix CPU issues of
iterating over huge list of transactions for some addresses. The pagination of those addresses
happens client-side, in browser and forces the server to fetch and return all transactions
summaries on each page load; leading to really heavy load in some cases.
> [CBR-119] Ugly fix to avoid some OOM problems on Explorer

- default.nix
This will allow the Daedalus installers build (both nix-build and make-installers) to easily get the cardano-sl version.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-59
New feature (non-breaking change which adds functionality).
nix build -f default.nix daedalus-bridge
cat result/version
> [DEVOPS-59] nix: Add daedalus-bridge.version attribute

- infra/Pos/Reporting/Methods.hs
- infra/cardano-sl-infra.cabal
- pkgs/default.nix
- stack.yaml
- tools/src/launcher/Main.hs
- wallet/src/Pos/Wallet/Web/Tracking/BListener.hs
This PR closes the `git-flow` circle by merging the (only) [cardano-specific hotfix](https://github.com/input-output-hk/cardano-sl/pull/2674) shipped as part of `release/1.1.1` into `develop`, so that it can be incorporated into `release/1.2.0`. 
In order to do so, I have done something maybe controversial, which is reverting some [prior work in this area](https://github.com/input-output-hk/cardano-sl/commit/8e69119f58ff0a71cb5ba1efdc949e3cabf03508#diff-7a262de0838d24280027efe3fb946fab) and then cherry-picking @avieth 's commit on top of it. My rationale was that the reverted commit was pretty much untested, whereas Alex's fix has been shipped in the fielde and it proved to be reliable.
Due to this consideration, I preferred to unwind a piece of untested work in favour of a tested one, …
> Backport PR#2674 [CSL-2374] from `release/1.1.1` to `develop`

- wallet-new/integration/Functions.hs
- wallet-new/src/Cardano/Wallet/Client.hs
Requests will return max 10 results per page by default. That was the reason for https://iohk.myjetbrains.com/youtrack/issue/CSL-2474 error which was temporarely workarounded by increasing to return 50 results instead of 10.
This issue recursive fetches all results from requests that have more pages and return results to the caller (integration tests)
Possible improvements:
- page requests can be made in parallel. This would slightly speed up long test cases (100+ actions) which usually have more then 1 page per request.
https://iohk.myjetbrains.com/youtrack/issue/CSL-2476
Running integration tests (` ./scripts/test/wallet/multi-integration.sh 120` or `stack exec cardano-integration-test` with 1000 actions per test https://github.com/input-output-hk/cardano-sl/blob/akegalj/csl2476-auto-pag …
> Auto paginate request in integration tests

- wallet-new/cardano-sl-wallet-new.cabal
Fixes the following warning when building with stack
```
wallet-new/cardano-sl-wallet-new.cabal:
- In wallet-new-specs component:
WalletHandlersSpec- In wallet-new-specs component:
WalletHandlersSpec- In wallet-new-specs component:
WalletHandlersSpec- In wallet-new-specs component:
WalletHandlersSpec- In wallet-new-specs component:
WalletHandlersSpec
Missing modules in the cabal file are likely to cause undefined
reference errors from the linker, along with other problems.
```
> cardano-sl-wallet-new.cabal: Fix cabal build warning

- wallet-new/docs/.gitignore
- wallet-new/docs/references.bib
- wallet-new/docs/spec.tex
This describes how the wallet can be extended to track metadata, and how this can be instantiated to provide the transaction history required by the wallet V1 API.
> [CBR-60] Wallet spec: tracking metadata (transaction history)

- wallet-new/integration/Main.hs
- wallet-new/server/Cardano/Wallet/API/V1/LegacyHandlers/Wallets.hs
- wallet-new/src/Cardano/Wallet/API/V1/Errors.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Error.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Legacy.hs
This issue:
* changes error when trying to create a wallet with already used mnemonic
* hides information that mnemonic is duplicated (see comment here https://iohk.myjetbrains.com/youtrack/issue/CSL-2431#comment=93-19922 )
* adds error type to `V1.WalletError` and `WalletLayerError` for this error
By code review we are certain old `Wallet with that mnemonics already exists` error is thrown only from `V0.newWallet` and `V0.restoreWalletFromSeed` and its caught at all places. Alternativelly, to be extra safe, we could catch and modify V0 errors here https://github.com/input-output-hk/cardano-sl/blob/feature/csl2431-newwallet-error/wallet-new/server/Cardano/Wallet/Server/Plugins.hs#L142 : 
```haskell
. try
. fmap (join . over _Left V0ToV1Error)
...
where
V0ToV1Error (e :: V0.WalletError) = …
```
> [CSL-2431] Change error in V1 when mnemonic phrase had already been used

- pkgs/default.nix
- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/src/Cardano/Wallet/Kernel.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/AcidState.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/AcidStateUtil.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/BlockMeta.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Create.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Delete.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Read.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Update.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/InDb.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Resolved.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Spec.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Update.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/TxMeta.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Util/AcidState.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Util/IxSet.hs
- wallet-new/src/Cardano/Wallet/Kernel/PrefilterTx.hs
- wallet-new/src/Cardano/Wallet/Kernel/Types.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
- wallet-new/test/unit/UTxO/Interpreter.hs
NOTE: This is really only a single commit, but it depends on https://github.com/input-output-hk/cardano-sl/pull/2779 .
This provides the design of the acid-state layer. There are still some holes in the implementation but the layer itself is spec'ed out and can be reviewed. This PR makes no changes to existing code (provides no integration), but provides a whole series of new modules under the `Cardano.Wallet.Kernel.DB.*` module prefix. 
Once this PR is merged, this closes https://iohk.myjetbrains.com/youtrack/issue/CSL-2105 , but also https://iohk.myjetbrains.com/youtrack/issue/CSL-2409 , https://iohk.myjetbrains.com/youtrack/issue/CSL-2408 and https://iohk.myjetbrains.com/youtrack/issue/CSL-2411 .
> WIP: [CSL-2105] acid state design

- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/src/Cardano/Wallet/WalletLayer/Error.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Legacy.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Legacy/Info.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Legacy/Settings.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/QuickCheck.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Types.hs
Implement WalletPassiveLayer for settings and info
https://iohk.myjetbrains.com/youtrack/issue/CSL-2338
Not applicable.
Not applicable.
> [CSL-2488] Implement WalletPassiveLayer for settings and info.

- .gitignore
- appveyor.yml
- default.nix
- release.nix
- scripts/common-functions.sh
- scripts/launch/connect-to-cluster/default.nix
- scripts/launch/demo-cluster/default.nix
- scripts/launch/demo.sh
- scripts/test/wallet/integration/build-test.nix
- scripts/test/wallet/integration/default.nix
Adds nix framework for launching demo cluster and running integration tests.
Remaining issues:
* derivation in release.nix that hydra can build for any code changes that could affect tests.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-798
`nix-shell --pure --run $(nix-build -A walletIntegrationTests)` runs the script exiting with status code of integration tests script
`nix-shell --pure --run $(nix-build -A demoCluster)` launches cluster and keeps running until you hit `ctrl-c`
`nix-build -A buildWalletIntegrationTests` runs tests in build environment isolated from network. Builds are cached so it will just return the derivation if it doesn't need to rebuild.
Note: it's expected to fail the tests because of a broken test case that @parsonsmatt is working on.
> Devops 798 integration tests

- appveyor.yml
- auxx/cardano-sl-auxx.cabal
- binary/cardano-sl-binary.cabal
- block/cardano-sl-block.cabal
- client/cardano-sl-client.cabal
- core/cardano-sl-core.cabal
- crypto/cardano-sl-crypto.cabal
- db/cardano-sl-db.cabal
- delegation/cardano-sl-delegation.cabal
- explorer/cardano-sl-explorer.cabal
- generator/cardano-sl-generator.cabal
- infra/cardano-sl-infra.cabal
- lib/cardano-sl.cabal
- lrc/cardano-sl-lrc.cabal
- networking/cardano-sl-networking.cabal
- node/cardano-sl-node.cabal
- pkgs/default.nix
- ssc/cardano-sl-ssc.cabal
- tools/cardano-sl-tools.cabal
- txp/cardano-sl-txp.cabal
- update/cardano-sl-update.cabal
- util/cardano-sl-util.cabal
- wallet-new/cardano-sl-wallet-new.cabal
- wallet/cardano-sl-wallet.cabal
For the 1.2.0 release branch:
- Applies a fix for AppVeyor builds (DEVOPS-817).
- Bumps the cabal version so that tools report the correct version.
> [DEVOPS-817] Fix appveyor build on release branch and bump cabal version

- explorer/src/Pos/Explorer/ExplorerMode.hs
- networking/src/Mockable/Monad.hs
There were some missing instances causing compilation failures. This PR fixes them.
None
`stack build --fast --bench --no-run-benchmarks --test --no-run-test` before this PR will fail with `No instance Ord (ThreadId (.........))` error. After this PR they succeed.
> Fix develop build

- default.nix
MacOS builds were failing on hydra, e.g.https://hydra.iohk.io/build/121437/nixlog/1
This was previously worked around by weeding out dependencies but disabling shared libraries also solves the problem.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-831
> [DEVOPS-831] Static linking fixes nix build on macOS Sierra

- node-ipc/node-ipc.cabal
Cabal was giving a warning on a `ChangeLog.md` file listed in the cabal file but not present in the repo.
Its a one line diff!
> node-ipc: Remove ChangeLog.md entry from cabal file

- pkgs/generate.sh
Fixes this error:
error: Nix database directory ‘/nix/var/nix/db’ is not writable: Permission denied
Nix 2.0 no longer needs or sets the `NIX_REMOTE` variable, but when using nix-build (1.11.15) inside a shell it requires the variable.
So this provides a default for `NIX_REMOTE=daemon`.
The `NIX_REMOTE` variable setting can be removed completely when we update our nixpkgs pin to something that includes Nix 2.0.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-822
./pkgs/generate.sh
> [DEVOPS-822] pkgs/generate.sh: Work with nix 2.0

- wallet-new/docs/spec.tex
- wallet-new/test/unit/Wallet/Inductive/Invariants.hs
- wallet-new/test/unit/Wallet/Rollback/Full.hs
The definition of `updateExpected` has a silly bug. This fixes it, and re-enables the invariant that was previously broken.
> [CBR-266] Fix expected UTxO in applyBlock/rollback

- wallet-new/docs/spec.tex
- wallet-new/test/unit/Test/Spec/Models.hs
- wallet-new/test/unit/UTxO/DSL.hs
- wallet-new/test/unit/Wallet/Abstract.hs
- wallet-new/test/unit/Wallet/Basic.hs
- wallet-new/test/unit/Wallet/Incremental.hs
- wallet-new/test/unit/Wallet/Inductive.hs
- wallet-new/test/unit/Wallet/Inductive/Interpreter.hs
- wallet-new/test/unit/Wallet/Inductive/Invariants.hs
- wallet-new/test/unit/Wallet/Rollback/Basic.hs
- wallet-new/test/unit/Wallet/Rollback/Full.hs
This adds the final rollback invariants. It relies on https://github.com/input-output-hk/cardano-sl/pull/2930 because without that fix the invariants are not true. It also extends the interpreter to give a more informative history when an invariant breaks.
> [CBR-147] Rollback invariants

- binary/Pos/Binary/Class/Primitive.hs
- lib/src/Test/Pos/Helpers.hs
The CBOR serialisation tests in `Test.Pos.Cbor.CborSpec` were failing very occasionally running `binaryTests` on `Attributes X1`. One of the `binaryTests` is a canonicity test that uses `perturbCanonicity`. In this case it was duplicating the last element of the `Map` underlying `UnparsedFields`. Due to a small bug in `deserializeOrFail` that didn't return all leftover bytes from the input this was decoded fine, breaking canonicity. This has been fixed and tested against various previously failing seeds.
[CDEC-320](https://iohk.myjetbrains.com/youtrack/issue/CDEC-320)
- [~] 🏭 Refactoring that does not change existing functionality …
> [CDEC-320] Investigate Cbor serialisation failure in CI. 

- default.nix
- ghc-8.0.2-darwin-rec-link.patch
GHC links the full transitive closure over the dependencies when building dynamic libraries.
This quickly leads to a large number of referenced dynamic libraries, which all count towards the load command size limit on macOS. Which manifests in the linker refusing to load the library with: malformed mach-o: load commands size (32864) > 32768.
The macOS linker is capable of recursively linking dylibs, and as such only direct ones would be needed. However computing the direct dependencies in GHC at link time is rather complex, due to GHC's aggressive cross-library inlining.
We can however use the linker to dead strip dynamic lirbaries that are unused. As such we drop all dynamic lirbaries that are not referenced.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-850
> [DEVOPS-850] dead strip unused dylibs on macOS

- scripts/launch/demo.sh
- tools/src/launcher/Main.hs
- tools/src/launcher/launcher-config.yaml
A bit ugly but it's not like the `cardano-launcher` gives us more flexibility. This will now at least check that files are there and regenerate all of them if one is missing. 
Note that I've removed the `tlsPath` option that I previously added to the launcher config to avoid duplicating information here. The downside is that it becomes complicated if we need to generate certificates in different directories (which we don't do). The configs in the `daedalus` 's PR will need to be adjusted as well.
[[CBR-265]](https://iohk.myjetbrains.com/youtrack/issue/CBR-265)
Start a cluster using the launcher (`./scripts/launcher/demo-with-wallet-api.sh`) in different scenario (with no `./run/tls-files` folder, with missing files in that folder, or with all files).
> [CBR-265] Check for each file required for TLS instead of only the parent dir

- infra/Pos/Network/Types.hs
- infra/Pos/Reporting/Methods.hs
- infra/Pos/StateLock.hs
- infra/Pos/Util/TimeLimit.hs
- infra/cardano-sl-infra.cabal
- node-ipc/node-ipc.cabal
- node-ipc/src/Cardano/NodeIPC.hs
- txp/Pos/Txp/MemState/Metrics.hs
- util/Pos/Util/Log.hs
- util/Pos/Util/LogSeverity.hs
- util/Pos/Util/LoggerConfig.hs
[WIP]: cardano-sl-infra moving to use abstract logging interface (Pos.Util.Log)
task: CBR-207, user story: CBR-97
- [ x ] 🛠 New feature (non-breaking change which adds functionality)
- [ x ] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [ x ] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [ ~ ] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline …
> cardano-sl-infra: replace logging with cardano-sl-util (Pos_Util_Log)

- binary/cardano-sl-binary.cabal
- lib/bench/Bench/Pos/Criterion/FollowTheSatoshiBench.hs
- lib/cardano-sl.cabal
- pkgs/default.nix
- wallet-new/bench/Bench/Cardano/Wallet/Config/Endpoints.hs
- wallet-new/bench/Bench/Cardano/Wallet/Config/Wallets.hs
I thought benchmark programs were being built in CI but obviously they are not or these issues would have been found before they were merged to develop.
This may actually be due to a [bug in stack](https://github.com/commercialhaskell/stack/issues/4045).
N/A
Ran:
```
stack test && stack bench --no-run-benchmarks
```
> Resurrect broken benchmark programs

- wallet/src/Pos/Util/Mnemonics.hs
See haskoin@f00f09d392ca38bb4b68a65c8515ed70f8986841.
I've came to the conclusion that it is safe to apply this fix. The fix only touches the `numCS` which is used internally in the `fromMnemonic` function to compute a number from a checksum to compare the computed checksum from the generated entropy with the one that is part of the mnemonic words (words actually represent the entropy and its checksum). 
Beside, the patch affects a pattern-match result that solely depends on the length of the checksum, and only matters when the length is a multiple of `8`.
Hence:
```hs
-- We support mnemonic phrase where entropy can be of any length, multiple of 32, 
-- from 0 (alas :'( ) to 512 bits.
-- i.e. [0,32,64,96,128,160,192,224,256,288,320,352,384,416,448,480,512]
let acceptedLength = [ 32 * n | …
```
> [CO-298] Apply fix from haskoin on mnemonic checksum calculation

- lib/src/Pos/Web/Server.hs
- lib/src/Pos/Web/Types.hs
- wallet-new/src/Cardano/Wallet/Server/CLI.hs
`--no-client-auth` to disable client certificate verification by the wallet backend.
This will re-enable the behavior in place before client certificate verification was introduced. By default, it is turned on (to be discussed).
> /!\ TODO /!\ ops remaining work in the installers to make use of this flag.
[[DEVOPS-879]](https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-879)
> [DEVOPS-879] Introduce '--no-client-auth' flag 

- default.nix
- scripts/ci/ci.sh
Benchmarks were not being built in CI and therefore were getting broken without anyone noticing.
This enables building (but not running) of benchmarks.
The CI for this PR should successfully fail because it doesn't include the merge of #3005.
I would like some feedback about the defaults in nix. Should the `enableBenchmarks` arg default to true or false? Should there be separate derivations with benchmarks enabled?
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-632
nix-build -A cardano-sl-wallet-new --arg enableBenchmarks true
> [DEVOPS-632] ci: Build benchmarks in hydra and buildkite

- block/cardano-sl-block.cabal
- block/src/Pos/Block/Logic/Creation.hs
- block/test/Test/Pos/Block/Arbitrary.hs
- client/src/Pos/Client/Txp/History.hs
- core/cardano-sl-core.cabal
- core/src/Pos/Core/Block.hs
- core/src/Pos/Core/Block/Constructors.hs
- core/src/Pos/Core/Delegation/HeavyDlgIndex.hs
- core/src/Pos/Core/Ssc.hs
- core/src/Pos/Core/Ssc/CommitmentAndOpening.hs
- core/test/Test/Pos/Core/Gen.hs
- core/test/cardano-sl-core-test.cabal
- delegation/src/Pos/Delegation/Types.hs
- explorer/src/Pos/Explorer/TestUtil.hs
- generator/src/Pos/Generator/Block/Logic.hs
- lib/src/Pos/DB/DB.hs
- lib/test/Test/Pos/Ssc/SeedSpec.hs
- lib/test/Test/Pos/Types/BlockSpec.hs
- pkgs/default.nix
- ssc/Pos/Arbitrary/Ssc.hs
- ssc/Pos/Ssc/Base.hs
- ssc/Pos/Ssc/Worker.hs
- wallet-new/test/unit/UTxO/Context.hs
When `Test.Pos.Core.Gen` was added to `cardano-sl-core-test`, dependencies on `cardano-sl-delegation`, `cardano-sl-block`, and `cardano-sl-ssc` were introduced. This introduced potential dependency cycles.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-371
Since this PR just moves code around between packages / directories, it relies on existing tests.
> [CDEC-371] Remove unnecessary `core-test` dependencies

- block/bench/LICENSE
- block/bench/Setup.hs
- block/bench/cardano-sl-block-bench.cabal
- block/cardano-sl-block.cabal
- block/test/Test/Pos/Block/Arbitrary/Generate.hs
- default.nix
- explorer/bench/Bench/Pos/Explorer/ServerBench.hs
- lib/bench/Bench/Configuration.hs
- lib/bench/Bench/Pos/Criterion/FollowTheSatoshiBench.hs
- pkgs/default.nix
- stack.yaml
#3008 added the `buildWithBenchmarks` function to `default.nix`, but only enabled it for `cardano-sl-wallet-new`. This enables it for all packages with `benchmark` sections in their cabal file.
[CDEC-370](https://iohk.myjetbrains.com/youtrack/issue/CDEC-370)
> [CDEC-370] Enable benchmarks for all packages with benchmarks

- block/test/Test/Pos/Block/Arbitrary.hs
Fix `stack build`.
N/A
- [x ] 🐞 Bug fix (non-breaking change which fixes an issue)
> Remove unused import

- docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md
Else you will run into the following error:
> No compiler found, expected minor version match with ghc-8.0.2 (x86_64) (based on resolver setting in /home/user/.opt/cardano-sl/stack.yaml).
>
> To install the correct GHC into /home/user/.stack/programs/x86_64-linux-nix/, try running "stack setup" or use the "--install-ghc" flag. To use your system GHC installation, run "stack config set system-ghc --global true", or use the "--system-ghc" flag.
> docs: run `stack setup` to install `ghc` first.

- tools/src/topology-gen/Main.hs
This tool can be used to help with the construction of the static routing for core and relay nodes (that live in topology.yaml files).
The idea is that routes are constructed manually but checked automatically. I've also extended it slightly to emit the routes in a yaml form close to what we need for the topology.yaml, but some extra work would be needed to make this actually properly automatic, since it does not contain the full info yet.
The code currently contains a specific routing pattern for:
* 7 core nodes
* 7 relays,
* each core sends to 2 other core nodes, with a primary and secondary
* each relay sends to 2 other relay nodes, with a primary and secondary
* each core sends to 1 relay nodes, with a primary and secondary
* each relay sends to 1 core nodes, with a primary and …
> Network topology generator

- explorer/frontend/default.nix
yarn2nix needs to have a `src` argument to generate its nix expression (at evaluation time). It's not good if building `src` depends on building cardano-sl.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-916
nix-instantiate -A cardano-sl-explorer-frontend
nix-build -A cardano-sl-explorer-frontend
ls -l ./result
> [DEVOPS-916] nix: Fix slow eval of cardano-sl-explorer-frontend

- auxx/Main.hs
- auxx/src/Command/BlockGen.hs
- auxx/src/Mode.hs
- default.nix
- explorer/src/explorer/Main.hs
- generator/src/Test/Pos/Block/Logic/Mode.hs
- generator/test/Test/Pos/Binary/CommunicationSpec.hs
- lib.nix
- node-ipc/cardano-sl-node-ipc.cabal
- node/Main.hs
- pkgs/default.nix
- release.nix
- scripts/ci/ci.sh
- scripts/set-git-rev/default.nix
- scripts/set-git-rev/set-git-rev.hs
- stack.yaml
- tools/src/launcher/Main.hs
- util/Pos/Util/CompileInfo.hs
- util/Pos/Util/CompileInfoGit.hs
- util/cardano-sl-util.cabal
- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/generate-swagger-file/Main.hs
- wallet-new/server/Main.hs
- wallet/cardano-sl-wallet.cabal
- wallet/test/Test/Pos/Wallet/Web/Methods/PaymentSpec.hs
This solves the problem of nix rebuilds with identical sources but different git revisions. It doesn't require creating extra cabal projects. The code in utils gets a little simpler as well. The code could get even more simpler if `HasCompileInfo` were removed -- maybe I should do that?
There is also the addition of an `all-cardano-sl` attribute.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-810
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-908
nix-build -A cardano-sl-auxx
./result/bin/cardano-auxx --version
nix-build -A cardano-sl-auxx --argstr gitrev 1234
./result/bin/cardano-auxx --version
> [DEVOPS-810] [DEVOPS-908] Inject gitrev using file-embed

- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/integration/TransactionSpecs.hs
- wallet-new/integration/WalletSpecs.hs
- wallet-new/src/Cardano/Wallet/API/Response.hs
- wallet-new/src/Cardano/Wallet/API/V1/Errors.hs
- wallet-new/src/Cardano/Wallet/API/V1/Generic.hs
- wallet-new/src/Cardano/Wallet/API/V1/Headers.hs
- wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers/Addresses.hs
- wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers/Transactions.hs
- wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers/Wallets.hs
- wallet-new/src/Cardano/Wallet/API/V1/Migration/Types.hs
- wallet-new/src/Cardano/Wallet/API/V1/Swagger.hs
- wallet-new/src/Cardano/Wallet/API/V1/Swagger/Example.hs
- wallet-new/src/Cardano/Wallet/API/V1/Types.hs
- wallet-new/src/Cardano/Wallet/Client.hs
- wallet-new/src/Cardano/Wallet/Server/Plugins.hs
- wallet-new/test/MarshallingSpec.hs
The example accountId from the API doc isn't much relevant and reflects an invalid value
https://iohk.myjetbrains.com/youtrack/issue/CO-319
1) Run a cardano-node
2) Visit https://localhost:8091/docs/v1/index/ - you will see changes showed bellow
3) Roundtrip tests pass (the screenshot bellow)
`accountIndex` in request body shows correct value range
`accountIndex` on description on the right picks correct value (not bellow the minimum)
`accountId` (same thing as `accountIndex`) in request params shows correct value range
roundtrip tests
@KtorZ I wonder why did we ended up with `accountId` and `accountIndex` json keys for the same thing. Is it still too late to unify it? (it would be a breaking change for exchanges)
> Akegalj/co 319/swagger account index

- core/src/Pos/Core/Configuration/Core.hs
Remove field accessors from `GenesisConfiguration`
https://iohk.myjetbrains.com/youtrack/issue/CDEC-299
> Remove field accessors from `GenesisConfiguration`

- explorer/frontend/default.nix
Hydra is not happy with yarn2nix. For some reason `scripts/ci/check-hydra.sh` does not find the problem. This change passes `package.json` and `yarn.lock` directly to `mkYarnPackage`.
```
Errors occurred at 2018-06-27 01:49:32.
hydra-eval-jobs returned exit code 1: access to path '/nix/store/aq5cnwcaksc3j57zm3a80iv50ia8h3b4-frontend/package.json' is forbidden in restricted mode
(use '--show-trace' to show detailed location information)
```
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-916
> [DEVOPS-916] hydra: Fix cardano-sl-explorer-frontend eval

- scripts/ci/ci.sh
The all-cardano-sl collection is taking 3 hours to build and test on our macOS build agents.
This change cuts the build down to just daedalus-bridge, which is the wallet and tools necessary to run Daedalus on macOS.
The relevant test suite packages will still be executed because they are added as cabal package dependencies.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-908
Examine Buildkite build of this branch and see if it takes less than 3 hours.
https://buildkite.com/input-output-hk/cardano-sl/builds?branch=devops-908-buildkite-faster
> [DEVOPS-908] BuildKite: speed up macOS builds

- core/src/Pos/Core/Configuration/Core.hs
This reverts commit b258f926580387f113d746f7f897444c0dcfc570 from PR #3140.
The record fields are used for parsing of `lib/configuration.yaml`.
> Revert "[CDEC-299] Remove field accessors for `GenesisConfiguration`"

- scripts/launch/connect-to-cluster/default.nix
macOS doesn't have a glibcLocales package. It was saying:
in job 'mainnet.connectScripts.wallet.x86_64-darwin':
cannot coerce null to a string, at /nix/store/6pvxqra7xrw29wdlrbpc8hbm1k5vhqvq-8a30d0e9b856466e4844a0da74b2b1c4818af5f647c3979d9f381e7eafadd107-8015a00/scripts/launch/connect-to-cluster/default.nix:70:63
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-877
nix-instantiate release.nix --argstr system x86_64-darwin -A mainnet.connectScripts.wallet.x86_64-darwin
nix-build release.nix -A mainnet.connectScripts.wallet.x86_64-linux -o connect-mainnet.sh
./connect-mainnet.sh
> [DEVOPS-877] scripts/launch/connect-to-cluster: fix eval on macOS

- lib/cardano-sl.cabal
- lib/src/Pos/Launcher/Configuration.hs
- lib/test/Test/Pos/Launcher/ConfigurationSpec.hs
- pkgs/default.nix
This solves the recent problem with `lib/configuration.yaml` not being parsable anymore.  This happend because core team rightly removed some partial accessor functions.   I just updated the yaml file and I alsoI added a test.  This is a short term solution, long term I think we should write `FromJSON` instances for the types we are reading, because just removing fields from config file will make it less and less readable.  @erikd it's up to you to decide if this maintaining `FromJSON` instances is worth the effort vs readability of the config file.  I guess this really depends how many more partial functions we will remove.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-405
> [CDEC-405]

- default.nix
- lib.nix
- scripts/launch/connect-to-cluster/default.nix
- scripts/launch/demo-cluster/default.nix
- scripts/test/stylish.nix
stylish-haskell needs to be run under a utf-8 locale. Otherwise it will crash leaving a partially written file.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-936
cat $(nix-build release.nix -A tests.stylishHaskell)/stylish.diff
> [DEVOPS-936] Fix tests.stylishHaskell output when files are utf-8

- default.nix
- explorer/frontend/default.nix
- lib.nix
- scripts/set-git-rev/default.nix
- scripts/test/hlint.nix
- scripts/test/shellcheck.nix
- scripts/test/stylish.nix
The change to `justStaticExecutablesGitRev` broke the `.env` attribute of haskell derivations.
Also there is a new nixpkgs lib function for filtering sources.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-810
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-937
nix-shell default.nix -A cardano-sl-wallet-new.env
nix-build -A all-cardano-sl
> [DEVOPS-810] Fix nix-shell env

- explorer/cardano-sl-explorer.cabal
- explorer/test/Test/Pos/Explorer/Arbitrary.hs
- explorer/test/Test/Pos/Explorer/Identity/BinarySpec.hs
- infra/src/Pos/Infra/Communication/Types/Relay.hs
- pkgs/default.nix
As it stands, the `Arbitrary` instances for data types in `explorer` all exist in `explorer/src/Pos/Arbitrary` when they should actually be in `explorer/test/Test/Pos/Explorer/Arbitrary`. The PR appropriately moves the `Arbitrary` instances.
[https://iohk.myjetbrains.com/youtrack/issue/CDEC-375](https://iohk.myjetbrains.com/youtrack/issue/CDEC-375)
> [CDEC-375] Move Arbitrary instances to test directory in explorer

- block/src/Pos/Block/Error.hs
- client/src/Pos/Client/KeyStorage.hs
- lib/src/Pos/Util/UserSecret.hs
- pkgs/default.nix
- update/src/Pos/Update/Poll/Modifier.hs
- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/server/Main.hs
- wallet-new/src/Cardano/Wallet/Kernel.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
- wallet-new/src/Cardano/Wallet/Kernel/Keystore.hs
- wallet-new/src/Cardano/Wallet/Kernel/Types.hs
- wallet-new/src/Cardano/Wallet/WalletLayer.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
- wallet-new/test/unit/Test/Spec/Kernel.hs
- wallet-new/test/unit/Test/Spec/Keystore.hs
- wallet-new/test/unit/Test/Spec/Submission.hs
- wallet-new/test/unit/Wallet/Inductive/Cardano.hs
- wallet-new/test/unit/WalletUnitTest.hs
This PR introduces an opaque `Keystore` abstraction and a set of APIs meant to be able to store and retrieve `EncryptedSecretKey` from disk "out-of-acid-state", in the sense that those delicate sensitive information shouldn't be stored inside `acid-state`, to not incur in the risk of accidentally leaking them in the transaction logs.
The presented API models the one for `Data.Map` and should be quite general thanks to the use of the `Kernel.WalletId` type which incapsulate the notion of different ids, being them coming from HD wallets or elsewhere.
The concrete implementation is quite inefficient and relies on the already-present `UserSecret`, as reinventing the wheel here would be detrimental as it makes sense to piggyback on what we have already instead of rewriting it from scratch. …
> [CBR-314] Kernel Keystore

- infra/test/Test/Pos/Infra/Arbitrary/Slotting.hs
- infra/test/cardano-sl-infra-test.cabal
- pkgs/default.nix
- sinbin/test/LICENSE
- sinbin/test/Setup.hs
- sinbin/test/Test/Pos/Sinbin/Arbitrary/Slotting.hs
- sinbin/test/cardano-sl-sinbin-test.cabal
- stack.yaml
- update/test/Test/Pos/Update/Arbitrary/Core.hs
- update/test/Test/Pos/Update/Arbitrary/Poll.hs
- update/test/cardano-sl-update-test.cabal
Free up `infra-test` by moving `Test.Pos.Infra.Arbitrary.Slotting` to `sinbin-test`.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-416
> [CDEC-416] Sinbin `Test.Pos.Infra.Arbitrary.Slotting`

- tools/src/dbgen/Lib.hs
Remove field accessors for `FakeTxsHistory` data type
https://iohk.myjetbrains.com/youtrack/issue/CDEC-285
> [CDEC-285] Remove field accessors for `FakeTxsHistory` data type

- block/cardano-sl-block.cabal
- block/test/Test/Pos/Block/Arbitrary.hs
- block/test/Test/Pos/Block/Arbitrary/Message.hs
- block/test/cardano-sl-block-test.cabal
- generator/cardano-sl-generator.cabal
- generator/test/Test/Pos/Block/Logic/CreationSpec.hs
- lib/cardano-sl.cabal
- lib/src/Pos/Context/Context.hs
- lib/src/Pos/Worker/Ssc.hs
- lib/test/Test/Pos/Cbor/CborSpec.hs
- lib/test/Test/Pos/Ssc/Identity/SafeCopySpec.hs
- lib/test/Test/Pos/Ssc/Toss/BaseSpec.hs
- lib/test/Test/Pos/Ssc/Toss/PureSpec.hs
- lib/test/Test/Pos/Ssc/VssCertDataSpec.hs
- pkgs/default.nix
- ssc/cardano-sl-ssc.cabal
- ssc/src/Pos/Ssc/Behavior.hs
- ssc/test/LICENSE
- ssc/test/Setup.hs
- ssc/test/Test/Pos/Ssc/Arbitrary.hs
- ssc/test/cardano-sl-ssc-test.cabal
- stack.yaml
- wallet-new/src/Cardano/Wallet/Orphans/Arbitrary.hs
- wallet/src/Pos/Arbitrary/Wallet/Web/ClientTypes.hs
As it stands, the Arbitrary instances for data types in `ssc` all exist in `ssc` when they should actually be exposed from a separate package, `ssc-test`.
In addition to this, `Pos.Arbitrary.Ssc` was actually used within `Pos.Ssc.Worker`. It was used to [generate a random Opening](https://github.com/input-output-hk/cardano-sl/blob/develop/ssc/src/Pos/Ssc/Worker.hs#L235) in the event that we call [`onNewSlotOpening`](https://github.com/input-output-hk/cardano-sl/blob/develop/ssc/src/Pos/Ssc/Worker.hs#L206) while passing an instance of [`SscOpeningParams`](https://github.com/input-output-hk/cardano-sl/blob/develop/ssc/src/Pos/Ssc/Behavior.hs#L36) constructed with [`SscOpeningWrong`](https://github.com/input-output-hk/cardano-sl/blob/develop/ssc/src/Pos/Ssc/Behavior.hs#L39). This was changed …
> [CDEC-427] Move Arbitrary instances from ssc to ssc-test

- scripts/common-functions.sh
- scripts/launch/demo.sh
This adds `--nix` parameter to `./scripts/launch/demo.sh`
> Added `--nix` argument to ./scripts/launch/demo.sh

- wallet-new/src/Cardano/Wallet/API/V1/Swagger.hs
Now that client TLS verification is activated, clients are expected to provide a valid TLS client certificate. cURL command given as examples in the documentation should reflect that.
[CO-328](https://iohk.myjetbrains.com/youtrack/issue/CO-328)
> [CO-328] Add missing '--client' option in cURL API doc examples

- scripts/package-dep-graph.sh
- stack.yaml
Flesh out `package-dep-graph.sh`, document it in `stack.yaml`
https://iohk.myjetbrains.com/youtrack/issue/CDEC-429
^ this change adds & modifies a script which generates a PNG image of the `cardano-sl` dependency graph. As such, I'm not sure what tests would be useful for it.
> [CDEC-429] Flesh out `package-dep-graph.sh`, document it in `stack.yaml`

- scripts/haskell/git-pre-commit-hook
Runs stylish-haskell and hlint on the haskell files about to be
committed. Documentation in the script itself.
N/A
> Add an example get pre-commit hook

- auxx/cardano-sl-auxx.cabal
- binary/cardano-sl-binary.cabal
- binary/test/cardano-sl-binary-test.cabal
- block/cardano-sl-block.cabal
- block/test/cardano-sl-block-test.cabal
- core/cardano-sl-core.cabal
- core/test/cardano-sl-core-test.cabal
- crypto/cardano-sl-crypto.cabal
- delegation/cardano-sl-delegation.cabal
- delegation/test/cardano-sl-delegation-test.cabal
- explorer/cardano-sl-explorer.cabal
- generator/cardano-sl-generator.cabal
- infra/cardano-sl-infra.cabal
- infra/test/Test/Pos/Infra/Arbitrary/Communication.hs
- infra/test/cardano-sl-infra-test.cabal
- lib/cardano-sl.cabal
- lrc/cardano-sl-lrc.cabal
- networking/cardano-sl-networking.cabal
- node/cardano-sl-node.cabal
- pkgs/default.nix
- ssc/cardano-sl-ssc.cabal
- tools/cardano-sl-tools.cabal
- txp/cardano-sl-txp.cabal
- txp/test/cardano-sl-txp-test.cabal
- update/cardano-sl-update.cabal
- update/test/cardano-sl-update-test.cabal
- util/cardano-sl-util.cabal
- util/test/cardano-sl-util-test.cabal
- wallet-new/cardano-sl-wallet-new.cabal
- wallet/cardano-sl-wallet.cabal
Remove unneeded package dependencies. I've left out a few packages, which aren't actually compiled, for which `weeder` claims all of their `build-depends` are unnecessary.
[https://iohk.myjetbrains.com/youtrack/issue/CDEC-425](https://iohk.myjetbrains.com/youtrack/issue/CDEC-425)
> [CDEC-425] Weed out unused package dependencies

- block/src/Pos/GState/BlockExtra.hs
- lib/src/Pos/Diffusion/Full/Block.hs
The fix in #3235 had an off-by-one error: the streaming began with the newest client-supplied checkpoint in the server's chain, whereas it apparently should have begun with the child of that block (that's how it was before the patch, but it leaked memory). The demo script seems to work with this patch.
> [DEVOPS-944] resolve off-by-one in block stream

- lib/src/Pos/Launcher/Scenario.hs
- pkgs/default.nix
- txp/src/Pos/Txp/Base.hs
- txp/src/Pos/Txp/DB/Utxo.hs
- txp/src/Pos/Txp/Toil/Stakes.hs
- txp/src/Pos/Txp/Toil/Utxo/Util.hs
- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/src/Cardano/Wallet/Kernel/Types.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
- wallet-new/test/unit/Test/Infrastructure/Genesis.hs
- wallet-new/test/unit/Test/Spec/Translation.hs
- wallet-new/test/unit/UTxO/Context.hs
- wallet-new/test/unit/UTxO/Interpreter.hs
- wallet-new/test/unit/UTxO/Translate.hs
This PR calculates the running stakes throughout translation of the DSL. These are used to run follow-the-satoshi and create an epoch boundary block when needed.
https://iohk.myjetbrains.com/youtrack/issue/CBR-253
> [CSL-2495] Create epoch boundary blocks in the wallet-new tests

- core/test/Test/Pos/Core/Gen.hs
Bump range from 10^12 to 10^15. 10^12 is not enough to cover the
range used in Cardano, but 10^15 is.
This is a follow up to PR #3236, which [bumped the range of `Coeff`](https://github.com/input-output-hk/cardano-sl/pull/3236/files#diff-6ec2f26e2869d3c19cb621038f455659R433), but not by enough.
> Increase `genCoeff` range & document why

- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/integration/AccountSpecs.hs
- wallet-new/integration/Main.hs
- wallet-new/integration/Util.hs
- wallet-new/src/Cardano/Wallet/API/Indices.hs
- wallet-new/src/Cardano/Wallet/API/V1/Accounts.hs
- wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers/Accounts.hs
- wallet-new/src/Cardano/Wallet/API/V1/Swagger.hs
- wallet-new/src/Cardano/Wallet/API/V1/Swagger/Example.hs
- wallet-new/src/Cardano/Wallet/API/V1/Types.hs
- wallet-new/src/Cardano/Wallet/Client.hs
- wallet-new/src/Cardano/Wallet/Client/Http.hs
There are needs for exchanges to retrieve only the balance of a given account. A call to `/api/v1/wallets/{walletId}/accounts/{accountId} already contains this field but is unpractical for exchanges since they usually have accounts with MANY addresses, resulting in a huge response from the API.
[CO-324](https://iohk.myjetbrains.com/youtrack/issue/CO-324)
> [CO-324] Accounts per-field endpoints

- wallet-new/src/Cardano/Wallet/API/Response.hs
- wallet-new/src/Cardano/Wallet/API/V1/Swagger/Example.hs
- wallet-new/src/Cardano/Wallet/API/V1/Types.hs
Use `Example` typeclass instead of `Arbitrary` when creating Swagger schema.
1. Import and use `Example` typeclass in `../V1/Types.hs`
instead of `Arbitrary`
2. Resolve circular dependencies
`Errors.hs` -> `Types.hs` -> `Example.hs` -> `Response.hs` -> `Errors.hs`
by moving `Example` instances from `Example.hs` to where the datatypes
are defined, so that `Example.hs` does not need to import `Response.hs`
or `Types.hs`.
Regarding name collisions between `Data.Swagger` and `Cardano.Wallet.API.V1.Swagger.Example`, I suspect `hiding` is the wrong way to go?
[CO-327](https://iohk.myjetbrains.com/youtrack/issue/CO-327)
- [~] I have updated any …
> [CO-327] Rely on Example type-class for Swagger API schema

- pkgs/default.nix
- util/cardano-sl-util.cabal
- util/test/cardano-sl-util-test.cabal
`text-format` isn't imported in `cardano-sl-util` or `cardano-sl-util-test`, despite being listed in their build-depends.
This is a one-off fix.
^ We are just removing an unused module.
> Remove `text-format` from repo

- binary/cardano-sl-binary.cabal
- binary/src/Pos/Binary/Class/Core.hs
- binary/src/Pos/Binary/Class/Primitive.hs
- binary/src/Pos/Binary/Class/TH.hs
- binary/test/Test/Pos/Binary/BiSizeBounds.hs
- binary/test/Test/Pos/Binary/Helpers.hs
- binary/test/cardano-sl-binary-test.cabal
- binary/test/test.hs
- core/cardano-sl-core.cabal
- core/src/Pos/Core/Common/AddrSpendingData.hs
- core/src/Pos/Core/Common/AddrStakeDistribution.hs
- core/src/Pos/Core/Common/Address.hs
- core/src/Pos/Core/Common/BlockCount.hs
- core/src/Pos/Core/Common/Coin.hs
- core/src/Pos/Core/Txp/Tx.hs
- core/src/Pos/Core/Txp/TxWitness.hs
- core/test/Test/Pos/Core/Bi.hs
- core/test/cardano-sl-core-test.cabal
- crypto/Pos/Crypto/Hashing.hs
- crypto/Pos/Crypto/Orphans.hs
- crypto/Pos/Crypto/Signing/Types/Signing.hs
- crypto/test/Test/Pos/Crypto/Bi.hs
- pkgs/default.nix
- stack.yaml
- test.hs
This PR implements the "static size estimate" work from CBR-318. The idea is to provide a way to compute he upper- and lower-bounds on the encoded size for a given type.
To get this capability, I've added a `encodedSizeExpr` method to the `Bi` typeclass. At some type `a`, this method returns a symbolic expression describing the range of sizes that an encoded `a` could have. `encodedSizeExpr` has a default implementation that just returns a symbolic representation of the type: something like "the size of `a` is "the size of `a`"". I have only provided more specific implementations for basic types and whatever was needed to get estimates for `TxAux`.
The expressions are represented by the `Size` type. A variety of utility functions let you carry out basic operations like simplification, …
> Matt noonan/size estimates

- docs/how-to/launch-testnet.md
- lib/configuration.yaml
- lib/testnet-genesis.json
Fix the testnet genesis parameters total balance and block version data.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-398
nix-build -A demoClusterLaunchGenesis -o demo-cluster-launch-genesis.sh
./demo-cluster-launch-genesis.sh
(check logs to see that it works ok)
Current testnet is running with this genesis data. Poor addresses have 19,999,999.999999 Ada and fake AVVM seeds redeem 20,000,000 Ada.
> [DEVOPS-398] Update testnet launch genesis data

- block/cardano-sl-block.cabal
- block/src/Pos/Block/BListener.hs
- block/src/Pos/Block/Logic/Creation.hs
- block/src/Pos/Block/Logic/Internal.hs
- block/src/Pos/Block/Lrc.hs
- delegation/cardano-sl-delegation.cabal
- delegation/src/Pos/Delegation/Logic/Mempool.hs
- delegation/src/Pos/Delegation/Logic/VAR.hs
- generator/cardano-sl-generator.cabal
- generator/src/Pos/Generator/Block/Mode.hs
- generator/src/Test/Pos/Block/Logic/Emulation.hs
- generator/src/Test/Pos/Block/Logic/Mode.hs
- infra/src/Pos/Infra/Communication/Protocol.hs
- infra/src/Pos/Infra/DHT/Workers.hs
- infra/src/Pos/Infra/Discovery/Model/Class.hs
- infra/src/Pos/Infra/Discovery/Model/Neighbors.hs
- infra/src/Pos/Infra/Network/CLI.hs
- infra/src/Pos/Infra/Slotting/Impl/Simple.hs
- infra/src/Pos/Infra/Slotting/Util.hs
- lrc/cardano-sl-lrc.cabal
- lrc/src/Pos/Lrc/Mode.hs
- pkgs/default.nix
- ssc/cardano-sl-ssc.cabal
- ssc/src/Pos/Ssc/Toss/Trans.hs
- txp/cardano-sl-txp.cabal
- txp/src/Pos/Txp/Logic/Local.hs
- txp/src/Pos/Txp/MemState/Class.hs
Change the imports of `JsonLog` and `Mockable` from `networking` to `core` (where the modules are now prefixed by `Pos.Core.`). This allows `networking` to float up until it is right below `infra`.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-432
^ Module level refactoring (switching of imports between packages). Existing tests should be sufficient.
> [CDEC-432] Free `networking` from the "blockchain packages"

- infra/src/Pos/Infra/Communication/Types/Protocol.hs
- wallet-new/test/unit/Test/Spec/Translation.hs
- wallet-new/test/unit/Wallet/Inductive/Invariants.hs
- wallet-new/test/unit/Wallet/Inductive/Validation.hs
Remove partial field accessors from `HandlerSpec`, `InductiveValidationError`, `InvariantViolation` and `ValidationResult` data types.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-403
> [CDEC-403] Remove partial field accessors from `HandlerSpec`, `InductiveValidationError`, `InvariantViolation` and `ValidationResult` data types.

- appveyor.yml
AppVeyor are deleting old build artifacts and breaking our builds.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-957
1. Check AppVeyor CI status for this PR.
> [DEVOPS-957] AppVeyor: Update Rocksdb.zip URL to S3 location

- default.nix
Test output is very sparse in CI logs:
```
running tests
Running 1 test suites...
Test suite test: RUNNING...
Test suite test: PASS
```
In nix we have a mechanism for enabling streaming log output with more details. This was introduced in DEVOPS-274, and it was somewhat of a hack.
To enable streaming test output, we still need to explicitly apply `addRealTimeTestLogs` to the relevant derivations in the `cardanoPkgs` overrides in `default.nix`. As part of DEVOPS-960 I'd like to see it automatically applied to all Haskell package derivations coming from this repo or prefixed by `cardano`, but this is a start. After manually enabling it, e.g. by adding `cardano-sl-infra = addRealTimeTestLogs super.cardano-sl-infra;` to `default.nix`, I get output like this instead:
```
...
[12 of 12] …
```
> [DEVOPS-960] Clean up mechanism for streaming test output in CI logs

- scripts/package-dep-graph.sh
Add SVG output option to script.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-429
^ technically closed, but this was requested to be added, and seems too small to open a new ticket for.
> package-dep-graph.sh: add SVG output option

- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/src/Cardano/Wallet/Kernel.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/AcidState.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/BlockMeta.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Spec.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Update.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Util.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Util/IxSet.hs
- wallet-new/src/Cardano/Wallet/Kernel/PrefilterTx.hs
- wallet-new/src/Cardano/Wallet/Kernel/Types.hs
- wallet-new/src/Cardano/Wallet/Kernel/Util.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
- wallet-new/test/unit/Test/Infrastructure/Genesis.hs
- wallet-new/test/unit/Test/Spec/Kernel.hs
- wallet-new/test/unit/Test/Spec/Translation.hs
- wallet-new/test/unit/UTxO/Context.hs
- wallet-new/test/unit/UTxO/Interpreter.hs
- wallet-new/test/unit/UTxO/Translate.hs
- wallet-new/test/unit/Util/Buildable/QuickCheck.hs
- wallet-new/test/unit/Wallet/Inductive.hs
- wallet-new/test/unit/Wallet/Inductive/Cardano.hs
- wallet-new/test/unit/Wallet/Inductive/History.hs
- wallet-new/test/unit/Wallet/Inductive/Interpreter.hs
- wallet-new/test/unit/Wallet/Inductive/Invariants.hs
- wallet-new/test/unit/Wallet/Rollback/Full.hs
- wallet/test/Test/Pos/Wallet/Arbitrary/Web/ClientTypes.hs
Implement rollback
https://iohk.myjetbrains.com/youtrack/issue/CBR-150
https://iohk.myjetbrains.com/youtrack/issue/CBR-151
> [CBR-150] Implement rollback

- docs/exchange-onboarding.md
- docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md
Doc fix
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-976?query=nix-darwin
> [DEVOPS-976] update binary cache instructions for nix 2

- explorer/src/Pos/Explorer/Aeson/ClientTypes.hs
- explorer/src/Pos/Explorer/Web/Api.hs
- explorer/src/Pos/Explorer/Web/ClientTypes.hs
- explorer/src/Pos/Explorer/Web/Server.hs
- explorer/src/Pos/Explorer/Web/TestServer.hs
- explorer/src/documentation/Main.hs
- lib/configuration.yaml
- lib/src/Pos/Configuration.hs
A community contribution by @refi93.
https://github.com/input-output-hk/cardano-sl/pull/3009
Cherry picked from that fork/branch.
> added unspent transaction outputs endpoint to explorer

- pkgs/default.nix
- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/FromGeneric.hs
- wallet-new/src/Cardano/Wallet/Kernel/Transactions.hs
- wallet-new/test/unit/Test/Spec/CoinSelection.hs
This PR takes out the hard-coded transaction size estimates in the new wallet , replacing them with uses of the new size-expression code in `Bi`. 
CBR-291, perhaps?
> Change the hard-coded size estimates to use Bi.

- db/cardano-sl-db.cabal
- db/src/Pos/DB/Block/GState/BlockExtra.hs
- infra/src/Pos/Infra/Diffusion/Subscription/Subscriber.hs
- lib/bench/Bench/Pos/Diffusion/BlockDownload.hs
- lib/cardano-sl.cabal
- lib/src/Pos/Diffusion/Full/Block.hs
- lib/src/Pos/Logic/Full.hs
- lib/src/Pos/Logic/Types.hs
- lib/test/Test/Pos/Diffusion/BlockSpec.hs
- pkgs/default.nix
The Cardano SL codebase currently depends on the pipes package in addition to depending on conduit.
Since used of conduit is far more prevalent we should replace all usage of pipes with conduit.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-464
^ no new tests added - existing ones should cover these changes.
> [CDEC-464] Switch uses of `pipes` to `conduit`

- pkgs/default.nix
- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/src/Cardano/Wallet/Kernel/Actions.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
- wallet-new/test/unit/Test/Spec/WalletWorker.hs
This code improve wallet worker start-up and exception handling. The previous implementation of this wasn't particularly careful regarding exceptions and logging. For example, linking the worker thread with the calling thread could be prevented by an async exception, leaving a dangling worker running. This code carefully considers these scenarios. Additionally, this new code prevents `invoke` from being used outside its intended scope. If that happens, then the caller will get an exception. 
The `Shutdown` constructor for `WalletAction` was removed because all it achieved was opening a second exit door for the worker client, which further complicated the implementation of `withWalletWorker`'s internals. The only exit now is having the client simply return or fail with an exception, as it …
> [CBR-243] improve wallet worker start-up and exception handling

- default.nix
- docs/how-to/demo-cluster.md
- scripts/README.md
- scripts/launch/connect-to-cluster/default.nix
- scripts/launch/demo-cluster/default.nix
- scripts/launch/demo-nix.sh
- scripts/test/wallet/integration/default.nix
This adds a top level argument to cardano-sl nix to `useStackBinaries`. By passing this argument, None of the nix built cardano binaries are used or even in the dependency tree. All this requires is nix to be installed to generate scripts developers can run to:
1) run a wallet against any environments supported by the scripts
2) override wallet configs for custom settings (see https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exchange-onboarding.md#generate-custom-configuration)
3) run a full demo cluster with 4 core nodes, 1 relay and 1 wallet
4) run the wallet integration test suite against demo cluster listed in 3.
The way this works is if `useStackBinaries` is specified, the binary being executed that normal comes from `iohkPkgs` built by nix is prefixed with `stack exec …
> [DEVOPS-985] add useStackBinaries parameter to default.nix

- lib/configuration.yaml
Fix integration test failures because of not enough coin available.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-988
> [DEVOPS-988] Set devnet max sizes to same as mainnet

- networking/src/Ntp/Client.hs
Force ntp check by overwriting `NtpStatus` mutable cell.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-356
> [CDEC-356] Force ntp check

- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/integration/AccountSpecs.hs
- wallet-new/integration/Main.hs
- wallet-new/integration/Util.hs
- wallet-new/src/Cardano/Wallet/API/Indices.hs
- wallet-new/src/Cardano/Wallet/API/Response.hs
- wallet-new/src/Cardano/Wallet/API/V1/Accounts.hs
- wallet-new/src/Cardano/Wallet/API/V1/Handlers/Accounts.hs
- wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers/Accounts.hs
- wallet-new/src/Cardano/Wallet/API/V1/Swagger.hs
- wallet-new/src/Cardano/Wallet/API/V1/Swagger/Example.hs
- wallet-new/src/Cardano/Wallet/API/V1/Types.hs
- wallet-new/src/Cardano/Wallet/Client.hs
- wallet-new/src/Cardano/Wallet/Client/Http.hs
- wallet/src/Pos/Util/Mnemonic.hs
- wallet/src/Pos/Wallet/Aeson/ClientTypes.hs
- wallet/test/Test/Pos/Util/MnemonicSpec.hs
This PR contains some API V1 improvements. Another one will follow in the upcoming week with another set of changes. We are shipping this first part now to avoid too big PR and because some of its content is needed by the Daedalus team to move on.
This contains:
- CO-324 Per-field endpoints
- CO-327 Swagger schemas' examples don't rely on the Example type-class
- CO-328 --cert cURL option is missing from API documentation
- CO-342 Backward-compatible CBackupPhrase parser
[[CO-325]](https://iohk.myjetbrains.com/youtrack/issue/CO-325)
> [CO-325] API V1 Improvements - Part 1

- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/src/Cardano/Wallet/API/V1/Accounts.hs
- wallet-new/src/Cardano/Wallet/API/V1/Handlers.hs
- wallet-new/src/Cardano/Wallet/API/V1/Handlers/Accounts.hs
- wallet-new/src/Cardano/Wallet/API/V1/Handlers/Transactions.hs
- wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers.hs
- wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers/Accounts.hs
- wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers/Transactions.hs
- wallet-new/src/Cardano/Wallet/API/V1/Transactions.hs
- wallet-new/src/Cardano/Wallet/API/V1/Types.hs
- wallet-new/src/Cardano/Wallet/Client.hs
- wallet-new/src/Cardano/Wallet/Client/Http.hs
- wallet-new/src/Cardano/Wallet/Kernel/Accounts.hs
- wallet-new/src/Cardano/Wallet/Kernel/Addresses.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Util/AcidState.hs
- wallet-new/src/Cardano/Wallet/Kernel/Transactions.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Accounts.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Active.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Addresses.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Legacy.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Types.hs
- wallet-new/test/Cardano/Wallet/WalletLayer/QuickCheck.hs
- wallet-new/test/unit/Test/Spec/CreateAddress.hs
This cleans up some of the code a bit, stubs out some handlers for the
redemption end point.
As agreed with squad 1, this also moves the redemption endpoint to be part of
transactions endpoint rather than the accounts endpoint. This makes more sense,
since redemption creates a new transaction (otherwise it was the odd one out on
the accounts endpoint, the only one requiring additional parameters in the
legacy implementation, or requiring the active wallet in the new
implementation).
https://iohk.myjetbrains.com/youtrack/issue/CBR-349
> [CBR-349] Pave the way for redemption

- wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Util/AcidState.hs
As it stood, zoomCreate took a concrete value to use as default. However, in
certain circumstances we actually want to run an /action/ when the value does
not exist. This is now supported.
https://iohk.myjetbrains.com/youtrack/issue/CBR-364
> [CBR-364] Generalize zoomCreate

- default.nix
- scripts/test/wallet/integration/build-test.nix
> [DEVOPS-980] Fix log collection in integration test

- wallet-new/server/Main.hs
- wallet-new/src/Cardano/Wallet/API/V1/Handlers/Transactions.hs
- wallet-new/src/Cardano/Wallet/Kernel.hs
- wallet-new/src/Cardano/Wallet/Kernel/Addresses.hs
- wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/FromGeneric.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Create.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Read.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Resolved.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Sqlite.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/TxMeta/Types.hs
- wallet-new/src/Cardano/Wallet/Kernel/Mode.hs
- wallet-new/src/Cardano/Wallet/Server.hs
This only changes comments (and a few variable names). I went over the TODOs still in the code, removed ones that were no longer relevant or had already been done, and created tickets for the important ones that still remain. TODOs about coding style or that sort of thing I just left.
> [CBR-227] Go over TODOs, remove stray, add tickets

- chain/test/test.hs
These were [added to the package](https://github.com/input-output-hk/cardano-sl/pull/3416/commits/c8a1b7e85bdac72363c8a7c783130eb801ae90e3), but the changeset which added
them to the test executable was checked out by accident.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-499
***
I'm omitting the usual fields because this is a hotfix PR for #3416.
> [CDEC-499] Run `Test.Pos.Chain.Txp.tests`

- CHANGELOG.md
- lib/src/Pos/Reporting/Production.hs
Reporting is currently complex and brittle, and one failure mode occurs
when the network connection goes down, and reporting tries to report,
but dies due to an IOException because the network is down.
Installing a simple `catchIO` handler around `reportNode` should catch
such exceptions and report their occurence in the log.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-470
- [~] I have added tests to cover my …
> [CDEC-470] Catch IOExceptions in `productionReporter`

- wallet-new/src/Cardano/Wallet/API/V1/Handlers/Transactions.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Read.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Read.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Read.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Util/AcidState.hs
- wallet-new/src/Cardano/Wallet/Kernel/Transactions.hs
- wallet-new/src/Cardano/Wallet/Kernel/Util.hs
- wallet-new/src/Cardano/Wallet/WalletLayer.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Accounts.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Addresses.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Transactions.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
- wallet-new/test/unit/Test/Spec/BlockMetaScenarios.hs
- wallet-new/test/unit/Test/Spec/GetTransactions.hs
- wallet-new/test/unit/Wallet/Inductive/Cardano.hs
There was a lot of duplication, inconsistent naming, and dead code. Most
importantly, a lot of pure errors were silently thrown as pure exceptions by a
blanket wrapper. This wrapper is now completely gone, the naming is entirely
consistent, (most) duplication is gone, and the dead code is removed.
The split into modules is now also consistent:
* The `Spec.Read` module works on a checkpoint
* The `HdWallet.Read` module works on a HdWallet
* The `DB.Read` lifts this to the entire acid-state DB
This takes advantage of the new Query' infrastructure introduced previously.
Renamed functions:
```
queryAccountTotalBalannce      currentTotalBalance
queryAccountUtxo               currentUtxo
queryAccountAvailableUtxo      currentAvailableUtxo
queryAccountAvailableBalance   currentAvailableBalance …
```
> [CBR-382] Refactor the `.Read` modules

- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/src/Cardano/Wallet/Kernel.hs
- wallet-new/src/Cardano/Wallet/Kernel/BListener.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Resolved.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Sqlite.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/TxMeta.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/TxMeta/Types.hs
- wallet-new/src/Cardano/Wallet/Kernel/PrefilterTx.hs
- wallet-new/src/Cardano/Wallet/Kernel/Transactions.hs
- wallet-new/src/Cardano/Wallet/Kernel/Types.hs
- wallet-new/src/Cardano/Wallet/Kernel/Util/Core.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Transactions.hs
- wallet-new/test/unit/Test/Spec/Kernel.hs
- wallet-new/test/unit/Test/Spec/TxMetaScenarios.hs
- wallet-new/test/unit/TxMetaStorageSpecs.hs
- wallet-new/test/unit/UTxO/Interpreter.hs
- wallet-new/test/unit/Wallet/Inductive/Cardano.hs
This PR:
- adds the possibility for multiple Accounts to insert the same Tx. This is achieved by using a Compound Primary Key (TxId, AccountId).
- Inserts Incoming Txs in meta db
- fixes stray comments and strange leftovers from previous PRs.
- adds tests for sqlite and general tests using the Interpeter.
TODO: creating the V1.Transaction in some tests failed, so for now they just create the TxMeta.
CBR-375
- [] I have added tests to cover my changes.
> [CBR-375] Create transaction metadata for incoming transactions

- explorer/frontend/default.nix
Cardano explorer was showing `v. 0.2.0( @GITREV )` in the footer.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-999
- Bug fix (non-breaking change which fixes an issue)
```
nix-build -A cardano-sl-explorer-frontend
cd result
grep -Ri gitrev
python3 -m http.server --bind 127.0.0.1 8000
```
1. Check the cardano explorer site footer for a correct git revision.
> [DEVOPS-999] explorer frontend: Replace @GITREV@ with actual rev

- scripts/package-dep-graph.sh
make the script callable on nixos
> make compatible with nixos

- pkgs/default.nix
- stack.yaml
- tools/cardano-sl-tools.cabal
- tools/src/gencerts/Configuration.hs
Currently on 1.3.0, if an IP SAN is set, it treats it as a DNS name instead and still throws an invalid certificate error, which also can break daedalus on the demo cluster. This is fixed in develop and proposed to be targeted to 1.3.1 release to fix this issue. This would also be an issue for any exchanges running the x509 tool manually to generate a CA that specified SAN's other than localhost, for example if they had a LAN or public IP they wanted the wallet to use and be secured/trusted with SSL by any application/browser with the ca.crt loaded into the trust store.
(cherry picked from commit 834ade85577c2fca8d8b3649582499e2abc78515)
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-992
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-992
> [DEVOPS-992] Fix x509 generator SANs to work with IP addresses

- release.nix
this ensures that `pkgs.cabal2nix` is pre-built and in the cache for whatever `nixpkgs-src.json` we choose to use
previously, it relies on `cache.nixos.org` already having a copy
> also cache cabal2nix on hydra

- pkgs/default.nix
- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/src/Cardano/Wallet/Kernel/ChainState.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/AcidState.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/BlockMeta.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/InDb.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Util/IxSet.hs
- wallet-new/src/Cardano/Wallet/Kernel/PrefilterTx.hs
- wallet-new/test/MarshallingSpec.hs
- wallet-new/test/unit/UTxO/Interpreter.hs
Some things to keep in mind:
* Round-trip QuickCheck tests are missing.
* The basic approach to defining instances for types wrapped in `InDb` is described in the code:
> -- Notice that when serializing and deserializing, a type like `InDb foo` will
> -- distribute `InDb` among the non-primitive types that make up `foo`. This
> -- choice doesn't show up in the types. 
* There are a lot of redundant type signatures. This is deliberate, so that changing the definition of a datatype in the future triggers a type-checker error if possible.
> [CBR-305] SafeCopy instances for InDb types

- tools/src/launcher/Main.hs
Changing to the working directory before starting cardano-node allows other paths (nodeDbPath in particular) to be supplied as relative paths. This allows us to work around unicode bugs in rocksdb.
Note that on Linux and macOS, the launcher is already being started within the Daedalus data directory.
https://iohk.myjetbrains.com/youtrack/issue/CBR-391
No automated tests for this. Needs to be checked by running with Daedalus.
1. Log in to Windows as user "ŮŝĕŗŃåɱĕ".
2. Start Daedalus (built with this code included).
3. Check that cardano-node.exe has not failed with some `c_rocksdb_open` error.
> [CBR-391] launcher: add a workingDir setting to the launcher config

- wallet-new/integration/AccountSpecs.hs
- wallet-new/test/unit/Test/Spec/Accounts.hs
Adding test for partial getters
https://iohk.myjetbrains.com/youtrack/issue/CBR-366
Unit tests:
```stack test --ta "-m GetAccountBalance" cardano-sl-wallet-new:wallet-unit-tests```
```stack test --ta "-m GetAccountAddresses" cardano-sl-wallet-new:wallet-unit-tests```
Integration tests:
```nix-build release.nix -A tests.walletIntegration```
> [CBR-366] Adding test for partial getters

- pkgs/default.nix
- stack.yaml
- util/Pos/Util/Log.hs
- util/Pos/Util/Log/Internal.hs
- util/Pos/Util/Log/LogSafe.hs
- util/Pos/Util/Log/LoggerConfig.hs
- util/Pos/Util/Log/LoggerName.hs
- util/Pos/Util/Log/Scribes.hs
- util/Pos/Util/Log/Severity.hs
- util/cardano-sl-util.cabal
- util/test/Test/Pos/Util/LogSpec.hs
We want to switch libraries from ‘log-warper’ to ‘katip’ as the latter promises to easily support JSON logging which is needed for structured logging.
The external library ‘katip’ is registered as a dependency in ‘stack.yaml’ and the cabal file of module ‘util’, where the new logging’s implementation will reside. No current code must use the new library, except the new tests.
* no changes to existing code
* adding files to 'util' only
CBR-207
- [~] …
> [CBR-207] introduce 'katip'

- auxx/Main.hs
- explorer/src/explorer/Main.hs
- lib/src/Pos/Client/CLI/Params.hs
- lib/src/Pos/Client/CLI/Secrets.hs
- node/Main.hs
- tools/src/dbgen/Main.hs
- wallet-new/server/Main.hs
CDEC-509 introduced a bug that stopped the wallet from starting. This fixes it by using `Maybe GeneratedSecrets` where necessary.
[CBR-400](https://iohk.myjetbrains.com/youtrack/issue/CBR-400)
> [CBR-400] Fix wallet failing to start

- wallet-new/docs/RelatingWalletSpecToCardano.md
- wallet-new/src/Cardano/Wallet/Kernel.hs
On wallet startup, initialise the Submission layer with all pending transactions in the wallet state.
https://iohk.myjetbrains.com/youtrack/issue/CBR-381
readability, structure etc
> [CBR-381] Initialise Submission layer on wallet startup

- lib/src/Pos/Context/Context.hs
- wallet-new/src/Cardano/Wallet/Kernel/NodeStateAdaptor.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Info.hs
- wallet-new/test/unit/Test/Spec/TxMetaScenarios.hs
This PR wires the `getInfo` with some real logic allowing us to fully implement `/api/v1/node-info` using the new data layer.
https://iohk.myjetbrains.com/youtrack/issue/CBR-246
> [CBR-246] Implement getInfo with the new data layer

- util/Pos/Util/Trace.hs
- util/Pos/Util/Trace/Named.hs
- util/Pos/Util/Trace/Unstructured.hs
- util/cardano-sl-util.cabal
- util/test/Test/Pos/Util/TraceSpec.hs
Alexander Vieth introduced logging in IO with ‘Trace’ in module ‘networking’. Logging does not depend on a monad in the context but is directly done using a passed-in function. This type of logging showed to be very effective, and our computation does not need to be run in a logging monad (on top of the other monads).
The implementation of ‘Pos.Util.Trace.Named’ and its tests reside in module ‘util’. No current code will use this functions.
This PR depends on PR #3476 and PR #3477. Once they are merged, `CI` tests should succeed.
CBR-213
- [~] 🏭 Refactoring that does not change existing functionality but does improve …
> [CBR-213] introduce 'Trace.Named'

- core/src/Pos/Core/Slotting/EpochOrSlot.hs
- db/cardano-sl-db.cabal
- db/src/Pos/DB/Block.hs
- db/src/Pos/DB/Block/Epoch.hs
- db/src/Pos/DB/Block/Internal.hs
- db/src/Pos/DB/Rocks/Functions.hs
- db/src/Pos/DB/Rocks/Types.hs
This is probably not documented as well as it could be. Please point out things that you think need documenting.
This PR adds new code, but does not drastically change the operation of the code, but adds a shim layer to the old block storage so that when consolidation is activated, blocks can be retrieved from either the consolidated epoch/index files (if they have been consolidated) or the blund files if they have not.
The consolidation code is *really* difficult to test because it needs a *huge* about or environment that is *really* difficult to set up. I do have a separate program to test consolidation and it does work, and it is possible to retrieve blunds/block/undos that have been consolidated.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-494
With the code in this PR:
* Made …
> CDEC-494: Part two of block consolidation

- db/src/Pos/DB/Block/Epoch.hs
The changes in PRs #3491 and #3482 turned out to be incompatible.
To avoind things like this, it would be ideal if PRs were not merged unless they were rebased and had a complete CI build first.
N/A
> Fix bad Github merge

- pkgs/default.nix
- util/cardano-sl-util.cabal
- util/src/Pos/Util/Log.hs
- util/src/Pos/Util/Log/Internal.hs
- util/src/Pos/Util/Log/LoggerConfig.hs
- util/src/Pos/Util/Log/Rotator.hs
- util/src/Pos/Util/Log/Scribes.hs
log rotation for 'katip'
* log files are named with "iso" date appended to filename: `logs/node.log-20180829201517`
* configuration (`--log-config`) defines rotation parameters:
** write to new file if max size is reached (currently 5 MB)
** write to new file if current log file was created more than ''t'' (default: 24) hours ago
** remove oldest files and only keep ''n'' files (currently 20) 
(since IO is quite expensive, the removal of files from the filesystem is only done at most every 10 seconds)
CBR-211
- [~] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, …
> [CBR-211] log rotation checks for size and age of files

- default.nix
- release.nix
- scripts/launch/connect-to-cluster/default.nix
- scripts/launch/demo-cluster/default.nix
> [DEVOPS-1027] make hydra show metrics for derivations

- wallet-new/integration/Main.hs
This test was highly un-reliable, failing in CI for no good reason
about 50% of the time. This test will be replaced.
> Disable the 'runActionCheck' wallet integration test

- util/src/Pos/Util/Log/Scribes.hs
this change preserves the format of the logging output
when we switch to the new logging library `katip` 
* this will be compatible with any tools that grep the textual logs
CBR-345
- [~] I have updated any documentation accordingly, if needed. Documentation …
> [CBR-345] printing log items compatible with current format

- util/src/Pos/Util/Log.hs
- util/src/Pos/Util/Log/LoggerConfig.hs
- util/src/Pos/Util/Log/LoggerName.hs
- util/src/Pos/Util/Log/Scribes.hs
- util/test/Test/Pos/Util/LogSpec.hs
provide a mapping of LoggerName -> Severity, and apply it in filtering messages in katip's scribes
* log-config defines minimum severity for a named logging context
turning off specific logging messages has been done in the current log configuration to prevent massive log creation.
with these changes for the new "structured logging" we provide the same functionality. 
CBR-348
CBR-402
RCD-32
- [~] If my code deals with exceptions, it follows the …
> [CBR-348] log-config defines Loggername - Severity mapping

- core/src/Pos/Core/Conc.hs
Just saw this as I was looking at test coverage results and couldn't help myself. I just had to fix it!
> Avoid potential Int overflow in delay function

- scripts/test/hlint.nix
Remove tput to stop command not found messages in logs.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1031
> [DEVOPS-1031] remove tput from hlint test

- tools/src/launcher/Main.hs
Backport of [CBR-391](https://iohk.myjetbrains.com/youtrack/issue/CBR-391) from `release/1.3.1` to `develop`.
> [CBR-391] launcher: add a workingDir setting to the launcher config (backport from release/1.3.1)

- explorer/frontend/src/Explorer/Util/Config.purs
- explorer/frontend/src/Explorer/View/Common.purs
Backport of [DEVOPS-398](https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-398) from `release/1.3.1` to `develop`.
> [DEVOPS-398] explorer frontend: reword Testnet banner (backport from release 1.3.1)

- scripts/prepare-genesis/README.md
Explanation suggested that `slotDuration` field is in microseconds, but
actual duration is `20000` which is 20 thousand **milliseconds**
(20 seconds).
This is a comment only PR that was rescued from the recent purge of old PRs.
> Fixed `slotDuration` time unit

- wallet-new/integration/AccountSpecs.hs
integration test for redeemADA. The tests do the following:
1. Wallet is created.
2. New account is added to the wallet. 
3. The check that the account balance is 0 is enforced. 
4. Redemption  value is constructed (using fake avvv seed available for dev setup- which is used as secret key in Ed25519 which is used for redemption stuff)
5. `redeemAda` is called
6. Corresponding transaction index is checked.
7.  Balance of the account is checked if it is increased by 100000. 
8. Finally, `redeemAda` is tried again with the same redemption value and it is expected to end up with error `Request error (Cannot send redemption transaction: Redemption address balance is 0)"`
Remark: checking redeemADA with the same redemption value - I expect error here and at this moment the below works: …
> [CBR-398] Adding integration test for redeemADA functionality

- db/cardano-sl-db.cabal
- db/src/Pos/DB/Rocks/Functions.hs
- db/test/Test/Pos/DB/Functions.hs
- db/test/Test/Pos/DB/Mode.hs
- db/test/test.hs
- pkgs/default.nix
The functions in `Pos.DB.Functions` were previously not unit tested. Before removing `dbSerializeVersion` and refactoring them, we need to make sure we don't break anything.
[CDEC-509](https://iohk.myjetbrains.com/youtrack/issue/CDEC-509)
> [CDEC-509] Add some tests for Pos.DB.Functions before refactoring

- core/src/Pos/Core/NetworkMagic.hs
[https://iohk.myjetbrains.com/youtrack/issue/CO-354](https://iohk.myjetbrains.com/youtrack/issue/CO-354)
> [CO-354] Make use of an Int32 instead of a Word32 in NetworkMagic

- default.nix
- release.nix
Adds a `fasterBuild` argument to the nix build. This will result in `-O0` being passed to GHC. This can be enabled for PR builds (see input-output-hk/iohk-ops#418) to get quicker turnaround.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1032
> [DEVOPS-1032] nix: Add flag to build with optimization disabled

- wallet-new/src/Cardano/Wallet/Kernel/NodeStateAdaptor.hs
When implementing the new data-layer 'node-info' handler, we've made the
choice to have the underlying check for NtpStatus blocking /
synchronous. This choices is usually fine as the check normally takes
around ~100ms. However, when running on CI, we do not connect to the
Internet and therefore, will always timeout for those check.  This could
be the cause for the integration tests bootstrap not syncing properly
(not telling us about it).
[[CBR-427]](https://iohk.myjetbrains.com/youtrack/issue/CBR-427)
> [CBR-427] Make NtpCheck non-blocking unless explicitly forced

- scripts/launch/demo-cluster/default.nix
- scripts/launch/demo-cluster/make-topology.nix
> [CBR-414] fix demo-nix.sh to have all core nodes working

- wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Create.hs
- wallet-new/src/Cardano/Wallet/Kernel/Decrypt.hs
- wallet-new/src/Cardano/Wallet/Kernel/Wallets.hs
This commit enforces that when we build a new 'HdAddress' out of an
Address, we decrypt the HD payload contained within and we use it to
retrieve the derivation path for both the newly-generated 'HdAddress'
and the parent 'HdAccount'.
https://iohk.myjetbrains.com/youtrack/issue/CBR-419
> [CBR-419] Enforce invariant on defaultHdAddressWith

- scripts/launch/demo-cluster/default.nix
- wallet-new/integration/Util.hs
> [DEVOPS-1046] Use new internal/import-wallet endpoint

- lib/src/Pos/Launcher/Scenario.hs
Prior to this commit, an exception in the wallet would simply log an
error message and silently die, keeping the underlying node running.
This is rather unintuitive especially in situation where we don't
necessarily have eyes on logs (e.g. running a demo cluster).  When a
node uses the wallet, if the wallet crashes, the node ought to crash as
well.
That is especially true when network binding address is already taken,
which occurs fairly often during development / testing (i.e. a prior
node is still listening to :8090 and the new one fails to bound. Then,
requests are made against a running node which is not the one we
expect!!)
[[CBR-426]](https://iohk.myjetbrains.com/youtrack/issue/CBR-426)
> [CBR-426] Crashes node upon wallet failure

- CHANGELOG.md
- pkgs/default.nix
- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/src/Cardano/Wallet/API/Response.hs
- wallet-new/test/SwaggerSpec.hs
The previous swagger spec had names like `WalletResponse<[Wallet]>` where `<[]>` are banned characters. This PR replaces them with URI friendly characters -- specifically, the above would now be `WalletResponse-_Wallet_`.
https://iohk.myjetbrains.com/youtrack/issue/CO-322
> [CO-322] Fix Swagger names in the spec

- CHANGELOG.md
- pkgs/default.nix
- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/server/Main.hs
- wallet-new/src/Cardano/Wallet/API/Response.hs
- wallet-new/src/Cardano/Wallet/Server/LegacyPlugins.hs
- wallet-new/src/Cardano/Wallet/Server/Middlewares.hs
- wallet-new/src/Cardano/Wallet/Server/Plugins.hs
We have had a lot of trouble where people will send no content-type or
simply 'application/json' and request would fail with 415 Unsupported
Media Type. Without knowing where to look, the error looks quite
unexpected and could give a lot of headache. This commit does two
changes:
- It slightly modifies the 'Accept' instance to use 'contentTypes'
instead of 'contentType'. The latter is defined from the former by
simply taking the head of the list returned by 'contentTypes', which in
our case is 'application/json;charset=utf-8'
- It provides a default content-type 'application/json' when no
content-type is provided
- Add entry in the CHANGELOG once changing base against `develop`
[[CO-370]](https://iohk.myjetbrains.com/youtrack/issue/CO-370)
With cURL:
> > POST /api/v1/wallets HTTP/1.1
> > …
> [CO-370] Make Content-Type parsing more lenient

- lib/src/Pos/Launcher/Launcher.hs
- node/Main.hs
- node/cardano-sl-node.cabal
- pkgs/default.nix
- wallet-new/server/Main.hs
Working towards acceptance criteria CO-356.1 & CO-356.5, this task would make it easy to start-up a node without much knowledge or manipulation of the internals. Starting a node should be as easy as providing a bunch of configuration parameters coming from a CLI.
Also, these bits of code are currently duplicated between the `lib@node/Main.hs` code and `wallet-new@server/Main.hs`, and similar things are needed in the incoming integration tests and demo.
This PR removes this duplication and unify the way nodes are launched :+1:
Starting a node becomes as simple as:
```hs
SimpleNodeArgs cArgs nArgs <- getSimpleNodeOptions
let lArgs = loggingParams "node" cArgs
launchNode nArgs cArgs lArgs $ \genesisConfig _ txpConfig _ _ _ nodeRes -> do
let plugins = [ updateTriggerWorker ]
let action  = …
```
> [CO-371] Refactor launchers 

- CHANGELOG.md
Forgot to update CHANGELOG as part of #3461 :confused: 
\-
> [CO-325] Update CHANGELOG.md

- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/server/Main.hs
- wallet-new/src/Cardano/Wallet/Action.hs
- wallet-new/src/Cardano/Wallet/LegacyAction.hs
The action exposed there are necessary for someone who wants to start a
wallet node from haskell (like in the `integration-tests` for instance ... ). They're currently part of the server/Main.hs
which is an executable, making it impossible to be imported by another
module. This commits extract them from 'server/Main.hs' making them
easy to re-use and/or remove!
[[CO-386]](https://iohk.myjetbrains.com/youtrack/issue/CO-386)
> [CO-386] Separate and expose wallet actions

- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Addresses.hs
- wallet-new/test/unit/Test/Spec/Addresses.hs
- wallet-new/test/unit/WalletUnitTest.hs
This PR adds tests for listing addresses:
- the results are always deterministic (in the sense that doing the same request 2 times yields the same response)
- paginating the results, yields no duplicate results.
- paginating the results may bring them in a different order (e.g. requesting 10 + 10 results in two pages will bring the same results but in different order than if we requested 20 in one page).
- The last point does not apply if there is a single account. In that case results are always in the same order.
UPDATE: a very small bug affected pagination when there are multiple accounts (see the diff in wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Addresses.hs). Now order is consistent always.
https://iohk.myjetbrains.com/youtrack/issue/CBR-371
> [CBR-371] unit tests for listing addresses

- util/src/Pos/Util/Wlog/Compatibility.hs
- util/test/Test/Pos/Util/WlogSpec.hs
apply minimum severity as soon as possible, and only forward messages to the logging framework  that pass this filter
CBR-345
- [~] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) …
> [CBR-345] apply minSeverity as soon as possible

- CHANGELOG.md
- pkgs/default.nix
- stack.yaml
- tools/cardano-sl-tools.cabal
- tools/src/gencerts/Main.hs
- tools/src/gencerts/README.md
- x509/LICENSE
- x509/README.md
- x509/cardano-sl-x509.cabal
- x509/configuration.yaml.example
- x509/src/Cardano/X509/Configuration.hs
- x509/src/Data/X509/Extra.hs
This module was currently defined as a binary executable for
cardano-sl-tools which makes it impossible to require it from any other
library. Ideally, we would like to keep the executable as it is but have
the library exposed somewhere else. That will come in handy for
integration tests and also in the launcher code.
Doing so, I've also removed the {#- RecordWildCards -#} extension
and turned non specific imports to specific ones. Apart from that, there's no 
real logical change, just a bit of reshuffling.
[[CO-387]](https://iohk.myjetbrains.com/youtrack/issue/CO-387)
> [CO-388] Pull out cardano-x509-certificates internals as a library 

- wallet-new/src/Cardano/Wallet/Kernel/BListener.hs
This PR tries to put an interim solution to the recent memory leaks we have been experiencing for the new data layer. In a nutshell, every time we receive a block, we call applyBlock (even if the block is not relevant to this wallet node) and that has the unfortunate consequence of appending an entry to the acid-state transaction log, which can grow very big up until we don't call createAcidStateCheckpoint (something we do periodically as part of a plugin every 12 minutes, by default).
The proper fix would be to simply stop calling applyBlock when a block is not interesting to us, but this is not easy to do currently as we do need to write to the DB a new Checkpoint (unfortunate naming, it's the wallet checkpoint as-per-the-spec) in our list of Checkpoints.
So, the plan is to fix this …
> [CBR-438] Create checkpoints in applyBlock

- client/src/Pos/Client/Txp/Util.hs
- wallet-new/src/Cardano/Wallet/API/V1/Handlers/Transactions.hs
- wallet-new/src/Cardano/Wallet/API/V1/Swagger.hs
- wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/FromGeneric.hs
- wallet-new/src/Cardano/Wallet/Kernel/Transactions.hs
- wallet-new/src/Cardano/Wallet/WalletLayer.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Active.hs
- wallet-new/test/unit/Test/Spec/NewPayment.hs
This PR relax a constraint we had in the previous implemention of `Kernel.estimateFee` where the spending password was needed. The reason was that we did piggyback on the `Kernel.newTransaction` low level API to first generate a new `TxAux` and then compute the fee as the difference between the `balance(inputs) - balance(outputs)`. But this meant we did need a `spendingPassword` in order to a) generate the change addresses and b) sign the addresses for the `TxWitnesses`.
This PR reshuffles the internals by creating another low-level API called `newUnsignedTransaction` (which hopefully will be also useful to @denisshevchenko or adaptable to his use case with minimal modifications) which computes an _unsigned_ transaction and uses that for the estimation of the fees.
This resolves the issue …
> [CBR-440] Do not require the spending password for the estimation of the fees

- wallet-new/src/Cardano/Wallet/Kernel/Wallets.hs
- wallet-new/test/unit/Test/Spec/Wallets.hs
When the password is updated we should check if it is the
`emptyPassphrase` and, if so, update `HdRoot` to have no spending
password.
This <s>commit</s> pr also adds a test property that ensures the hdRoot has no
spending password afterwards, and modifies the existing property to only
test updates with non-empty passwords, where we expect the new hdRoot to
*have* a spending password.
[CBR-437](https://iohk.myjetbrains.com/youtrack/issue/CBR-437)
> [CBR-437] Kernel.Wallets.updatePassword should record if the user decided to remove it

- lib/src/Pos/Launcher/Resource.hs
- util/src/Pos/Util/Log/LoggerConfig.hs
This was done in 7c59b1a2afcd8d433244b86f46c9e28781f856e0 but
then overriden by a wrong merge-conflict resolution in https://github.com/input-output-hk/cardano-sl/pull/3533/files#diff-f337564bf2743258dca7074867253d8fL241.
This commits re-applies the patch on top of the new changes.
Note that it turns out the  'Semigroup' instance for 'LoggerTree'
was broken :/ (being left-associative instead of right-associative).
> [CO-357] Re-emit: Fix 'overrideConsoleLog'

- pkgs/default.nix
- tools/src/gencerts/Main.hs
- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/src/Cardano/Wallet/Client/Http.hs
- x509/README.md
- x509/cardano-sl-x509.cabal
- x509/src/Cardano/X509/Configuration.hs
- x509/src/Data/X509/Extra.hs
- x509/test/Main.hs
- x509/test/Test/Cardano/X509/Configuration/Arbitrary.hs
As per comment in #3610 --> https://github.com/input-output-hk/cardano-sl/pull/3610#issuecomment-421955739
[[CO-379]](https://iohk.myjetbrains.com/youtrack/issue/CO-389)
> [CO-389] Write properties for cardano-sl-x509 

- lib.nix
- release.nix
1. Makes sure that `shell.nix` is built by hydra ⇒ available to download from cache.
2. Prevents locally created `.ghc.environment*` files from being included in the local nix-build and breaking it mysteriously.
- Build and dev environment
> Nix shell - more caching

- default.nix
- shell.nix
If you checkout the develop branch of cardano-sl and type nix-shell, it will start building packages, e.g. stack and cabal-install (!), rather than downloading them from a binary cache.
Continued from #3627.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1059
1. `nix-shell`
2. `nix-build release.nix -A shell.x86_64-linux`
> [DEVOPS-1059] Build and cache the nix-shell environment

- x509/src/Data/X509/Extra.hs
Turns out that we can't use the 'encode' function from Net.IP as it generates
invalid encoding for x509. I left a NOTE explaining what's going on such that
next readers will know what's going on.
[CO-389](https://iohk.myjetbrains.com/youtrack/issue/CO-389)
> [CO-389] Patch x509 parseSAN function to encode IP to valid bytes

- wallet-new/src/Cardano/Wallet/Kernel/Transactions.hs
This is one of the series of fixes that deals with making integration tests green.
The current one is the fix to esk address in mkSigner. Thanks to that at least one transaction is successfull
https://iohk.myjetbrains.com/youtrack/issue/CO-367
> [CO-367] Fixing esk of addresses in mkSigner

- lib/src/Pos/Network/Block/Retrieval.hs
When streaming blocks we never left recovery mode. This meant that in case the peer we streamed data from died we would never switch to a different node from which to sync from.
https://iohk.myjetbrains.com/youtrack/issue/CO-363
1. Build the acceptance test, nix-build -A acceptanceTests.mainnet.full -o acceptance-test
2. Start the acceptance test, ./acceptance-test
3. Block the IP address of the peer the node is syncing with, e.g iptables -D INPUT -s  PEERIP -j DROP
4. Wait for connection to time out.
5. Verify that syncing resumes with a new peer.
> CO-363: When streaming blocks, reconnect on error

- core/src/Pos/Aeson/Core/Configuration.hs
- core/src/Pos/Core/Configuration.hs
- core/src/Pos/Core/Configuration/Core.hs
- core/src/Pos/Core/Genesis/Canonical.hs
- core/test/Test/Pos/Core/Arbitrary.hs
- core/test/Test/Pos/Core/ExampleHelpers.hs
- core/test/Test/Pos/Core/Gen.hs
- core/test/Test/Pos/Core/Json.hs
- crypto/test/Test/Pos/Crypto/Gen.hs
- lib/cardano-sl.cabal
- lib/configuration.yaml
- lib/src/Test/Pos/Helpers.hs
- lib/test/Test/Pos/ConfigurationSpec.hs
- lib/test/Test/Pos/Genesis/CanonicalSpec.hs
- pkgs/default.nix
https://iohk.myjetbrains.com/youtrack/issue/CO-354
> [release/1.3.1] [CO-354] Override RequiresNetworkMagic from CoreConfiguration

- default.nix
- docs/how-to/launch-testnet.md
- lib/configuration.yaml
- scripts/common-functions.sh
- scripts/launch/connect-to-cluster/default.nix
- scripts/launch/demo-cluster/default.nix
- scripts/launch/demo-cluster/make-topology.nix
- scripts/prepare-genesis/default.nix
This PR contains:
* Part of testnet configuration, cherry-picked from #3091 and #3243 (develop branch).
* Docs with an explanation of testnet parameters.
* A fix for CBR-414, cherry-picked from #3582, so that "testnet" and "mainnet" demo clusters can both be launched for testing.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-398
https://iohk.myjetbrains.com/youtrack/issue/CO-354
https://iohk.myjetbrains.com/youtrack/issue/CBR-414
nix-build -A demoClusterLaunchGenesis -o demo-cluster-launch-genesis.sh
./demo-cluster-launch-genesis.sh
> [release/1.3.1] [DEVOPS-398] Testnet config

- scripts/test/acceptance/default.nix
Tests will fail if more that 2GB memory is used. This is a simple way of noticing space leaks in the sync code.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1052
- New or improved tests for existing code
> [DEVOPS-1052] tests: Limit memory usage of nightly blockchain sync

- .gitignore
- cabal.project
- docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md
- node/cardano-sl-node.cabal
- pkgs/default.nix
- shell.nix
- utxo/cardano-sl-utxo.cabal
- wallet-new/cardano-sl-wallet-new.cabal
Building with `cabal new-build` gives you a multi-package project with Nix downloading all of the dependencies from its binary cache.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1061
- New feature in build system and dev environment.
```
nix-shell
cabal new-configure
cabal new-build all
cabal new-repl cardano-sl-wallet-new
stack --nix setup
stack --nix build
nix-build -A all-cardano-sl
```
> [DEVOPS-1061] Add support for cabal new-build

- log-configs/daedalus.yaml
Daedalus now expects the node's public log files in `$log_prefix/pub` in JSON format.
this is a prerequisite for end-to-end tests
CBR-97
DDW-413
- [~] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [~] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant …
> [CBR-97] logging configuration for Daedalus with structured logging

- chain/src/Pos/Chain/Ssc/Error/Verify.hs
- chain/src/Pos/Chain/Ssc/Toss/Base.hs
- core/src/Pos/Core/Slotting/SlotId.hs
- db/src/Pos/DB/Block/Lrc.hs
- lib/src/Pos/Worker/Ssc.hs
- util/src/Pos/Util/Util.hs
clean formatting of slots/epoch indexes as proposed by @cleverca22 
reason: there were more occurences of wrong formatting in the logs.
moved the formatting code 'intords' from `core` to `util`
reason: the formatting should be available in all modules
CBR-345
- [~] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the …
> [CBR-345] clean formatting of slots/epoch indexes

- util/src/Pos/Util/Log/Internal.hs
- util/src/Pos/Util/Log/Rotator.hs
- util/src/Pos/Util/Log/Scribes.hs
Create a symbolic link for every log file created for UNIX-like systems. Symbolic link will follow the latest active log file.
For example:
* logs/node -> node-20180919092116
* logs/node-20180919091013
* logs/node-20180919091536
* logs/node-20180919092116
This allows a `tail -F` to follow the log files even when they are recreated under log rotation.
Also, create the log prefix directory on startup if it does not exist.
[CBR-345](https://iohk.myjetbrains.com/youtrack/issue/CBR-345)
> [CBR-345] Create symbolic link for log files.

- core/src/Pos/Core/Slotting/TimeDiff.hs
- infra/src/Pos/Infra/Slotting/Util.hs
- log-configs/template-demo.yaml
- util/cardano-sl-util.cabal
- util/src/Pos/Util/Log.hs
- util/src/Pos/Util/Log/LoggerConfig.hs
- util/src/Pos/Util/Log/Rotator.hs
- util/src/Pos/Util/Log/Structured.hs
- util/src/Pos/Util/Wlog/Compatibility.hs
- util/test/Test/Pos/Util/LogStructuredSpec.hs
Structured logging of data structures.
Up to the current version of code only Text  messages are logged. So we want to log items (besides Text ) that have a ToJSON  instance.
[CBR-423](https://iohk.myjetbrains.com/youtrack/issue/CBR-423)
> [CBR-423] Structured logging of data structures

- CHANGELOG.md
Add ChangeLog for 1.3.1 release.
There is one outstanding ticket to link - CO-354. That entry can be updated in a future PR.
> [DEVOPS-998] ChangeLog for 1.3.1

- auxx/Main.hs
- default.nix
- explorer/src/explorer/Main.hs
- lib/src/Pos/Launcher/Scenario.hs
- lib/src/Pos/Worker.hs
- lib/src/Pos/Worker/Block.hs
- lib/src/Pos/Worker/Delegation.hs
- lib/src/Pos/Worker/Ssc.hs
- lib/src/Pos/Worker/Update.hs
- node/Main.hs
- scripts/launch/connect-to-cluster/default.nix
- wallet-new/src/Cardano/Wallet/Action.hs
- wallet-new/src/Cardano/Wallet/Server/LegacyPlugins.hs
- wallet-new/src/Cardano/Wallet/Server/Plugins.hs
(cherry picked from commit 32432712424e6ac85f927494f48a06b0b65fa053)
without these changes, you get:
`[cardano-sl.reporter:Error:ThreadId 627] [2018-09-25 18:16:53.23 UTC] Reporting error with reason "Worker/plugin with logger name "*production*" failed with exception: state-wallet-mainnet-staging/tls/server/server.crt: openBinaryFile: does not exist (No such file or directory){ nodeIps: '[]', peers: 'OutboundQ internal state '{Peers {peersRoutes = Routes {_routesCore = [], _routesRelay = [], _routesEdge = []}, peersClassification = fromList []}}'' }"`
with the changes, you get:
`[cardano-sl.reporter:Error:ThreadId 627] [2018-09-25 18:16:53.23 UTC] Reporting error with reason "Worker/plugin with work name "doc worker" and logger name "*production*" failed with exception: …
> [DEVOPS-1063] improve error message when a worker throws

- default.nix
- lib.nix
- log-configs/template-demo.yaml
- scripts/common-functions.sh
- scripts/test/yamlValidation.nix
this will automatically test that each yaml file to confirm it parses in haskell
currently, 2 non-parsing files are commented out pending comments from developers
and we need to find more yaml files and their matching types to add
> [DEVOPS-1057] automated testing of yaml files

- lib/configuration.yaml
Bump the applicationVersion for mainnet and staging which is used by the update system for the wallets.
https://iohk.myjetbrains.com/youtrack/v2/issue/DEVOPS-998
- Configuration change
> [release/1.3.1] [DEVOPS-998] Bump applicationVersion

- scripts/test/wallet/integration/default.nix
Since a1e7e801 introduced a pipe after `stack test`, we were
wrongly getting the status from the `tee` command instead.
[[CO-400]](https://iohk.myjetbrains.com/youtrack/issue/CO-400)
- ~~[ ] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).~~
> [CO-400] Fix exit code acquiring in nix integration tests

- .gitignore
- pkgs/generate.sh
- pkgs/regen.nix
- scripts/check-stack2nix.sh
It was returning different results on Buildkite compared to when run locally.
https://iohk.myjetbrains.com/youtrack/v2/issue/DEVOPS-1045
- Bug fix for build scripts and dev environment
```
./pkgs/generate.sh
git diff  # there should be no difference
```
> [DEVOPS-1045] pkgs/generate.sh: Fix purity of script

- wallet-new/src/Cardano/Wallet/Server/Plugins.hs
[[CO-403]](https://iohk.myjetbrains.com/youtrack/issue/CO-403)
> [CO-403] Remove `wallet` dependency from `Cardano/Wallet/Server/Plugins.hs` 

- wallet-new/src/Cardano/Wallet/API/V1/Types.hs
[[CO-405]](https://iohk.myjetbrains.com/youtrack/issue/CO-405)
> [CO-405] Remove old wallet code from API.V1.Types

- binary/cardano-sl-binary.cabal
- chain/cardano-sl-chain.cabal
- core/cardano-sl-core.cabal
- crypto/cardano-sl-crypto.cabal
- db/cardano-sl-db.cabal
- infra/cardano-sl-infra.cabal
- util/cardano-sl-util.cabal
DEVOPS-1060 merges all cabal files into a single file, and then these tests collide with eachother
ive broken the change out into its own PR, since having identical test names doesnt seem to be very nice
> [DEVOPS-1060] make all test suite names unique

- .gitignore
- Makefile
- pkgs/default.nix
- stack.yaml
- wallet-new/src/Cardano/Wallet/Kernel/BListener.hs
There was a space leak in acid-state. This PR incorporates that fix and removes the checkpointing code that was a temporary in-repo fix.
> [CBR-446] Evaluate acid-state fix

- lib.nix
- nix/commit-id.nix
Previously it would fail to get the gitrev value:
error: illegal name: '.git'
(use '--show-trace' to show detailed location information)
You would have to supply a `--argstr gitrev NNN` manually to get it to work.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-949
- Bug fix to build system and dev environment.
```
git checkout develop
git worktree add ../csl/devops-949 devops-949-nix-git-worktree
cd ../csl/devops-949
nix-build -A cardano-sl-wallet-new-static
./result/bin/cardano-node --version
```
> [DEVOPS-949] nix: Support building from git worktrees

- wallet-new/src/Cardano/Wallet/Kernel/Internal.hs
`beginRestoration` runs `restoreWalletHistoryAsync` on the same thread used in the definition of `_wriCancel`:
```haskell
beginRestoration
...
restoreTask <- async $
catch (restoreWalletHistoryAsync ...)
\e ::SomeException -> ...
theTask <- newMVar restoreTask
addOrReplaceRestoration pw wId $ WalletRestorationInfo
{ ...
, _wriCancel   = readMVar theTask >>= cancel
}
```
In `restoreWalletHistoryAsync` we call `finish` when the restoration is complete, which in 
turn calls `removeRestoration`. 
Since `_wriCancel` kills the thread that runs 
```
restoreWalletHistoryAsync -> finish -> removeRestoration
```
we need to cancel only after removing the restoration task: 
```haskell
removeRestoration :: PassiveWallet -> WalletId -> IO ()
removeRestoration pw wId = do
wri <- lookupRestorationInfo pw …
```
> [CBR-452] Restoration stuck at completed

- pkgs/default.nix
- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/src/Cardano/Wallet/Server/Plugins/AcidState.hs
This commit improves the archive pruner function called as part of the
acid-state worker plugin.
In particular, we keep only the 3 most recent archives and we compress
them, deleting the rest. This allows us to go from this:
to something like this:
And the produced archive can be opened just fine:
https://iohk.myjetbrains.com/youtrack/issue/CBR-460
> [CBR-460] Improve the archive pruner

- default.nix
- nix/overlays/benchmark.nix
- nix/overlays/debug.nix
- nix/overlays/dont-check.nix
- nix/overlays/faster-build.nix
- nix/overlays/metric.nix
- nix/overlays/required.nix
This is a pure refactoring of the nix logic.  The primary goal is
to modularize the overlays and subsequently make rebasing easier by
removing these lines from the `default.nix`.
> [DEVOPS-1067] [nix] Split overlays into their own files

- generator/app/VerificationBench.hs
- generator/bench/Bench/Pos/Criterion/Block/Logic.hs
- lib/src/Pos/Launcher/Configuration.hs
- lib/test/Test/Pos/Launcher/ConfigurationSpec.hs
- util/src/Pos/Util/Wlog/Compatibility.hs
`Pos.Launcher.Configurations` exposes a function:
```hs
withConfigurations
:: (WithLogger m, MonadThrow m, MonadIO m)
=> ...
-> m r
```
which highly suggests that the caller Monad `m` could define its own logger instance and expect `withConfigurations` to leverage it for whatever logging this function must perform. However:
```hs
usingNamedPureLogger "pure-logger" $ withConfigurations Nothing Nothing False opts
```
This will fail with a hard `LoggingHandler MVar isn't initialized` which suggests that some other logger than the one provided is used.
Turns out that `withConfigurations` relies on `withConfigurationsM` which perform logging in plain IO only using the given logger's name to do so. 
This was most likely introduced when before pure loggers and ability to log in IO were …
> [CO-409] Fix `withConfigurations` usage of `WithLogger` ==> Allow pure logger to be used.

- CHANGELOG.md
- wallet-new/integration/TransactionSpecs.hs
- wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers/Transactions.hs
- wallet-new/src/Cardano/Wallet/API/V1/ReifyWalletError.hs
- wallet-new/src/Cardano/Wallet/API/V1/Swagger.hs
- wallet-new/src/Cardano/Wallet/API/V1/Types.hs
- wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/FromGeneric.hs
- wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/Generic.hs
- wallet-new/test/WalletNewJson.hs
- wallet-new/test/golden/WalletError_NotEnoughMoney
- wallet-new/test/golden/WalletError_NotEnoughMoneyAvailableBalanceIsInsufficient
- wallet-new/test/golden/WalletError_NotEnoughMoneyCannotCoverFee
When computing fees or making a transaction, it could happen that funds
are currently "locked" out because selected in a pending transaction. In
such case, the UTxO can't be spent until the transaction has been
accepted by (at least) a node. The API currently returns a
NotEnoughMoney error in such case, whereas the total balance (as
returned by /api/v1/wallets/{walletId} endpoint) might show enough
funds.
This refines a bit the `NotEnoughMoney` error to make the reason
of failure clearer without breaking (too much) the existing API.
NOTE: There's one "expected" failing integration test which actually shed the light on a newly discovered bug (0 fee transaction).
[[CBR-461]](https://iohk.myjetbrains.com/youtrack/issue/CBR-461)
- ~~[ ] All new and existing tests passed.~~
> [CBR-461] Improve diagnostic for `NotEnoughMoney` error 

- wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/Generic.hs
- wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/Generic/Fees.hs
commit 527afc745b463475e143c5c6079cd9a94f516515
Author: KtorZ <matthias.benkort@gmail.com>
Date:   Wed Oct 3 17:12:00 2018 +0200
[CBR-462] Throws right error when running out of UTxO in fee calculation
In this context, @CoinSelHardErrUtxoDepleted@ might be thrown by
`pickUtxo` as we iterate over the selected change outputs which here
means that we are running out of UTxOs to cover the fee.  Hence, we
ought to remap the error accordingly to @CoinSelHardErrCannotCoverFee@.
commit 78c113e95420691a71b22e3bed26c9b730eb7168
Author: KtorZ <matthias.benkort@gmail.com>
Date:   Wed Oct 3 17:05:48 2018 +0200
[CBR-462] Fix fee estimation when transaction's amount matches account's balance
When calling
```
reduceChangeOutputs
:: forall dom. CoinSelDom dom
=> Fee dom
-> [Value dom]
-> ([Value dom], Fee …
```
> [CBR-462] Fix 0 fee transaction

- lib/src/Pos/Network/Block/Retrieval.hs
- networking/src/Network/Broadcast/OutboundQueue.hs
Cherry pick two commits from `release/1.3.1` branch which fixed RCD-28. It was merged to `release/1.3.1` branch in this [PR](https://github.com/input-output-hk/cardano-sl/pull/3294)
https://iohk.myjetbrains.com/youtrack/issue/RCD-28
> [RCD-28] cherry pick fix from release/1.3.1

- lib/src/Pos/Diffusion/Full/Block.hs
- log-configs/cluster.yaml
- util/README.md
- util/src/Pos/Util/Trace/Named.hs
- util/src/Pos/Util/Wlog.hs
- util/src/Pos/Util/Wlog/Compatibility.hs
- util/test/Test/Pos/Util/LogStructuredSpec.hs
- util/test/Test/Pos/Util/WlogSpec.hs
* `LoggerConfig` for benchmarking, which outputs measurements in JSON log
* minor bug fixes
* documentation (in `util/README`) of
** named logging context
** structured logging
** logging setup via the `LoggerConfig`
CBR-345
- [~] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [~] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline …
> [CBR-345] cleanup and documentation

- docs/configuration.md
See the [datatype declaration](https://github.com/input-output-hk/cardano-sl/blob/bd0b7eac015a6ddba2ecbd07e81c6132ec3ea4dc/chain/src/Pos/Chain/Update/BlockVersionData.hs#L32) - we clearly use Milliseconds rather than Microseconds.
> Fix typo {Micro->Milli}Second

- wallet-new/src/Cardano/Wallet/Kernel/BListener.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/AcidState.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Update.hs
`ApplyBlock` takes an arg `Maybe (Set HdAccountId)` to allow callers to restrict the accounts.
In the backfilling code we were calling applyBlock with restricted accounts = `Just {}`
The effect was that the first block in backfilling would not be applied, and all subsequent blocks would fail because of the "missing predecessor block" that was not applied. Since we retry failures, this was causing an infinite loop with backfilling never happening.
This fix:
* removes the bug that was creating the empty restrictions `Just {}`
* changes the type of the restrictions in the ApplyBlock  signature to `Maybe (NonEmpty HdAccountId)` to prevent invalid restrictions
* add info log messages for the start and end of Backfilling, add a warning message when we recursively handle errors (so that an …
> [CBR-453] Fix bug in backfilling

- wallet-new/test/unit/Test/Spec/CoinSelection.hs
One of our tests picked up a corner case in the generators and in the
largestFirst policy, where big UTxO entries were going to be picked to
satisfy small payments, leaving beefy ones "uncovered". The fix here was
simply to sort the payees by amount _in the tests_, not in the coin
selection code. The reason is simple:
* We don't use `largestFirst` in production code. We rely only on the
`atLeast` low-level API inside the `random` policy, which is the one
we use in production;
* We have tests hitting `largestFirst` only for the sake of implicitly
testing `atLeast`;
* The `random` policy doesn't require this sorting precondition.
Therefore, embedding this sorting into the main coin selection code
would have been a waste of CPU cycles. Doing it in the tests only
suffices. …
> [CBR-465] Sort payees by amount in coin selection tests

- infra/src/Pos/Infra/Reporting/Http.hs
- pkgs/default.nix
- stack.yaml
I'm just trying to add https://github.com/input-output-hk/cardano-sl/pull/3394 to `develop`.
Part of https://iohk.myjetbrains.com/youtrack/issue/TSD-116
> [TSD-116] Bump report server on master

- docs/configuration.md
- docs/how-to/launch-testnet.md
- lib/configuration.yaml
- lib/testnet-genesis.json
Cherry picks of the configuration and docs changes relating to testnet and address discrimination from the release/1.3.1 branch.
The address discrimination feature will be re-implemented for the develop branch separately.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-398
https://iohk.myjetbrains.com/youtrack/issue/CO-354
```
nix-build -A demoCluster -o demo-cluster.sh && ./demo-cluster.sh
nix-build -A connectScripts.mainnet.wallet -o connect-mainnet.sh && ./connect-mainnet.sh
nix-build -A connectScripts.staging.wallet -o connect-staging.sh && ./connect-staging.sh
nix-build -A connectScripts.testnet.wallet -o connect-testnet.sh && ./connect-testnet.sh
```
> [DEVOPS-398] [CO-354] AD/Testnet config and docs from release/1.3.1

- wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Read.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Read.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Transactions.hs
While restoring a wallet in daedalus, it was reported that all txs appeared as failed, until restoration ended and they were turned into confirmed. This was caused because during restoration we totally ignored historical checkpoints. We provide a new zooming operation which uses a function which associated the results of the two checkpoints - partial and historical . We use this zooping operation for txs and this resolves the issue with daedalus
If the tx is in Sqlite but not in acid-state, we report it as Applying (Pending in Daedalus).
The same zooping operation can be used to fix also addresses, which are reported as "used":failed, until resotration finishes. This pr does NOT fix this issue:
During restoration:
```
$ curl --capath  "/path/to/tls" https://localhost:8090/api/v1/addresses …
```
> [CBR-445] Adds the option to associate partial and historical checkpoints during restoration

- wallet-new/integration/TransactionSpecs.hs
- wallet-new/src/Cardano/Wallet/API/V1/ReifyWalletError.hs
- wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/FromGeneric.hs
- wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/Generic.hs
- wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/Generic/Fees.hs
- wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/Generic/Random.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Read.hs
- wallet-new/src/Cardano/Wallet/Kernel/Transactions.hs
- wallet-new/test/unit/Test/Spec/CoinSelection.hs
- wallet-new/test/unit/Test/Spec/CoinSelection/Generators.hs
In a previous PR (#3704 - CBR-462), we patched the coin selection and remap the `UTxODepleted` error to a `CannotCoverFee` error. 
From this, the frontend team discovered a new bug caused because again, `UTxODepleted` was thrown instead of a correct `UTxOExhausted`. 
Instead of patching again and re-mapping the error to the correct one, I took a step back and slightly reviewed the original abstraction such that we would now have:
```hs
type PickUtxo m = Core.Coin  -- ^ Fee to still cover
-> CoinSelT Core.Utxo CoinSelHardErr m (Maybe (Core.TxIn, Core.TxOutAux))
```
instead of
```hs
type PickUtxo m = Core.Coin  -- ^ Fee to still cover
-> CoinSelT Core.Utxo CoinSelHardErr m (Core.TxIn, Core.TxOutAux)
```
The rational here is that, the outcome may depend of the context. We use this function …
> [CBR-464] Raise Correct `CoinSelHardErr` during coin selection

- wallet-new/docs/RelatingWalletSpecToCardano.md
- wallet-new/src/Cardano/Wallet/Kernel/Submission.hs
- wallet-new/src/Cardano/Wallet/Kernel/Submission/Worker.hs
This PR addresses CBR-182.
The old wallet had a 60 minute TTL hardcoded into the interface.
The new wallet has a constant retry time of around 21 minutes, after which the wallet removes it from the set of transactions to attempt to send.
We could attempt to calculate the TTL more exactly, but this would be inefficient. The `Schedule` type maintains a mapping from `Slot` to a `ScheduleEvent` which contains a list of `ScheduleSend`s. These `ScheduleSend` contain a transaction ID. We would need to convert the `Schedule` into a `Map TxId SubmissionCount` (an operation that is linear in size of the schedule) and, for each pending Transaction, look up the submission count and calculate the TTL based on the remaining submissions and the time between submissions.
As this is currently hardcoded, …
> [CBR-182] Add resubmission TTL estimation to the docs.

- lib/src/Pos/Diffusion/Full/Block.hs
A new update will cause the block retrival worker to exit
which means that the streaming thread could end up blocking
for ever when attempting to write to the full block queue.
Update so that we limit the time that we the streaming thread will
wait on the block queue incase of an exception.
https://iohk.myjetbrains.com/youtrack/issue/CBR-424
- [~] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.
- [~] CHANGELOG entry has been added and is …
> [CBR-424] Fix deadlock triggered by update/shutdown

- wallet-new/src/Cardano/Wallet/Kernel/BIP39.hs
- wallet-new/src/Cardano/Wallet/Types/UtxoStatistics.hs
- wallet-new/src/Cardano/Wallet/Util.hs
When tackling CO-373, we had to work-around a few things as some instances in the moved module were conflicting with other legacy types not-yet-removed from the code-base.
We now can tackle the rest.
[[CO-426]](https://iohk.myjetbrains.com/youtrack/issue/CO-426)
> [CO-426] - Follow-up on CO-373

- CHANGELOG.md
- pkgs/default.nix
- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/src/Cardano/Wallet/API/Response.hs
- wallet-new/src/Cardano/Wallet/API/V1/Swagger.hs
- wallet-new/src/Cardano/Wallet/Action.hs
- wallet-new/src/Cardano/Wallet/Server/Middlewares.hs
- wallet-new/test/MarshallingSpec.hs
- wallet-new/test/WalletNewJson.hs
- wallet-new/test/golden/UnsupportedMimeTypeError_UnsupportedMimeTypePresent
Implement more friendly 415 Unsupported Media Type error.
**BEFORE**
```
$ curl -X POST -vk -H "Content-Type: patate" http://localhost:8090/api/v1/wallets 
> POST /api/v1/wallets HTTP/1.1
> Host: localhost:8090
> User-Agent: curl/7.60.0
> Accept: */*
> Content-Type: patate
> 
< HTTP/1.1 415 Unsupported Media Type
< Transfer-Encoding: chunked
< Date: Fri, 05 Oct 2018 08:57:20 GMT
< Server: Warp/3.2.22
< 
* Connection #0 to host localhost left intact
```
**AFTER**
```
$ curl -X POST -vk -H "Content-Type: patate" http://localhost:8090/api/v1/wallets
> POST /api/v1/wallets HTTP/1.1
> Host: localhost:8090
> User-Agent: curl/7.60.0
> Accept: */*
> Content-Type: patate
> 
< HTTP/1.1 415 Unsupported Media Type
< Transfer-Encoding: chunked
< Date: Mon, 08 Oct 2018 13:14:42 GMT
< Server: …
```
> [CO-417] Add more friendly 415 Unsupported Media Type error

- docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md
- shell.nix
We can't use a "ghcWithPackages" as the compiler for stack with Nix integration because the packages conflict with what stack has built.
This reverts the ghc change in the haskell.lib.buildStackProject shell and adds an additional attribute for a shell where "cabal new-build" can use prebuilt package dependencies.
> [DEVOPS-1061] shell.nix: Undo change to buildStackProject shell

- scripts/launch/connect-to-cluster/default.nix
- scripts/launch/demo-cluster/default.nix
Changes the default wallet data layer to the new one by adding `new-wallet` flag when running cardano-node.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1037
> [DEVOPS-1037] Enable new data layer for wallet in nix scripts

- .buildkite/pipeline.yml
- networking/src/Node/Internal.hs
- node-ipc/server.js
- node-ipc/wallet-topology.yaml
- wallet-new/src/Cardano/Wallet/Kernel/Actions.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
Like #3740 but with more fixes.
- The bracket_ order was wrong for walletWorker
- withWalletWorker is simpler and better: if either the reader or writer thread dies exceptionally, the other also dies. The writer would previously close the queue and then wait on the reader. Now this happens only on normal termination.
- `node` would deadlock in the call to `killNode` on exceptional shutdown. `killNode` would cancel the dispatcher thread, then close the network-transport endpoint. Since we used network-transport-tcp with the fair `QDisc`, which blocks on write, there would be deadlock, for the dispatcher thread would no longer be reading that `QDisc`. Thus `killNode` would throw a blocked indefinitely on `STM` transaction exception, overriding the `exitFailure (ExitCode 20)` raised by a …
> [CBR-467] fix STM and exception mistakes

- wallet-new/README.md
- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/integration/AccountSpecs.hs
- wallet-new/integration/AddressSpecs.hs
- wallet-new/integration/CLI.hs
- wallet-new/integration/Main.hs
- wallet-new/integration/RandomStateWalk.hs
- wallet-new/integration/SetupTestEnv.hs
- wallet-new/integration/TransactionSpecs.hs
- wallet-new/integration/Util.hs
- wallet-new/integration/WalletSpecs.hs
Most of this PR consists of  refactorings that don't change functionality.
The motivation for this PR is to clean up parts of the code to make it easier to add the new features.
* `Main.hs`: has been reduced to a minimum to make it easy to read and modifiy.
Functions that are related to the RandomStateWalk have been moved to that module.
Functions for setting up the `WalletClient` have been moved to `SetupTestEnv.hs`.
* `SetupTestEnv.hs`
exports exports `setupClient :: CLIOptions -> IO (WalletClient IO, Manager)`
which has been inlined in `main :: IO ()` before.
`setupClient` is needed to run tests and single queries from the REPL.
* `Functions.hs` / `RandomStateWalk.hs`
The module `Functions.hs` has been renamed to  `RandomStateWalk.hs`.
some weeks ago some 5 lines have been added to …
> CO-424 some cleanups in preparation for adding new functionalities

- default.nix
- scripts/ci/check-hydra.sh
Uses jq to parse output of hydra-eval-jobs. If hydra-eval-jobs exits failure it throws an error. If any attributes have an error key, it exits failure and prints all failing derivations.
This also fixes evals for hydra.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1100
> [DEVOPS-1100] Catch errors in check-hydra.sh and exit appropriately

- appveyor.yml
- docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md
- faucet/cardano-sl-faucet.cabal
- nix/overlays/required.nix
- pkgs/default.nix
- release.nix
- scripts/bench/buildbench.sh
- scripts/build/cardano-sl.sh
- tools/cardano-sl-tools.cabal
Removes references to `cardano-sl-wallet`. 
TODO:
Quite a lot are remaining, but they *should* disappear after `wallet/` is removed.
From this pr:
```
git grep "cardano-sl-wallet" | grep -v "wallet-new"
docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md:-  `cardano-sl-wallet-static`:
pkgs/default.nix:"cardano-sl-wallet" = callPackage
pkgs/default.nix:pname = "cardano-sl-wallet";
pkgs/default.nix:, cardano-sl-wallet
pkgs/default.nix:cardano-sl-wallet
pkgs/default.nix:cardano-sl-wallet
pkgs/default.nix:cardano-sl-wallet
pkgs/default.nix:cardano-sl-wallet
pkgs/default.nix:"cardano-sl-wallet-test" = callPackage
pkgs/default.nix:, cardano-sl-wallet
pkgs/default.nix:pname = "cardano-sl-wallet-test";
pkgs/default.nix:cardano-sl-wallet
stack.yaml:  cardano-sl-wallet:            -Wall …
```
> [CO-430] Cleanup cardano-sl references to `cardano-sl-wallet`

- default.nix
- scripts/launch/demo-cluster/default.nix
- scripts/launch/demo-nix.sh
- scripts/test/wallet/integration/default.nix
Re-adds the dropped nix changes from demo cluster PR
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1101
> [DEVOPS-1101] nix demo/wallet integration test integration

- core/src/Pos/Core/Conc.hs
- lib/src/Pos/Util/UserSecret.hs
- util/src/Pos/Util/Wlog/Compatibility.hs
- wallet-new/src/Cardano/Wallet/Kernel/Keystore.hs
resolved ambiguous type; the logging message was looping inifinitely and never delivered.
DEVOPS-1097
- [~] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.
- [~] All …
> [DEVOPS-1097] resolved ambiguous types

- .buildkite/nightly.yml
- default.nix
- docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md
- docs/nix.md
- explorer/frontend/default.nix
- nix/overlays/benchmark.nix
- nix/overlays/faster-build.nix
- nix/overlays/required.nix
- nix/stack-shell.nix
- release.nix
- scripts/launch/connect-to-cluster/default.nix
- scripts/launch/demo-cluster/default.nix
- scripts/prepare-genesis/default.nix
- scripts/test/acceptance/default.nix
- scripts/test/wallet/integration/default.nix
- shell.nix
- stack.yaml
Continues on from #3761 and #3760.
* Salvage a commit with a buildkite fix from #3757.
* Allow `shell.nix` to work for `cabal new-build` by moving the `stack --nix` shell to `nix/stack-shell.nix`.
* Documentation and comments.
* Bring back `demoClusterLaunchGenesis` and fix it.
* In the connect scripts, add a helper script which wraps curl, to make wallet API requests easier.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1083
- Refactors and documentation.
- Build system and dev environment.
> [DEVOPS-1083] Nix documentation and refactor part III

- lib/src/Pos/Client/CLI/Options.hs
- lib/src/Pos/Client/CLI/Params.hs
- tools/src/dbgen/Main.hs
- util/src/Pos/Util/Log/Scribes.hs
flag to turn off logging to the console.
PR for Daedalus: https://github.com/input-output-hk/daedalus/pull/1144
(adds the flag `--log-console-off` to the installer which writes it to the `launcher-config.yaml`)
DEVOPS-1109
start a node with `--log-console-off` and verify that no message is printed on the console.
> [DEVOPS-1109] cli argument to inhibit console log: --log-console-off

- wallet-new/integration/RandomStateWalk.hs
- wallet-new/integration/TransactionSpecs.hs
- wallet-new/integration/Util.hs
Here we are switching in a enterprise of confirming the transaction into looking at the status of the transaction. The current tests rely on the confirmation number, which is not correct. The only reason those tests don't fail entirely at this moment is because there is an implicit ordering at the creation_time of the tx. So when the tests take the first tx of the list and check on it, this happens to be the correct tx. But this is very unreliable.
In a nutshell we demand that the transaction's status is either `InNewestBlocks` or  `Persisted`
https://iohk.myjetbrains.com/youtrack/issue/CO-436
- [] 🐞 Bug fix (non-breaking change which fixes an issue)
```
nix-build -A walletIntegrationTests -o launch_integration_tests --arg useStackBinaries true
./launch_integration_tests
```
> [CO-436] Change integration tests way of confirming transactions

- wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Spec.hs
- wallet-new/src/Cardano/Wallet/Kernel/Util/Core.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs
This pr has two parts:
- The first part is a bug fix (CBR-466). When we ask for addresses during restoration, even after a tx that uses an address is discovered, the address is still reported as unused. This happens because currently only partial checkpoints are queried and historical checkpoint are ignored. The first commit of this pr solves this issue.
- The second part is more of an improvement that was not provided by the old wallet (CBR-193). When we discover a utxo at the begining of restoration, we mark the relevant addresses as used. This means that some addresses are reported as used, even before the tx that uses them is discovered.
https://iohk.myjetbrains.com/youtrack/issue/CBR-193
https://iohk.myjetbrains.com/youtrack/issue/CBR-466
Start a restoration. When a tx of the wallet …
> [CBR-466] fix address reported as unused during restoration

- generator/app/VerificationBench.hs
- generator/bench/Bench/Pos/Criterion/Block/Logic.hs
- lib/src/Pos/Launcher/Resource.hs
- networking/bench/LogReader/Main.hs
- networking/bench/Receiver/Main.hs
- networking/bench/Sender/Main.hs
- networking/src/Bench/Network/Commons.hs
- networking/test/Test/Network/Broadcast/OutboundQueueSpec.hs
- tools/src/keygen/Main.hs
- tools/src/launcher/Main.hs
- util/src/Pos/Util/Wlog.hs
- util/src/Pos/Util/Wlog/Compatibility.hs
Logging does some buffering which was not flushed to the backends when node or tools exited.
Now there is an explicit flush of the queues and all outputs will be closed.
CBR-477
verify output is complete: e.g. in tool `cardano-keygen`
sync-test with the node containing the changes in Launcher/Resource.hs, when Ctrl-C'ed:
```
[cardano-sl.*production*:Debug:ThreadId 9760] [2018-10-31 12:12:38.37 UTC] Rolling: verifying
[cardano-sl.diffusion.outboundqueue.self:Warning:ThreadId 9801] [2018-10-31 12:12:38.43 UTC] sending MsgRequestBlocks (fromList [NodeId 13.229.245.242:3000:0]) to NodeId 13.229.245.242:3000:0 failed with AsyncCancelled :: SomeException
[cardano-sl.node:Error:ThreadId 9770] [2018-10-31 …
```
> [CBR-477] flush logs before applications exit

- tools/src/keygen/Main.hs
An error, `GeneratedSecrets missing from Genesis.Config`, is thrown when trying to make use of the `cardano-keygen` tool.
It was found that we attempt to extract a `Maybe GeneratedSecrets` from the config (and throw if it is `Nothing`) before we even know which command was specified by the user. Because the `configGeneratedSecrets` field is always set to `Nothing` in the `GCSrc` case, the error will always be thrown whenever trying to make use of `cardano-keygen` with a config which makes use of a `GCSrc`.
Therefore, the solution would be that, since `GeneratedSecrets` is only required for the `generate-keys-by-spec` command, we should *only* attempt to extract `GeneratedSecrets` in the `GenerateKeysBySpec` case. This also means that the `generate-keys-by-spec` command can only be used …
> [RCD-38] Fix "GeneratedSecrets missing" error

- tools/src/keygen/Main.hs
NOTE: This is the same exact change as #3812, but `cherry-pick`ed over to `develop`.
An error, `GeneratedSecrets missing from Genesis.Config`, is thrown when trying to make use of the `cardano-keygen` tool.
It was found that we attempt to extract a `Maybe GeneratedSecrets` from the config (and throw if it is `Nothing`) before we even know which command was specified by the user. Because the `configGeneratedSecrets` field is always set to `Nothing` in the `GCSrc` case, the error will always be thrown whenever trying to make use of `cardano-keygen` with a config which makes use of a `GCSrc`.
Therefore, the solution would be that, since `GeneratedSecrets` is only required for the `generate-keys-by-spec` command, we should *only* attempt to extract `GeneratedSecrets` in the …
> [RCD-38] [develop] Fix "GeneratedSecrets missing" error

- lib/src/Pos/Client/CLI/Options.hs
- wallet-new/src/Cardano/Wallet/Action.hs
- wallet-new/src/Cardano/Wallet/Server/CLI.hs
- wallet-new/src/Cardano/Wallet/Server/LegacyPlugins.hs
- wallet-new/src/Cardano/Wallet/Server/Plugins.hs
by default, it binds to `127.0.0.1:8091` and there is no way to turn it off, causing conflicts whenever you try to run 2 wallets at once
> [DEVOPS-1099] make the wallet documentation optional, and default it to off

- explorer/src/Pos/Explorer/Socket/App.hs
Configure explorer to accept the testnet URL as a valid "origin" for requests.
This fixes the realtime updates.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1121
- Bug fix of configuration
> [DEVOPS-1121] explorer: add testnet URL to CORS origin whitelist

- chain/src/Pos/Chain/Update/BlockVersionData.hs
- chain/src/Pos/Chain/Update/Poll/Failure.hs
- core/src/Pos/Core/Slotting/EpochIndex.hs
- db/cardano-sl-db.cabal
- db/src/Pos/DB/Block/Slog/Logic.hs
- db/src/Pos/DB/Update/GState.hs
- db/src/Pos/DB/Update/Poll/Logic/Apply.hs
- db/src/Pos/DB/Update/Poll/Logic/Base.hs
- db/src/Pos/DB/Update/Poll/Logic/Version.hs
- db/test/Test/Pos/DB/Update/Poll/Logic/Version.hs
- db/test/test.hs
- explorer/src/Pos/Explorer/Socket/App.hs
- lib/src/Pos/Worker/Block.hs
- pkgs/default.nix
Implement a hard fork mechanism to transition from the legacy codebase to the new codebase.
I'm labeling with `DO NOT MERGE` because the debug commits must be dropped before this is merged.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-610
> [CDEC-610] Hard Fork mechanism

- log-configs/cluster.yaml
We need debug-level logging from nodes in the cluster.
https://iohk.myjetbrains.com/youtrack/issue/RCD-42
- Bug fix of configuration file.
```
nix-build -A cardano-sl-node-static -o cardano-node
./cardano-node/bin/cardano-node-simple --address 127.0.0.1:3000 --listen 127.0.0.1:3000 --system-start `date +%s` --log-config log-configs/cluster.yaml --logs-prefix tmp/logs --db-path tmp/db --configuration-file lib/configuration.yaml --configuration-key mainnet_dryrun_full --topology scripts/bench/topology/topology.yaml --node-id node0
```
> [RCD-42] log-configs/cluster.yaml: Include debug messages in json log

- .buildkite/nightly.yml
Will get more consistent results.
Avoids the problem where the nightly test run starts but the macOS builds from Hydra aren't yet ready, and so the buildkite agent needs to build for itself.
Other tests are still executed on macOS as part of normal builds.
None
- Buildkite pipeline tweak
> Nightly tests: Only run tests on Linux

- wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/FromGeneric.hs
- wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/Generic.hs
- wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/Generic/Fees.hs
- wallet-new/src/Cardano/Wallet/Kernel/Transactions.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Active.hs
- wallet-new/test/unit/Test/Spec/CoinSelection.hs
- wallet-new/test/unit/Test/Spec/GetTransactions.hs
- wallet-new/test/unit/Test/Spec/NewPayment.hs
This pr tries to fix a bug on coin and fee selection, which was reported by QA.
The bug was caused because in some cases some changes were not included in the transaction, resulting in huge fees.
The CoinSelection works in many different stages:
- first given some payees, some inputs are selected which cover the expenses (fees are ignored for now). Changes are computed at this stage.
- then fees are computed and we reduce changes to cover the fees. If they are enough, we are done.
- if not new inputs are selected. 
The problem is that these additional inputs (last step) which cover the fees, may not be entirely consumed for the fees: we need to return what's left as change.
TODO:
UPDATE: we split additional changes to existing change outputs. We do this in FromGeneric module (instead of …
> [CSL-2526] update changes after covering remaining fees

- core/test/Test/Pos/Core/Arbitrary.hs
- wallet-new/src/Cardano/Wallet/API/V1/ReifyWalletError.hs
- wallet-new/src/Cardano/Wallet/WalletLayer.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Active.hs
- wallet-new/test/unit/Test/Spec/CoinSelection/Generators.hs
- wallet-new/test/unit/Test/Spec/GetTransactions.hs
- wallet-new/test/unit/Test/Spec/NewPayment.hs
On release/2.0.0, one can attempt to construct and send transactions to addresses which are of a different network via the wallet-new V1 API. Even though the nodes reject this transaction since it's invalid (as a result of CO-410), an error should be returned by the API in order to prevent users from even attempting this.
[[RCD-40]](https://iohk.myjetbrains.com/youtrack/issue/RCD-40)
> [RCD-40] Enforce address discrimination check when sending transactions 

- explorer/frontend/src/Explorer/View/Footer.purs
If this is testnet explorer (i.e. the read "testnet" label is visible), then hide the site footer with a CSS class. This makes it look better when embedded in an iframe.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1094
- New feature, conditional on testnet mode.
Look at the staging explorer and testnet explorer. The first should have a footer visible, the second not.
> [DEVOPS-1094] explorer frontend: hide footer in testnet mode

- wallet-new/src/Cardano/Wallet/Kernel/DB/AcidState.hs
- wallet-new/src/Cardano/Wallet/Kernel/Keystore.hs
- wallet-new/src/Cardano/Wallet/Kernel/Migration.hs
- wallet-new/src/Cardano/Wallet/Kernel/Restore.hs
- wallet-new/src/Cardano/Wallet/Kernel/Wallets.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
- wallet-new/test/unit/Test/Spec/Addresses.hs
- wallet-new/test/unit/Test/Spec/GetTransactions.hs
- wallet-new/test/unit/Test/Spec/NewPayment.hs
- wallet-new/test/unit/Wallet/Inductive/Cardano.hs
This PR changes the wallet migration code in order to remove the last dependency on the legacy wallet.
In order to achieve this, the following changes were made to wallet migration:
* previously, we extracted metadata from the legacy DB for the purposes of migration. This included migrating a "default address" for each migrated wallets
* instead of migrating from the legacy db, we now migrate all wallets that have an encrypted secret key in the wallet Keystore
* however, this does not give us the wallet spending password, which prevents us from being able to create a default address for each migrated wallet
* the solution is to remove the invariant that new wallets be created/restored with a default address (and instead make the address optional)
* existing code paths that create/restore …
> [CO-407] Remove legacy-wallet dependency from new wallet Migration

- tools/src/launcher/Main.hs
> [DDW-480] Fix error message show user for x509 regeneration failures

- release.nix
This adds a required jobset to release.nix that has constituents of what we currently have for branch protection. This is to reduce the number of notifications we have from hydra.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1126
> [DEVOPS-1126] add required jobset to release.nix

- wallet-new/src/Cardano/Wallet/Kernel/BListener.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Read.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Read.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Pending.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Update.hs
- wallet-new/src/Cardano/Wallet/Kernel/PrefilterTx.hs
- wallet-new/src/Cardano/Wallet/Kernel/Restore.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
At this moment prefiltering comes down to filtering out the relevant inputs and so the regular call to updatePending fails to see that the foreign transaction that got removed. Up till now we were looking at the outputs instead of the inputs not because of any fundamental difference between regular and foreign pending transactions, but rather because prefiltering is removing some information that we need and so we look at the outputs as a (somewhat poor) substitute instead. As a consequence we have `updatePending` and `updateForeign` removing corresponding inputs and outputs, respectively.
Here, the following changes are proposed:
1. We adopt lookup seeking one of our currently tracked foreign transaction to appear in the block's inputs, and if so, make sure it appears in the prefiltered …
> [CO-432] Add foreign transaction to input and remove updateForeign

- wallet-new/src/Cardano/Wallet/Kernel/PrefilterTx.hs
Prefiltering seems to totally ignore txIds from Inputs while creating blockMeta. On the other hand it uses TxIns to see which utxos are used. This means that if an account has only inputs in a tx, the tx will apear as Failed. This can happens when it creates a tx and uses a utxo entirely (no changes). QA testing found this bug while trying to empty the wallet, which is a special case of the above.
**Before the fix**, we can see the Prefiltered Block of a failed Transaction which empties the wallet:
PrefilteredBlock. There is no _blockMetaSlotId.
{
pfbInputs = fromList [TxInUtxo (AbstractHash a3cf538a8390fda0cf5477bbdf49da68415a44f45db14ad9b8c2dd9ea62219d6) 0], 
pfbOutputs = fromList [], 
pfbAddrs = [], 
pfbMeta = LocalBlockMeta {localBlockMeta = BlockMeta {_blockMetaSlotId = InDb {_fromDb …
> [RCD-46] fix Prefiltering not ignoring txIds from Inputs

- bors.toml
- docs/PULL_REQUEST_TEMPLATE.md
- docs/how-to/bors.md
Adds the config file and documentation for Bors.
The bot won't be enabled without warning, and not until the trial on [iohk-ops](https://github.com/input-output-hk/iohk-ops) has succeeded.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1028
- CI
> [DEVOPS-1028] Enable Bors

- wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/FromGeneric.hs
- wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/Generic.hs
- wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/Generic/Fees.hs
- wallet-new/test/unit/InputSelection/FromGeneric.hs
- wallet-new/test/unit/Test/Spec/CoinSelection.hs
So, basically, by conflating a bit the selected entries and changes, a
lot of things become easier.  At the price of one thing: fairness.
The previous code was splitting fee across change proportionally to
inputs.  So here, I just split the fee across all changes, regardless of
the input.
One could see it as another type of fairness :upside_down_face: ...  But
that's also a lot simpler to handle, because we can just manipulate all
inputs and all changes directly and compute fee for those directly.
[RCD-45](https://iohk.myjetbrains.com/youtrack/issue/RCD-45)
[RCD-44](https://iohk.myjetbrains.com/youtrack/issue/RCD-44)
```
Wallet unit tests
Coin selection policies unit tests
largestFirst
one payee, SenderPaysFee, fee = 0
+++ OK, passed 1000 tests.
one payee, ReceiverPaysFee, fee = 0
+++ OK, …
```
> [RCD-45] & [RCD-44] Review fee calculation entirely

- chain/src/Pos/Chain/Block/Logic/Integrity.hs
- lib/src/Pos/Communication/Limits.hs
This change ensures that, even if the maximum block size is reduced (and it is), the epoch boundary blocks (also called genesis blocks) are still allowed a higher maximum size.
This is a cherry-pick from #3864.
ChangeLog entry for this added in #3811.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1137
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1140
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1141
- Bug fix
- New feature
- Breaking change
1. Wait for the next epoch after the maximum block size parameter has been reduced.
2. Check that nodes are still able to validate blocks.
> release/2.0.0 [DEVOPS-1141] Set an ample maximum block size for epoch boundary blocks

- chain/src/Pos/Chain/Block/Logic/Integrity.hs
- lib/src/Pos/Communication/Limits.hs
This change ensures that, even if the maximum block size is reduced (and it is), the epoch boundary blocks (also called genesis blocks) are still allowed a higher maximum size.
This is a cherry-pick from #3867.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1137
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1140
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1141
- Bug fix
- New feature
- Breaking change
1. Nightly sync test should pass.
> [DEVOPS-1141] Set an ample maximum block size for epoch boundary blocks

- pkgs/default.nix
- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/src/Cardano/Wallet/Kernel/DB/Sqlite.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/TxMeta.hs
- wallet-new/test/unit/TxMetaStorageSpecs.hs
https://github.com/input-output-hk/cardano-sl/pull/3870 develop version
https://iohk.myjetbrains.com/youtrack/issue/CBR-475
> [CBR-475] Fix race conditions in SQlite

- pkgs/default.nix
- wallet-new/cardano-sl-wallet-new.cabal
- wallet-new/src/Cardano/Wallet/Kernel/DB/Sqlite.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/TxMeta.hs
- wallet-new/test/unit/TxMetaStorageSpecs.hs
Multithreading at SQlite is not the greatest. The intermediate libraries we use make things slightly worse. We already suffer from 2 known issues: 
- unexpected exceptions because of race conditions (https://github.com/IreneKnapp/direct-sqlite/issues/77). This can make things like this not pattern match
`Left (Sqlite.SQLConstraintError Sqlite.Unique "tx_metas_outputs.meta_id, tx_metas_outputs.output_index")` because we get the wrong exception and the node crashes with:
```
StorageFailure (SQLOtherError SQLite3 returned ErrorConstraint while attempting to perform step: not an error)
cardano-node: StorageFailure (SQLOtherError SQLite3 returned ErrorConstraint while attempting to perform step: not an error)
```
- `withTransaction` is not multithreaded. If 2 threads (which for example …
> [CBR-475] adds MVar for any sqlite-operation

- wallet-new/src/Cardano/Wallet/Kernel/Migration.hs
When I create a wallet without a password on the 1.3.1 build and then upgrade\migrate to 2.0.0; the resulting wallet has a spending password enforced. 
When migrating from an old data-layer, we don't have much information about whether there was a password defined on a wallet. So, we use to apply some heuristic based on the password last upate timestamp.
This is rather unreliable and can return misleading metadata for wallets which don't have passwords. Because there's no such thing as "no password" (secret keys are actually encrypted with an empty passphrase), it is possible to assess whether a key was encrypted with a password by trying to decrypt with an empty one. If it succeeds, then we can tell for sure that there's no password defined for the given key. …
> [RCD-47] Fix 'hasSpendingPassword' metadata recovery during migration

- lib/configuration.yaml
In preparation for a new RC build.
staging: 16 -> 17
testnet: 1 -> 2
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1112
- Configuration change
> [DEVOPS-1112] configuration.yaml: bump staging and testnet applicationVersions

- .buildkite/pipeline.yml
- .buildkite/windows.ps1
This is a squash of the changes in #3802, without deleting `appveyor.yml`, without the setup script, and with ghc 8.2.2 instead of 8.4.4.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1113
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1138
- Build system improvement
1. Daedalus should build on AppVeyor using the artifact from this build.
2. The resulting Daedalus installer for windows should pass smoke tests.
> [DEVOPS-1113] Buildkite: Add Windows build

- wallet-new/integration/TransactionSpecs.hs
- wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/FromGeneric.hs
- wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/Generic.hs
- wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/Generic/Fees.hs
- wallet-new/src/Cardano/Wallet/Kernel/PrefilterTx.hs
- wallet-new/test/unit/InputSelection/FromGeneric.hs
- wallet-new/test/unit/Test/Spec/CoinSelection.hs
See #3861 and #3855 
This is port to `develop` which also includes extra integration tests to emphasize on the fixed issues. 
[RCD-46](https://iohk.myjetbrains.com/youtrack/issue/RCD-46)
[RCD-45](https://iohk.myjetbrains.com/youtrack/issue/RCD-45)
[RCD-44](https://iohk.myjetbrains.com/youtrack/issue/RCD-44)
Added the following tests:
```hs
-- Initial Selection:      Final Selection:
--   inputs : [200000]       inputs : [200000]
--   outputs: [1]            outputs: [1]
--   changes: [199999]       changes: [28094]
--   fee+   : 171905         fee+   : 171817
--
--           Actual fee: 171905 (+88)
randomTest "fee calculation: no extra inputs, no extra change" 1 $ run $ do
source <- fixtureWallet (Core.mkCoin <$> [200000])
resp <- makePayment (Core.mkCoin 1) source =<< getRandomAddress …
```
> [RCD-44] & [RCD-45] &  [RCD-46] - Review fee calculation and Fix prefiltering not ignoring inputs' ids [develop]

- explorer/frontend/src/Explorer/View/Footer.purs
The testnet link was using an old URL.
https://iohk.myjetbrains.com/youtrack/issue/RCD-48
- Bug fix
- Look at footer links on http://cardano-explorer.awstest.iohkdev.io/ (staging) or https://cardanoexplorer.com (mainnet) and check testnet.
> [RCD-48] explorer frontend: Update testnet link in footer

- appveyor.yml
Bump OpenSSL to 1.0.2q, as build for 1.0.2p is no longer available.
> appveyor:  bump OpenSSL to 1.0.2q, as build for 1.0.2p is no longer available

- appveyor.yml
- release.nix
(cherry picked from commit 54d803e2061d18ee96fb053c5dd169d4e708b6e7)
> [DEVOPS-1126] add required jobset to release.nix (#3852)

- scripts/test/acceptance/default.nix
Adds GHC heap profiling plot to the Buildkite nightly sync test.
There is only one heap profile which includes both the sync and wallet restore phases together.
It is fairly easy to distinguish the phases on the charts. If the sync and restore phases must be in separate charts then this can be done.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1146
- Tests
> [DEVOPS-1146] Add heap profile chart to nightly sync test

- CHANGELOG.md
- wallet/src/Pos/Wallet/Web/State/Storage.hs
The restore process does not correctly restore the balance for additional accounts. (The flaw is that the "quick restore" only restores the balance for the accounts that were created already, and in the overall restore workflow only the first account gets created before the quick restore is kicked off).
See #3896 
[DEVOPS-1153](https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1153)
> [DEVOPS-1153] Extend addWAddress to support newly-found accounts

- tools/cardano-sl-tools.cabal
- tools/src/launcher/Main.hs
> [RCD-52]  cardano-launcher | win64:  kill self via PID, not process name

- faucet/cardano-sl-faucet.cabal
- faucet/src/Cardano/WalletClient.hs
- pkgs/default.nix
Fix faucet withdrawals which occasionally fail due to unavailable UTxO.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1172
- Bug fix in faucet -- i.e. testnet only.
This is done with a local build with a faucet connected to the local Daedalus wallet.
> [DEVOPS-1172] faucet: Use OptimizeForHighThroughput grouping policy

- lib/configuration.yaml
Update the applicationVersion for the staging installers, but revert the part which changes the `lastKnownBlockVersion` for the staging cluster. This must be `0.2.0` not `0.1.0`.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1112
> [DEVOPS-1112] Staging application version

- wallet-new/src/Cardano/Wallet/Kernel/DB/Sqlite.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/TxMeta.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/TxMeta/Types.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Accounts.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Transactions.hs
We store some information related to transaction in the metadata store (sqlite). However, when looking up transaction with metadata referring to wallet we don't know about, we fail with a not so friendly error "WalletNotFound" despite no wallet being given as part of the query.
This fix is actually two folds:
- It discards incoherent transactions fetched from the DB, if any,
and shout a warning in the log. This is in order to make the system
more resilient to conconcurrent calls while a wallet or account is
being deleted (since metadata and accounts / wallets are stored in
separated databases, we can't easily run both delete in a single
transaction).
- It also deletes corresponding metadata when an account or a wallet
is removed. This may cause extra damage? What if there are pending …
> [CBR-495] Fix inconsistent metadata store after deletion

- wallet-new/src/Cardano/Wallet/Kernel.hs
Turns out we aren't actually removing the sqlite database when passing --rebuild-db becaue the SQLite db is actually stored in a file and not a directory. 
[[CBR-496]](https://iohk.myjetbrains.com/youtrack/issue/CO-445)
> [CBR-496] Fix --rebuild-db not rebuilding sqlite

- release.nix
* Only require nix-tools linux passing for required jobset
* only run cross tests on windows
> [DEVOPS-1184] Prevent OSX from building unncessary nix-tools

- cluster/src/Cardano/Cluster.hs
- lib/src/Pos/Node/API.hs
- node/src/Cardano/Node/API.hs
- node/src/Cardano/Node/Client.hs
This PR implements the node update endpoints.
There's a change to the implementation of the API. The decision is covered here:
https://github.com/input-output-hk/cardano-wallet/issues/151
> Implement Update endpoints for the Node API

- db/src/Pos/DB/Block/Epoch.hs
The original epoch consolidation code only worked for Ouroborous
classic epochs which had an epoch boundary block (EBB) between
each epoch. OBFT has epochs just like classic, but does not have
EBBs. This commit modifies the existing epoch consolidation code
so that it works on both classic and OBFT epochs.
https://iohk.myjetbrains.com/youtrack/issue/CBR-497
Sync the whole mainnet block chain (which is Ouroboros Classic/Original). Currently not able to test OBFT.
> CBR-497: Adapt epoch consolidation for OBFT

- log-configs/connect-to-cluster.yaml
(cherry picked from commit b49b9de9cd5af64e372c07c7502ddeb83948fa6f)
> [DEVOPS-1134] use text backend for conenctScripts logging config (#3856)

- util/test/Test/Pos/Util/LogStructuredSpec.hs
This should fix
- nix-tools.tests.x86_64-pc-mingw32-cardano-sl-util.util-test.x86_64-linux
> [DEVOPS-1177] Fix windows test (don't just delete files)

- cluster/app/demo/Main.hs
- cluster/app/prepare-environment/Main.hs
- cluster/src/Cardano/Cluster.hs
- cluster/src/Cardano/Cluster/Environment.hs
- cluster/test/Cardano/Cluster/Environment/Spec.hs
@parsonsmatt, this should unlock quite a few things for you to fix integration tests on `cardano-wallet`. Now, we generate a TLS environment for each node in the cluster, and they all start a monitoring api (and it's corresponding doc) using the generated certificates as an authentication mean.
This will have some rippling effects in `cardano-wallet` here:
https://github.com/input-output-hk/cardano-wallet/blob/develop/test/integration/Test/Integration/Framework/Cluster.hs#L75-L87
I'll leave that to you if that's okay :)
```
$ stack exec -- cardano-sl-cluster-demo
Cluster is starting (4 core(s), 1 relay(s), 1 edge(s))...
...core0 OK!
......address:       127.0.0.1:3000
......api address:   127.0.0.1:8080
......doc address:   127.0.0.1:8180
......system start:  1545335561
...core1 OK! …
```
> Enable monitoring API (and corresponding doc) for all nodes in the cluster

- lib/src/Pos/Util/Servant.hs
The APIResponse type isn't exactly right -- if we are returning a value
of type `APIResponse a`, that means we have successfully acquired a
value of type `a` to put in the record. So it doesn't make sense to
return an error status.
The arbitrary instance is modified to always return `SuccessStatus`.
https://github.com/input-output-hk/cardano-wallet/pull/185
Send the …
> Fix Arbitrary instance for APIResponse

- lib/configuration.yaml
Increase versions used by update system.
mainnet: 11 -> 12
staging: 18 -> 19
testnet: 4 -> 5
https://github.com/input-output-hk/internal-documentation/wiki/Daedalus-installer-history
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1203
- Configuration
> [DEVOPS-1203] configuration.yaml: Bump applicationVersion

- lib/src/Pos/Node/API.hs
- lib/src/Pos/Util/UnitsOfMeasure.hs
- node/src/Cardano/Node/API.hs
- wallet/test/unit/API/MarshallingSpec.hs
This leverages generics and type-classes to avoid re-writing the same stuff
all other the place. It provides an easy way to give unit for existing types
in the API.
In the meantime, I've also slightly refactored the TxFeePolicy to remove the 'tag' in favor of
allowing only linear fee to be returned. This is less flexible but that's also not something
we're likely to change in the next ... years or so.
- [?] All new and existing tests passed. 
```json
{
"slotId": {
"slot": 8,
"epoch": 2
},
"slotDuration": {
"quantity": 7000,
"unit": "milliseconds"
},
"slotCount": 20,
"softwareInfo": {
"version": 0,
"applicationName": "cardano-sl"
},
"projectVersion": "2.0.0",
"gitRevision": "1e04867bdb15e3642789e38860b0d253132d372a",
"maxTxSize": {
"quantity": 4096,
"unit": "bytes"
},
"feePolicy": {
"a": { …
```
> Reduce boilerplate for 'MeasuredIn' types

- infra/src/Pos/Infra/Diffusion/Subscription/Dns.hs
- networking/src/Ntp/Client.hs
- networking/src/Ntp/Util.hs
This PR solves to problems, both when node starts without internet connection:
* dns queries reach a limit of open files: the rate in which `dnsSubscriptionTarget` runs is much higher than udp socket timeouts which would trigger closing the socket.  The solution is to retry resolving dns after a fixed 30s timeout after each unsuccessful loop.
* dns queries in the NtpClient did happen only on startup; now we retry after 30s
There are no tests, however this was easy to test manually and it fixes the original issue.
https://iohk.myjetbrains.com/youtrack/issue/CDEC-659
Run a node with out internet connection.  Run `/api/v1/node-info?force_ntp_check` to see if it returns. Then connect to internet and query the `node-info` endpoint once again and see if the return value in …
> [CDEC-659] offline dns queries fixes

- chain/src/Pos/Chain/Update/BlockVersionData.hs
- chain/test/Test/Pos/Chain/Update/Arbitrary.hs
Adds a data type, `ObftConsensusStrictness` which will be utilized in `OBFT` block validation. 
- `ObftStrict` implies that we will validate blocks strictly according to the round-robin slot leader schedule.
- `ObftLenient` implies that we will follow the more lax rules under which any valid slot leader is able to mint a block given that `blocksMintedByLeaderInLastK < k * t` where `t` is some constant such that `1/5 <= t <= 1/4`.
https://iohk.myjetbrains.com/youtrack/issue/CBR-481
https://iohk.myjetbrains.com/youtrack/issue/CBR-482
- [~] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, …
> [CBR-481/482] Add ObftConsensusStrictness data type

- wallet/cardano-wallet.cabal
- wallet/src/Cardano/Wallet/Kernel/NodeStateAdaptor.hs
- wallet/src/Cardano/Wallet/WalletLayer/Kernel.hs
- wallet/src/Cardano/Wallet/WalletLayer/Kernel/Settings.hs
This shouldn't have it to `cardano-sl/develop`. We only intend to release that in 1.6 so I've removed the decoupling bits from the `/wallet` and completed the implementation of the `/api/v1/node-settings` to support the newly exposed settings, but using the NodeStateAdaptor.
> Revert Node Settings Decoupling

- CHANGELOG.md
- wallet-new/src/Cardano/Wallet/API/V1/Addresses.hs
- wallet-new/src/Cardano/Wallet/API/V1/Handlers/Addresses.hs
- wallet-new/src/Cardano/Wallet/API/V1/LegacyHandlers/Addresses.hs
- wallet-new/src/Cardano/Wallet/API/V1/Swagger.hs
- wallet-new/src/Cardano/Wallet/API/V1/Types.hs
- wallet-new/src/Cardano/Wallet/Client.hs
- wallet-new/src/Cardano/Wallet/Client/Http.hs
- wallet-new/src/Cardano/Wallet/Kernel/Addresses.hs
- wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
- wallet-new/src/Cardano/Wallet/Kernel/Decrypt.hs
- wallet-new/src/Cardano/Wallet/Kernel/Wallets.hs
- wallet-new/src/Cardano/Wallet/WalletLayer.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
- wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Addresses.hs
- wallet-new/test/Cardano/Wallet/WalletLayer/QuickCheck.hs
Backporting input-output-hk/cardano-wallet#259 to 1.4.2
> Batch Import Addresses  to  1.4.2

- chain/cardano-sl-chain.cabal
- chain/src/Pos/Chain/Genesis/Config.hs
- chain/src/Pos/Chain/Lrc.hs
- chain/src/Pos/Chain/Lrc/OBFT.hs
- chain/test/Test/Pos/Chain/Lrc/FtsSpec.hs
- chain/test/Test/Pos/Chain/Lrc/ObftRoundRobinSpec.hs
- chain/test/Test/Pos/Chain/Lrc/StakeAndHolder.hs
- core/test/Test/Pos/Core/Arbitrary.hs
- db/cardano-sl-db.cabal
- db/src/Pos/DB/Lrc/Consumer/Delegation.hs
- db/src/Pos/DB/Lrc/OBFT.hs
Adds functionality for determining slot leaders and richmen during the OBFT era. Also adds a test `ObftRoundRobinSpec` which introduces a couple of property tests pertaining to the OBFT round-robin slot leader schedule. 
_Note: This PR does not actually modify block generation or validation code. It only introduces the functions which will be utilized in upcoming PRs._
https://iohk.myjetbrains.com/youtrack/issue/CBR-481
https://iohk.myjetbrains.com/youtrack/issue/CBR-482 …
> [CBR-481/482] Add functionality for determining slot leaders during OBFT

- CHANGELOG.md
> Update CHANGELOG about changes in 1.5 (for the wallet backend)

- CHANGELOG.md
- script-runner/TestCases.hs
- script-runner/common/AutomatedTestRunner.hs
- script-runner/common/NodeControl.hs
- script-runner/common/PocMode.hs
- script-runner/common/Types.hs
- script-runner/stack-test
Pull the `richmen:` key-ed value from `lib/configuration.yaml` and
use that to determine the cluster size at runtime.
https://iohk.myjetbrains.com/youtrack/v2/issue/devops-1131
* Existing tests should handle this change.
`./script-runner/stack-test test4.2` …
> [DEVOPS-1131] script-runner: runtime core node count configuration

- CHANGELOG.md
- wallet/src/Cardano/Wallet/API/V1/ReifyWalletError.hs
- wallet/src/Cardano/Wallet/API/V1/Swagger.hs
- wallet/src/Cardano/Wallet/API/V1/Types.hs
- wallet/src/Cardano/Wallet/Kernel/Transactions.hs
- wallet/test/integration/Test/Integration/Framework/DSL.hs
- wallet/test/integration/Test/Integration/Scenario/Transactions.hs
Add multioutput integration tests
Fix Lens accesses and confusion between WalAddress vs WalletAddress vs V1 Address
This is backport of https://github.com/input-output-hk/cardano-wallet/issues/190
> Support UtxoNotEnoughFragmented error

- CHANGELOG.md
- lib/src/Pos/Util/Swagger.hs
- wallet/src/Cardano/Wallet/API/V1/Swagger.hs
Ported from cardano-wallet c49e93a350e8294a380385258b9232df2d00ac20 to
- lib/src/Pos/Util/Swagger.hs (for the node monitoring api docs)
- wallet/src/Cardano/Wallet/API/V1/Swagger.hs (for the wallet docs)
input-output-hk/cardano-wallet#299
1. Build and run a wallet with `--wallet-doc-address` set
```
stack exec cardano-node -- --topology=docs/network/example-topologies/mainnet-staging.yaml \
--configuration-key mainnet_dryrun_full \
--db-path ../staging-db \
--tlscert ../tls-certs/server.crt --tlskey ../tls-certs/server.key --tlsca ../tls-certs/ca.crt --no-client-auth --wallet-doc-address         127.0.0.1:8190
```
2. Visit https://127.0.0.1:8190/docs/v1/index/#section/Errors
3. Should load at the Error section
1. 
```
stack build cardano-sl-node --ghc-options=-optl-Wl,-dead_strip_dylibs …
```
> Preserve query and fragment part of the URI while redirecting for relative paths (swagger doc)

- CHANGELOG.md
- chain/src/Pos/Chain/Block/Block.hs
- chain/src/Pos/Chain/Block/Logic/Integrity.hs
- chain/src/Pos/Chain/Block/Slog/Types.hs
- chain/src/Pos/Chain/Update/BlockVersionData.hs
- chain/test/Test/Pos/Chain/Block/Arbitrary.hs
- chain/test/Test/Pos/Chain/Block/BlockSpec.hs
- db/src/Pos/DB/BatchOp.hs
- db/src/Pos/DB/Block/Logic/Creation.hs
- db/src/Pos/DB/Block/Logic/Header.hs
- db/src/Pos/DB/Block/Logic/Internal.hs
- db/src/Pos/DB/Block/Logic/VAR.hs
- db/src/Pos/DB/Block/Slog/Logic.hs
- db/src/Pos/DB/Delegation/Logic/VAR.hs
- db/src/Pos/DB/Update/Logic/Global.hs
- generator/bench/Bench/Pos/Criterion/Block/Logic.hs
- lib/src/Pos/Network/Block/Logic.hs
- utxo/src/UTxO/Translate.hs
- utxo/src/UTxO/Verify.hs
- wallet/test/unit/Test/Spec/Translation.hs
Implementation of block validation, both strict and lenient, for the `OBFT` era.
Since `OBFT ObftLenient` validation is able to validate blocks from the `Original` era, I've decided to raise this PR before the implementation of `OBFT` block generation as it could serve as a pretty good test for whether lenient validation operates as expected. 
After this change, the node should actually create and verify blocks as per usual even while in the `OBFT ObftLenient` era. However, we should expect block validation to fail during the `OBFT ObftStrict` era since this form of validation expects slot leaders to follow the strict round-robin schedule.
https://iohk.myjetbrains.com/youtrack/issue/CBR-481
- [~] 🛠 New feature (non-breaking change …
> [CBR-481] Implement OBFT block validation

- CHANGELOG.md
- script-runner/TestCases.hs
I had repeated myself in `testHardForkMechanism`, by copying the
body of `test4`. Due to (what seems like) a botched rebase, my
CBR-503 PR was broken, and because of the duplication, I didn't
catch it in review. This commit factors out the shared logic, and
does checking (`confSetBvAndSv`) to make sure proposals are sane.
I also fix `testHFM` by making the BlockVersions and SoftwareVersions
agree.
https://iohk.myjetbrains.com/youtrack/issue/CBR-503
See `script-runner/README.md` …
> [CBR-503] Refactor `script-runner` testcases; fix testHFM

- chain/src/Pos/Chain/Block/Logic/Integrity.hs
- db/src/Pos/DB/Block/Slog/Logic.hs
In #4059, I mistakenly left some log messages which can end up being very large as they include the entire slot leader schedule which, in the case of mainnet, is huge.
https://iohk.myjetbrains.com/youtrack/issue/CBR-481
> Remove logs which attempt to write entire slot leader schedule

- CHANGELOG.md
- wallet/src/Cardano/Wallet/API/V1/ReifyWalletError.hs
This is the last bit of backporting of batch import of addresses through APIs. Here, proper mapping of kernel addresses to API errors is enforced 
Part of https://iohk.myjetbrains.com/youtrack/issue/CO-447 , namely
input-output-hk/cardano-wallet#327
- [] 🐞 Bug fix (non-breaking change which fixes an issue)
- [] 🛠 New feature (non-breaking change which adds functionality)
> Backporting of proper error kernel-to-API mapping during batch addresses import

- CHANGELOG.md
- chain/src/Pos/Chain/Block/Slog/Types.hs
- db/src/Pos/DB/Block/Lrc.hs
- db/src/Pos/DB/Update/Logic/Global.hs
- infra/src/Pos/Infra/Slotting/Util.hs
- lib/src/Pos/Worker/Block.hs
- script-runner/common/NodeControl.hs
- script-runner/runtest.nix
- script-runner/shell.nix
- script-runner/stack-gui
- script-runner/stack-test
- utxo/src/UTxO/Translate.hs
Implementation of block generation/creation for the `OBFT` era.
https://iohk.myjetbrains.com/youtrack/issue/CBR-482
> [CBR-482] Implement OBFT block creation/generation

- CHANGELOG.md
- lib/src/Pos/Node/API.hs
- node/src/Cardano/Node/API.hs
- wallet/src/Cardano/Wallet/Kernel/NodeStateAdaptor.hs
- wallet/test/unit/Test/Spec/TxMetaScenarios.hs
it would be nice if the frontend got more descriptive information out of the ntp api endpoint. The ntp client exposes:
```
data NtpStatus =
-- | The difference between NTP time and local system time
NtpDrift NtpOffset
-- | NTP client has send requests to the servers
| NtpSyncPending
-- | NTP is not available: the client has not received any respond within
-- `ntpResponseTimeout` or NTP was not configured.
| NtpSyncUnavailable deriving (Eq, Show)```
```
At the moment the node maps both NtpSyncPending and NtpSyncUnavailable to null, but it would be better if null mean just one thing, and that NtpSyncPending was also revealed to the wallet.
[CBR-505](https://iohk.myjetbrains.com/youtrack/issue/CBR-505)
The `localTimeInformation` field can now have three different shapes:
```json
{ "status": …
> [CBR-505] Extend LocalTimeInformation in node-info API

- appveyor.yml
- lib/bench/Bench/Pos/Diffusion/BlockDownload.hs
- lib/src/Pos/Diffusion/Full.hs
- lib/src/Pos/Diffusion/Full/Block.hs
- lib/src/Pos/Launcher/Runner.hs
- lib/test/Test/Pos/Diffusion/BlockSpec.hs
The subscription thread is now killed when the main continuation ends. This means that applications which actually have a "normal" shutdown path (such as the Byron proxy) can actually shutdown without throwing exceptions / control+c.
Ending the full diffusion layer continuation while there is a `streamBlocks` in process will no longer hang.
Also adds a config option for the streaming batch size.
> full diffusion layer normal shutdown

- CHANGELOG.md
- lib/configuration.yaml
- wallet/src/Cardano/Wallet/Action.hs
- wallet/src/Cardano/Wallet/Kernel/Migration.hs
Since a few users have already ran the migration, they might have migrated wallet with incorrect metadata, wrongly stating that
their wallet has no spending password, and as a consequence, preventing them from doing anything with their wallet. So, we do now
run an extra sanity check upon every start to make sure that the wallet acid state metadata matches what we find in the keystore.
[[DEVOPS-150]](https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1250)
```
$ curl -vkX POST "http://localhost:8090/api/v1/wallets" \
-H "Content-Type: application/json;charset=utf-8" \
-d '{
"operation": "create",
"spendingPassword": "",
"backupPhrase": [...],
"assuranceLevel": "normal",
"name": "Without Password"
}' | jq .data
{
"id": "Ae2tdPwUPEZ1UMga1bnFFD7FoFN9ZFoPLCWLaGcqNnfovcrcT3oMSuAz8DD",
"name": …
```
> [DEVOPS-1250] backport RCD-47 fix about 'hasSpendingPassword' metadata with extra sanity check

- wallet/src/Cardano/Wallet/Kernel/Transactions.hs
This can happen because we only _estimate_ the maximum number of inputs allowed for the coin selection.
As a result, the transaction generated as a result of the coin selection may be slightly bigger than
the maximum sized allowed by the network (currently 8kb). So, having an extra sanity checks prevent
wrong transactions to be submitted (and added to our pendin set)
?
> add extra guard to fail if trying to submit a too big transaction

- CHANGELOG.md
- chain/cardano-sl-chain.cabal
- chain/src/Pos/Chain/Block/Header.hs
- chain/src/Pos/Chain/Block/Logic/Integrity.hs
- chain/src/Pos/Chain/Block/Slog/LastBlkSlots.hs
- chain/src/Pos/Chain/Block/Slog/Types.hs
- chain/test/Test/Pos/Chain/Block/Arbitrary.hs
- chain/test/Test/Pos/Chain/Block/Slog/LastBlkSlots.hs
- chain/test/test.hs
- db/cardano-sl-db.cabal
- db/src/Pos/DB/Block.hs
- db/src/Pos/DB/Block/GState/BlockExtra.hs
- db/src/Pos/DB/Block/Logic/Header.hs
- db/src/Pos/DB/Block/Logic/SplitByEpoch.hs
- db/src/Pos/DB/Block/Logic/Util.hs
- db/src/Pos/DB/Block/Logic/VAR.hs
- db/src/Pos/DB/Block/Slog/Context.hs
- db/src/Pos/DB/Block/Slog/Logic.hs
- db/src/Pos/DB/Update/Logic/Global.hs
- db/test/Test/Pos/DB/Block/Logic/SplitByEpoch.hs
- db/test/test.hs
- explorer/src/Pos/Explorer/ExplorerMode.hs
- generator/src/Test/Pos/Block/Logic/Mode.hs
- lib/src/Pos/Launcher/Resource.hs
- lib/src/Pos/Worker/Block.hs
- utxo/src/UTxO/Translate.hs
- utxo/src/UTxO/Verify.hs
Fix issue that caused the node to loose sync with the chain in OBFT era and then fail to re-sync once out of sync.
https://iohk.myjetbrains.com/youtrack/issue/CBR-525
Synced the OBFT testnet numerous times.
> CBR-525: Fix failure to sync issue when switching to OBFT

- scripts/test/acceptance/default.nix
Nobody's ever used the .hp file, and it's a waste of time to upload it.
This removes the upload from the nightly sync test script.
> Acceptance tests: Don't upload .hp file

- CHANGELOG.md
- wallet/src/Cardano/Wallet/Kernel/CoinSelection/Generic/Random.hs
- wallet/src/Cardano/Wallet/Kernel/Transactions.hs
- wallet/test/integration/Test/Integration/Scenario/Transactions.hs
- wallet/test/integration/configuration.yaml
- A fix for the error messages which used to report a wrong balance upon failure. 
- Implementation of the solution A
- Three automated regression tests:
- Verify that the fallback fix indeed works. Test was introduced prior to the fix to illustrate how the random-improve algorithm would greedily consume all available inputs leaving nothing for remaining outputs. Fixed with the fallback introduced in A.
- Verify that the API now returns a correct balance when indeed, the selection fails to select additional UTxO in a multi-outputs transaction
- An extra regression tests related to [CO-449](https://iohk.myjetbrains.com/youtrack/issue/CO-449), proving that the guard added for CO-449 is indeed successful at catching oversized transactions
See …
> [CO-450] Fix random-improve fallback (develop)

- core/cardano-sl-core.cabal
- core/src/Pos/Core/Reporting/Methods.hs
- infra/cardano-sl-infra.cabal
- infra/src/Pos/Infra/Reporting/Http.hs
- infra/src/Pos/Infra/Reporting/NodeInfo.hs
- lib/src/Pos/Reporting/Production.hs
- nix/.stack.nix/cardano-sl-core.nix
- nix/.stack.nix/cardano-sl-infra.nix
- nix/.stack.nix/cardano-sl-tools.nix
- nix/.stack.nix/default.nix
- stack.yaml
- tools/cardano-sl-tools.cabal
- tools/src/launcher/Main.hs
Devops disabled the server these reports were uploaded to some time
ago so we can remove this from the node. Doing this will make
building cardano-byron-proxy easier.
> Exorcise cardano-report-server

- default.nix
- explorer/frontend/default.nix
- explorer/frontend/yarn.lock
- lib.nix
- lib/configuration.yaml
- lib/shelley-staging-genesis.json
- lib/shelley-staging-short-genesis.json
- lib/testnet-genesis.json
- nix/scripts.nix
- release.nix
> New Shelley Staging Environments and Testnet

- default.nix
- explorer/python-api/README.md
- explorer/python-api/app.py
- explorer/python-api/default.nix
- explorer/python-api/explorer_python_api/ExplorerDumper.py
- explorer/python-api/explorer_python_api/__init__.py
- explorer/python-api/explorer_python_api/db-tables.sql
- explorer/python-api/explorer_python_api/db.py
- explorer/python-api/explorer_python_api/explorer.py
- explorer/python-api/explorer_python_api/logger.py
- explorer/python-api/setup.py
- explorer/src/Pos/Explorer/Aeson/ClientTypes.hs
- explorer/src/Pos/Explorer/Web/Api.hs
- explorer/src/Pos/Explorer/Web/ClientTypes.hs
- explorer/src/Pos/Explorer/Web/Server.hs
- explorer/src/Pos/Explorer/Web/TestServer.hs
- explorer/src/documentation/Main.hs
- release.nix
> Explorer python api

- explorer/python-api/default.nix
- explorer/python-api/explorer_python_api/ExplorerDumper.py
- explorer/python-api/explorer_python_api/app.py
- explorer/python-api/explorer_python_api/db.py
> Adds metrics and optimizations

- lib.nix
it is a bit unfortunate that is hash is in two places... what would be a better solution? (easy access to the hash in lib.nix has been added for cardano-node)
> Fix hash in lib.nix for shelley_staging_short.

- CHANGELOG.md
- wallet/shell.nix
- wallet/src/Cardano/Wallet/API/Internal.hs
- wallet/src/Cardano/Wallet/API/Internal/Handlers.hs
- wallet/src/Cardano/Wallet/API/V1/Types.hs
- wallet/src/Cardano/Wallet/Client.hs
- wallet/src/Cardano/Wallet/Client/Http.hs
- wallet/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
- wallet/src/Cardano/Wallet/WalletLayer.hs
- wallet/src/Cardano/Wallet/WalletLayer/Kernel.hs
- wallet/src/Cardano/Wallet/WalletLayer/Kernel/Internal.hs
> [CBR-533] add a new endpoint to calculate the walletid for a given mnemonic

- CHANGELOG.md
- infra/src/Pos/Infra/Diffusion/Subscription/Dns.hs
- wallet/src/Cardano/Wallet/API.hs
It's possible for the same address to be resolved from different DNS
names. The subscription system now recognizes this and avoids attempting
to subscribe to the same IP address more than once concurrently.
This means you can now give the same domain name multiple times in the
subscription specification, and the system will attempt to subscribe to
different addresses from each of them concurrently. That's useful when
we expect the names to give multiple addresses.
> DNS subscription proper fallback/valency

- auxx/Main.hs
- chain/shell.nix
- db/shell.nix
- default.nix
- infra/shell.nix
- infra/src/Pos/Infra/Diffusion/Transport/TCP.hs
- infra/src/Pos/Infra/Network/CLI.hs
- infra/src/Pos/Infra/Network/Types.hs
- lib/configuration.yaml
- lib/mainnet-ci-genesis.json
- lib/shell.nix
- lib/src/Pos/Diffusion/Full.hs
- lib/src/Pos/Worker/Block.hs
- scripts/prepare-genesis/default.nix
This supplies the necessary changes for a mixed-cluster integration test, as per https://github.com/input-output-hk/cardano-node/issues/255 :
1. `mainnet_ci_full` genesis & configuration, starting in OBFT node
2. fix for an OBFT EBB rollback issue, which was trying to erase EBB even if the chain was started in OBFT mode, leading to https://github.com/input-output-hk/cardano-node/issues/255#issuecomment-543247537
3. change in `network-transport-tcp` to be more lenient regarding remote address claims: https://github.com/deepfire/network-transport-tcp/commit/44f84a887cf954dd924f28b7e8da107228e57c13.  This is necessary to avoid problems when starting multiple nodes on the same machine.
4. small improvements in genesis generation
Additionally, this resets the protocol version for the …
> Single-machine multi-node mixed cluster CI prerequisites
